"""Clear thinking ladder: Intermediate, Advanced and Expert courses that
follow "Clear thinking" (thinking). Lessons mix concepts, worked examples,
multiple choice, ordering, numeric problems that re-roll, and short
written answers checked for structure. Numbers in problems are made up
examples, labeled as such; no statistics are invented.
Rebuild with: python3 build_library.py
"""
from ladder_kit import C, W, M, O, L, X, WR, NQ, course, words, must, avoid, lines

KW = ["thinking", "critical thinking", "reasoning"]

# =====================================================================
# Intermediate: Arguments you can test
# =====================================================================

TI1 = L("Premises and conclusions", KW + ["argument", "premise", "conclusion", "claim", "reasons"], [
    C("Find the skeleton first",
      "An argument is a conclusion plus the reasons offered for it (premises). Before judging an argument, restate it: what is being claimed, and what is it supposed to follow from? Words such as therefore, so and which means usually point to a conclusion; because, since and given that usually point to premises. Many disagreements are really about an unstated premise, so write the hidden one down too."),
    W("Restate an argument",
      "Example: \"We should move the meeting to Tuesday, because half the team is out on Monday.\"",
      ["Conclusion: we should move the meeting to Tuesday.",
       "Stated premise: half the team is out on Monday.",
       "Hidden premise: the meeting needs most of the team present.",
       "Hidden premise: Tuesday works for more people than Monday."],
      "Write the conclusion, the stated reasons and the hidden assumptions."),
    M("\"Sales fell after the redesign, so the redesign hurt sales.\" What is the conclusion?",
      ["Sales fell", "The redesign hurt sales", "There was a redesign", "Sales will rise"], 1,
      "So introduces the conclusion. The premise is that sales fell after the redesign."),
    M("Which hidden premise does that argument rely on?",
      ["Nothing else changed around the same time that could explain the fall", "Redesigns are expensive", "Sales always fall in winter", "The designer was new"], 0,
      "If a price change or a season explains the fall, the conclusion does not follow."),
    O("Analyze an argument, in order.",
      ["Find the conclusion", "List the stated premises", "Write down the hidden premises", "Ask whether each premise is true", "Ask whether the conclusion follows if they are"],
      "Separate what is claimed from why. Then test truth and logic separately."),
    WR("Restate this argument with lines starting with Conclusion:, Premise: and Hidden premise:. \"Our competitor cut prices, so we have to cut ours too.\"",
       [must("^conclusion:.*(cut|lower|reduce)", "Conclusion: we must cut prices", flags="im"),
        must("^premise:.*competitor", "Premise: the competitor cut prices", flags="im"),
        must("^hidden premise:", "At least one Hidden premise:", flags="im"),
        words(15, 120)],
       "Conclusion: we have to cut our prices.\nPremise: our competitor cut its prices.\nHidden premise: our customers choose mainly on price.\nHidden premise: we will lose more from lost sales than from a lower price.",
       "The hidden premises are where the real debate is: do our customers choose on price?"),
])

TI2 = L("Valid, sound and strong", KW + ["deduction", "induction", "valid", "sound", "logic", "strong argument"], [
    C("Two ways an argument can fail",
      "A deductive argument is valid if the conclusion must be true whenever the premises are true; it is sound if it is valid and the premises really are true. An inductive argument, from examples or patterns, is never certain; it is strong if the premises make the conclusion likely. An argument can fail by having a false premise, or by having true premises that do not support the conclusion."),
    M("\"All cats are mammals. My pet is a mammal. So my pet is a cat.\" This argument is...",
      ["Valid and sound", "Invalid: the premises can be true while the conclusion is false", "Valid but unsound", "Strong inductive"], 1,
      "A dog is also a mammal. This is the pattern called affirming the consequent."),
    M("\"All birds can fly. Penguins are birds. So penguins can fly.\" This argument is...",
      ["Valid but unsound, because the first premise is false", "Invalid", "Sound", "Strong"], 0,
      "The logic works; a premise is false. Valid is about form; sound adds true premises."),
    W("Check an inductive argument",
      "Example: \"Every customer we interviewed liked the new feature, so our customers like it.\"",
      ["Ask how many were interviewed: 5 or 500?",
       "Ask how they were chosen: our biggest fans or a random sample?",
       "Ask whether anything about the interview pushed toward yes.",
       "Strength depends on the sample's size and how representative it is."],
      "Inductive strength rests on how the examples were gathered."),
    O("Test a generalization from examples, in order.",
      ["State the general claim", "Ask how many examples support it", "Ask how the examples were chosen", "Look for counterexamples", "Decide how probable the claim is, not whether it is certain"],
      "Inductive conclusions come in degrees. The last step is a judgment of strength, not a proof."),
    NQ("Example: a survey asked {n} people chosen at random and {k} said yes. What percent said yes? (One decimal.)",
       "{k} / {n}, times 100, is {A}%. Whether that generalizes depends on how the people were chosen.",
       {"n": [100, 1000, 50], "k": [20, 90, 5]}, "k/n*100", {"n": 200, "k": 60}, rnd=1, tol=0.1),
])

TI3 = L("Fallacies that sound reasonable", KW + ["fallacies", "straw man", "false dilemma", "slippery slope", "ad hominem", "appeal to authority"], [
    C("Patterns worth naming",
      "Some reasoning errors recur so often they have names. A straw man attacks a weaker version of the other view. A false dilemma offers two options when there are more. A slippery slope claims one step must lead to an extreme without showing why. An ad hominem attacks the person instead of the argument. An appeal to authority leans on someone's status outside their expertise. Naming the pattern is less useful than asking what would make the argument good."),
    M("\"Either we launch this month or we lose the market forever.\" Which pattern is most likely?",
      ["Straw man", "False dilemma", "Ad hominem", "None"], 1,
      "Launching next month, a smaller launch, or a beta are options left out."),
    M("\"She wants a four day week trial? So she thinks nobody should ever work.\" Which pattern?",
      ["Straw man", "Slippery slope", "Appeal to authority", "Base rate neglect"], 0,
      "A trial of a shorter week is restated as an extreme nobody proposed."),
    M("\"A famous actor says this supplement works.\" What is the strongest response?",
      ["Actors are never right", "Ask what evidence there is, since acting fame is not expertise in medicine", "Accept it", "It must be false"], 1,
      "Rejecting it because of who said it is its own error. Ask for evidence."),
    M("\"If we allow remote Fridays, soon nobody will come in at all.\" Which pattern?",
      ["Slippery slope", "Ad hominem", "Straw man", "Appeal to authority"], 0,
      "It asserts a chain to an extreme without showing why each step would happen."),
    O("Respond to a suspected fallacy, in order.",
      ["Restate the argument fairly", "Name what seems to be missing, such as other options or evidence", "Ask what would make the argument good", "Judge the improved version, not the weak one"],
      "Shouting the fallacy's name wins nothing. Repairing the argument shows whether the conclusion survives."),
    WR("Rewrite this false dilemma as a fairer statement that names at least three options: \"Either we hire a full time designer or our website stays terrible.\"",
       [must("(freelanc|contract|part time|template|agency|train|course)", "Names a realistic alternative"),
        must("(or|options|could)", "Presents options"),
        avoid("^either\\b", "Does not start with Either"),
        words(15, 80)],
       "We could hire a full time designer, bring in a freelancer for the main pages, or use a well made template and improve it ourselves. Each has a different cost and timeline.",
       "Fair framing lists the real options and lets the trade offs speak."),
])

TI4 = L("Weighing sources", KW + ["sources", "evidence", "credibility", "primary source", "lateral reading", "misinformation"], [
    C("Who says so, and how do they know?",
      "A claim is only as good as its source's access to the facts and its incentives. Primary sources (the study, the dataset, the court filing) beat summaries of them. Lateral reading, the habit of fact checkers, means leaving the page to see what other reliable sources say about the claim and about the site itself, instead of judging a page by how professional it looks."),
    M("A viral post quotes a study. What should you check first?",
      ["How many shares it has", "Whether the study exists and actually says what the post claims", "Whether the post has a nice design", "Whether you agree"], 1,
      "Summaries often stretch a study's findings. Go to the source."),
    M("Which source is generally most direct for a company's reported revenue?",
      ["A forum comment", "The company's own filed financial report", "A blog that summarizes rumors", "A tweet from a rival"], 1,
      "Filed reports are primary and carry legal obligations. Still read them knowing the company's incentives."),
    O("Check an unfamiliar claim, in order.",
      ["Pause before sharing or reacting", "Find who originally made the claim", "Read laterally: what do other reliable sources say?", "Trace it to the primary source if one exists", "Decide how confident to be"],
      "The pause is the step that stops most mistakes."),
    W("Separate what was found from what was said",
      "Example headline: \"Study shows chocolate makes you smarter.\" The study: people in countries that eat more chocolate win more science prizes.",
      ["Found: a correlation across countries.",
       "Not found: anything about individuals or about cause.",
       "Alternative: richer countries both buy more chocolate and fund more research.",
       "Honest headline: countries that eat more chocolate win more prizes; wealth may explain both."],
      "Compare the headline's claim with what the evidence can support."),
    WR("Write three questions you would ask before trusting a claim you read online. One per line.",
       [lines(3, "Three questions"),
        must("\\?", "Written as questions"),
        must("(who|source|original)", "One asks about the source"),
        must("(evidence|data|study|how do they know|proof)", "One asks about the evidence"),
        words(12, 80)],
       "Who first made this claim, and what do they gain?\nWhat evidence supports it, and can I see it?\nWhat do other reliable sources say?",
       "Source, evidence and other sources: three questions that catch most bad claims."),
])

TI5 = L("Base rates", KW + ["base rate", "base rate neglect", "prior", "false positive", "screening"], [
    C("Start with how common it is",
      "A base rate is how common something is before you look at the specifics. People tend to ignore base rates when given a vivid description or a test result. When a condition is rare, even an accurate test produces many false alarms, because there are so many more people without the condition to be wrongly flagged."),
    W("A rare condition and a good test",
      "Example: 1 in 100 people has a condition. A test catches 90% of real cases and wrongly flags 9% of people without it. Imagine 1,000 people.",
      ["With the condition: 10 people; the test flags 9.",
       "Without: 990 people; the test wrongly flags about 89.",
       "Total flagged: about 98. Of those, 9 really have it.",
       "Chance a flagged person has it: 9 / 98, about 9%."],
      "Count people, not percentages: false alarms from the big group swamp the true cases."),
    NQ("Example: {b} in 1,000 have a condition. The test catches 90% of real cases and wrongly flags {f}% of others. Of those flagged, what percent really have it? (One decimal.)",
       "True positives {tp}; false positives {fp}; so {A}%.",
       {"b": [5, 100, 5], "f": [1, 10, 1]}, "b*0.9/(b*0.9+(1000-b)*f/100)*100", {"b": 10, "f": 9}, rnd=1, tol=0.1,
       show={"tp": "b*0.9", "fp": "(1000-b)*f/100"}),
    X("How rarity changes the answer",
      "Example: the same test (90% catch rate, 9% false alarms). Drag how common the condition is.",
      "(x*0.9)/(x*0.9+(100-x)*0.09)*100", "x", 0.5, 50, 0.5, "How common (%)", "Chance a flagged person has it (%)"),
    M("A description of a quiet person who loves books. Are they more likely a librarian or a salesperson?",
      ["Librarian, clearly", "It depends heavily on how many more salespeople there are than librarians", "Equal odds", "Salesperson, always"], 1,
      "If salespeople far outnumber librarians, even a good fit for librarian may lose to the base rate."),
    O("Use a base rate, in order.",
      ["Find how common the thing is in the relevant group", "Consider how strong the specific evidence is", "Adjust from the base rate, not from zero", "Check the result with counts of people"],
      "Base rate first, then adjust. Starting from the vivid detail is the classic mistake."),
])

TI6 = L("Confounders and reverse causation", KW + ["confounding", "reverse causation", "causation", "correlation", "third variable"], [
    C("Three stories behind every correlation",
      "When A and B move together, A might cause B, B might cause A (reverse causation), or a third factor might cause both (a confounder). Chance and how the data were selected are two more explanations. Randomized experiments break confounding by assigning A at random; without them, look for the other stories before accepting the first."),
    M("People who use standing desks report less back pain. Which is a reverse causation story?",
      ["Standing desks prevent pain", "People without back pain find standing comfortable, so they keep using standing desks", "Wealth causes both", "Pure chance"], 1,
      "The pain level may choose the desk, not the other way round."),
    M("Towns with more fire trucks have more fire damage. What is the most plausible explanation?",
      ["Fire trucks cause damage", "Bigger towns have both more trucks and more fires: a confounder", "Damage buys trucks", "Coincidence"], 1,
      "Town size drives both. Compare towns of similar size."),
    W("Name the alternatives",
      "Example claim: \"Students who eat breakfast get better grades, so breakfast improves grades.\"",
      ["Cause: breakfast helps concentration.",
       "Confounder: stable home routines lead to both breakfast and study habits.",
       "Reverse: students who do well may be more organized in the morning.",
       "Test: a randomized trial of school breakfasts would separate these."],
      "List the stories, then ask which evidence would tell them apart."),
    O("Check a causal claim, in order.",
      ["State the claimed cause and effect", "Ask whether the effect could cause the cause", "List possible confounders", "Ask whether an experiment or natural experiment exists", "Decide how strongly to believe the claim"],
      "Experiments, when they exist, beat clever arguments about observational data."),
    WR("A news story says: \"Coffee drinkers live longer.\" Write one confounder and one reverse causation story, with lines starting with Confounder: and Reverse:.",
       [must("^confounder:", "Confounder:", flags="im"),
        must("^reverse:", "Reverse:", flags="im"),
        words(15, 100)],
       "Confounder: people with more money and less stressful jobs may both drink cafe coffee and get better healthcare.\nReverse: people who are already seriously ill may cut back on coffee, so the non drinkers include more sick people.",
       "Both stories would produce the same correlation without coffee doing anything."),
])

TI7 = L("Expected value for everyday choices", KW + ["expected value", "decisions", "probability", "risk", "trade offs"], [
    C("Weigh outcomes by how likely they are",
      "Expected value multiplies each outcome by its probability and adds them up. It is the average result if you could repeat the choice many times. It is a guide, not the whole story: for one off choices, the worst case and how much you could bear to lose matter too."),
    W("Should you buy the extended warranty?",
      "Example: a 400 appliance. Warranty costs 60 for two years. Suppose a 10% chance of a failure that costs 250 to fix.",
      ["Expected repair cost without the warranty: 10% times 250 = 25.",
       "Warranty cost: 60.",
       "On average the warranty costs 35 more than it saves.",
       "Buy it only if a 250 surprise would really hurt, which savings can usually cover."],
      "Expected value says skip it; the worst case says whether you can."),
    NQ("Example: a {p}% chance of a cost of {c}. What is the expected cost?",
       "{p}% times {c} = {A}.",
       {"p": [5, 50, 5], "c": [100, 2000, 50]}, "p/100*c", {"p": 10, "c": 250}, rnd=2),
    NQ("Example: option A pays {a} for sure. Option B pays {b} with probability {p}% and nothing otherwise. What is B's expected value?",
       "{p}% times {b} = {A}, compared with {a} for A.",
       {"a": [50, 500, 50], "b": [100, 2000, 100], "p": [10, 90, 10]}, "p/100*b", {"a": 200, "b": 500, "p": 50}, rnd=2),
    M("A choice has a higher expected value but a small chance of losing everything you own. What is wise?",
      ["Take it, expected value is all that matters", "Weigh the ruin risk separately: outcomes you cannot recover from deserve extra caution", "Never take any risk", "Flip a coin"], 1,
      "Expected value assumes repeated plays. Ruin ends the game."),
    O("Use expected value, in order.",
      ["List the options", "List the outcomes for each with rough probabilities", "Multiply and add for each option", "Check the worst case for each", "Choose, noting what would change your mind"],
      "Rough probabilities are fine; writing them down is what helps."),
])

TI8 = L("Second order effects", KW + ["second order", "consequences", "unintended consequences", "systems", "and then what"], [
    C("And then what?",
      "First order effects are the immediate results of a decision. Second order effects are what happens because of those results, often as people respond. A rule that rewards one number may cause people to game it; a discount may train customers to wait for discounts. Asking \"and then what?\" two or three times surfaces effects that dominate in the long run."),
    W("Follow a decision forward",
      "Example: a city makes a busy road free of tolls.",
      ["First order: driving on it gets cheaper.",
       "Second order: more people drive on it.",
       "Third order: congestion rises until travel times are similar to before, a pattern called induced demand.",
       "Question to ask: what did we actually want, faster trips or cheaper ones?"],
      "Trace how people respond, not just the direct effect."),
    M("A team is rewarded for closing support tickets quickly. What second order effect is likely?",
      ["Nothing changes", "Tickets get closed before the problem is solved, and customers reopen them", "Customers become happier automatically", "Fewer tickets are created"], 1,
      "People optimize what is measured. Pair speed with a quality measure."),
    O("Think through consequences, in order.",
      ["State the decision and its direct effect", "Ask how people will respond", "Ask what those responses cause", "Look for who loses and who adapts", "Adjust the decision to handle the likely responses"],
      "The responses of people affected are where most surprises come from."),
    WR("Pick a decision (real or this one: a shop offers free returns on everything). Write a chain of at least three effects, one per line, each starting with Then:.",
       [must("(^then:[^\\n]*\\n){2,}^then:", "Three Then: lines", flags="im"),
        words(15, 120)],
       "Then: more people buy because trying is risk free.\nThen: more items come back, some damaged, raising costs.\nThen: the shop raises prices or limits returns, and some customers feel misled.",
       "Each line follows from the one before. The third effect is the one plans usually miss."),
    NQ("Example: a discount of {d}% raises units sold by {u}%. By what percent does revenue change? (One decimal.)",
       "Revenue multiplier: {k} times {m}, so a change of {A}%.",
       {"d": [5, 40, 5], "u": [5, 60, 5]}, "((1-d/100)*(1+u/100)-1)*100", {"d": 20, "u": 30}, rnd=1, tol=0.1,
       show={"k": "1-d/100", "m": "1+u/100"}),
])

TI9 = L("Capstone: dissect an argument", KW + ["capstone", "argument analysis", "critique", "evaluate", "reasoning"], [
    C("Put the tools together",
      "A full analysis restates the argument, separates premises from conclusion, finds hidden assumptions, checks the evidence and its source, looks for confounders and base rates, and considers second order effects. The goal is not to win but to see how strong the argument really is and what would make it stronger."),
    M("\"Since we added the chat widget, sign ups are up 20%, so the widget works.\" What is the most important missing check?",
      ["The widget's color", "Whether anything else changed in the same period, such as a campaign or a season", "How many lines of code it took", "Who built it"], 1,
      "Before and after comparisons are easily confounded. A split test would answer it."),
    O("Write the analysis, in order.",
      ["Restate the claim and its reasons", "Name hidden assumptions", "Check the evidence and its source", "Give the strongest alternative explanation", "State a verdict and what would change it"],
      "A verdict with what would change it is honest and useful."),
    NQ("Example: sign ups went from {a} to {b} a week after a change. What is the percent change? (One decimal.)",
       "({b} minus {a}) / {a}, times 100, is {A}%.",
       {"a": [100, 500, 10], "b": [100, 700, 10]}, "(b-a)/a*100", {"a": 250, "b": 300}, rnd=1, tol=0.1),
    WR("Dissect an argument you have heard (or the chat widget one). Use lines starting with Claim:, Reasons:, Assumptions:, Evidence:, Alternative: and Verdict:.",
       [must("^claim:", "Claim:", flags="im"),
        must("^reasons:", "Reasons:", flags="im"),
        must("^assumptions:", "Assumptions:", flags="im"),
        must("^evidence:", "Evidence:", flags="im"),
        must("^alternative:", "Alternative:", flags="im"),
        must("^verdict:", "Verdict:", flags="im"),
        avoid("\\b(obviously|clearly|everyone knows)\\b", "Avoids words that skip the reasoning"),
        words(50, 220)],
       "Claim: the chat widget raised sign ups.\nReasons: sign ups rose 20% in the month after it launched.\nAssumptions: nothing else changed in that month; the rise is larger than normal week to week noise.\nEvidence: a before and after count from our analytics, one month each.\nAlternative: the spring email campaign started the same week and could explain the rise.\nVerdict: plausible but unproven; a two week split test with and without the widget would settle it.",
       "Clear structure, a real alternative and a cheap test that would change the verdict."),
    C("Intermediate complete",
      "You can take an argument apart and test each piece. Advanced turns to uncertainty: probabilities, updating, studies and forecasts."),
])

# =====================================================================
# Advanced: Reasoning under uncertainty
# =====================================================================

TA1 = L("Thinking in probabilities", KW + ["probability", "calibration", "confidence", "uncertainty", "likelihood"], [
    C("Replace yes or no with how likely",
      "Most real questions do not have a certain answer, so a useful belief is a probability: 70% is more informative than \"probably\". Being calibrated means that of all the things you say are 70% likely, about 70% happen. You can check calibration by writing predictions down with probabilities and scoring them later."),
    M("You said 90% for ten different predictions and six came true. What does that suggest?",
      ["You are well calibrated", "You are overconfident at that level", "You are underconfident", "Nothing at all"], 1,
      "90% claims should come true about nine times in ten. Six suggests your 90% means something closer to 60%. Ten is a small sample, so keep scoring."),
    W("Score a forecast with the Brier score",
      "Example: you said 80% it would rain. It rained (outcome 1).",
      ["The Brier score is (forecast minus outcome) squared.",
       "(0.8 minus 1) squared = 0.04.",
       "Had it not rained: (0.8 minus 0) squared = 0.64.",
       "Lower is better; always saying 50% scores 0.25 every time."],
      "Confident and right scores well; confident and wrong scores badly."),
    NQ("Example: you forecast {p}% and the event did not happen. What is the Brier score? (Four decimals.)",
       "({pp} minus 0) squared = {A}.",
       {"p": [5, 95, 5]}, "(p/100)^2", {"p": 80}, rnd=4, tol=0.0001, show={"pp": "p/100"}),
    NQ("Example: you forecast {p}% and the event happened. What is the Brier score? (Four decimals.)",
       "({pp} minus 1) squared = {A}.",
       {"p": [5, 95, 5]}, "(p/100-1)^2", {"p": 70}, rnd=4, tol=0.0001, show={"pp": "p/100"}),
    O("Build calibration, in order.",
      ["Write predictions with a probability and a date", "Wait for the outcomes", "Group predictions by the probability you gave", "Compare how often each group came true with the probability", "Adjust how confident you are next time"],
      "Scoring is what turns vague hunches into a skill you can improve."),
])

TA2 = L("Updating with Bayes", KW + ["bayes", "updating", "evidence", "likelihood ratio", "prior", "posterior"], [
    C("Start somewhere, then move",
      "Bayes' rule says how much to change a belief given new evidence. Start with a prior probability. Ask how much more likely the evidence is if the belief is true than if it is false: the likelihood ratio. In odds form: posterior odds = prior odds times likelihood ratio. Evidence that is about as likely either way should barely move you."),
    W("Update in odds",
      "Example: you think there is a 20% chance a colleague is planning to leave. You see they have taken three long lunches this week. Suppose that is 3 times as likely if they are interviewing as if not.",
      ["Prior odds: 20 to 80, or 1 to 4.",
       "Multiply by the likelihood ratio of 3: 3 to 4.",
       "Convert back: 3 / (3 + 4), about 43%.",
       "The evidence moved you a lot, but not to certainty."],
      "Odds times likelihood ratio, then back to a probability."),
    NQ("Example: prior {p}%, likelihood ratio {r}. What is the posterior probability, in percent? (One decimal.)",
       "Prior odds {o}; times {r} gives {po}; posterior {A}%.",
       {"p": [5, 80, 5], "r": [0.5, 10, 0.5]}, "(p/(100-p)*r)/(1+p/(100-p)*r)*100", {"p": 20, "r": 3}, rnd=1, tol=0.1,
       show={"o": "p/(100-p)", "po": "p/(100-p)*r"}),
    M("A piece of evidence is equally likely whether your belief is true or false. How should you update?",
      ["A lot", "Not at all: the likelihood ratio is 1", "Toward certainty", "Away from the belief"], 1,
      "Evidence that does not discriminate between the possibilities carries no information about them."),
    X("Same evidence, different priors",
      "Example: drag your prior. The evidence has a likelihood ratio of 4.",
      "(x/(100-x)*4)/(1+x/(100-x)*4)*100", "x", 1, 95, 1, "Prior (%)", "Posterior (%)"),
    O("Update a belief, in order.",
      ["Write your prior as a probability", "Describe the new evidence", "Estimate how much more likely it is if the belief is true", "Multiply the odds and convert back", "Record the new belief and what would move it again"],
      "Rough numbers still beat no numbers: they show whether evidence should move you a little or a lot."),
])

TA3 = L("Regression to the mean", KW + ["regression to the mean", "luck", "skill", "extreme results", "sports illustrated"], [
    C("Extremes tend to be followed by ordinary",
      "When a result depends partly on luck, an extreme result is likely to be followed by one closer to average, simply because the luck does not repeat. This is regression to the mean. It fools people into crediting whatever they did after a bad result (it got better) or blaming whatever they did after a good one (it got worse)."),
    M("A manager praises staff after great months and criticizes them after bad ones, and concludes that criticism works and praise backfires. What explains the pattern?",
      ["Criticism works", "Regression to the mean: after extremes, results drift back toward average whatever the manager does", "Staff dislike praise", "Pure coincidence once"], 1,
      "Performance would rise after bad months and fall after great ones even with no feedback."),
    W("Mix skill and luck",
      "Example: a score is skill plus luck. A player's skill is 50. Luck adds a random amount between minus 20 and plus 20.",
      ["A score of 68 likely includes lucky plus 18 or so.",
       "Next time, expected luck is 0, so the expected score is 50.",
       "The higher the luck share, the stronger the pull back.",
       "Judge people on many results, not their best or worst."],
      "Expect the luck part to average out."),
    NQ("Example: true skill is {s}. A score of {x} was observed. If luck averages zero, what score do you expect next time?",
       "The expected next score is the skill, {A}, since luck is expected to be zero.",
       {"s": [40, 80, 5], "x": [50, 100, 2]}, "s", {"s": 50, "x": 68}, rnd=0),
    NQ("Example (a simple model): next score = average + {r} times (this score minus average), with average {m} and this score {x}. What is the predicted next score? (One decimal.)",
       "{m} + {r} times ({x} minus {m}) = {A}.",
       {"r": [0.1, 0.9, 0.1], "m": [40, 70, 5], "x": [60, 100, 5]}, "m+r*(x-m)", {"r": 0.5, "m": 50, "x": 80}, rnd=1, tol=0.1),
    O("Before crediting an intervention, in order.",
      ["Ask whether it was applied after an extreme result", "Ask how much of the result is luck", "Look for a comparison group that got no intervention", "Compare the change in both groups"],
      "A comparison group shows how much improvement would have happened anyway."),
])

TA4 = L("Survivorship and selection bias", KW + ["survivorship bias", "selection bias", "sampling", "missing data", "who is not in the data"], [
    C("Ask who is missing",
      "Survivorship bias is drawing conclusions only from the cases that made it through some filter: successful companies, books still in print, buildings still standing. Selection bias more broadly is any way the cases you see differ from the ones you do not. The fix is to ask how the data were gathered and what the filtered out cases would look like."),
    M("\"Old buildings were built better; the ones still standing are beautiful and solid.\" What is the problem?",
      ["Nothing", "The poorly built old buildings have mostly fallen down or been demolished, so we only see the survivors", "Old buildings are smaller", "Modern buildings are also old"], 1,
      "The filter of time removed the weak ones."),
    M("A course advertises that its graduates earn high salaries. Which question matters most?",
      ["How nice the campus is", "Who enrolled and who dropped out, and how they compare with similar people who did not take it", "The course's logo", "How long the course is"], 1,
      "If it admits already well paid people or only counts completers, the comparison is biased."),
    W("A filtered sample",
      "Example: a survey of app reviews finds 80% love the app.",
      ["Who writes reviews? Mostly people with strong feelings.",
       "Who left early without reviewing? Unknown.",
       "Who uninstalled before being asked? Missing.",
       "A random sample of all users who installed would answer the real question."],
      "List who could not appear in the data."),
    O("Check for selection, in order.",
      ["Describe how cases got into the data", "List who was filtered out", "Ask how they might differ", "Find or estimate data on the missing cases", "Restate the conclusion for the group the data actually covers"],
      "Sometimes the honest fix is narrowing the conclusion."),
    WR("A blog says: \"Every successful founder I interviewed dropped out of university, so dropping out helps.\" Write what is missing, starting with Missing:, and a better study, starting with Better:.",
       [must("^missing:.*(fail|unsuccess|did not|didn't|not interview|graduat)", "Missing: the founders who failed or the graduates", flags="im"),
        must("^better:", "Better:", flags="im"),
        words(15, 100)],
       "Missing: the many dropouts whose companies failed, and successful founders who graduated, who were never interviewed.\nBetter: follow a large group of people who started companies, compare success rates for dropouts and graduates, and account for differences such as family wealth.",
       "Compare the whole starting group, not only the winners."),
])

TA5 = L("Reading studies", KW + ["studies", "randomized controlled trial", "observational", "p hacking", "sample size", "replication"], [
    C("Design decides how much a study can say",
      "Randomized controlled trials assign the treatment by chance, so differences in outcomes are more likely caused by the treatment. Observational studies can show associations but are open to confounding. Small samples give noisy results. Testing many outcomes and reporting the ones that cross p below 0.05 (p hacking) produces false findings. A single study is a data point; replications and systematic reviews carry more weight."),
    M("A study tested 20 outcomes and reports the one with p below 0.05. What is the concern?",
      ["None", "With 20 tests, about one would cross 0.05 by chance even if nothing works", "The p value is too small", "The sample is too big"], 1,
      "Expected false positives at 0.05 across 20 independent tests: 20 times 0.05 = 1."),
    NQ("Example: {n} independent tests of things that have no real effect, each at a {a}% threshold. How many false positives would you expect?",
       "{n} times {a}% = {A}.",
       {"n": [10, 200, 10], "a": [1, 10, 1]}, "n*a/100", {"n": 20, "a": 5}, rnd=2),
    NQ("Example: with {n} independent tests at 5% and no real effects, what is the chance of at least one false positive, in percent? (One decimal.)",
       "1 minus 0.95 to the power {n}, times 100, is {A}%.",
       {"n": [1, 60, 1]}, "(1-0.95^n)*100", {"n": 20}, rnd=1, tol=0.1),
    O("Read a study, in order.",
      ["What question did it ask, and was it set in advance?", "Randomized or observational?", "How large was the sample?", "How big was the effect, not just whether it was significant?", "Has it been replicated?"],
      "Effect size and replication often matter more than a p value."),
    M("A large observational study links a food to lower disease rates. Which next step is most informative?",
      ["Share it widely", "Look for randomized trials or studies that control for income, exercise and other confounders", "Assume cause", "Ignore it entirely"], 1,
      "Observational links are a reason to investigate, not a conclusion."),
])

TA6 = L("Fermi estimates for forecasting", KW + ["fermi estimate", "estimation", "decomposition", "order of magnitude", "forecasting"], [
    C("Break it into pieces you can guess",
      "A Fermi estimate breaks an unknown quantity into factors you can estimate, multiplies them, and checks the order of magnitude. Errors in the factors partly cancel, so the result is often closer than any single guess. Give a range for each factor and carry it through to see how uncertain the answer is."),
    W("How many piano tuners in a city?",
      "Example: a city of 1,000,000 people. Every number below is an assumption to be checked.",
      ["Households: about 1,000,000 / 2.5 = 400,000.",
       "Suppose 1 in 20 has a piano: 20,000 pianos.",
       "Tuned once a year: 20,000 tunings.",
       "A tuner does about 4 a day for 250 days: 1,000 a year. So about 20 tuners."],
      "Each factor is a guess; the structure makes the guess checkable."),
    NQ("Example: a city of {p} people, {h} people per household, 1 in {k} households has a piano, tuned once a year, and a tuner does 1,000 tunings a year. About how many tuners? (One decimal.)",
       "{p} / {h} / {k} / 1,000 = {A}.",
       {"p": [200000, 5000000, 100000], "h": [2, 4, 0.5], "k": [10, 50, 5]}, "p/h/k/1000", {"p": 1000000, "h": 2.5, "k": 20}, rnd=1, tol=0.1),
    NQ("Example: low and high estimates of a quantity are {lo} and {hi}. What is their geometric mean, a good middle for ranges spanning factors? (Round.)",
       "The square root of {lo} times {hi} is about {A}.",
       {"lo": [10, 100, 10], "hi": [200, 2000, 100]}, "sqrt(lo*hi)", {"lo": 10, "hi": 1000}, rnd=0, tol=1),
    M("Your estimate's factors each might be off by a factor of 2. What should you report?",
      ["A single exact number", "A central estimate with a range, and which factor drives the uncertainty most", "Nothing, it is too uncertain", "Only the highest value"], 1,
      "A range and the biggest driver tell the reader what to check first."),
    O("Make a Fermi estimate, in order.",
      ["Define exactly what you are estimating", "Break it into factors", "Estimate each with a range", "Multiply through", "Sanity check against anything you know"],
      "Definition first; many estimates go wrong by answering a different question."),
])

TA7 = L("Premortems and red teams", KW + ["premortem", "red team", "planning", "failure", "risks", "overconfidence"], [
    C("Imagine it already failed",
      "A premortem asks a team to imagine that a plan has failed badly a year from now and to write down why. This makes it easier to voice doubts that optimism or politeness would otherwise silence. A red team is a group assigned to argue against a plan or attack a system. Both turn criticism from disloyalty into the job."),
    M("Why does the premortem framing help?",
      ["It is more fun", "Assuming failure has happened makes it easier to generate specific reasons, and gives permission to raise them", "It guarantees success", "It replaces planning"], 1,
      "People find it easier to explain a known outcome than to predict an uncertain one."),
    O("Run a premortem, in order.",
      ["Share the plan with everyone", "Ask them to imagine it failed badly one year from now", "Each person writes reasons alone", "Collect and group the reasons", "Change the plan to address the most likely or most serious ones"],
      "Writing alone first prevents the loudest voice from setting the list."),
    WR("Run a solo premortem on a plan of yours (or this one: launching a weekly newsletter). Write at least three reasons it failed, one per line, starting with Failed because:, then one line starting with Change:.",
       [must("(^failed because:[^\\n]*\\n){2,}^failed because:", "Three Failed because: lines", flags="im"),
        must("^change:", "Change:", flags="im"),
        words(25, 150)],
       "Failed because: we ran out of things to say after six issues.\nFailed because: nobody signed up beyond friends and family.\nFailed because: writing took twice as long as planned and we skipped weeks.\nChange: write four issues before launching and plan a monthly schedule first.",
       "Concrete reasons, and a change that addresses the most likely one."),
    NQ("Example: a plan has {n} independent steps, each with a {p}% chance of going fine. What is the chance all go fine, in percent? (One decimal.)",
       "{pp} to the power {n}, times 100, is {A}%.",
       {"n": [2, 12, 1], "p": [70, 99, 1]}, "(p/100)^n*100", {"n": 6, "p": 90}, rnd=1, tol=0.1, show={"pp": "p/100"}),
    C("Why plans need this",
      "A plan with many steps that each look likely can still be unlikely overall, as the last problem shows. Premortems surface the steps nobody was worried about."),
])

TA8 = L("The outside view", KW + ["reference class", "outside view", "planning fallacy", "base rates", "forecasting"], [
    C("How did similar cases turn out?",
      "The inside view forecasts from the details of your own case. The outside view starts from how a reference class of similar cases turned out, then adjusts for what is genuinely different. People tend to underestimate how long their own projects will take, a pattern called the planning fallacy; starting from the outside view counters it."),
    W("Forecast a project with a reference class",
      "Example: your team estimates a feature will take 4 weeks. Your last eight similar features took 5, 6, 6, 7, 8, 8, 9 and 11 weeks.",
      ["Reference class: the eight past features.",
       "Their median is 7.5 weeks; none took 4.",
       "Adjust for real differences: this one has a smaller scope, so perhaps 6 to 7 weeks.",
       "Forecast: about 6 to 8 weeks, with 4 as an optimistic case."],
      "Anchor on the reference class, then adjust modestly."),
    NQ("Example: your own estimate is {e} weeks; past similar projects took {r} times their estimates on average. What is the adjusted forecast? (One decimal.)",
       "{e} times {r} = {A} weeks.",
       {"e": [2, 20, 1], "r": [1, 2.5, 0.1]}, "e*r", {"e": 4, "r": 1.7}, rnd=1, tol=0.1),
    M("Which is the best reference class for forecasting your home renovation's cost?",
      ["Your hopes", "Similar renovations by people you know or published local cost surveys, compared with their initial budgets", "A new office building", "Your grocery bill"], 1,
      "Similar projects, with their original estimates, show the typical overrun."),
    O("Use the outside view, in order.",
      ["Choose a reference class of similar cases", "Find how they turned out", "Make that your starting forecast", "Adjust for real differences, cautiously", "State a range"],
      "Big adjustments away from the reference class need strong reasons."),
    M("Your project feels unique, so the reference class seems irrelevant. What is the usual lesson?",
      ["Uniqueness means ignore history", "Most projects feel unique to their teams; use the broadest sensible reference class and adjust a little", "Pick the most optimistic case", "Do not forecast"], 1,
      "Feeling unique is itself typical."),
])

TA9 = L("Capstone: a forecast with reasons", KW + ["capstone", "forecast", "probability", "reasoning", "prediction"], [
    C("A forecast someone can check",
      "A good forecast names a clear question with a date, gives a probability, explains the base rate and the evidence that moved it, and says what would change it. Then it gets scored. This capstone puts calibration, Bayes, the outside view and premortems into one short piece."),
    M("Which question is forecastable?",
      ["Will the project go well?", "Will the new checkout be live for all users by 30 June?", "Is the economy good?", "Will people like it?"], 1,
      "It has a clear yes or no outcome and a date."),
    NQ("Example: base rate {b}%. The evidence has a likelihood ratio of {r}. What is your forecast, in percent? (One decimal.)",
       "Odds {o} times {r}, converted back, give {A}%.",
       {"b": [10, 80, 5], "r": [0.5, 4, 0.5]}, "(b/(100-b)*r)/(1+b/(100-b)*r)*100", {"b": 40, "r": 2}, rnd=1, tol=0.1,
       show={"o": "b/(100-b)"}),
    O("Write the forecast, in order.",
      ["A precise question with a date", "A base rate from similar cases", "The specific evidence and how it moves you", "Your probability", "What would change your mind, and when you will score it"],
      "Question first; a fuzzy question cannot be scored."),
    WR("Write a forecast about something real (or the checkout launch). Use lines starting with Question:, Base rate:, Evidence:, Forecast:, Would change if: and Score on:. The forecast should be a percentage.",
       [must("^question:.*\\b(by|before|on)\\b", "Question: with a date", flags="im"),
        must("^base rate:.*\\d", "Base rate: with a number", flags="im"),
        must("^evidence:", "Evidence:", flags="im"),
        must("^forecast:\\s*\\d{1,3}\\s*%", "Forecast: as a percentage", flags="im"),
        must("^would change if:", "Would change if:", flags="im"),
        must("^score on:", "Score on:", flags="im"),
        avoid("^forecast:\\s*(100|0)\\s*%", "Not 0% or 100%", flags="im"),
        words(40, 200)],
       "Question: will the new checkout be live for all users by 30 June?\nBase rate: about 3 of our last 8 launches shipped on their planned date, so roughly 40%.\nEvidence: code is complete and testing is half done, which feels like a likelihood ratio of about 2.\nForecast: 57%\nWould change if: the payment provider review takes more than two weeks.\nScore on: 1 July.",
       "Specific, numeric, reasoned and scheduled to be scored."),
    C("Advanced complete",
      "You can think in probabilities, update on evidence, read studies with care and forecast honestly. Expert turns to decisions: process, groups, systems and communicating uncertainty."),
])

# =====================================================================
# Expert: Judgment and decisions
# =====================================================================

TE1 = L("Decision quality versus outcomes", KW + ["decision journal", "journal", "journaling", "resulting", "outcome bias", "decision quality", "process"], [
    C("Good decisions can turn out badly",
      "Judging a decision only by its outcome is called outcome bias, or resulting. A good decision uses the information and time available well; a good outcome also needs luck. A decision journal records, at the time, what you decided, why, what you expected and how confident you were, so you can later judge the process separately from the result."),
    M("You took a well researched job offer and the company folded unexpectedly. What is the fair judgment?",
      ["It was a bad decision", "The outcome was bad; whether the decision was bad depends on what you knew and could have found out at the time", "It was a perfect decision", "Decisions do not matter"], 1,
      "Separate the quality of the reasoning from the luck of the result."),
    O("Write a decision journal entry, in order.",
      ["The decision and the date", "The options you considered", "Why you chose this one", "What you expect to happen, with a probability", "When you will review it"],
      "Write it before the outcome is known, or hindsight rewrites your reasons."),
    WR("Write a decision journal entry for a real or example decision. Use lines starting with Decision:, Options:, Why:, Expect: (with a percentage) and Review on:.",
       [must("^decision:", "Decision:", flags="im"),
        must("^options:[^\\n]*(,| or )", "Options: at least two", flags="im"),
        must("^why:", "Why:", flags="im"),
        must("^expect:.*\\d{1,3}\\s*%", "Expect: with a percentage", flags="im"),
        must("^review on:", "Review on:", flags="im"),
        words(30, 160)],
       "Decision: move our team meeting from weekly to every two weeks.\nOptions: keep weekly, every two weeks, or replace it with written updates.\nWhy: most weekly items are status updates that could be written; fewer meetings free up focus time.\nExpect: 70% that people report the same or better coordination after two months.\nReview on: 1 December.",
       "A record you can judge later on process, not just outcome."),
    NQ("Example: of {n} journaled decisions where you said {p}%, {k} turned out as expected. What percent came true? (One decimal.)",
       "{k} / {n}, times 100, is {A}%, against the {p}% you predicted.",
       {"n": [20, 60, 5], "p": [60, 90, 10], "k": [5, 20, 1]}, "k/n*100", {"n": 20, "p": 70, "k": 12}, rnd=1, tol=0.1),
    M("Your journal shows decisions made late at night turn out worse. What is the useful response?",
      ["Ignore the pattern", "Set a rule: no important decisions after a certain hour unless urgent", "Make more decisions at night", "Stop keeping a journal"], 1,
      "Journals pay off by revealing patterns in your process that you can change."),
])

TE2 = L("Reversible and irreversible decisions", KW + ["reversible", "irreversible", "one way door", "two way door", "speed", "options"], [
    C("Match the care to the cost of being wrong",
      "Some decisions are easy to undo (two way doors): trying a tool, testing a price, a small hire for a short project. Others are hard or impossible to undo (one way doors): selling a house, a major public commitment, firing someone. Slow, careful analysis suits irreversible decisions; for reversible ones, speed and learning by trying usually beat analysis. Another lever is to make a decision more reversible, for example with a trial period."),
    M("Which is most reversible?",
      ["Signing a ten year lease", "Trying a new project tool for one month on one team", "Selling the company", "Publishing a confidential document"], 1,
      "A short, limited trial is easy to undo."),
    M("A team spends six weeks debating which note taking app to use. What is the likely mistake?",
      ["Not enough analysis", "Treating a reversible decision as irreversible; a two week trial would teach more", "Choosing too fast", "Nothing"], 1,
      "Analysis has a cost. For cheap to reverse choices, experiment."),
    O("Decide how carefully to decide, in order.",
      ["Ask how costly it would be to reverse", "Ask whether you can make it more reversible", "If reversible, set a short trial and a review date", "If not, gather information and consider a premortem", "Decide and record why"],
      "The first question sets how much process the decision deserves."),
    NQ("Example: a trial costs {c}. If the change works, it saves {s} a year. You think there is a {p}% chance it works. What is the expected first year value of trying? (Round.)",
       "{p}% times {s} minus {c} = {A}.",
       {"c": [100, 2000, 100], "s": [500, 10000, 500], "p": [10, 90, 10]}, "p/100*s-c", {"c": 500, "s": 3000, "p": 40}, rnd=0),
    WR("Name one decision you face (or an example). Write lines starting with Decision:, Reversible: (yes or no, with why) and Approach:.",
       [must("^decision:", "Decision:", flags="im"),
        must("^reversible:\\s*(yes|no|partly|mostly)", "Reversible: yes or no", flags="im"),
        must("^approach:.*(trial|test|pilot|research|premortem|wait|analy|ask)", "Approach: how you will decide", flags="im"),
        words(20, 120)],
       "Decision: switch our team to a four day week.\nReversible: partly; we can go back, but trust suffers if we reverse quickly.\nApproach: a three month pilot with clear measures and a review date agreed up front.",
       "Matching the approach to how reversible it is."),
])

TE3 = L("Better decisions in groups", KW + ["groups", "wisdom of crowds", "groupthink", "independent estimates", "meetings", "dissent"], [
    C("Collect views before you discuss them",
      "Groups can beat individuals when members bring independent information and their judgments are combined. They do worse when people anchor on the first or loudest opinion, or hold back doubts to keep harmony (groupthink). Simple fixes: have everyone write an estimate or view before discussion, let the most junior person speak first, and assign someone to argue the other side."),
    W("Average independent estimates",
      "Example: five people estimate a project's weeks independently: 6, 8, 5, 12 and 9.",
      ["Mean: (6 + 8 + 5 + 12 + 9) / 5 = 8.",
       "Median: 8.",
       "The spread (5 to 12) shows real uncertainty worth discussing.",
       "If they had discussed first, they might all have said 6 after the first speaker."],
      "Independence first, then combine, then discuss the spread."),
    NQ("Example: four independent estimates are {a}, {b}, {c} and {d}. What is their average? (One decimal.)",
       "({a} + {b} + {c} + {d}) / 4 = {A}.",
       {"a": [2, 20, 1], "b": [2, 20, 1], "c": [2, 20, 1], "d": [2, 20, 1]}, "(a+b+c+d)/4", {"a": 6, "b": 8, "c": 5, "d": 12}, rnd=1, tol=0.1),
    M("Why should the senior person speak last?",
      ["Seniors know less", "Their view tends to anchor others, so speaking last protects independent views", "It is polite", "It saves time"], 1,
      "Order of speaking shapes what others are willing to say."),
    O("Run a decision meeting, in order.",
      ["Share the question and background in advance", "Everyone writes their view and reasons alone", "Reveal views, most junior first", "Discuss the disagreements", "The decider decides and records why"],
      "Writing alone before talking is the single biggest improvement."),
    M("A team always agrees quickly and nobody raises concerns. What is the risk?",
      ["None, it is efficient", "Groupthink: doubts may be suppressed rather than absent", "Too much conflict", "Too many ideas"], 1,
      "Silence is not consent. Ask for concerns explicitly, or assign a devil's advocate."),
])

TE4 = L("Systems thinking: feedback loops", KW + ["systems thinking", "feedback loops", "reinforcing", "balancing", "delays", "stocks and flows"], [
    C("Loops, stocks and delays",
      "A system is a set of parts whose interactions produce behavior over time. A stock is an amount that builds up or drains (money in an account, people on a waitlist); flows change it. Reinforcing loops amplify change (more users attract more users). Balancing loops push toward a target (a thermostat). Delays between action and effect cause overshoot and oscillation."),
    M("A bathroom shower is too cold; you turn it hotter, wait little, turn it more, and it ends up scalding. What causes this?",
      ["A broken heater", "A delay in a balancing loop: you act before seeing the effect of your last change", "A reinforcing loop", "Bad luck"], 1,
      "Delays cause overshoot. Smaller changes and waiting help."),
    M("A popular restaurant gets more popular because people see a queue outside. What kind of loop?",
      ["Balancing", "Reinforcing", "Neither", "Delay"], 1,
      "Popularity feeds more popularity until a balancing limit, such as wait times, kicks in."),
    W("A stock and its flows",
      "Example: a support queue has 120 tickets. Each day 40 arrive and the team resolves 35.",
      ["Net flow: 40 minus 35 = plus 5 a day.",
       "After 10 days: 120 + 50 = 170.",
       "Adding one more person who resolves 8 a day makes the net flow minus 3.",
       "Then the backlog shrinks by 3 a day, taking 40 days to clear 120."],
      "The stock changes by inflow minus outflow, every period."),
    NQ("Example: a backlog of {s} items, {i} arrive a day and {o} are cleared a day. What is the backlog after {d} days?",
       "{s} + ({i} minus {o}) times {d} = {A}.",
       {"s": [50, 500, 10], "i": [10, 60, 5], "o": [10, 60, 5], "d": [5, 30, 5]}, "max(0, s+(i-o)*d)", {"s": 120, "i": 40, "o": 35, "d": 10}, rnd=0),
    O("Map a system, in order.",
      ["Name the behavior over time that worries you", "Identify the stocks involved", "Draw the flows in and out", "Find the reinforcing and balancing loops", "Look for delays, then for where to intervene"],
      "Start from behavior over time; it points to the stocks and loops that matter."),
])

TE5 = L("Metrics and Goodhart's law", KW + ["goodhart's law", "metrics", "kpis", "targets", "gaming", "measurement"], [
    C("When a measure becomes a target",
      "Goodhart's law is usually put as: when a measure becomes a target, it ceases to be a good measure. People find ways to move the number that do not move the goal behind it. Defenses: track several measures that would be hard to game together, pair quantity with quality, keep watching the real goal directly, and change measures when they drift from it."),
    M("A call center targets average call length under 3 minutes. What is the likely gaming?",
      ["Better service", "Agents rush or transfer difficult calls, so problems go unsolved and callers ring back", "Nothing", "Longer calls"], 1,
      "Pair it with a measure of problems solved on the first call."),
    M("Which pairing makes a reading app's \"minutes read\" target harder to game?",
      ["Minutes read alone", "Minutes read plus completion of chapters and user ratings", "Number of app opens", "Number of notifications sent"], 1,
      "Measures that move together only when the real goal improves are harder to fake."),
    O("Design a measure, in order.",
      ["State the real goal in plain words", "Choose a measure that moves when the goal moves", "Ask how someone could move the measure without the goal", "Add a counter measure for that", "Review whether the measures still track the goal"],
      "The third step is the one most teams skip."),
    WR("Pick a metric used at work or school (or: lines of code written). Write lines starting with Goal:, Metric:, Gaming: and Counter:.",
       [must("^goal:", "Goal:", flags="im"),
        must("^metric:", "Metric:", flags="im"),
        must("^gaming:", "Gaming: how it could be gamed", flags="im"),
        must("^counter:", "Counter: a measure that resists it", flags="im"),
        words(20, 120)],
       "Goal: ship useful software.\nMetric: lines of code written.\nGaming: writing verbose code and avoiding deletions, which makes the code harder to maintain.\nCounter: track features shipped and bugs reported by users, and review changes for quality.",
       "Naming the gaming in advance is the best defense."),
    NQ("Example: a team cut average handling time from {a} to {b} minutes, but repeat calls rose from {r1}% to {r2}%. With 1,000 problems, how many calls are now needed if each repeat is one extra call?",
       "1,000 times (1 + {r2}%) = {A} calls, up from {c1}.",
       {"a": [5, 10, 1], "b": [2, 4, 1], "r1": [5, 15, 5], "r2": [20, 40, 5]}, "1000*(1+r2/100)", {"a": 6, "b": 3, "r1": 10, "r2": 30}, rnd=0,
       show={"c1": "1000*(1+r1/100)"}),
])

TE6 = L("Mental models: inversion and first principles", KW + ["mental models", "inversion", "first principles", "problem solving", "assumptions"], [
    C("Two ways to see a problem freshly",
      "Inversion asks the opposite question: instead of how to succeed, ask how you would guarantee failure, then avoid those things. First principles thinking breaks a problem into basic facts that you know are true, and rebuilds from there instead of copying how things are usually done. Both are ways to escape assumptions that nobody has checked."),
    W("Invert a goal",
      "Example goal: run better meetings.",
      ["Inverted: how would we make meetings as bad as possible?",
       "No agenda; invite everyone; let one person talk; end with no decision; never follow up.",
       "Flip each: agenda in advance; only needed people; time box speakers; end with a decision; send notes.",
       "The list of failures is often easier to write, and more complete."],
      "List ways to fail, then avoid each."),
    M("A team assumes a feature needs a mobile app. What is the first principles question?",
      ["Which app framework is best?", "What does the user actually need to do, and what is the simplest way to let them do it?", "How do competitors build apps?", "How many developers can we hire?"], 1,
      "Start from the need, not the usual solution."),
    O("Apply first principles, in order.",
      ["State the problem", "List the assumptions behind the usual solution", "Ask which are actually true, and why", "Rebuild a solution from the true ones", "Compare it with the usual approach"],
      "Many assumptions survive only because nobody checked them."),
    WR("Invert a goal of yours (or: \"save more money\"). Write at least three ways to fail, one per line starting with Fail:, then one line starting with So: that lists what you will do instead.",
       [must("(^fail:[^\\n]*\\n){2,}^fail:", "Three Fail: lines", flags="im"),
        must("^so:", "So:", flags="im"),
        words(20, 120)],
       "Fail: keep the card saved in every shopping app.\nFail: save whatever is left at the end of the month.\nFail: never look at my statements.\nSo: remove saved cards, move savings on payday automatically, and review spending every Sunday.",
       "Each Fail line turns into a concrete action."),
    NQ("Example (first principles cost): a product's materials cost {m}, labor {l} and shipping {s}. Its usual price is {p}. What percent of the price is the basic cost? (One decimal.)",
       "({m} + {l} + {s}) / {p}, times 100, is {A}%.",
       {"m": [5, 50, 5], "l": [5, 40, 5], "s": [2, 20, 2], "p": [100, 400, 20]}, "(m+l+s)/p*100", {"m": 20, "l": 15, "s": 6, "p": 200}, rnd=1, tol=0.1),
])

TE7 = L("Disagreeing productively", KW + ["disagreement", "crux", "double crux", "debate", "persuasion", "steelman"], [
    C("Find the crux",
      "Most disagreements rest on a few beliefs that, if changed, would change someone's view: the crux. Instead of trading conclusions, ask each other: what would make you change your mind? Restate the other view until they agree it is fair (steelmanning). Separate disagreements about facts, which evidence can settle, from disagreements about values, which need trade offs."),
    M("Two colleagues argue about remote work. One says productivity fell; the other says people are happier. What is likely happening?",
      ["One is lying", "They are weighing different things: a factual question about productivity and a values question about what matters", "They agree", "Nothing can be done"], 1,
      "Name both. The factual part may be checkable; the values part needs a trade off."),
    O("Work through a disagreement, in order.",
      ["Restate the other view until they agree it is fair", "Separate facts from values", "Ask each side what would change their mind", "Find evidence on the factual crux", "Decide how to trade off the values"],
      "Restating first lowers the temperature and surfaces the real point."),
    WR("Write a question you could ask in a disagreement to find the crux, and a fair one sentence restatement of a view you disagree with. Use lines starting with Question: and Restatement:.",
       [must("^question:.*\\?", "Question: ending in a question mark", flags="im"),
        must("^question:.*(change your mind|convince|would it take|what would)", "Asks what would change their mind", flags="im"),
        must("^restatement:", "Restatement:", flags="im"),
        avoid("\\b(stupid|idiot|obviously wrong)\\b", "No insults"),
        words(15, 100)],
       "Question: what would you need to see to change your mind about the office move?\nRestatement: you think being in one place helps new people learn faster, and that is worth the longer commute.",
       "A crux question and a restatement the other person would sign."),
    M("Which response best steelmans \"we should not raise prices\"?",
      ["\"You just like being popular.\"", "\"You think our customers are price sensitive and a rise could lose more revenue than it gains.\"", "\"You hate money.\"", "\"You have not thought about it.\""], 1,
      "A steelman states the strongest version of the view, in terms its holder would accept."),
    NQ("Example: a price rise of {r}% would lose {l}% of customers. By what percent does revenue change? (One decimal.)",
       "{k} times {m}, minus 1, times 100, is {A}%. This is the factual crux the two sides can check.",
       {"r": [5, 30, 5], "l": [2, 30, 2]}, "((1+r/100)*(1-l/100)-1)*100", {"r": 10, "l": 8}, rnd=1, tol=0.1,
       show={"k": "1+r/100", "m": "1-l/100"}),
])

TE8 = L("Communicating uncertainty", KW + ["uncertainty", "probability words", "ranges", "confidence", "estimative language"], [
    C("Say how sure you are, in a way people read the same",
      "Words such as likely, possible and probably are read very differently by different people. Some intelligence agencies have published scales tying words to probability ranges for this reason. Clearer options: give a number or range (\"about 70%\", \"between 3 and 5 weeks\"), say what the estimate rests on, and say what would change it."),
    M("Which statement communicates uncertainty most clearly?",
      ["\"It might slip.\"", "\"We expect launch in 3 to 5 weeks; I would put about 70% on 4 weeks or sooner, mostly depending on the payment review.\"", "\"Soon.\"", "\"It is possible we are late.\""], 1,
      "A range, a probability and the main driver."),
    O("Communicate an estimate, in order.",
      ["The best estimate", "The range", "How confident you are", "What it depends on most", "When you will update it"],
      "Lead with the answer, then the uncertainty around it."),
    WR("Rewrite this vague update with a range, a probability and the main driver: \"The report will probably be done soon, maybe.\"",
       [must("\\d+\\s*(to|and)\\s*\\d+", "Gives a range"),
        must("\\d{1,3}\\s*%", "Gives a probability"),
        must("(depend|driver|if|unless|assum|waiting|because)", "Names the main driver"),
        avoid("\\bmaybe\\b", "Drops \"maybe\""),
        words(15, 80)],
       "The report will be done in 3 to 5 days; I am about 80% confident in 4 days or fewer. It depends mainly on getting the sales data by Wednesday.",
       "Specific and honest about what it rests on."),
    NQ("Example: you give {n} estimates as 80% ranges. How many would you expect to contain the true value if you are calibrated?",
       "80% of {n} = {A}.",
       {"n": [5, 100, 5]}, "0.8*n", {"n": 20}, rnd=1),
    M("Your 80% ranges contained the truth only half the time. What should you do?",
      ["Make ranges narrower", "Make ranges wider until about 80% contain the truth", "Stop giving ranges", "Nothing"], 1,
      "Ranges that are too narrow are a common form of overconfidence."),
])

TE9 = L("Capstone: a decision memo", KW + ["capstone", "decision memo", "recommendation", "options", "trade offs", "risks"], [
    C("One page to decide",
      "A decision memo gives the decision needed and by when, the options, a recommendation with reasons, the key uncertainties with probabilities, the risks with how you will reduce them, how reversible it is, and what would change the recommendation. It pulls together everything in this ladder: clear arguments, base rates, expected value, premortems, metrics and honest uncertainty."),
    M("What should come first in a decision memo?",
      ["The history of the project", "The decision needed, by when, and the recommendation", "A list of every option ever considered", "Acknowledgments"], 1,
      "Answer first. Readers decide whether to read further from the first lines."),
    NQ("Example: option A has a {p}% chance of gaining {g} and otherwise loses {l}. What is its expected value? (Round.)",
       "{p}% times {g} minus {q}% times {l} = {A}.",
       {"p": [10, 90, 10], "g": [1000, 20000, 1000], "l": [500, 10000, 500]}, "p/100*g-(1-p/100)*l", {"p": 60, "g": 10000, "l": 5000}, rnd=0,
       show={"q": "100-p"}),
    O("Write the memo, in order.",
      ["Decision needed and recommendation", "Options considered", "Reasons and expected value", "Key uncertainties and risks, with mitigations", "Reversibility and what would change the recommendation"],
      "Recommendation up front; the rest supports or qualifies it."),
    WR("Write a decision memo for a real or example decision. Use lines starting with Decision:, Recommendation:, Options:, Reasons:, Uncertainty: (with a percentage), Risks:, Reversible: and Would change if:.",
       [must("^decision:", "Decision:", flags="im"),
        must("^recommendation:", "Recommendation:", flags="im"),
        must("^options:", "Options:", flags="im"),
        must("^reasons:", "Reasons:", flags="im"),
        must("^uncertainty:.*\\d{1,3}\\s*%", "Uncertainty: with a percentage", flags="im"),
        must("^risks:", "Risks:", flags="im"),
        must("^reversible:", "Reversible:", flags="im"),
        must("^would change if:", "Would change if:", flags="im"),
        avoid("\\b(obviously|clearly|guaranteed)\\b", "No words that skip the reasoning"),
        words(70, 300)],
       "Decision: whether to open a second shop location this year; needed by 1 November.\nRecommendation: run a three month pop up in the new area first, then decide.\nOptions: sign a five year lease now, run a pop up first, or wait a year.\nReasons: a lease is hard to reverse; a pop up costs about a tenth as much and tests demand directly.\nUncertainty: I put about 55% on the new area matching our current sales per customer, based on two similar local openings.\nRisks: the preferred site may be taken; we will ask the landlord for a right of first refusal.\nReversible: the pop up yes; the lease no.\nWould change if: pop up sales reach 80% of our current shop's level in the first two months.",
       "Answer first, honest uncertainty, risks handled and a clear trigger to revisit."),
    C("Expert complete",
      "You can judge decisions by process, match care to reversibility, run groups well, think in systems and measures, disagree productively and communicate uncertainty. Keep the decision journal going: it is how all of this keeps improving."),
])


def add(courses, picks):
    courses.append(course("thinking-intermediate", "Critical thinking", "Intermediate", "Arguments you can test", "thinking", "Critical thinking", 55,
        "Premises, validity, fallacies, sources, base rates, confounders, expected value and second order effects.",
        [("Arguments", [TI1, TI2, TI3]), ("Evidence", [TI4, TI5, TI6]),
         ("Consequences", [TI7, TI8, TI9])], "thinking"))
    courses.append(course("thinking-advanced", "Probabilistic reasoning", "Advanced", "Reasoning under uncertainty", "thinking-intermediate", "Critical thinking", 85,
        "Calibration, Bayes, regression to the mean, selection bias, studies, Fermi estimates, premortems and the outside view.",
        [("Probabilities", [TA1, TA2, TA3]), ("Evidence with care", [TA4, TA5, TA6]),
         ("Forecasting", [TA7, TA8, TA9])], "thinking"))
    courses.append(course("thinking-expert", "Decision making", "Expert", "Judgment and decisions", "thinking-advanced", "Probabilistic reasoning", 85,
        "Decision journals, reversibility, group decisions, systems, metrics, mental models, disagreement and uncertainty.",
        [("Deciding well", [TE1, TE2, TE3]), ("Systems and measures", [TE4, TE5, TE6]),
         ("Judgment with others", [TE7, TE8, TE9])], "thinking"))
