"""Math ladder: Intermediate, Advanced and Expert courses that follow
"Numbers you can use" (math). Hands-on work is worked problems you reveal
step by step, numeric problems that re-roll with fresh numbers (their
fixed versions are rendered from the same formula, so they cannot
disagree), explore sliders and short write ups. Every number in a prompt
is a labeled example, not a statistic about the world.
Rebuild with: python3 build_library.py
"""
from ladder_kit import C, W, M, O, L, X, WR, NQ, course, words, must, avoid, lines

KW = ["math", "numbers"]

# =====================================================================
# Intermediate: Math for real decisions
# =====================================================================

MI1 = L("Percent change and percentage points", KW + ["percent", "percentage points", "percent change", "increase", "decrease"], [
    C("Change divided by where you started",
      "Percent change is (new minus old) divided by old, times 100. The base is always the starting value, which is why a rise from 50 to 75 is 50% but a fall from 75 back to 50 is only 33%. When the thing itself is a percentage, such as an interest rate going from 4% to 5%, the difference is 1 percentage point, which is a 25% increase in the rate. Saying which one you mean avoids most confusion."),
    W("Up and back down",
      "Example: a price goes from 80 to 100, then back to 80. What are the two percent changes?",
      ["Up: (100 minus 80) divided by 80 is 20 / 80 = 0.25, so a 25% rise.",
       "Down: (80 minus 100) divided by 100 is minus 20 / 100, so a 20% fall.",
       "Same 20 in money, different bases, different percentages.",
       "That is why a 25% rise followed by a 20% fall lands exactly where you started."],
      "Always ask: percent of what?"),
    NQ("Example: a monthly bill rises from {a} to {b}. What is the percent increase?",
       "({b} minus {a}) divided by {a}, times 100, is {A}%.",
       {"a": [40, 80, 5], "b": [85, 120, 5]}, "(b-a)/a*100", {"a": 60, "b": 90}, rnd=1, tol=0.1),
    M("A loan rate goes from 4% to 6%. Which statement is correct?",
      ["The rate rose 2%", "The rate rose 2 percentage points, which is a 50% increase in the rate", "The rate rose 50 percentage points", "The rate doubled"], 1,
      "The gap is 2 points. Relative to the old rate of 4, that is a 50% increase. Both are true; say which you mean."),
    NQ("Example: a stock falls {d}%. What percent rise would bring it back to where it started?",
       "After a {d}% fall you hold {k} of the original. To get back, multiply by 1 / {k}, a rise of {A}%.",
       {"d": [10, 50, 10]}, "(1/(1-d/100)-1)*100", {"d": 20}, rnd=1, tol=0.1, show={"k": "1-d/100"}),
    X("Losses need bigger gains",
      "Drag the size of a fall. The line shows the rise needed to recover. Small falls need roughly equal rises; large falls need much larger ones.",
      "(1/(1-x/100)-1)*100", "x", 0, 80, 5, "Fall (%)", "Rise needed to recover (%)"),
    O("Compute a percent change, in order.",
      ["Find the starting value", "Subtract it from the new value", "Divide the difference by the starting value", "Multiply by 100 and label it rise or fall"],
      "The starting value appears twice: as the thing you subtract and as the base you divide by."),
    C("Watch the base in the news",
      "Crime up 50% can mean from 2 cases to 3. When a percentage sounds dramatic, look for the counts behind it. A big percent of a tiny base is still tiny."),
])

MI2 = L("Reverse percentages and chained changes", KW + ["reverse percentage", "original price", "discount", "tax", "successive changes", "multiplier"], [
    C("Think in multipliers",
      "A 20% rise is multiplying by 1.20. A 15% discount is multiplying by 0.85. Thinking in multipliers makes two hard problems easy. Chained changes multiply: a 10% rise then a 10% fall is 1.10 times 0.90 = 0.99, a 1% net fall. Reverse percentages divide: if a price after 20% tax is 60, the price before tax is 60 / 1.20 = 50, not 60 minus 20%."),
    W("Undo a sales tax",
      "Example: a receipt says 54.00 including a 20% tax. What was the price before tax?",
      ["Before tax, times 1.20, equals 54.",
       "So before tax equals 54 / 1.20 = 45.",
       "Check: 45 times 1.20 is 54. Correct.",
       "The tempting wrong answer, 54 minus 20% = 43.20, takes 20% of the wrong base."],
      "To undo a change, divide by its multiplier."),
    NQ("Example: after a {p}% discount, a jacket costs {s}. What was the original price?",
       "Original times {m} = {s}, so the original is {s} / {m} = {A}.",
       {"p": [10, 40, 5], "s": [36, 90, 6]}, "s/(1-p/100)", {"p": 25, "s": 60}, rnd=2, tol=0.01, show={"m": "1-p/100"}),
    NQ("Example: a price rises {a}% and then falls {b}%. What is the overall change, in percent? (Use a negative number for a fall.)",
       "Multiply: {ma} times {mb} = {f}. The overall change is {A}%.",
       {"a": [10, 50, 10], "b": [10, 50, 10]}, "((1+a/100)*(1-b/100)-1)*100", {"a": 20, "b": 20}, rnd=1, tol=0.1,
       show={"ma": "1+a/100", "mb": "1-b/100", "f": "(1+a/100)*(1-b/100)"}),
    M("A shop offers 30% off, then an extra 20% off the reduced price. What is the total discount?",
      ["50%", "44%", "56%", "40%"], 1,
      "0.70 times 0.80 is 0.56, so you pay 56% and save 44%. Discounts on discounts are smaller than they sound."),
    O("Find an original value after a change, in order.",
      ["Write the change as a multiplier", "Write: original times multiplier equals the new value", "Divide the new value by the multiplier", "Check by multiplying back"],
      "The check takes five seconds and catches the subtract the percentage mistake every time."),
    C("Growth rates over years multiply too",
      "Three years of 10% growth is 1.1 times 1.1 times 1.1, about 1.331, a 33.1% rise, not 30%. That small gap is compounding, and it grows with time."),
])

MI3 = L("Rates and unit conversions", KW + ["rates", "units", "conversion", "unit price", "speed", "per"], [
    C("Units are part of the answer",
      "Rates compare two quantities: kilometers per hour, price per kilogram, liters per 100 km. Conversions are multiplications by a fraction equal to one, such as 1,000 m / 1 km, arranged so unwanted units cancel. Writing the units next to every number turns most rate problems into bookkeeping."),
    W("Compare unit prices",
      "Example: pack A is 750 g for 4.50. Pack B is 1.2 kg for 6.60. Which is cheaper per kilogram?",
      ["A: 750 g is 0.75 kg. 4.50 / 0.75 = 6.00 per kg.",
       "B: 6.60 / 1.2 = 5.50 per kg.",
       "B is cheaper by 0.50 per kg.",
       "Convert to the same unit first, then divide price by quantity."],
      "Same unit, then price over quantity."),
    NQ("Example: a pack of {g} g costs {p}. What is the price per kilogram?",
       "{g} g is {kg} kg. {p} divided by {kg} is {A} per kg.",
       {"g": [250, 1000, 250], "p": [2, 8, 0.5]}, "p/(g/1000)", {"g": 500, "p": 3.5}, rnd=2, tol=0.01, show={"kg": "g/1000"}),
    NQ("Example: you drive {d} km at an average of {v} km per hour. How many minutes does it take?",
       "{d} divided by {v} is {h} hours; times 60 is {A} minutes.",
       {"d": [30, 180, 15], "v": [40, 100, 10]}, "d/v*60", {"d": 90, "v": 60}, rnd=1, tol=0.5, show={"h": "d/v"}),
    M("A car uses 6 liters per 100 km. How far can it go on 45 liters?",
      ["270 km", "750 km", "7.5 km", "450 km"], 1,
      "45 liters divided by 6 liters per 100 km is 7.5 hundreds of km, which is 750 km."),
    O("Convert units with confidence, in order.",
      ["Write the starting quantity with its unit", "Multiply by conversion fractions so unwanted units cancel", "Cancel the units and multiply the numbers", "Check the result is a sensible size"],
      "If the units do not cancel to the one you want, the setup is wrong before any arithmetic happens."),
    C("Average speed is not the average of speeds",
      "Drive 60 km at 30 km per hour and 60 km back at 60 km per hour. Total 120 km in 3 hours is 40 km per hour, not 45. Average rates weight by time, not by trips."),
])

MI4 = L("Solving for the unknown", KW + ["algebra", "equations", "solve", "unknown", "formula", "rearrange"], [
    C("An equation is a balance",
      "Whatever you do to one side of an equation, do to the other, and it stays true. Solving means undoing what was done to the unknown, in reverse order. If a number was multiplied by 3 and then had 5 added, subtract 5 first, then divide by 3. The same moves rearrange any formula to make another quantity the subject."),
    W("Undo in reverse order",
      "Example: a taxi charges a 3.50 flag fall plus 2.25 per km. Your fare was 21.50. How far did you go?",
      ["Write it: 3.50 + 2.25 times d = 21.50.",
       "Undo the addition last done: subtract 3.50 from both sides, 2.25 times d = 18.00.",
       "Undo the multiplication: divide by 2.25, d = 8.",
       "Check: 3.50 + 2.25 times 8 = 3.50 + 18 = 21.50."],
      "Reverse the operations, then check by substituting back."),
    NQ("Example: a gym charges a {f} joining fee plus {m} a month. After how many months will you have paid {t} in total?",
       "{f} + {m} times n = {t}, so n = ({t} minus {f}) / {m} = {A}.",
       {"f": [20, 60, 10], "m": [15, 40, 5], "n": [4, 12, 1]}, "n", {"f": 40, "m": 25, "n": 8}, rnd=0, show={"t": "f+m*n"}),
    NQ("Example: the formula for a temperature in Fahrenheit is F = 1.8C + 32. What is {F} F in Celsius?",
       "C = (F minus 32) / 1.8 = ({F} minus 32) / 1.8 = {A}.",
       {"F": [50, 104, 9]}, "(F-32)/1.8", {"F": 77}, rnd=1, tol=0.1),
    M("Rearrange speed = distance / time to make time the subject.",
      ["time = speed times distance", "time = distance / speed", "time = speed / distance", "time = distance minus speed"], 1,
      "Multiply both sides by time, then divide both sides by speed."),
    O("Solve a two step equation, in order.",
      ["Write the equation from the words", "Undo the addition or subtraction", "Undo the multiplication or division", "Substitute back to check"],
      "Writing the equation is usually the hard part. The solving is mechanical."),
    C("Check the size, not only the arithmetic",
      "If you solve for a person's age and get 312, the algebra may be right but the setup is wrong. A quick sense check catches setup errors no amount of careful arithmetic will."),
])

MI5 = L("Linear models: start and rate", KW + ["linear", "slope", "intercept", "rate of change", "graphs", "models"], [
    C("A starting value plus a steady rate",
      "Many real situations are roughly linear: a fixed fee plus a cost per unit, a tank draining at a steady rate, a salary plus commission. They all fit y = start + rate times x. The rate is the slope: how much y changes when x goes up by one. Two points are enough to find both: rate = change in y / change in x, then work back to the start."),
    W("Find the model from two points",
      "Example: a phone plan costs 35 for 2 GB and 55 for 6 GB. Find the model.",
      ["Rate: (55 minus 35) / (6 minus 2) = 20 / 4 = 5 per GB.",
       "Start: 35 = start + 5 times 2, so start = 25.",
       "Model: cost = 25 + 5 times GB.",
       "Check the other point: 25 + 5 times 6 = 55. Correct."],
      "Rate from the two changes, start from either point."),
    NQ("Example: a plan costs {c1} for {x1} GB and {c2} for {x2} GB, and is linear. What is the cost per extra GB?",
       "({c2} minus {c1}) divided by ({x2} minus {x1}) is {A}.",
       {"s": [10, 30, 5], "r": [2, 8, 1], "x1": [1, 3, 1], "x2": [5, 10, 1]}, "r", {"s": 20, "r": 4, "x1": 2, "x2": 7}, rnd=2,
       show={"c1": "s+r*x1", "c2": "s+r*x2"}),
    X("Slope and start",
      "Example model: cost = 25 + 5 times GB. Drag the number of GB and watch the cost rise by the same amount every step. That steady step is what linear means.",
      "25 + 5*x", "x", 0, 20, 1, "Gigabytes", "Monthly cost"),
    M("Plan A is 30 a month plus 2 per GB. Plan B is 10 a month plus 6 per GB. When does A become cheaper?",
      ["Above 3 GB", "Above 5 GB", "Above 10 GB", "Never"], 1,
      "Equal when 30 + 2x = 10 + 6x, so 20 = 4x and x = 5. Above 5 GB, A's lower rate wins."),
    NQ("Example: Plan A is {a} a month plus {ra} per GB. Plan B is {b} a month plus {rb} per GB. At how many GB do they cost the same?",
       "{a} + {ra}x = {b} + {rb}x, so x = ({a} minus {b}) / ({rb} minus {ra}) = {A}.",
       {"a": [25, 45, 5], "b": [5, 20, 5], "ra": [1, 3, 1], "rb": [5, 8, 1]}, "(a-b)/(rb-ra)", {"a": 30, "b": 10, "ra": 2, "rb": 6}, rnd=2, tol=0.01),
    C("Linear is a model, not a law",
      "Real costs often bend: volume discounts, caps, steps. A linear model is useful within the range you checked it on. Outside that range, check again before trusting it."),
])

MI6 = L("Break even and margins", KW + ["break even", "fixed costs", "variable costs", "margin", "profit", "pricing"], [
    C("When does it start paying?",
      "Costs come in two kinds: fixed costs that stay the same whatever you sell (rent, a machine) and variable costs per unit (ingredients, shipping). Each unit sold contributes its price minus its variable cost toward the fixed costs. Break even units = fixed costs / (price minus variable cost per unit). Every unit after that is profit."),
    W("A market stall",
      "Example: a stall costs 120 a day. Each sandwich costs 2.50 to make and sells for 6. How many to break even?",
      ["Contribution per sandwich: 6 minus 2.50 = 3.50.",
       "Break even: 120 / 3.50 is about 34.3.",
       "You cannot sell a third of a sandwich, so round up: 35 sandwiches.",
       "At 35, profit is 35 times 3.50 minus 120 = 2.50."],
      "Fixed costs divided by contribution per unit, rounded up."),
    NQ("Example: fixed costs are {f} a month. Each unit sells for {p} and costs {v} to make. How many units to break even? (Round up to a whole unit.)",
       "Contribution is {p} minus {v} = {c}. {f} / {c}, rounded up, is {A}.",
       {"f": [400, 3000, 200], "p": [12, 30, 2], "v": [4, 10, 1]}, "ceil(f/(p-v))", {"f": 1200, "p": 20, "v": 8}, rnd=0, show={"c": "p-v"}),
    NQ("Example: an item sells for {p} and costs {v} to make. What is the margin as a percent of the price?",
       "({p} minus {v}) / {p}, times 100, is {A}%.",
       {"p": [20, 60, 5], "v": [5, 15, 1]}, "(p-v)/p*100", {"p": 40, "v": 10}, rnd=1, tol=0.1),
    M("Markup and margin: an item costs 60 and sells for 100. Which is right?",
      ["Markup 40%, margin 60%", "Markup 66.7% on cost, margin 40% of price", "Both 40%", "Both 66.7%"], 1,
      "Markup is profit over cost: 40 / 60. Margin is profit over price: 40 / 100. Mixing them up is a classic pricing error."),
    O("Work out break even, in order.",
      ["List the fixed costs for the period", "Find the variable cost per unit", "Subtract it from the price to get contribution per unit", "Divide fixed costs by contribution and round up"],
      "Get the costs right first. Forgetting a fixed cost such as card fees or insurance is the usual reason a plan that broke even on paper loses money."),
    C("Lower price, higher break even",
      "Discounting cuts the contribution per unit, so you need more sales just to stand still. A 20% discount on a product with a 40% margin halves the contribution; you need twice the units to earn the same."),
])

MI7 = L("Exponential growth and decay", KW + ["exponential", "growth", "decay", "half life", "doubling", "compound"], [
    C("Same percentage, every period",
      "Linear change adds the same amount each period; exponential change multiplies by the same factor. Value after n periods = start times (1 + r) to the power n, with r negative for decay. Exponential growth looks slow at first and then fast, which is why it is easy to underestimate early and hard to stop later."),
    W("Two towns",
      "Example: Town A grows by 500 people a year. Town B grows 5% a year. Both start at 10,000. Compare after 1 and after 20 years.",
      ["Year 1: A has 10,500; B has 10,000 times 1.05 = 10,500. Identical.",
       "Year 20: A has 10,000 + 20 times 500 = 20,000.",
       "B has 10,000 times 1.05 to the power 20, about 26,533.",
       "The same first year, very different twenty years later."],
      "Linear adds; exponential multiplies, and the gap grows."),
    NQ("Example: a population of {p} grows {r}% a year. What is it after {n} years? (Round to a whole number.)",
       "{p} times {g} to the power {n} is about {A}.",
       {"p": [1000, 5000, 500], "r": [2, 8, 1], "n": [3, 10, 1]}, "p*(1+r/100)^n", {"p": 2000, "r": 5, "n": 4}, rnd=0, tol=1, show={"g": "1+r/100"}),
    NQ("Example: a medicine's amount in the body halves every {h} hours. What percent of a dose is left after {t} hours?",
       "{t} hours is {k} half lives. 0.5 to the power {k}, times 100, is {A}%.",
       {"h": [2, 8, 2], "k": [1, 4, 1]}, "100*0.5^k", {"h": 4, "k": 3}, rnd=2, tol=0.01, show={"t": "h*k"}),
    X("Doubling time",
      "Drag the growth rate. The value shows how many periods it takes to double. Compare it with 72 divided by the rate: the rule of 72 is a good shortcut for everyday rates.",
      "log(2)/log(1+x/100)", "x", 1, 20, 1, "Growth rate per period (%)", "Periods to double"),
    M("Something doubles every 3 days. It fills a pond on day 30. When was the pond half full?",
      ["Day 15", "Day 27", "Day 29", "Day 10"], 1,
      "One doubling before full: day 30 minus 3. Exponential processes look small until the last few periods."),
    C("Nothing grows exponentially forever",
      "Real growth runs into limits: space, money, customers, food. Exponential models describe the early phase well; plan for the curve to bend."),
])

MI8 = L("Logarithms: counting multiplications", KW + ["logarithm", "log", "orders of magnitude", "scale", "doublings"], [
    C("A log asks how many times",
      "A logarithm answers: how many times do I multiply by this base to get that number? log base 2 of 8 is 3, because 2 times 2 times 2 is 8. log base 10 of 1,000 is 3. Logs turn multiplying into adding, which is why they are used for scales that span huge ranges, and why they solve growth problems: how long until something doubles or reaches a target."),
    W("How many years to reach a target?",
      "Example: 5,000 grows 6% a year. When does it reach 8,000?",
      ["Write it: 5,000 times 1.06 to the power n = 8,000.",
       "Divide: 1.06 to the power n = 1.6.",
       "Take logs: n = log(1.6) / log(1.06), about 0.470 / 0.0583.",
       "n is about 8.07, so just over 8 years."],
      "Divide to isolate the power, then use logs to bring the exponent down."),
    NQ("How many times must you double 1 to reach {x}? (log base 2)",
       "2 to the power {A} is {x}.",
       {"k": [3, 12, 1]}, "k", {"k": 6}, rnd=0, show={"x": "2^k"}),
    NQ("Example: {s} grows {r}% a year. How many years until it reaches {t}? (One decimal.)",
       "n = log({t} / {s}) / log({g}), which is about {A} years.",
       {"s": [1000, 5000, 1000], "r": [3, 10, 1], "m": [1.5, 3, 0.5]}, "log(m)/log(1+r/100)", {"s": 5000, "r": 6, "m": 1.5}, rnd=1, tol=0.1,
       show={"t": "s*m", "g": "1+r/100"}),
    M("A scale goes up by 1 for every tenfold increase in what it measures. Level 6 versus level 4 means...",
      ["2 times more", "20 times more", "100 times more", "6/4 times more"], 2,
      "Two steps of tenfold: 10 times 10. Log scales hide big multiplications behind small differences."),
    O("Solve a growth problem for time, in order.",
      ["Write start times growth factor to the power n equals target", "Divide both sides by the start", "Take the log of both sides", "Divide by the log of the growth factor"],
      "Any base of log works, as long as you use the same one on both sides."),
    C("Plot growth on a log scale",
      "On a log scale, steady percentage growth is a straight line. If a chart of something growing looks like a straight line on a log axis, it is growing at a steady rate; if the line bends down, growth is slowing."),
])

MI9 = L("Capstone: compare two offers", KW + ["capstone", "comparison", "decision", "model", "plans", "offers"], [
    C("Put the level together",
      "Real decisions mix the tools from this level: percent changes, multipliers, rates, linear models, break even points and growth. You will compare two options with a model, find where they cross, and write the decision with its condition."),
    W("Two job offers",
      "Example: Offer A pays 50,000 with 3% yearly raises. Offer B pays 53,000 with 1% yearly raises. Which pays more in year 5?",
      ["Year 5 is four raises after year 1.",
       "A: 50,000 times 1.03 to the power 4, about 56,275.",
       "B: 53,000 times 1.01 to the power 4, about 55,152.",
       "A overtakes B by year 5, even though B starts 3,000 higher. Over five years in total, B still paid a little more."],
      "Compare on the measure that matters to you, over the time you expect to stay."),
    NQ("Example: Offer A pays {a} rising {ra}% a year; Offer B pays {b} rising {rb}% a year. What does A pay in year 5 (after four raises)? Round to a whole number.",
       "{a} times {ga} to the power 4 is about {A}.",
       {"a": [40000, 60000, 5000], "ra": [2, 5, 1], "b": [45000, 65000, 1000], "rb": [0, 2, 1]}, "a*(1+ra/100)^4", {"a": 50000, "ra": 3, "b": 53000, "rb": 1}, rnd=0, tol=1,
       show={"ga": "1+ra/100"}),
    NQ("Example: Plan A costs {fa} upfront and {ma} a month. Plan B costs {fb} upfront and {mb} a month. After how many months is A cheaper overall? (Round up to a whole month.)",
       "They are equal when {fa} + {ma}n = {fb} + {mb}n, at n = ({fa} minus {fb}) / ({mb} minus {ma}). Rounded up: {A}.",
       {"fa": [200, 600, 100], "ma": [10, 20, 5], "fb": [0, 100, 50], "mb": [30, 50, 5]}, "ceil((fa-fb)/(mb-ma))", {"fa": 400, "ma": 15, "fb": 50, "mb": 40}, rnd=0),
    O("Compare two options with a model, in order.",
      ["Write a formula for the cost or value of each option", "Find where they are equal", "Decide which side of that point you expect to be on", "Write the decision with its condition"],
      "The crossover point turns a vague which is better into a precise if you stay longer than n months, choose A."),
    WR("Write a decision for a comparison of two options from your life (or the plans above). Name both options, the crossover point with its number, and the decision with its condition, such as if I keep it longer than 14 months.",
       [must("\\d", "Uses a number for the crossover"),
        must("(if|when|unless|longer than|more than|after)", "States the condition"),
        must("(choose|pick|go with|take|buy|stay with|switch)", "States a decision"),
        words(25, 120)],
       "Plan A costs 400 upfront and 15 a month; Plan B costs 50 upfront and 40 a month. They cost the same at 14 months. I expect to keep the phone for two years, so I will choose Plan A; if I thought I would switch within a year, B would be cheaper.",
       "A decision with its condition is robust: if your situation changes, you already know what to do."),
    C("Intermediate complete",
      "You can model everyday decisions with percent, rates, lines and growth. Advanced moves to statistics: how to reason with data and uncertainty."),
])

# =====================================================================
# Advanced: Statistics you can trust
# =====================================================================

MA1 = L("Distributions and the normal curve", KW + ["distribution", "normal", "bell curve", "histogram", "skew", "statistics"], [
    C("The shape of the data",
      "A distribution shows how often each value occurs. Many measurements that are the sum of lots of small effects, such as heights or measurement errors, are roughly normal: a symmetric bell around the mean. Others are skewed: incomes, house prices and waiting times have long right tails, where the mean is pulled above the median. The shape decides which summary numbers are honest."),
    M("House prices in a city have a long right tail. Which summary best describes a typical house?",
      ["The mean", "The median", "The maximum", "The range"], 1,
      "A few very expensive houses drag the mean up. The median, the middle value, stays with the typical house."),
    C("The 68, 95, 99.7 rule",
      "For a normal distribution, about 68% of values lie within one standard deviation of the mean, about 95% within two, and about 99.7% within three. It is a rule for normal data only; skewed data can break it badly."),
    NQ("Example: test scores are roughly normal with mean {m} and standard deviation {s}. About what percent of scores fall between {lo} and {hi}?",
       "{lo} to {hi} is the mean plus or minus two standard deviations, which covers about {A}% of a normal distribution.",
       {"m": [60, 80, 5], "s": [4, 10, 2]}, "95", {"m": 70, "s": 6}, rnd=0, show={"lo": "m-2*s", "hi": "m+2*s"}),
    NQ("Example: heights are roughly normal with mean {m} cm and standard deviation {s} cm. About what percent are taller than {hi} cm?",
       "{hi} is one standard deviation above the mean. 68% lie within one, so 32% lie outside, split evenly: about {A}% above.",
       {"m": [160, 180, 5], "s": [5, 10, 1]}, "16", {"m": 170, "s": 7}, rnd=0, show={"hi": "m+s"}),
    O("Summarize a new data set, in order.",
      ["Plot it, for example as a histogram", "Look at the shape: symmetric, skewed, several peaks", "Choose summaries that fit the shape", "Report them with the plot"],
      "Plot first. Summary numbers computed before you look can describe a shape that is not there."),
    C("Two peaks means two groups",
      "A distribution with two humps often mixes two populations, such as weekday and weekend sales. Averaging them describes neither. Split the data first."),
])

MA2 = L("Standard deviation and z scores", KW + ["standard deviation", "variance", "z score", "spread", "outliers"], [
    C("How far from typical",
      "Standard deviation measures typical distance from the mean. To compute it by hand: find the mean, subtract it from each value, square the differences, average them (divide by n for a whole population, or n minus 1 for a sample), and take the square root. A z score expresses a value in standard deviations from the mean: z = (value minus mean) / standard deviation, which lets you compare results on different scales."),
    W("Standard deviation of four numbers",
      "Example: the values 2, 4, 4, 6, treated as a whole population.",
      ["Mean: (2 + 4 + 4 + 6) / 4 = 4.",
       "Differences: minus 2, 0, 0, 2. Squares: 4, 0, 0, 4.",
       "Average of squares (variance): 8 / 4 = 2.",
       "Standard deviation: the square root of 2, about 1.41."],
      "Square, average, square root."),
    NQ("Example: a value of {x} in data with mean {m} and standard deviation {s}. What is its z score?",
       "({x} minus {m}) / {s} = {A}.",
       {"m": [50, 80, 5], "s": [4, 10, 2], "k": [-2, 3, 0.5]}, "k", {"m": 60, "s": 8, "k": 1.5}, rnd=2, show={"x": "m+k*s"}),
    M("You scored 82 on a test with mean 70 and SD 6, and 90 on one with mean 85 and SD 10. On which did you do relatively better?",
      ["The second, because 90 is higher", "The first: z = 2 versus z = 0.5", "They are the same", "Cannot tell"], 1,
      "(82 minus 70) / 6 = 2 and (90 minus 85) / 10 = 0.5. Relative to the group, the first score is far more unusual."),
    NQ("Example: the values {a}, {b}, {c}, {d} as a whole population. What is their standard deviation? (Two decimals.)",
       "The mean is {mu}. The square root of the average squared difference is {A}.",
       {"a": [1, 5, 1], "b": [4, 8, 1], "c": [6, 10, 1], "d": [9, 15, 2]},
       "sqrt(((a-(a+b+c+d)/4)^2+(b-(a+b+c+d)/4)^2+(c-(a+b+c+d)/4)^2+(d-(a+b+c+d)/4)^2)/4)", {"a": 2, "b": 4, "c": 6, "d": 9}, rnd=2, tol=0.01,
       show={"mu": "(a+b+c+d)/4"}),
    O("Find a standard deviation by hand, in order.",
      ["Find the mean", "Subtract the mean from each value and square the result", "Average the squares (n, or n minus 1 for a sample)", "Take the square root"],
      "Squaring stops positive and negative differences from cancelling. The square root brings the result back to the original units."),
    C("Outliers move it a lot",
      "Because differences are squared, one extreme value can inflate the standard deviation. For skewed data, the interquartile range (the middle 50%) is often a more honest measure of spread."),
])

MA3 = L("Samples and margin of error", KW + ["sampling", "sample", "margin of error", "survey", "poll", "bias"], [
    C("A sample stands in for everyone",
      "We survey a sample to learn about a population. A random sample gives an estimate whose error shrinks with the square root of the sample size: four times the sample halves the error. For a percentage near 50%, the 95% margin of error is roughly 1 divided by the square root of n. That covers only random error; a biased sample (only people who answer the phone at noon) can be wrong by much more, and a bigger sample does not fix it."),
    NQ("Example: a random sample of {n} people. Using margin of error about 1 / square root of n, what is the margin of error in percentage points? (One decimal.)",
       "1 / the square root of {n} is about {f}, so about plus or minus {A} points.",
       {"n": [100, 2500, 100]}, "100/sqrt(n)", {"n": 400}, rnd=1, tol=0.1, show={"f": "1/sqrt(n)"}),
    M("A poll of 1,000 says 52% support a policy, margin of error 3 points. Which reading is fair?",
      ["Support is definitely above 50%", "Support is plausibly anywhere from about 49% to 55%, so the majority is not certain", "Exactly 52% support it", "The poll is useless"], 1,
      "The interval includes values below 50. Headlines that call a 52% result a clear majority ignore the margin."),
    M("An online poll gets 50,000 responses from a news site's readers. What is the main problem?",
      ["The margin of error is too large", "Self selected respondents are not a random sample, so the result may be biased no matter how many respond", "50,000 is too few", "Nothing"], 1,
      "Size cannot fix who chose to respond. A small random sample often beats a huge biased one."),
    NQ("Example: your survey has a margin of error of about {e} points. Roughly how many people would you need to halve it?",
       "Halving the error needs four times the sample. You have about {n} now, so about {A}.",
       {"e": [2, 10, 1]}, "4*(100/e)^2", {"e": 5}, rnd=0, tol=1, show={"n": "(100/e)^2"}),
    O("Run a fair survey, in order.",
      ["Define the population you care about", "Draw a random sample from it", "Ask neutral questions", "Report the estimate with its margin and how people were chosen"],
      "Who you ask matters more than how many. Report the method so readers can judge it."),
    C("Margins for subgroups are wider",
      "If 1,000 people were surveyed but only 100 are under 25, the result for under 25s has a margin closer to 10 points than 3. Be careful with breakdowns."),
])

MA4 = L("Conditional probability", KW + ["conditional probability", "given", "two way table", "independence", "probability"], [
    C("Probability given something",
      "P(A given B) is the probability of A among only the cases where B happened: P(A and B) / P(B). It is not the same as P(B given A). The share of smokers among people with lung cancer is very different from the share of people with lung cancer among smokers. A two way table of counts makes these easy and hard to mix up."),
    W("Read a two way table",
      "Example: 200 customers. 60 bought insurance; of those, 15 made a claim. Of the 140 who did not buy, 7 had a loss.",
      ["P(claim given insured) = 15 / 60 = 0.25.",
       "P(loss given not insured) = 7 / 140 = 0.05.",
       "P(insured given a claim or loss happened) = 15 / (15 + 7), about 0.68.",
       "Three different questions, three different denominators."],
      "Ask: among whom? That group is the denominator."),
    NQ("Example: of 1,000 emails, {s} are spam. A filter flags {fs} of the spam and {fh} of the others. What percent of flagged emails are actually spam? (One decimal.)",
       "Flagged: {fs} + {fh} = {f}. Spam among flagged: {fs} / {f}, which is {A}%.",
       {"s": [100, 300, 50], "fs": [80, 100, 5], "fh": [10, 60, 10]}, "fs/(fs+fh)*100", {"s": 200, "fs": 90, "fh": 30}, rnd=1, tol=0.1,
       show={"f": "fs+fh"}),
    M("Two events are independent when...",
      ["They cannot both happen", "Knowing one happened does not change the probability of the other", "They have the same probability", "They happen at different times"], 1,
      "Independence means P(A given B) = P(A). Mutually exclusive events, which cannot both happen, are actually strongly dependent."),
    NQ("Example: P(rain) is {r}% and P(traffic jam given rain) is {j}%. What is P(rain and a jam), in percent?",
       "P(rain and jam) = P(rain) times P(jam given rain) = {rr} times {jj} = {A}%.",
       {"r": [10, 50, 10], "j": [20, 80, 10]}, "r*j/100", {"r": 30, "j": 60}, rnd=1, show={"rr": "r/100", "jj": "j/100"}),
    O("Answer a conditional probability question, in order.",
      ["Identify the condition, the given part", "Restrict to the cases where it holds", "Count the cases where the event also happens", "Divide by the size of the restricted group"],
      "The condition defines the denominator. Get that right and the rest is counting."),
    C("Watch for the swapped conditional",
      "Most people found guilty had a motive is not the same as most people with a motive are guilty. This swap, sometimes called the prosecutor's fallacy, has misled real courts."),
])

MA5 = L("Bayes' rule in practice", KW + ["bayes", "base rate", "false positive", "testing", "update", "prior"], [
    C("Start from the base rate",
      "Bayes' rule updates a probability with new evidence. In practice it is easiest with natural frequencies: imagine 10,000 people, apply the base rate, then the test's accuracy, and count. When a condition is rare, even an accurate test produces many false positives compared with true positives, because the healthy group is so much larger."),
    W("A rare condition and a good test",
      "Example: 1% of people have a condition. A test catches 90% of real cases and wrongly flags 5% of healthy people. You test positive. How likely is it you have it?",
      ["Imagine 10,000 people: 100 have it, 9,900 do not.",
       "True positives: 90% of 100 = 90.",
       "False positives: 5% of 9,900 = 495.",
       "Chance a positive is real: 90 / (90 + 495), about 15%. Most positives are false, because healthy people vastly outnumber sick ones."],
      "Count people, not percentages."),
    NQ("Example: {b}% of people have a condition. A test catches {sn}% of cases and wrongly flags {fp}% of healthy people. Of 10,000 people, how many true positives and false positives in total test positive?",
       "True: {tp}. False: {fpos}. Total positives: {A}.",
       {"b": [1, 5, 1], "sn": [80, 95, 5], "fp": [2, 10, 1]}, "100*b*sn/100 + (10000-100*b)*fp/100", {"b": 1, "sn": 90, "fp": 5}, rnd=0,
       show={"tp": "100*b*sn/100", "fpos": "(10000-100*b)*fp/100"}),
    NQ("Same setup with your numbers: {b}% base rate, {sn}% caught, {fp}% false alarms. What percent of positives are real? (One decimal.)",
       "{tp} true positives out of {tot} positives is {A}%.",
       {"b": [1, 5, 1], "sn": [80, 95, 5], "fp": [2, 10, 1]}, "(b*sn)/(b*sn+(100-b)*fp)*100", {"b": 2, "sn": 90, "fp": 5}, rnd=1, tol=0.1,
       show={"tp": "100*b*sn/100", "tot": "100*b*sn/100 + (10000-100*b)*fp/100"}),
    X("Base rates rule",
      "Example test: catches 90% of cases, false alarms on 5% of healthy people. Drag how common the condition is and watch the chance that a positive is real.",
      "(x*90)/(x*90+(100-x)*5)*100", "x", 0.5, 30, 0.5, "How common the condition is (%)", "Chance a positive is real (%)"),
    M("What is the most useful next step after a positive result on a screening test for a rare condition?",
      ["Panic", "A second, independent test, because your probability is now much higher than the base rate but still uncertain", "Ignore it", "Retake the same test until negative"], 1,
      "Each piece of independent evidence updates again. That is why screening is usually followed by a more specific test."),
    C("Bayes outside medicine",
      "Fraud alerts, spam filters, security screening and hiring tests all face the same arithmetic. When the thing you are hunting for is rare, expect most alarms to be false and design the follow up accordingly."),
])

MA6 = L("Confidence intervals", KW + ["confidence interval", "estimate", "uncertainty", "standard error", "interval"], [
    C("An estimate with honest error bars",
      "A confidence interval gives a range of plausible values for something you estimated from a sample. A 95% interval for a mean is roughly the sample mean plus or minus 2 standard errors, where the standard error is the standard deviation divided by the square root of n. The 95% describes the method: if you repeated the study many times, about 95% of the intervals built this way would contain the true value."),
    NQ("Example: a sample of {n} has a standard deviation of {s}. What is the standard error of the mean? (Two decimals.)",
       "{s} divided by the square root of {n} is {A}.",
       {"n": [16, 400, 16], "s": [4, 20, 2]}, "s/sqrt(n)", {"n": 64, "s": 12}, rnd=2, tol=0.01),
    NQ("Example: sample mean {m}, standard error {se}. What is the upper end of the rough 95% interval (mean plus 2 standard errors)?",
       "{m} + 2 times {se} = {A}.",
       {"m": [20, 80, 5], "se": [0.5, 4, 0.5]}, "m+2*se", {"m": 50, "se": 1.5}, rnd=2),
    M("Which reading of a 95% confidence interval from 4.1 to 5.3 is most accurate?",
      ["95% of individuals are between 4.1 and 5.3", "The method that produced this range captures the true mean in about 95% of repeated studies", "The true mean is 4.7", "There is no uncertainty left"], 1,
      "It is about the mean, not individuals, and about the method's long run success rate."),
    M("Two groups' 95% intervals overlap a little. What can you conclude?",
      ["They are definitely the same", "Overlap alone does not settle it; compare the difference and its own interval", "They are definitely different", "The study failed"], 1,
      "Slightly overlapping intervals can still correspond to a clear difference. Compute the interval for the difference itself."),
    O("Report an estimate honestly, in order.",
      ["State what was measured and in whom", "Give the estimate", "Give the interval", "Say what could bias it beyond random error"],
      "Intervals cover random sampling error only. Biases need words, not error bars."),
    C("Wider is more honest than falsely narrow",
      "A wide interval is not a failure. It tells you how much the data can and cannot say, which is exactly what a decision maker needs."),
])

MA7 = L("Hypothesis tests and p values", KW + ["hypothesis test", "p value", "significance", "null hypothesis", "statistical significance"], [
    C("How surprising would this be by chance?",
      "A hypothesis test asks: if there were really no effect (the null hypothesis), how often would we see a result at least this extreme just by chance? That probability is the p value. A small p value means the data would be surprising if nothing were going on. It is not the probability that the null hypothesis is true, and it does not measure how big or important the effect is."),
    M("A study reports p = 0.03. Which statement is correct?",
      ["There is a 3% chance the result is due to chance alone", "If there were no real effect, results this extreme would occur about 3% of the time", "There is a 97% chance the effect is real", "The effect is large"], 1,
      "The p value is computed assuming no effect. Turning it into the chance the effect is real needs base rates, as in Bayes."),
    W("A coin that might be biased",
      "Example: a coin lands heads 9 times in 10 flips. Is that surprising for a fair coin?",
      ["Under a fair coin, P(exactly 9 heads) = 10 / 1,024 and P(10 heads) = 1 / 1,024.",
       "P(9 or more heads) = 11 / 1,024, about 0.011.",
       "Counting the equally extreme other side (1 or fewer heads) doubles it: about 0.021.",
       "Surprising for a fair coin, but with ten flips it is still worth flipping more before concluding."],
      "Compute how often chance alone would do this well."),
    NQ("Example: a fair coin flipped {n} times. What is the probability of getting all heads? (As a percent, two decimals.)",
       "0.5 to the power {n}, times 100, is {A}%.",
       {"n": [3, 10, 1]}, "100*0.5^n", {"n": 5}, rnd=2, tol=0.01),
    NQ("Example: a team runs {k} independent tests where no real effect exists, each at the 5% level. About how many false positives would they expect?",
       "Each has a 5% chance: {k} times 0.05 = {A}.",
       {"k": [20, 200, 20]}, "k*0.05", {"k": 40}, rnd=1),
    O("Read a significance claim, in order.",
      ["Ask what the null hypothesis was", "Check the effect size, not just the p value", "Ask how many tests were run", "Look for replication"],
      "Many tests produce some small p values by chance alone. Replication is the strongest check there is."),
    C("Significant is not the same as important",
      "With a huge sample, a tiny meaningless difference can be statistically significant. With a small sample, a real and important effect can miss significance. Always look at the size of the effect and its interval."),
])

MA8 = L("Correlation and regression", KW + ["correlation", "regression", "line of best fit", "r", "prediction", "causation"], [
    C("How strongly two things move together",
      "The correlation coefficient r runs from minus 1 to 1 and measures how closely two variables follow a straight line together. A regression line predicts one from the other: predicted y = intercept + slope times x. Correlation does not show causation, measures only straight line relationships, and can be driven by a few outliers. Always look at the scatter plot."),
    M("Ice cream sales and drownings are positively correlated. The most likely explanation is...",
      ["Ice cream causes drowning", "A third factor, hot weather, drives both", "Drowning causes ice cream sales", "Pure coincidence"], 1,
      "A lurking variable can create correlation between two things that do not affect each other."),
    NQ("Example: a regression line is predicted sales = {b} + {m} times ad spend (in thousands). What are predicted sales at ad spend of {x} thousand?",
       "{b} + {m} times {x} = {A}.",
       {"b": [10, 50, 5], "m": [2, 8, 0.5], "x": [2, 10, 1]}, "b+m*x", {"b": 20, "m": 3.5, "x": 6}, rnd=2),
    M("r = 0 between two variables means...",
      ["They are unrelated in every way", "No straight line relationship; there could still be a strong curved one", "One causes the other", "The data is wrong"], 1,
      "A perfect U shape can have r near 0. Plot before you conclude."),
    NQ("Example: r is {r}. What share of the variation in y does a straight line on x explain, in percent (r squared)?",
       "{r} squared is {rs}, which is {A}%.",
       {"r": [0.3, 0.9, 0.1]}, "r^2*100", {"r": 0.7}, rnd=0, tol=0.5, show={"rs": "r^2"}),
    O("Analyze a relationship, in order.",
      ["Plot the scatter", "Look for curves, clusters and outliers", "Compute r and fit a line if it is roughly linear", "Ask what else could explain the pattern before claiming cause"],
      "The plot comes first. Four very different data sets can share the same r and line."),
    C("Do not extrapolate far",
      "A line fitted to ad spend between 2 and 10 thousand says little about 100 thousand. Predictions outside the observed range are guesses with a formula attached."),
])

MA9 = L("Capstone: check a claim from data", KW + ["capstone", "claims", "evaluate", "statistics", "evidence", "critique"], [
    C("Put the level together",
      "You will evaluate a claim the way a careful statistician would: what was measured, in whom, how big the effect is, how uncertain, what chance and bias could explain, and what you would need to see next."),
    W("A headline under the microscope",
      "Example claim: people who drink coffee live longer, from a study of 2,000 adults, with a 95% interval for the reduction in risk from 2% to 18%.",
      ["Design: observational, not randomized. Coffee drinkers may differ in income, health and habits.",
       "Effect size: the interval is wide; the true effect could be small.",
       "Chance: the interval excludes zero, so chance alone is not a likely explanation.",
       "Conclusion: an association worth studying, not proof that coffee extends life."],
      "Design, size, uncertainty, alternative explanations."),
    M("Which feature most strengthens a causal claim?",
      ["A large sample alone", "A randomized controlled trial where the effect replicates", "A small p value", "A famous author"], 1,
      "Randomization breaks the link between the treatment and other differences. Replication guards against chance and errors."),
    NQ("Example: a study reports a risk falling from {a}% in the control group to {b}% in the treated group. What is the absolute risk reduction, in percentage points?",
       "{a} minus {b} = {A} points. The relative reduction sounds bigger: {rel}%.",
       {"a": [8, 20, 2], "b": [2, 6, 1]}, "a-b", {"a": 8, "b": 6}, rnd=1, show={"rel": "(a-b)/a*100"}),
    O("Evaluate a claim, in order.",
      ["Find the original study, not just the headline", "Identify the design and the population", "Look at the effect size and its interval", "List alternative explanations and what would rule them out"],
      "Headlines drop the details that matter most. The original study is where they are."),
    WR("Evaluate a statistical claim you have seen (or the coffee example). Write lines starting with Claim:, Design:, Effect:, Uncertainty:, Alternatives: and Verdict:.",
       [must("^claim:", "Claim:", flags="im"),
        must("^design:", "Design:", flags="im"),
        must("^effect:", "Effect:", flags="im"),
        must("^uncertainty:", "Uncertainty:", flags="im"),
        must("^alternatives:", "Alternatives:", flags="im"),
        must("^verdict:", "Verdict:", flags="im"),
        avoid("\\bprove[sd]?\\b", "Avoids saying the data proves it", hint="Statistics supports or weakens a claim. Say how strongly."),
        words(50, 220)],
       "Claim: coffee drinkers live longer.\nDesign: observational study of 2,000 adults, not randomized.\nEffect: risk 10% lower on average.\nUncertainty: 95% interval from 2% to 18%, so the effect could be small.\nAlternatives: coffee drinkers may be healthier or wealthier to begin with.\nVerdict: an interesting association; it does not show coffee causes longer life.",
       "Structured skepticism: neither believing nor dismissing, but weighing."),
    C("Advanced complete",
      "You can read data and uncertainty with care. Expert moves to modeling: estimating, optimizing, simulating and deciding under uncertainty."),
])

# =====================================================================
# Expert: Modeling the world
# =====================================================================

ME1 = L("Estimation with bounds", KW + ["fermi", "estimation", "bounds", "orders of magnitude", "sanity check", "geometric mean"], [
    C("Estimate a range, not a point",
      "Expert estimators break a quantity into factors they can bound, estimate a low and a high value for each, and combine them. Multiplying the lows and the highs gives a range. When the low and high are far apart, the geometric mean (the square root of low times high) is a better middle guess than the ordinary average, because errors in estimation tend to be multiplicative."),
    W("Piano tuners in a city of one million",
      "Example: estimate how many full time piano tuners a city of 1,000,000 people supports.",
      ["Households: about 1,000,000 / 2.5 = 400,000.",
       "Share with a piano: between 1 in 50 and 1 in 10, so 8,000 to 40,000 pianos.",
       "Tunings: about once a year each. A tuner does about 4 a day, 250 days a year, so 1,000 a year.",
       "Tuners: 8 to 40. Geometric mean: the square root of 8 times 40, about 18."],
      "Bound each factor, multiply the bounds, take the geometric mean."),
    NQ("Example: your low estimate is {lo} and your high estimate is {hi}. What is the geometric mean? (Round to a whole number.)",
       "The square root of {lo} times {hi} is about {A}.",
       {"lo": [2, 20, 2], "hi": [50, 400, 50]}, "sqrt(lo*hi)", {"lo": 8, "hi": 200}, rnd=0, tol=1),
    NQ("Example: factor one is between {a1} and {a2}, factor two between {b1} and {b2}. What is the ratio of the high product to the low product?",
       "High: {a2} times {b2}. Low: {a1} times {b1}. Ratio: {A}. Uncertainties multiply.",
       {"a1": [1, 5, 1], "a2": [6, 12, 2], "b1": [2, 6, 2], "b2": [10, 30, 10]}, "(a2*b2)/(a1*b1)", {"a1": 2, "a2": 8, "b1": 2, "b2": 20}, rnd=1, tol=0.1),
    M("Your range for a market size is 2 million to 200 million. What is the most useful next step?",
      ["Report the average, about 100 million", "Find the factor with the widest range and research it first", "Give up", "Pick the high end"], 1,
      "The widest factor contributes most of the uncertainty. Narrowing it shrinks the whole range fastest."),
    O("Make a bounded estimate, in order.",
      ["Write the quantity as a product of factors", "Bound each factor with a low and high", "Multiply the lows and the highs", "Narrow the factor that contributes the most uncertainty"],
      "Decomposition makes a wild guess into several tame ones, and shows where to look for data."),
    C("Check against something known",
      "Before trusting an estimate, compare it with one fact you know, such as a published total or a related count. If your estimate implies every person buys four cars a year, the model is wrong somewhere."),
])

ME2 = L("Expected value and risk", KW + ["expected value", "variance", "risk", "insurance", "gambles", "kelly"], [
    C("Average outcome is not the whole story",
      "Expected value is the probability weighted average of outcomes. It is the right guide for small, repeated bets. For large or one off decisions, the spread matters too: an option with a higher average but a chance of ruin can be worse than a safer one. This is why people rationally buy insurance with a negative expected value: it removes outcomes they could not absorb."),
    W("Two projects",
      "Example: Project A pays 100 for sure. Project B pays 300 with probability 0.5 and minus 50 with probability 0.5.",
      ["EV of A: 100.",
       "EV of B: 0.5 times 300 + 0.5 times minus 50 = 150 minus 25 = 125.",
       "B has the higher average but a 50% chance of losing 50.",
       "If losing 50 would be a disaster for you, A can be the better choice despite the lower EV."],
      "Compare averages, then ask whether you can survive the bad outcome."),
    NQ("Example: a bet pays {w} with probability {p}% and loses {l} otherwise. What is its expected value?",
       "{pp} times {w} minus {q} times {l} = {A}.",
       {"w": [50, 300, 50], "p": [10, 60, 10], "l": [20, 100, 10]}, "p/100*w-(1-p/100)*l", {"w": 200, "p": 30, "l": 50}, rnd=2,
       show={"pp": "p/100", "q": "1-p/100"}),
    NQ("Example: insurance costs {c} a year. It covers a loss of {L} that happens with probability {p}% a year. What is the expected yearly cost of the loss without insurance?",
       "{pp} times {L} = {A}. Paying {c} is above the expected loss; the difference buys protection from the rare large hit.",
       {"c": [100, 400, 50], "L": [5000, 20000, 5000], "p": [1, 2, 1]}, "p/100*L", {"c": 300, "L": 10000, "p": 2}, rnd=2,
       show={"pp": "p/100"}),
    NQ("Example: outcomes {a} and {b}, each with probability 0.5. What is the standard deviation of the outcome?",
       "The mean is {mu}; each outcome is {d} away, so the standard deviation is {A}.",
       {"a": [0, 100, 20], "b": [120, 400, 40]}, "(b-a)/2", {"a": 0, "b": 200}, rnd=2, show={"mu": "(a+b)/2", "d": "(b-a)/2"}),
    M("When is maximizing expected value most clearly the right rule?",
      ["For one huge bet you can only make once", "For many small, independent bets where no single loss hurts you", "Never", "Only for insurance"], 1,
      "Over many repetitions the average wins out. With one big bet, the spread and the chance of ruin matter."),
    C("Expected value needs honest probabilities",
      "EV math is only as good as the probabilities you feed it. When they are guesses, compute EV for a range of probabilities and see whether the decision changes."),
])

ME3 = L("Optimization: finding the best", KW + ["optimization", "maximum", "minimum", "tradeoff", "constraints", "best price"], [
    C("Best usually means a trade off",
      "Optimization finds the input that makes something as large or as small as possible. Many real problems have a sweet spot because two effects pull against each other: raise a price and each sale earns more but fewer people buy. Write the quantity as a formula of one decision variable, then search for the peak: by trying values, by reasoning about symmetry, or with calculus."),
    W("The best price",
      "Example: at a price of p, a cafe sells 200 minus 10p sandwiches a day. Each costs 4 to make. Which price maximizes profit?",
      ["Profit = (p minus 4) times (200 minus 10p).",
       "It is zero at p = 4 and at p = 20, and a parabola peaks halfway between its zeros.",
       "Best price: (4 + 20) / 2 = 12.",
       "Profit at 12: 8 times 80 = 640 a day."],
      "Write profit as a function of price, find where it is zero, and the peak is in the middle."),
    NQ("Example: at price p you sell {a} minus {b}p units. Each costs {c}. Which price maximizes profit?",
       "Profit is zero at p = {c} and at p = {z}. The peak is halfway: {A}.",
       {"a": [100, 300, 20], "b": [5, 10, 5], "c": [2, 8, 1]}, "(c + a/b)/2", {"a": 200, "b": 10, "c": 4}, rnd=2, show={"z": "a/b"}),
    X("Find the peak",
      "Example model from the worked problem: profit = (p minus 4) times (200 minus 10p). Drag the price and find where profit peaks.",
      "(x-4)*(200-10*x)", "x", 4, 20, 0.5, "Price", "Daily profit"),
    NQ("Example: you have {f} m of fence for a rectangular pen against a wall (fence on three sides). What is the largest area, in square meters?",
       "With sides x, x and {f} minus 2x, area = x({f} minus 2x), which peaks at x = {q}. Area = {A}.",
       {"f": [20, 100, 4]}, "(f/4)*(f/2)", {"f": 40}, rnd=2, show={"q": "f/4"}),
    O("Solve an optimization problem, in order.",
      ["Name the decision variable", "Write the quantity to optimize as a formula of it", "Add the constraints, such as limits on budget or space", "Find the best value and check the edges of the allowed range"],
      "The best value can sit on an edge, such as the maximum budget, rather than at a peak in the middle. Always check the boundaries."),
    C("Optimize the right thing",
      "Maximizing clicks can hurt revenue, and maximizing this quarter's profit can hurt next year's. The hardest part of optimization is choosing the quantity worth optimizing."),
])

ME4 = L("Simulation thinking", KW + ["simulation", "monte carlo", "randomness", "uncertainty", "scenarios", "model"], [
    C("When the formula is hard, roll the dice",
      "Some questions are hard to solve exactly but easy to simulate: draw random inputs from their ranges, compute the outcome, repeat thousands of times, and look at the distribution of results. This is called Monte Carlo simulation. It shows not just an average but the chance of bad outcomes, such as the probability a project runs over budget."),
    W("A project with three uncertain tasks",
      "Example: three tasks each take between 2 and 6 days, any value equally likely. What is the chance the project takes more than 14 days?",
      ["Each run: draw three random durations, add them up.",
       "Repeat 10,000 times and count runs over 14 days.",
       "The average total is 12 days, but some runs reach 16 or more.",
       "The share of runs over 14 is the estimated probability, which a single best guess of 12 days would hide."],
      "Simulate the inputs, count the outcomes."),
    NQ("Example: in {n} simulated runs, {k} went over budget. What is the estimated probability of going over budget, in percent?",
       "{k} / {n}, times 100, is {A}%.",
       {"n": [1000, 10000, 1000], "p": [5, 40, 5]}, "p", {"n": 5000, "p": 15}, rnd=1, show={"k": "n*p/100"}),
    NQ("Example: simulation error shrinks with the square root of the number of runs. If 1,000 runs give an error of about {e} points, about what error would {m} times as many runs give?",
       "The square root of {m} is {r}, so the error becomes {e} / {r}, about {A} points.",
       {"e": [1, 4, 0.5], "m": [4, 100, 96]}, "e/sqrt(m)", {"e": 2, "m": 4}, rnd=2, tol=0.01, show={"r": "sqrt(m)"}),
    M("Why can a simulation's average differ from the plan built on each task's most likely duration?",
      ["Simulations are always wrong", "Durations are often skewed: tasks can run much later but rarely much earlier, so the average lands later than the most likely value", "Random numbers are biased", "They cannot differ"], 1,
      "When delays are lopsided, adding most likely values understates the total. Simulation exposes that."),
    O("Build a simple simulation, in order.",
      ["List the uncertain inputs and their ranges", "Write how the outcome is calculated from them", "Draw random inputs and compute the outcome many times", "Summarize: average, spread and the chance of bad outcomes"],
      "Spreadsheets can do this with RAND() in a few columns. The thinking is the hard part, not the software."),
    C("Garbage in, distribution out",
      "A simulation is only as good as its input ranges. If the ranges are too narrow, it will look confident and be wrong. Test what happens when you widen them."),
])

ME5 = L("Markov chains: states that change", KW + ["markov chain", "states", "transitions", "steady state", "churn", "probability"], [
    C("Tomorrow depends on today",
      "A Markov chain models something that moves between states, such as a customer who is active or lapsed, with fixed probabilities of moving each period. Multiply the current shares by the transition probabilities to get the next period's shares. Over time many chains settle into a steady state where the shares stop changing, which tells you the long run picture."),
    W("Active and lapsed customers",
      "Example: each month 90% of active customers stay active and 10% lapse; 20% of lapsed customers come back. Start with 1,000 active.",
      ["Month 1: active = 900; lapsed = 100.",
       "Month 2: active = 0.9 times 900 + 0.2 times 100 = 830; lapsed = 170.",
       "Steady state: the flow out equals the flow in, 0.1 times active = 0.2 times lapsed.",
       "So active is two thirds and lapsed one third in the long run: about 667 and 333."],
      "Update shares each step; in the steady state the flows balance."),
    NQ("Example: each month {s}% of active customers stay and {b}% of lapsed ones return. With {a} active and {l} lapsed now, how many are active next month?",
       "{sp} times {a} + {bp} times {l} = {A}.",
       {"s": [70, 95, 5], "b": [10, 40, 10], "a": [600, 1000, 100], "l": [0, 400, 100]}, "s/100*a + b/100*l", {"s": 90, "b": 20, "a": 900, "l": 100}, rnd=0, tol=0.5,
       show={"sp": "s/100", "bp": "b/100"}),
    NQ("Example: {o}% of active customers lapse each month and {b}% of lapsed ones return. In the steady state, what percent of customers are active? (One decimal.)",
       "Balance: {o} times active = {b} times lapsed, so active share = {b} / ({o} + {b}) = {A}%.",
       {"o": [5, 30, 5], "b": [10, 40, 10]}, "b/(o+b)*100", {"o": 10, "b": 20}, rnd=1, tol=0.1),
    M("A Markov chain assumes...",
      ["The future depends on the whole history", "The next state depends only on the current state, with fixed transition probabilities", "Nobody ever leaves a state", "All states are equally likely"], 1,
      "That assumption is what makes it simple. When history matters, such as how long someone has been lapsed, add more states."),
    O("Model a process as a Markov chain, in order.",
      ["Define the states", "Estimate the transition probabilities from data", "Check that each state's outgoing probabilities add to 1", "Step forward or solve for the steady state"],
      "The sum to 1 check catches most setup errors."),
    C("Small changes in retention, big long run effects",
      "In the example, cutting monthly lapses from 10% to 5% moves the steady state active share from 67% to 80%. Long run shares are very sensitive to the transition rates."),
])

ME6 = L("Queues and waiting", KW + ["queues", "waiting", "utilization", "littles law", "capacity", "throughput"], [
    C("Why lines explode near full capacity",
      "Little's law links three numbers in any stable system: average number in the system = arrival rate times average time in the system. It holds for coffee shops, support tickets and warehouses. Separately, when arrivals are random, waiting times grow sharply as utilization (busy time divided by capacity) approaches 100%. In the simplest textbook queue, the average time in the system is proportional to 1 / (1 minus utilization)."),
    W("A support desk",
      "Example: tickets arrive at 30 an hour, and each ticket spends 2 hours in the system on average. How many are open at any moment?",
      ["Little's law: L = arrival rate times time in system.",
       "L = 30 tickets per hour times 2 hours = 60 tickets.",
       "To cut open tickets to 30 at the same arrival rate, time in system must fall to 1 hour.",
       "The law needs no assumptions about the shape of the arrivals, only a stable system."],
      "Number in system = rate times time."),
    NQ("Example: customers arrive at {r} per hour and each spends {t} minutes in the shop. On average how many are in the shop?",
       "{r} per hour times {h} hours = {A}.",
       {"r": [20, 120, 10], "t": [6, 30, 6]}, "r*t/60", {"r": 60, "t": 12}, rnd=1, show={"h": "t/60"}),
    X("The utilization cliff",
      "Example: in the simplest textbook queue, average time in system is service time divided by (1 minus utilization). Drag utilization toward 100% and watch the time explode. Service time here is 1 unit.",
      "1/(1-x/100)", "x", 0, 95, 5, "Utilization (%)", "Average time in system (multiples of service time)"),
    NQ("Example: in that textbook queue, utilization goes from {u1}% to {u2}%. By what factor does average time in system grow?",
       "(1 minus {a}) / (1 minus {b}) = {A}.",
       {"u1": [50, 70, 10], "u2": [80, 95, 5]}, "(1-u1/100)/(1-u2/100)", {"u1": 50, "u2": 90}, rnd=2, tol=0.01,
       show={"a": "u1/100", "b": "u2/100"}),
    M("A team runs at 95% utilization and work keeps piling up. What does queueing math suggest?",
      ["Work harder", "Add slack: even a little spare capacity sharply cuts waiting", "Accept more work", "Nothing can help"], 1,
      "Near full utilization, small capacity changes have large effects on waiting. Slack is not waste in a random world."),
    C("Measure arrivals and time, not just busy-ness",
      "A busy team is not necessarily a fast one. Track how long work waits and how much is in progress; Little's law connects them, and limiting work in progress is one of the most reliable ways to cut waiting."),
])

ME7 = L("Decision trees and the value of information", KW + ["decision tree", "value of information", "uncertainty", "decisions", "expected value"], [
    C("Draw the choices, then the chances",
      "A decision tree lays out choices (squares), uncertain events (circles) with probabilities, and outcomes. Solve it from the right: compute expected values at chance nodes, then pick the best option at each decision. The value of information is how much better you could do if you learned the uncertain outcome before deciding. It caps what a test, survey or pilot is worth."),
    W("Launch or not",
      "Example: launching earns 100 if demand is high (probability 0.4) and loses 40 if low. Not launching earns 0.",
      ["EV of launching: 0.4 times 100 + 0.6 times minus 40 = 40 minus 24 = 16. Launch beats 0.",
       "With perfect information: if high, launch (100); if low, do not (0).",
       "EV with perfect information: 0.4 times 100 + 0.6 times 0 = 40.",
       "Value of perfect information: 40 minus 16 = 24. A market test costing more than 24 is not worth it."],
      "Value of information = EV knowing first minus EV deciding now."),
    NQ("Example: launching earns {g} if demand is high (probability {p}%) and loses {l} if low. Not launching earns 0. What is the expected value of launching?",
       "{pp} times {g} minus {q} times {l} = {A}.",
       {"g": [60, 200, 20], "p": [30, 70, 10], "l": [20, 80, 10]}, "p/100*g-(1-p/100)*l", {"g": 100, "p": 40, "l": 40}, rnd=2,
       show={"pp": "p/100", "q": "1-p/100"}),
    NQ("Same setup: high pays {g} with probability {p}%, low loses {l}. What is the value of perfect information? (Assume launching has positive EV.)",
       "With information you avoid the loss: EV {wi}. Without: {wo}. Difference: {A}, which is {q} times {l}.",
       {"g": [100, 200, 20], "p": [40, 70, 10], "l": [20, 60, 10]}, "(1-p/100)*l", {"g": 100, "p": 40, "l": 40}, rnd=2,
       show={"wi": "p/100*g", "wo": "p/100*g-(1-p/100)*l", "q": "1-p/100"}),
    M("A pilot study costs 30. The value of perfect information is 24. What should you conclude?",
      ["Run the pilot", "The pilot cannot be worth it, since even perfect information is worth only 24 and a real pilot is imperfect", "Run two pilots", "It depends on the weather"], 1,
      "Perfect information sets the ceiling. An imperfect pilot is worth less than that."),
    O("Solve a decision tree, in order.",
      ["Draw the decisions, chance events and outcomes", "Assign probabilities and payoffs", "Compute expected values from right to left", "Pick the best branch at each decision and check how sensitive it is to the probabilities"],
      "Sensitivity is the last step for a reason: a decision that flips with a small change in a guessed probability deserves more information."),
    C("Information is valuable only if it could change the decision",
      "If you would launch whatever the test said, the test is worth nothing for this decision, however interesting the results."),
])

ME8 = L("Sensitivity analysis", KW + ["sensitivity", "assumptions", "tornado", "break even", "robustness", "scenarios"], [
    C("Which assumption matters most?",
      "Every model rests on assumptions. Sensitivity analysis changes one input at a time across its plausible range and watches the output. Inputs that swing the output most deserve the most scrutiny. A tornado chart ranks them. Another useful question: by how much would this assumption have to change to flip the decision? If the answer is a tiny amount, the decision is fragile."),
    W("Profit with three assumptions",
      "Example: profit = units times (price minus cost) minus 5,000. Base case: 1,000 units, price 20, cost 12, profit 3,000.",
      ["Units 800 to 1,200: profit 1,400 to 4,600, a swing of 3,200.",
       "Price 18 to 22: profit 1,000 to 5,000, a swing of 4,000.",
       "Cost 11 to 13: profit 2,000 to 4,000, a swing of 2,000.",
       "Price is the most sensitive assumption. Research it first."],
      "Swing each input across its range; rank by the swing in the output."),
    NQ("Example: profit = units times (price minus {c}) minus {f}. With {u} units, what price makes profit exactly zero?",
       "{u}(p minus {c}) = {f}, so p = {c} + {f} / {u} = {A}.",
       {"c": [5, 15, 1], "f": [2000, 10000, 1000], "u": [500, 2000, 250]}, "c+f/u", {"c": 12, "f": 5000, "u": 1000}, rnd=2, tol=0.01),
    NQ("Example: base price {p}, break even price {b}. By what percent can the price fall before profit hits zero? (One decimal.)",
       "({p} minus {b}) / {p}, times 100, is {A}%. That is the safety margin on price.",
       {"p": [18, 30, 2], "b": [12, 17, 1]}, "(p-b)/p*100", {"p": 20, "b": 17}, rnd=1, tol=0.1),
    M("A decision flips if the conversion rate is 2.1% instead of 2.3%. What should you do?",
      ["Decide immediately", "Treat the decision as fragile: get better data on conversion, or choose the option that is safer across the range", "Ignore conversion", "Use the higher number"], 1,
      "When a small change flips the answer, the model is telling you where the real uncertainty is."),
    O("Run a sensitivity analysis, in order.",
      ["Build the base case", "Give each input a plausible low and high", "Vary one input at a time and record the output", "Rank inputs by their swing and find the break even values"],
      "One at a time keeps it readable. Then test the two or three biggest drivers together as scenarios."),
    WR("Write a short sensitivity note for a model or plan you know (or the profit example). Name the base case, the most sensitive input with its range, the break even value for it, and what you will do about it.",
       [must("base", "Names the base case"),
        must("(most sensitive|biggest swing|largest swing|matters most|drives)", "Names the most sensitive input"),
        must("break.?even|flips|zero", "Gives the break even or flip point"),
        must("\\d", "Uses numbers"),
        must("(will|plan|next|research|test|check)", "Says what you will do"),
        words(30, 140)],
       "Base case: 1,000 units at a price of 20 gives a profit of 3,000. Price is the most sensitive input: across 18 to 22, profit swings by 4,000. Break even price is 17, only 15% below the base. Next, I will test willingness to pay with a small price experiment before committing.",
       "Base, driver, threshold, action. That is a note a decision maker can use."),
    C("Report the range, not just the base",
      "A single number from a model invites false confidence. Report the base case together with the range and the inputs that drive it."),
])

ME9 = L("Capstone: build and stress test a model", KW + ["capstone", "model", "stress test", "forecast", "decision", "modeling"], [
    C("Put the level together",
      "A useful model is simple enough to explain, uses honest ranges, and is stress tested before anyone relies on it. You will build a small model for a decision, compute its base case and break even, test its sensitivity, and write it up."),
    W("Should a bakery add delivery?",
      "Example model: delivery costs 1,500 a month (driver and fuel). Each delivery order adds 6 in contribution. Expected orders: 200 to 400 a month.",
      ["Break even orders: 1,500 / 6 = 250.",
       "Low case 200 orders: 1,200 minus 1,500 = minus 300 a month.",
       "High case 400: 2,400 minus 1,500 = 900 a month.",
       "Middle 300: 300. The decision depends on whether orders beat 250, so a one month trial is worth running."],
      "Base, range, break even, and the cheapest way to learn more."),
    NQ("Example: delivery costs {f} a month and each order contributes {c}. How many orders a month to break even? (Round up.)",
       "{f} / {c}, rounded up, is {A}.",
       {"f": [1000, 3000, 250], "c": [4, 10, 1]}, "ceil(f/c)", {"f": 1500, "c": 6}, rnd=0),
    NQ("Example: with costs of {f} and {c} per order, what is the monthly profit at {o} orders?",
       "{o} times {c} minus {f} = {A}.",
       {"f": [1000, 3000, 250], "c": [4, 10, 1], "o": [100, 500, 50]}, "o*c-f", {"f": 1500, "c": 6, "o": 300}, rnd=0),
    O("Build a decision model, in order.",
      ["State the decision and what success means", "Write the simplest formula that captures it", "Give inputs ranges and compute base, low and high cases", "Find break even values and test the most sensitive inputs", "Recommend, with the cheapest way to reduce the key uncertainty"],
      "Simple first. Add detail only where the sensitivity analysis says it matters."),
    WR("Write up a model for a decision of your own (or the bakery). Use lines starting with Decision:, Model:, Inputs:, Cases:, Break even:, Most sensitive: and Recommendation:. Label made up numbers as examples or estimates.",
       [must("^decision:", "Decision:", flags="im"),
        must("^model:", "Model:", flags="im"),
        must("^inputs:", "Inputs:", flags="im"),
        must("^cases:", "Cases:", flags="im"),
        must("^break even:", "Break even:", flags="im"),
        must("^most sensitive:", "Most sensitive:", flags="im"),
        must("^recommendation:", "Recommendation:", flags="im"),
        must("example|estimate|assum", "Labels made up numbers as examples or estimates"),
        words(60, 260)],
       "Decision: should the bakery add delivery?\nModel: monthly profit = orders times 6 minus 1,500.\nInputs: cost 1,500 a month (quote); contribution 6 per order (estimate from current margins); orders 200 to 400 (example range from a customer poll).\nCases: low minus 300, middle 300, high 900 a month.\nBreak even: 250 orders a month.\nMost sensitive: order volume; contribution per order matters less.\nRecommendation: run a one month trial with a part time driver and continue only if orders pass 250.",
       "Clear decision, a formula anyone can check, honest ranges, a break even and a cheap next step."),
    C("Expert complete",
      "You can build, test and explain models that support real decisions. The habit to keep: ranges, break evens and sensitivity, every time."),
])


def add(courses, picks):
    courses.append(course("math-intermediate", "Quantitative reasoning", "Intermediate", "Math for real decisions", "math", "Practical math", 55,
        "Percent change, multipliers, rates, equations, linear models, break even, growth and logs.",
        [("Proportional reasoning", [MI1, MI2, MI3]), ("Algebra for life", [MI4, MI5, MI6]),
         ("Growth and scale", [MI7, MI8, MI9])], "quant"))
    courses.append(course("math-advanced", "Statistics", "Advanced", "Statistics you can trust", "math-intermediate", "Quantitative reasoning", 85,
        "Distributions, spread, sampling, conditional probability, Bayes, intervals, tests and regression.",
        [("Describing data", [MA1, MA2, MA3]), ("Probability with care", [MA4, MA5, MA6]),
         ("Inference", [MA7, MA8, MA9])], "quant"))
    courses.append(course("math-expert", "Mathematical modeling", "Expert", "Modeling the world", "math-advanced", "Statistics", 85,
        "Bounded estimates, risk, optimization, simulation, Markov chains, queues, decision trees and sensitivity.",
        [("Estimate and decide", [ME1, ME2, ME3]), ("Systems over time", [ME4, ME5, ME6]),
         ("Decisions under uncertainty", [ME7, ME8, ME9])], "quant"))
