"""SEO ladder: Intermediate, Advanced and Expert courses that follow
"Found on Google" (seo). Hands-on work happens on the same Workshop site
as the web ladder: build steps add head tags, headings, links, images and
structured data, scoped to classes these lessons introduce (.recipe-card,
.local, .faq and so on) so they never fight earlier work. Search Console
and forecasting math use numeric steps; briefs, robots files, redirect
maps and strategy memos use write steps. Numbers in prompts are labeled
examples, not industry statistics.
Rebuild with: python3 build_library.py
"""
from ladder_kit import (C, W, M, O, B, L, N, X, WR, course, has, count, attr, css, html, none, rx,
                        confirm, at_most, text_max, words, must, avoid, max_sentence, lines, changed,
                        self_check)

KW = ["seo", "search", "google", "ranking"]


def ld(sel, keys, label, type_=None, hint=None):
    """Every JSON-LD block parses and has the listed top level keys."""
    c = {"sel": sel, "jsonKeys": keys, "label": label}
    if type_:
        c["jsonType"] = type_
    if hint:
        c["hint"] = hint
    return c


def words_each(sel, n, label, hint=None):
    """Every match has at least n words of text."""
    c = {"sel": sel, "wordsMin": n, "label": label}
    if hint:
        c["hint"] = hint
    return c


def text_not(sel, pattern, label, hint=None):
    """Matches exist and none has text matching the pattern (case blind)."""
    c = {"sel": sel, "textNot": pattern, "label": label}
    if hint:
        c["hint"] = hint
    return c


LDSEL = "script[type=\"application/ld+json\"]"

# =====================================================================
# Intermediate: SEO you can ship
# =====================================================================

SI1 = L("Titles and descriptions that earn the click", KW + ["title", "meta", "description", "snippet", "ctr", "click"], [
    C("Your snippet is an ad you write for free",
      "In the results page, people see your title link and a short snippet, usually taken from your meta description. Google may rewrite either one when it thinks another line fits the query better, but a clear, specific title and description are what it uses most of the time. As a rule of thumb, titles of about 50 to 60 characters and descriptions of about 150 to 160 characters usually show without being cut off."),
    M("Which title is most likely to earn a click for the search \"easy weeknight pasta\"?",
      ["Home | Casa Verde", "Easy Weeknight Pasta: 12 Tested Recipes in 30 Minutes | Casa Verde", "Pasta pasta recipes pasta dinner easy pasta", "Welcome to our website, where we love food"], 1,
      "It repeats the searcher's words, adds a specific promise and ends with the brand. Stuffing the keyword reads as spam to people and to Google."),
    N("Example numbers: a page had 4,000 impressions and 80 clicks last month. What was its click-through rate, in percent?", 2,
      "80 divided by 4,000 is 0.02, which is 2%. A better title and description is the cheapest way to move this number.",
      gen={"vars": {"i": [2000, 8000, 1000], "c": [40, 200, 20]}, "answer": "c/i*100", "round": 2,
           "prompt": "Example numbers: a page had {i} impressions and {c} clicks last month. What was its click-through rate, in percent?",
           "explain": "{c} divided by {i}, times 100, is {A}%."}),
    M("Does the meta description directly raise your ranking?",
      ["Yes, it is a strong ranking factor", "No. It mainly affects whether people click, which is still worth a lot", "Only if it contains the keyword five times", "Only on mobile"], 1,
      "Google has said the meta description is not a ranking factor. Its job is to persuade the searcher who already sees you."),
    B("Give your page a title and a meta description that earn the click. The title must be 60 characters or fewer and mention what the page offers. The meta description must be between 70 and 160 characters.",
      "<title>Weeknight Dinners in 30 Minutes | Casa Verde</title>\n<meta name=\"description\" content=\"Tested weeknight dinners you can cook in 30 minutes, with a shopping list for your phone. New recipes every Friday.\">",
      "A specific title and a description that reads like a promise. Check the result in a snippet preview tool if you want to see it the way searchers will.",
      [has("title", "A title element"),
       text_max("title", 60, "The title is 60 characters or fewer",
                hint="Long titles get cut off with an ellipsis. Put the words searchers type first and the brand last."),
       attr("meta[name=\"description\"]", "content", "A meta description between 70 and 160 characters", match="^.{70,160}$",
            hint="Count the characters in the content attribute. Under 70 is usually too thin to persuade; over 160 is likely cut off.")]),
    O("Write a title the way a professional does.",
      ["Find the words searchers actually use for this page", "Lead with those words", "Add the specific promise that makes this page better", "End with the brand name"],
      "Searcher words first because people scan the start of each result. The brand last because it matters least to someone who has not heard of you yet."),
    C("One page, one promise",
      "Every indexable page deserves its own title and description. Ten pages titled Casa Verde compete with each other and tell searchers nothing. If you cannot write a distinct title for a page, ask whether the page needs to exist."),
])

SI2 = L("Headings that map the page", KW + ["headings", "h1", "h2", "structure", "outline", "hierarchy"], [
    C("Headings are the table of contents",
      "Search engines and screen readers both use headings to understand what a page covers and how it is organized. A good page has one main heading (h1) that matches the title's promise, then h2 headings for each major part and h3 headings inside those. Skimming only the headings should tell you what the page answers."),
    M("A designer used h4 for the page's main heading because it looked the right size. What is wrong?",
      ["Nothing, size is what matters", "Heading level describes structure, not size; use h1 and set the size with CSS", "h4 is not valid HTML", "Search engines ignore headings"], 1,
      "Pick the level for meaning, then style it. A page whose outline starts at h4 has no clear main topic."),
    O("Order this outline for a page answering \"how to store fresh herbs\".",
      ["h1: How to store fresh herbs so they last", "h2: Soft herbs like basil and parsley", "h3: The jar of water method", "h2: Hard herbs like rosemary and thyme", "h2: Freezing herbs for later"],
      "One h1, then h2 sections, with the h3 nested under the section it belongs to. The order of the last two sections is a choice; nesting is not.",
      groups=[[3, 4]]),
    M("Which h2 helps the skimmer most on a recipe page?",
      ["More info", "Ingredients for four people", "Section 2", "Click below"], 1,
      "Specific headings carry information on their own. A skimmer reading only headings should still learn something."),
    B("Give a new article a clean outline. Add an article with class guide that has exactly one h1 inside it (and no other h1 on the whole page), followed by at least two h2 headings, and at least one h3 that sits after an h2.",
      "<article class=\"guide\">\n  <h1>How to store fresh herbs so they last</h1>\n  <h2>Soft herbs like basil and parsley</h2>\n  <h3>The jar of water method</h3>\n  <p>Trim the stems and stand them in water.</p>\n  <h2>Hard herbs like rosemary and thyme</h2>\n  <p>Wrap them in a damp towel.</p>\n</article>",
      "One h1, a clear set of h2 sections and an h3 where a section needs a subsection. This outline is what search engines and screen readers read first.",
      [count(".guide h2", 2, "At least two h2 headings in the guide"),
       has(".guide h1", "An h1 inside the guide"),
       at_most("h1", 1, "Exactly one h1 on the whole page",
               hint="If an earlier lesson gave your page an h1, change one of them to h2. A page has one main topic."),
       has(".guide h2 ~ h3", "An h3 that comes after an h2")]),
    C("Answer early, then elaborate",
      "Put the direct answer near the top, under the h1, and use the h2 sections for detail. People who only need the answer get it fast, and the ones who stay find the depth they came for."),
])

SI3 = L("Search intent, mapped", KW + ["intent", "informational", "commercial", "transactional", "navigational", "serp"], [
    C("Four reasons people search",
      "Most queries fall into four rough groups. Informational: they want to learn (how to store basil). Navigational: they want a specific site (casa verde login). Commercial: they are comparing before buying (best chef knife under 100). Transactional: they are ready to act (buy chef knife). The page type has to match: a product page will not rank for a how-to query, and a blog post rarely ranks for a buy query."),
    M("What is the most reliable way to learn the intent behind a query?",
      ["Guess from the words", "Search it and look at what already ranks on page one", "Ask a friend", "Use the longest keyword"], 1,
      "Google has already tested what satisfies that query. If page one is all guides, a product page is fighting the searchers."),
    M("The query \"best running shoes for flat feet\" is mainly...",
      ["Navigational", "Informational about anatomy", "Commercial: they are comparing before buying", "Transactional for one exact shoe"], 2,
      "Best and for flat feet signal comparison shopping. A comparison guide with clear picks fits; a single product page does not."),
    O("Plan a page for a query, in order.",
      ["Search the query and note the page types that rank", "Name the intent those pages serve", "Pick the page type that fits that intent", "Write the brief: what this page must answer"],
      "Look first, decide second. Planning content before checking the results page is how teams write the wrong page type."),
    WR("Write a short brief for a page targeting the query \"how to keep basil fresh\". Name the intent, the page type, and at least two questions the page must answer. Use one line for each part.",
       [lines(3, "At least three lines"),
        must("informational", "Names the intent (informational)", hint="How to queries are informational: the searcher wants to learn."),
        must("guide|how.?to|article|tutorial|post", "Names a page type that fits (a guide or how to article)"),
        must("\\?", "Lists at least one question the page must answer", hint="Write the questions the searcher has, ending in question marks."),
        words(20, 120)],
       "Intent: informational, they want to learn a method.\nPage type: a short how to guide with photos.\nMust answer: Should basil go in the fridge? How long does it last in water? Can I freeze it?",
       "A brief that names intent and page type stops you from writing the wrong page. The questions become your h2 headings."),
    C("Mixed intent is normal",
      "Some queries show guides and products together, because searchers want different things. You do not have to win every slot. Pick the intent you can serve best and serve it well."),
])

SI4 = L("Keyword research without paid tools", KW + ["keywords", "research", "autocomplete", "people also ask", "long tail", "search console"], [
    C("The free tools are good enough to start",
      "You can find what people search with free sources: Google autocomplete as you type, the People also ask box, related searches at the bottom of the page, your own site search logs, the questions customers send you, and Search Console once your site has some traffic. Paid tools add volume estimates, but the phrases themselves come from the same place: real people."),
    W("Turn one seed into a list",
      "Seed: \"meal prep\". Find phrases worth a page.",
      ["Type meal prep into Google and note the autocomplete suggestions: meal prep ideas, meal prep for beginners, meal prep containers.",
       "Open People also ask: How long does meal prep last in the fridge? Is meal prep cheaper?",
       "Scroll to related searches: meal prep for the week on a budget.",
       "Group them by intent: learning (beginners, how long it lasts), buying (containers), planning (week on a budget)."],
      "Each group becomes a page, and each question becomes a section."),
    M("Search Console shows your page gets impressions for \"meal prep for one\" but you never mention cooking for one. What is the best move?",
      ["Ignore it", "Add a section that genuinely serves people cooking for one, if it fits the page", "Repeat the phrase ten times", "Delete the page"], 1,
      "Impressions without a matching section are a hint from real searchers. Serve them properly and the clicks tend to follow."),
    N("Example numbers: a phrase has about 900 searches a month. If your page ranked and earned 5% of those clicks, about how many visits a month is that?", 45,
      "900 times 0.05 is 45. Treat any volume number as a rough estimate; tools disagree, and the real range can be wide.",
      gen={"vars": {"s": [400, 2000, 100], "c": [3, 9, 1]}, "answer": "s*c/100", "round": 0,
           "prompt": "Example numbers: a phrase has about {s} searches a month. If your page earned {c}% of those clicks, about how many visits a month is that?",
           "explain": "{s} times {c}% is {A}. Volume figures are estimates, so plan with a range."}),
    O("Order a basic research session.",
      ["Write down the seed topics your customers care about", "Collect real phrases from autocomplete, People also ask and related searches", "Group the phrases by intent", "Pick one group per page and note the main phrase"],
      "Seeds, phrases, groups, pages. Skipping grouping is how sites end up with five thin pages competing for one query."),
    WR("Pick a seed topic for a site you know (or use \"meal prep\"). List at least four real search phrases you found or would expect, one per line, and mark each with its intent in brackets, like: meal prep for beginners [informational].",
       [lines(4, "At least four phrases, one per line"),
        must("\\[(informational|commercial|transactional|navigational)\\]", "Each phrase is marked with an intent in brackets", hint="Use one of: [informational], [commercial], [transactional], [navigational]."),
        must("\\[(commercial|transactional)\\]", "At least one phrase is commercial or transactional"),
        words(12, 120)],
       "meal prep for beginners [informational]\nhow long does meal prep last in the fridge [informational]\nbest meal prep containers [commercial]\nbuy glass meal prep containers [transactional]",
       "A list like this, grouped by intent, is the start of a content plan."),
    C("Volume is not value",
      "A phrase with small volume and buying intent can be worth more than a big informational one. Ask what the searcher will do after they land, not only how many of them there are."),
])

SI5 = L("Internal links with purpose", KW + ["internal links", "anchor text", "linking", "orphan", "breadcrumbs", "crawl"], [
    C("Links tell search engines what matters",
      "Internal links help crawlers find pages and help them understand what each page is about. The clickable words, called anchor text, are a strong hint: a link that says weeknight pasta recipes describes its target; a link that says click here describes nothing. Pages with no internal links pointing at them, called orphan pages, are easy for search engines to miss."),
    M("Which anchor text is best for a link to your herb storage guide?",
      ["Click here", "Read more", "how to store fresh herbs", "this"], 2,
      "Descriptive anchors help screen reader users scanning a list of links too. Click here makes sense only next to the sentence around it."),
    M("Your best guide is five clicks deep from the home page. What usually helps most?",
      ["Nothing, depth does not matter", "Link to it from relevant, well linked pages such as the home page or a topic hub", "Add more keywords to it", "Put it in the sitemap only"], 1,
      "Important pages should be a few clicks from the home page, linked from pages that already earn attention."),
    B("Add a related reading block. Create an aside with class related containing at least three links. Every link in it must have descriptive anchor text of three or more words, and none may say click here, read more or here.",
      "<aside class=\"related\">\n  <h2>Keep reading</h2>\n  <a href=\"herbs.html\">How to store fresh herbs</a>\n  <a href=\"pasta.html\">Weeknight pasta in 20 minutes</a>\n  <a href=\"prep.html\">Meal prep for a busy week</a>\n</aside>",
      "Every link now says where it goes. Crawlers learn what the target is about and people can decide before they click.",
      [count(".related a[href]", 3, "At least three links in .related"),
       words_each(".related a", 3, "Every link in .related has an anchor of three or more words",
                  hint="Short anchors like Pasta tell less than Weeknight pasta in 20 minutes."),
       text_not(".related a", "^(click here|read more|here|more|this|link)$", "No link says click here, read more, here or this",
                hint="Replace vague anchors with the topic of the page the link goes to.")]),
    O("Fix an orphan page, in order.",
      ["Find pages that no other page links to", "Decide whether each one deserves to exist", "Link the keepers from relevant pages with descriptive anchors", "Redirect or remove the rest"],
      "Not every orphan should be saved. Some are outdated and are better merged or removed."),
    C("Links are for readers first",
      "Add a link where a reader would genuinely want to go next. Links stuffed into footers with exact match anchors help nobody and can look manipulative."),
])

SI6 = L("Images search can read", KW + ["images", "alt", "alt text", "filenames", "lazy loading", "image search"], [
    C("Search reads the words around a picture",
      "Search engines cannot reliably tell what an image shows, so they rely on text: the alt attribute, the file name, the caption and the surrounding copy. Good alt text describes what the image shows for someone who cannot see it. It also feeds image search, which can send real traffic for visual topics like food, products and places."),
    M("Pick the best alt text for a photo of a finished lemon pasta in a white bowl.",
      ["image", "pasta pasta lemon pasta recipe best pasta", "Lemon spaghetti in a white bowl, topped with parsley", "IMG_2034.jpg"], 2,
      "Describe what is actually shown, briefly. Keyword lists are unhelpful for screen reader users and read as spam."),
    M("A purely decorative divider image should have...",
      ["A long description", "An empty alt attribute (alt=\"\") so screen readers skip it", "No alt attribute at all", "The page keyword"], 1,
      "Empty alt says this image carries no information. Leaving alt out entirely makes some screen readers read the file name."),
    B("Add a recipe card with class recipe-card that has an image. The image must have descriptive alt text of at least 15 characters, a file name made of words joined by hyphens (like lemon-spaghetti.jpg), width and height attributes, and loading=\"lazy\".",
      "<div class=\"recipe-card\">\n  <img src=\"lemon-spaghetti.jpg\" alt=\"Lemon spaghetti in a white bowl, topped with parsley\" width=\"600\" height=\"400\" loading=\"lazy\">\n  <h3>Lemon spaghetti</h3>\n</div>",
      "Alt text for people, a readable file name for search, dimensions so the layout does not jump, and lazy loading so images below the fold do not slow the first view.",
      [has(".recipe-card img", "An image in .recipe-card"),
       attr(".recipe-card img", "alt", "Alt text of at least 15 characters", match="^.{15,}$", every=True),
       attr(".recipe-card img", "src", "A descriptive file name with words joined by hyphens", match="(^|/)[a-z0-9]+(-[a-z0-9]+)+\\.(jpe?g|png|webp|avif)$", every=True,
            hint="Rename files like IMG_2034.jpg to something like lemon-spaghetti.jpg, all lowercase."),
       attr(".recipe-card img", "width", "A width attribute", every=True),
       attr(".recipe-card img", "height", "A height attribute", every=True),
       attr(".recipe-card img", "loading", "loading=\"lazy\"", match="^lazy$", every=True)]),
    O("Prepare an image before you upload it.",
      ["Crop it to what matters", "Resize it close to the largest size it will display", "Export in an efficient format such as WebP or a well compressed JPEG", "Give it a descriptive file name"],
      "Resize before you compress, and name it before it goes live. Renaming later breaks links to it."),
    C("Do not lazy load the first image",
      "Lazy loading helps images further down the page. The main image people see first, such as a hero photo, should load right away, or you make the most important picture arrive last."),
])

SI7 = L("Local search basics", KW + ["local", "local seo", "business profile", "nap", "reviews", "maps"], [
    C("Nearby searches work differently",
      "For searches like pizza near me, Google shows a map with business listings. Google says local results are based mainly on relevance, distance and prominence. You control relevance by describing your business accurately, and prominence grows with reviews, links and mentions. Distance you cannot change. The core tool is a free Google Business Profile."),
    M("Your bakery's address is written three different ways across your site, your profile and a directory. Why fix it?",
      ["It does not matter", "Consistent name, address and phone details make it easier for search engines to trust and match your listings", "Google penalizes abbreviations", "Directories require it by law"], 1,
      "Consistency is the point. Pick one format for your name, address and phone number, sometimes called NAP, and use it everywhere."),
    M("Which review practice follows Google's rules?",
      ["Offer a discount for five star reviews", "Ask every customer for an honest review and reply to them, good and bad", "Write reviews for yourself", "Only ask happy customers"], 1,
      "Incentivized and fake reviews break Google's policies. Asking everyone and replying professionally is allowed and builds trust."),
    B("Add your business contact details in a footer section with class local. Use an address element containing the business name, a street address, and a phone number written as a tel: link.",
      "<section class=\"local\">\n  <address>\n    <strong>Casa Verde Kitchen</strong><br>\n    12 Market Street, Springfield<br>\n    <a href=\"tel:+15555550123\">(555) 555 0123</a>\n  </address>\n</section>",
      "Clear contact details on the site, in the same format as your profile. The tel: link lets phone users call with one tap.",
      [has(".local address", "An address element inside .local"),
       has(".local address a[href^=\"tel:\"]", "A phone number as a tel: link"),
       {"sel": ".local address", "textMin": 25, "label": "The address includes a name and a street address"}]),
    O("Set up local search for a new shop.",
      ["Claim and verify the Google Business Profile", "Fill in the category, hours, photos and description accurately", "Put the same name, address and phone on your website", "Ask customers for honest reviews and reply to them"],
      "Verification first, because nothing else shows until it is done. Reviews are ongoing work, not a one time step."),
    N("Example numbers: your profile got 1,200 views last month and 36 people tapped to call. What percent of views led to a call?", 3,
      "36 divided by 1,200 is 0.03, so 3%. Watching this rate after you add photos or update hours tells you whether the change helped.",
      gen={"vars": {"v": [600, 3000, 200], "c": [12, 60, 6]}, "answer": "c/v*100", "round": 2,
           "prompt": "Example numbers: your profile got {v} views last month and {c} people tapped to call. What percent of views led to a call?",
           "explain": "{c} divided by {v}, times 100, is {A}%."}),
    C("Local pages that are actually local",
      "If you serve several towns, each town page needs real local detail: the address, the team, photos and directions. Swapping the town name into an identical page creates thin pages that rarely rank."),
])

SI8 = L("Reading Search Console", KW + ["search console", "impressions", "clicks", "ctr", "position", "queries", "reports"], [
    C("The four numbers",
      "Search Console's Performance report shows clicks, impressions (how often your page appeared in results), click-through rate (clicks divided by impressions) and average position. Average position is an average over every time you appeared, so a page that ranks 3 for one query and 40 for another can show something in between that matches neither."),
    N("Example numbers: a query shows 250 clicks from 10,000 impressions. What is the CTR in percent?", 2.5,
      "250 divided by 10,000 is 0.025, which is 2.5%.",
      gen={"vars": {"c": [100, 600, 50], "i": [5000, 20000, 1000]}, "answer": "c/i*100", "round": 2,
           "prompt": "Example numbers: a query shows {c} clicks from {i} impressions. What is the CTR in percent?",
           "explain": "{c} divided by {i}, times 100, is {A}%."}),
    M("A page has many impressions, an average position around 4, and a low CTR. What is the first thing to try?",
      ["Build more links", "Rewrite the title and description so the snippet matches the query better", "Delete the page", "Change the URL"], 1,
      "It already ranks well enough to be seen. People see it and choose something else, which points to the snippet."),
    M("Impressions doubled this month but clicks stayed flat. Which explanation is possible and worth checking first?",
      ["Google is broken", "The page started appearing for new queries where it ranks low, so many people see it but few scroll that far", "The CTR formula changed", "The site was penalized"], 1,
      "Open the queries for that page and sort by impressions. New low ranking queries add impressions without clicks."),
    O("Investigate a traffic drop, in order.",
      ["Confirm the drop and its dates in the Performance report", "Compare the period with the same one before it to find which pages and queries fell", "Check for site changes, indexing problems or manual actions around those dates", "Fix the cause you found, then annotate the date and watch the trend"],
      "Narrow first, then explain. Guessing at causes before you know which pages fell leads to fixing the wrong thing."),
    W("Find the quick wins",
      "Example data: Page A ranks at an average position of 8 for a query with 5,000 impressions. Page B ranks at 45 for a query with 9,000 impressions. Which do you work on first?",
      ["Page A is already near the top of page one. Small improvements can move it into positions where many more people click.",
       "Page B is far from page one. It needs much bigger work before more people see it.",
       "So Page A is the quick win: improve its content and snippet for that query.",
       "Page B goes on the list for deeper work later."],
      "Positions roughly 5 to 15 are often where small improvements pay off fastest."),
    C("Search Console data is sampled and delayed",
      "Numbers arrive a few days late and some rare queries are hidden for privacy. Use it for trends and direction rather than precise totals."),
])

SI9 = L("Capstone: optimize one page end to end", KW + ["capstone", "on page", "audit", "optimize", "checklist"], [
    C("Put the level together",
      "You will take one page and give it everything from this level: a title that earns the click, a description, one clear h1 and a heading outline, descriptive internal links, readable images and a canonical address. Then you write a short note on what you changed and how you will measure it."),
    M("Before optimizing a page, what must you know first?",
      ["How many words competitors use", "Which query and intent the page is meant to serve", "The keyword density", "The page's age"], 1,
      "Every other decision follows from the query and intent. Without them you cannot judge whether a title or heading is right."),
    O("Order an on page optimization pass.",
      ["Confirm the target query and intent", "Rewrite the title and description for that query", "Fix the heading outline and answer the query early", "Add descriptive internal links to and from the page", "Check images, alt text and file names"],
      "Intent first, snippet and outline next, links and images after. The middle steps can swap, but intent always comes first.",
      groups=[[1, 2], [3, 4]]),
    B("Capstone. Your page needs everything from this level: a title of 60 characters or fewer, a meta description of 70 to 160 characters, a canonical link with an absolute https URL, exactly one h1, at least two h2 headings in a .guide article, a .related block with at least three links, and a .recipe-card image with alt text, width and height.",
      "<title>Weeknight Dinners in 30 Minutes | Casa Verde</title>\n<meta name=\"description\" content=\"Tested weeknight dinners you can cook in 30 minutes, with a shopping list for your phone.\">\n<link rel=\"canonical\" href=\"https://casaverde.example/weeknight-dinners\">\n<article class=\"guide\">\n  <h1>Weeknight dinners in 30 minutes</h1>\n  <h2>What makes a dinner fast</h2>\n  <h2>Five dinners to start with</h2>\n</article>\n...",
      "That is a fully optimized page. The rest is measurement: watch its impressions, CTR and position for the target query over the next few weeks.",
      [text_max("title", 60, "Title of 60 characters or fewer"),
       attr("meta[name=\"description\"]", "content", "Meta description of 70 to 160 characters", match="^.{70,160}$"),
       attr("link[rel=\"canonical\"]", "href", "A canonical link with an absolute https URL", match="^https://",
            hint="Add <link rel=\"canonical\" href=\"https://yoursite.example/this-page\">. It names the one address you want indexed."),
       at_most("h1", 1, "Exactly one h1"),
       count(".guide h2", 2, "At least two h2 headings in .guide"),
       count(".related a[href]", 3, "At least three links in .related"),
       attr(".recipe-card img", "alt", "Recipe card image with alt text", match="^.{15,}$", every=True),
       attr(".recipe-card img", "width", "Recipe card image with width and height", every=True)]),
    WR("Write a short change note for this page: the target query, what you changed, and the one metric you will watch and when you will check it. Three or more lines.",
       [lines(3, "At least three lines"),
        must("query|keyword|search", "Names the target query"),
        must("ctr|click|impression|position", "Names a Search Console metric to watch"),
        must("week|month|days|\\d", "Says when you will check", hint="Changes take time to show up. Name a check date or a number of weeks."),
        words(20, 150)],
       "Target query: weeknight dinners in 30 minutes.\nChanged: new title and description, one h1, two new sections, three internal links, renamed and described images.\nWatch: CTR and average position for that query in Search Console, checked after four weeks.",
       "A change note turns optimization into an experiment you can learn from."),
    C("Intermediate complete",
      "You can now take any page and make it findable and clickable. Advanced goes under the hood: crawling, indexing, structured data, speed and sites that change."),
])

# =====================================================================
# Advanced: Technical SEO in depth
# =====================================================================

SA1 = L("Crawling, robots.txt and noindex", KW + ["crawl", "crawling", "robots.txt", "noindex", "indexing", "googlebot"], [
    C("Crawl, index, rank are separate gates",
      "A page has to be crawled (fetched), then indexed (stored and understood), before it can rank. robots.txt controls crawling: it asks bots not to fetch certain paths. A noindex robots meta tag controls indexing: it asks search engines not to show a page. They are not the same tool, and mixing them up is one of the most common technical mistakes."),
    M("You add Disallow: /drafts/ to robots.txt, and also put noindex on those pages. Months later some draft URLs still show in results with no description. Why?",
      ["robots.txt is ignored", "Blocked from crawling, Google never sees the noindex tag, but it can still index the bare URL from links", "noindex takes a year to work", "Drafts are always indexed"], 1,
      "Google documents this. To keep a page out of results, let it be crawled and serve noindex. Block crawling only for things you do not need fetched at all."),
    M("Which job is robots.txt right for?",
      ["Hiding private customer data", "Stopping crawlers from wasting time on endless internal search result URLs", "Removing a page from results fast", "Protecting a staging site"], 1,
      "robots.txt is public and only a request. Private data needs authentication; staging sites need a password, not a Disallow line."),
    WR("Write a robots.txt for a recipe site. Allow everything by default, block the internal search results under /search, and point to the sitemap at https://casaverde.example/sitemap.xml.",
       [must("^user-agent:\\s*\\*", "Starts a group for all crawlers with User-agent: *", flags="im"),
        must("^disallow:\\s*/search", "Disallows /search", flags="im"),
        must("^sitemap:\\s*https://\\S+sitemap\\S*\\.xml", "Names the sitemap with an absolute https URL", flags="im",
             hint="The Sitemap line needs the full URL, including https://."),
        avoid("^disallow:\\s*/\\s*$", "Does not block the whole site", flags="im",
              hint="Disallow: / on its own line blocks every page. Remove it."),
        lines(3, "At least three lines")],
       "User-agent: *\nDisallow: /search\n\nSitemap: https://casaverde.example/sitemap.xml",
       "Short and specific. Every extra rule is a chance to block something you needed."),
    B("Mark a thin page so it stays out of results while crawlers can still read it. Add a robots meta tag whose content includes noindex, inside an element with class thin-page (put the tag next to a short placeholder section), and keep follow so links on it still count.",
      "<section class=\"thin-page\">\n  <meta name=\"robots\" content=\"noindex, follow\">\n  <p>Search results for: basil</p>\n</section>",
      "In a real site this tag goes in the head of that page only. noindex, follow keeps it out of results while its links still help the pages they point to.",
      [attr("meta[name=\"robots\"]", "content", "A robots meta tag with noindex", match="noindex"),
       attr("meta[name=\"robots\"]", "content", "It keeps follow, not nofollow", match="^(?!.*nofollow).*follow",
            hint="Write content=\"noindex, follow\". nofollow would stop the links on the page from counting."),
       has(".thin-page", "The placeholder section with class thin-page")]),
    O("Remove a page from Google's results properly.",
      ["Make sure robots.txt does not block the page", "Serve a noindex tag, or a 404 or 410 if the page is gone", "Use the Removals tool in Search Console if it must disappear quickly", "Confirm it drops out with the URL Inspection tool"],
      "Unblocking comes first, because a blocked page can never show Google its noindex. The removals tool is temporary; the tag or status code is what makes it permanent."),
    C("Crawl budget matters only at scale",
      "Google says most sites with fewer than a few thousand URLs do not need to worry about crawl budget. It matters for very large sites, or sites that generate endless URLs through filters, calendars and session parameters."),
])

SA2 = L("Canonicals and duplicate content", KW + ["canonical", "duplicate", "parameters", "www", "https", "trailing slash"], [
    C("One page, many addresses",
      "The same content often lives at several URLs: with and without www, http and https, with tracking parameters such as ?utm_source=news, with and without a trailing slash, or sorted versions of a list. Search engines pick one to show, called the canonical. You help them pick the right one with a rel=canonical link, redirects, consistent internal links and your sitemap."),
    M("Is rel=canonical a command Google must follow?",
      ["Yes, always", "No, it is a strong hint Google weighs with redirects, internal links and sitemaps", "Only on https sites", "Only for product pages"], 1,
      "Google treats it as a signal. If your internal links all point to a different version, the hint can lose."),
    M("Which version should a product page sorted by price (/shoes?sort=price) usually name as canonical?",
      ["Itself", "The unsorted /shoes page", "The home page", "None"], 1,
      "The sorted view shows the same items. Pointing to /shoes consolidates signals on one URL."),
    N("Example: a site serves every page at http and https, with and without www, and with and without a trailing slash. How many addresses can each page be reached at?", 8,
      "2 times 2 times 2 is 8. Each independent choice doubles the count, which is why redirects to one version matter.",
      gen={"vars": {"k": [2, 5, 1]}, "answer": "2^k", "round": 0,
           "prompt": "Example: each page can be reached through {k} independent yes or no URL variations (like www or not, https or not). How many addresses can each page have?",
           "explain": "Each choice doubles the count: 2 to the power {k} is {A}."}),
    B("Add a self referencing canonical for your guide page. Use a link element with rel=\"canonical\" and an absolute https URL with no query string (no ?) and no fragment (no #).",
      "<link rel=\"canonical\" href=\"https://casaverde.example/guides/fresh-herbs\">",
      "Absolute, https, clean. A self canonical on every indexable page is a cheap guard against parameter duplicates.",
      [attr("link[rel=\"canonical\"]", "href", "A canonical link with an absolute https URL", match="^https://", every=True),
       attr("link[rel=\"canonical\"]", "href", "No query string or fragment in the canonical URL", match="^[^?#]+$", every=True,
            hint="Remove anything from ? or # onward. The canonical names the clean address."),
       at_most("link[rel=\"canonical\"]", 1, "Exactly one canonical link",
               hint="Two canonicals on one page send mixed signals, and Google may ignore both.")]),
    O("Consolidate a duplicate set, in order.",
      ["Pick the one URL you want shown", "301 redirect versions people never need, such as http and non www", "Add rel=canonical on versions that must stay, such as sorted views", "Point every internal link and the sitemap at the chosen URL"],
      "Decide first, then use the strongest signal each version allows: redirects where possible, canonicals where a page must remain, and consistency everywhere."),
    C("Duplicate is not a penalty",
      "Duplicate content across your own URLs is usually not punished. The cost is splitting: links and signals spread across copies, and the wrong copy may be shown. Consolidating fixes both."),
])

SA3 = L("Sitemaps that help", KW + ["sitemap", "xml", "lastmod", "index", "submit"], [
    C("A sitemap is a list of what you want indexed",
      "An XML sitemap lists the canonical URLs you want search engines to know about. The sitemaps protocol allows up to 50,000 URLs or 50 MB uncompressed per file; bigger sites use a sitemap index that lists several sitemaps. Including a URL does not force indexing, but it helps discovery, especially for new and deep pages."),
    M("Which URLs belong in the sitemap?",
      ["Every URL the server can produce", "Canonical, indexable pages that return 200", "Redirects so Google learns them", "Pages with noindex, to be safe"], 1,
      "A sitemap full of redirects, noindex pages and duplicates sends contradicting signals and wastes the file's value."),
    N("A shop has 120,000 product URLs to list. At 50,000 URLs per sitemap file, what is the minimum number of sitemap files needed?", 3,
      "120,000 divided by 50,000 is 2.4, so you need 3 files, listed together in one sitemap index.",
      gen={"vars": {"u": [60000, 260000, 20000]}, "answer": "ceil(u/50000)", "round": 0,
           "prompt": "A shop has {u} product URLs to list. At 50,000 URLs per sitemap file, what is the minimum number of sitemap files needed?",
           "explain": "{u} divided by 50,000, rounded up, is {A}."}),
    M("What should lastmod reflect?",
      ["The date the sitemap was generated", "The last significant change to the page's content", "Today, always, so Google crawls more", "The publish date only"], 1,
      "Google has said it uses lastmod when it is consistently accurate. Setting every date to today teaches it to ignore your dates."),
    WR("Write a small XML sitemap with two URLs from https://casaverde.example. Each url needs a loc with an absolute https address and a lastmod in YYYY-MM-DD format.",
       [must("<urlset[^>]*xmlns=\"http://www\\.sitemaps\\.org/schemas/sitemap/0\\.9\"", "A urlset with the sitemaps.org namespace",
             hint="Use <urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">."),
        must("<loc>https://[^<]+</loc>[\\s\\S]*<loc>https://[^<]+</loc>", "Two loc entries with absolute https URLs"),
        must("<lastmod>\\d{4}-\\d{2}-\\d{2}</lastmod>", "A lastmod in YYYY-MM-DD format"),
        must("</urlset>\\s*$", "Closes the urlset at the end")],
       "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n  <url>\n    <loc>https://casaverde.example/</loc>\n    <lastmod>2026-09-28</lastmod>\n  </url>\n  <url>\n    <loc>https://casaverde.example/guides/fresh-herbs</loc>\n    <lastmod>2026-09-14</lastmod>\n  </url>\n</urlset>",
       "Real sitemaps are generated by your site's code, but knowing the shape lets you spot a broken one in seconds."),
    O("Launch a sitemap, in order.",
      ["Generate it from your list of canonical, indexable URLs", "Check it returns 200 and validates as XML", "Reference it in robots.txt with a Sitemap line", "Submit it in Search Console and watch the indexing report"],
      "Correct contents first. Then make it findable two ways, and use Search Console to see how many listed URLs actually get indexed."),
    C("The gap is the insight",
      "Search Console shows how many sitemap URLs are indexed. A big gap between submitted and indexed points to thin, duplicate or blocked pages, which is a better to do list than any generic checklist."),
])

SA4 = L("Structured data with JSON-LD", KW + ["structured data", "schema", "json-ld", "rich results", "schema.org"], [
    C("Saying what a page is, in a machine language",
      "Structured data describes a page's content using the schema.org vocabulary: this is a Recipe with a cook time, this is an Organization with a logo, this is a Product with a price. Google recommends the JSON-LD format, a script block of JSON. It can make a page eligible for rich results such as recipe cards, but eligibility is not a guarantee, and the markup must describe content that is visible on the page."),
    M("Your recipe page adds Review markup with five stars, but there are no reviews on the page. What happens?",
      ["Free stars", "It breaks Google's structured data guidelines and can lead to a manual action", "Nothing", "It improves rankings"], 1,
      "Markup must match what users can see. Marking up invisible or invented content is treated as spam."),
    M("What does a valid Recipe markup most directly do?",
      ["Guarantees position one", "Makes the page eligible for recipe rich results, if Google chooses to show them", "Replaces the need for content", "Removes the need for a title"], 1,
      "Structured data helps understanding and eligibility. It does not make weak content rank."),
    B("Add JSON-LD structured data for one recipe. Put a script with type=\"application/ld+json\" inside your .recipe-card. The JSON must parse and have @context set to https://schema.org, @type set to Recipe, a name, and recipeIngredient as a list.",
      "<div class=\"recipe-card\">\n  <h3>Lemon spaghetti</h3>\n  <script type=\"application/ld+json\">\n  {\n    \"@context\": \"https://schema.org\",\n    \"@type\": \"Recipe\",\n    \"name\": \"Lemon spaghetti\",\n    \"totalTime\": \"PT25M\",\n    \"recipeIngredient\": [\"200 g spaghetti\", \"1 lemon\", \"Parmesan\"]\n  }\n  </script>\n</div>",
      "The preview never runs scripts, but search engines read this block. Paste the real page into Google's Rich Results Test to confirm it is eligible.",
      [has(".recipe-card " + LDSEL, "A JSON-LD script inside .recipe-card"),
       ld(".recipe-card " + LDSEL, ["@context", "@type", "name", "recipeIngredient"], "The JSON parses, is a Recipe, and has @context, name and recipeIngredient", type_="Recipe",
          hint="Check for a missing comma or a trailing comma after the last item, and use straight double quotes. JSON is strict."),
       rx("\"@context\"\\s*:\\s*\"https://schema\\.org/?\"", "@context is https://schema.org"),
       rx("\"recipeIngredient\"\\s*:\\s*\\[", "recipeIngredient is a list in square brackets")]),
    O("Ship structured data safely.",
      ["Choose the schema.org type that matches the page", "Mark up only content visible on the page", "Validate it with the Rich Results Test", "Watch the enhancement report in Search Console for errors"],
      "Right type, honest content, then testing before and after release."),
    C("Times and durations have formats",
      "Schema.org uses ISO 8601 for durations: PT25M is 25 minutes and PT1H30M is an hour and a half. Small format errors silently make markup ineligible, which is why validation is a step, not an option."),
])

SA5 = L("Core Web Vitals", KW + ["core web vitals", "lcp", "inp", "cls", "page experience", "speed"], [
    C("Three measures of how a page feels",
      "Google's Core Web Vitals measure real user experience. Largest Contentful Paint (LCP) is when the main content appears; good is 2.5 seconds or less. Interaction to Next Paint (INP) is how fast the page responds to taps and clicks; good is 200 milliseconds or less. Cumulative Layout Shift (CLS) is how much things jump around; good is 0.1 or less. Each is judged at the 75th percentile of real visits."),
    M("Text jumps down as a photo loads, and people tap the wrong button. Which metric is that, and the classic fix?",
      ["LCP; compress the photo", "CLS; give images width and height (or an aspect ratio) so space is reserved", "INP; remove JavaScript", "None of them"], 1,
      "Reserved space means nothing moves when the image arrives."),
    M("What does judged at the 75th percentile mean for LCP?",
      ["The average visit must be under 2.5 seconds", "At least 75% of visits must have LCP of 2.5 seconds or better to count as good", "Only the fastest 75% are counted", "Lab tests decide"], 1,
      "It is a bar for most visitors, including slower phones and networks, not just your fast laptop."),
    N("Example: of 2,000 recorded visits, 1,400 had LCP under 2.5 seconds. What percent of visits were good?", 70,
      "1,400 divided by 2,000 is 70%, which is short of the 75% needed for the page to be rated good.",
      gen={"vars": {"t": [1000, 4000, 500], "p": [55, 90, 5]}, "show": {"g": "t*p/100"}, "answer": "p", "round": 0,
           "prompt": "Example: of {t} recorded visits, {g} had LCP under 2.5 seconds. What percent of visits were good?",
           "explain": "{g} divided by {t} is {A}%. The page needs 75% or more to be rated good."}),
    B("Speed up the main image of your page. Add an image with class hero-img that loads early: give it width and height, fetchpriority=\"high\", and do not lazy load it. Then make sure every image inside .recipe-card is lazy loaded.",
      "<img class=\"hero-img\" src=\"weeknight-dinner-table.jpg\" alt=\"A weeknight dinner table set for four\" width=\"1200\" height=\"600\" fetchpriority=\"high\">",
      "The largest image usually decides LCP, so it gets priority, while images further down wait their turn. Width and height protect CLS.",
      [has("img.hero-img", "An image with class hero-img"),
       attr("img.hero-img", "fetchpriority", "The hero image has fetchpriority=\"high\"", match="^high$"),
       none("img.hero-img[loading=\"lazy\"]", "The hero image is not lazy loaded",
            hint="Lazy loading the biggest image delays it, which makes LCP worse."),
       attr("img.hero-img", "width", "The hero image has width and height", every=True),
       attr("img.hero-img", "height", "The hero image has a height attribute", every=True),
       none(".recipe-card img:not([loading=\"lazy\"])", "Every recipe card image is lazy loaded")]),
    O("Fix a slow LCP, in order.",
      ["Find which element is the LCP element in a tool such as PageSpeed Insights", "Make sure it is in the initial HTML, not added later by JavaScript", "Give it priority and a properly sized, compressed file", "Check field data again after release"],
      "Identify, then make it discoverable, then make it light. Field data confirms it worked for real visitors."),
    C("Lab and field disagree, and that is fine",
      "Lab tools test one simulated visit; field data such as the Chrome UX Report measures real ones. Use the lab to debug and the field to judge."),
])

SA6 = L("JavaScript and rendering", KW + ["javascript seo", "rendering", "spa", "links", "hydration", "client side"], [
    C("Crawl, then render, then index",
      "Google can run JavaScript, but rendering happens as a separate step that can come later than the first crawl, and other crawlers and many link preview bots do not run JavaScript at all. Content and links that exist in the initial HTML are the safest. Links must be real a elements with an href; a click handler on a div is not a link a crawler can follow."),
    M("Which navigation can a crawler follow?",
      ["<div onclick=\"go('/recipes')\">Recipes</div>", "<a href=\"/recipes\">Recipes</a>", "<span data-route=\"/recipes\">Recipes</span>", "<button onclick=\"router.push('/recipes')\">Recipes</button>"], 1,
      "Crawlers discover pages through href values. The others only work when a script runs and a person clicks."),
    M("A single page app shows a spinner, then loads the article with JavaScript. What helps search the most?",
      ["Nothing", "Server side rendering or pre rendering so the article is in the initial HTML", "A longer spinner", "Putting the text in an image"], 1,
      "Rendering on the server gives crawlers and users the content in the first response, and it usually helps LCP too."),
    B("Replace script only navigation with crawlable links. Add a nav with class crawl-nav containing at least three a elements with real href values, and make sure no element inside it uses an onclick attribute.",
      "<nav class=\"crawl-nav\" aria-label=\"Sections\">\n  <a href=\"/recipes\">Recipes</a>\n  <a href=\"/guides\">Guides</a>\n  <a href=\"/about\">About</a>\n</nav>",
      "Real links work for crawlers, keyboards, screen readers, middle click and copy link. Frameworks can still intercept the click for fast transitions.",
      [count(".crawl-nav a[href]", 3, "At least three links with href in .crawl-nav"),
       none(".crawl-nav [onclick]", "No onclick handlers inside .crawl-nav"),
       none(".crawl-nav a[href^=\"javascript:\"], .crawl-nav a[href=\"#\"]", "No javascript: or # placeholder links",
            hint="Give each link the real address of the page it opens.")]),
    O("Check how Google sees a JavaScript page.",
      ["Open the URL Inspection tool in Search Console", "Run a live test of the page", "Look at the rendered HTML and screenshot", "Confirm the main content and links are present"],
      "The rendered HTML is the truth. If content is missing there, Google cannot index it."),
    C("Status codes still matter in apps",
      "A single page app often answers every URL with 200 and draws a not found message with JavaScript. Search engines then see thousands of empty pages. Return a real 404 for missing content, or add noindex to the error view."),
])

SA7 = L("International sites and hreflang", KW + ["hreflang", "international", "languages", "x-default", "localization"], [
    C("Point each searcher to their version",
      "If a page exists in several languages or regions, hreflang annotations tell search engines which version suits which audience. Each version lists every version, including itself, using a language code (en, es) optionally with a region (en-GB, es-MX). An x-default entry names the page for everyone else. The annotations must be reciprocal: if page A points to B, B must point back to A."),
    M("Your English page lists the Spanish one in hreflang, but the Spanish page lists nothing. What happens?",
      ["It works anyway", "The annotation may be ignored, because hreflang pairs must confirm each other", "The Spanish page is deindexed", "Google translates it"], 1,
      "Return links are how search engines trust the pairing. One sided hreflang is a common reason it fails."),
    M("Which code is valid for Spanish in Mexico?",
      ["es-MX", "mx-ES", "spanish-mexico", "es_MX_2"], 0,
      "Language first (ISO 639-1), then region (ISO 3166-1 alpha-2), joined by a hyphen."),
    B("Add hreflang annotations for a page that exists in English and Spanish. Add link elements with rel=\"alternate\": one with hreflang=\"en\", one with hreflang=\"es\", and one with hreflang=\"x-default\". Every href must be an absolute https URL.",
      "<link rel=\"alternate\" hreflang=\"en\" href=\"https://casaverde.example/en/herbs\">\n<link rel=\"alternate\" hreflang=\"es\" href=\"https://casaverde.example/es/hierbas\">\n<link rel=\"alternate\" hreflang=\"x-default\" href=\"https://casaverde.example/en/herbs\">",
      "Both language versions carry this same block, which makes the pairs reciprocal. x-default catches everyone else.",
      [has("link[rel=\"alternate\"][hreflang=\"en\"]", "An en alternate"),
       has("link[rel=\"alternate\"][hreflang=\"es\"]", "An es alternate"),
       has("link[rel=\"alternate\"][hreflang=\"x-default\"]", "An x-default alternate"),
       attr("link[rel=\"alternate\"][hreflang]", "href", "Every alternate uses an absolute https URL", match="^https://", every=True,
            hint="Relative paths like /es/hierbas are not reliable here. Write the full https URL.")]),
    O("Launch a translated section, in order.",
      ["Translate and adapt the content for the audience, not just the words", "Give each language its own URL", "Add reciprocal hreflang on every version, with x-default", "Check the international targeting issues in your SEO tools after release"],
      "Separate URLs make each version indexable. Automatic redirects by IP can hide versions from crawlers, so let people choose."),
    C("Translation is not localization",
      "Prices, units, dates, examples and search phrases differ by market. People in Mexico and Spain may search for the same dish with different words, so research keywords per market."),
])

SA8 = L("Migrations without losing traffic", KW + ["migration", "redirects", "301", "redesign", "domain change", "launch"], [
    C("Most traffic losses are self inflicted",
      "Site moves, redesigns and URL changes are where established sites lose search traffic, usually because old URLs stop working. The fix is a redirect map: every old URL that matters points with a permanent 301 redirect to its closest new equivalent. Redirecting everything to the home page tends to be treated like a missing page."),
    M("Which redirect fits a permanent URL change?",
      ["302 Found", "301 Moved Permanently (or 308)", "A meta refresh after 10 seconds", "A JavaScript redirect only"], 1,
      "Permanent server side redirects are the clearest signal that the new URL replaces the old one."),
    M("An old product no longer exists and has no close equivalent. Best option?",
      ["Redirect to the home page", "Redirect to the closest category if it genuinely helps, otherwise return 404 or 410", "Keep the old page with no content", "Block it in robots.txt"], 1,
      "A redirect should land people somewhere that serves the same need. Otherwise an honest not found is better."),
    WR("Write a redirect map for a redesign. Use one line per redirect in the format: old path, new path, status. Include at least four lines, all with status 301, and do not send anything to the home page /.",
       [lines(4, "At least four redirect lines"),
        must("^/\\S+\\s*,\\s*/\\S+\\s*,\\s*301\\s*$", "Lines follow old path, new path, 301", flags="im",
             hint="Example line: /recipes/lemon-pasta, /dinners/lemon-spaghetti, 301"),
        avoid(",\\s*/\\s*,", "Nothing redirects to the home page",
              hint="Point each old URL at its closest new page instead of /."),
        avoid(",\\s*302\\s*$", "No temporary 302 redirects for permanent moves", flags="im")],
       "/recipes/lemon-pasta, /dinners/lemon-spaghetti, 301\n/recipes/herb-guide, /guides/fresh-herbs, 301\n/blog/meal-prep-101, /guides/meal-prep, 301\n/about-us, /about, 301",
       "A real map is usually a spreadsheet built from analytics and Search Console, so the URLs that earn traffic and links are never missed."),
    O("Run a site migration, in order.",
      ["Crawl the old site and export URLs with traffic and links", "Build and test the redirect map on staging", "Launch, and check that redirects and canonicals work on the live site", "Submit the new sitemap and monitor Search Console for errors"],
      "Inventory before anything changes, because once the old site is gone you cannot list what it had."),
    N("Example: your old site has 1,800 URLs and 1,710 of them have a tested redirect. What percent are covered?", 95,
      "1,710 divided by 1,800 is 0.95, so 95%. The 5% left should be checked against traffic before launch.",
      gen={"vars": {"t": [1000, 3000, 200], "p": [80, 98, 2]}, "show": {"d": "t*p/100"}, "answer": "p", "round": 0,
           "prompt": "Example: your old site has {t} URLs and {d} of them have a tested redirect. What percent are covered?",
           "explain": "{d} divided by {t} is {A}%."}),
    C("Expect a wobble",
      "Even a clean migration can fluctuate for a few weeks while search engines recrawl. Keep the redirects in place for a long time, ideally permanently, and keep the old domain registered."),
])

SA9 = L("Capstone: a technical audit", KW + ["capstone", "audit", "technical seo", "prioritize", "checklist"], [
    C("Find, then rank, then fix",
      "A technical audit is not a list of every warning a tool prints. It is a short, ranked list: what blocks crawling or indexing first, what wastes signals second, and what slows people down third. You will fix the page and write the ranked list."),
    M("Which issue goes first in an audit?",
      ["Missing alt text on one image", "robots.txt accidentally blocks the whole site", "Titles a little long", "Two pages share a description"], 1,
      "Nothing else matters if crawlers cannot fetch the site. Blockers outrank polish."),
    O("Rank these issues from most to least urgent.",
      ["Important pages carry noindex by mistake", "Old URLs from a redesign return 404 with no redirects", "Duplicate parameter URLs without canonicals", "LCP is slightly over 2.5 seconds on mobile"],
      "Things that remove pages from search first, lost signals next, efficiency and experience after."),
    B("Capstone. Make this page technically sound: exactly one canonical with a clean absolute https URL, valid Recipe JSON-LD in .recipe-card, hreflang links for en, es and x-default with absolute https URLs, a .crawl-nav with at least three real links and no onclick, a hero image with fetchpriority high and no lazy loading, and no robots meta tag that says noindex outside .thin-page.",
      "See the earlier lessons in this level. Each check below matches one of them.",
      "That page would pass a careful technical review. Real audits do this across templates, because fixing one template fixes thousands of pages.",
      [at_most("link[rel=\"canonical\"]", 1, "Exactly one canonical link"),
       attr("link[rel=\"canonical\"]", "href", "Canonical is absolute https with no ? or #", match="^https://[^?#]+$", every=True),
       ld(".recipe-card " + LDSEL, ["@context", "@type", "name"], "Valid Recipe JSON-LD in .recipe-card", type_="Recipe"),
       has("link[rel=\"alternate\"][hreflang=\"x-default\"]", "hreflang includes x-default"),
       attr("link[rel=\"alternate\"][hreflang]", "href", "hreflang URLs are absolute https", match="^https://", every=True),
       count(".crawl-nav a[href]", 3, "Crawlable nav with three or more links"),
       none(".crawl-nav [onclick]", "No onclick in the nav"),
       attr("img.hero-img", "fetchpriority", "Hero image has fetchpriority high", match="^high$"),
       none("img.hero-img[loading=\"lazy\"]", "Hero image is not lazy loaded"),
       none("meta[name=\"robots\"][content*=\"noindex\"]:not(.thin-page meta)", "No stray noindex outside .thin-page",
            hint="A noindex tag on a real page removes it from results. Keep it only on the thin placeholder.")]),
    WR("Write the ranked findings for a site you know (or an imaginary one). List at least three issues, most urgent first, one per line, each with its impact and its fix.",
       [lines(3, "At least three findings"),
        must("^\\s*1[.)]", "Numbered, starting at 1", flags="im"),
        must("fix|change|add|remove|redirect", "Each finding names a fix"),
        must("index|crawl|traffic|rank|users|visitors|speed", "Findings name the impact"),
        words(30, 200)],
       "1. Product pages carry noindex from the old staging template. Impact: 400 pages missing from results. Fix: remove the tag from the template.\n2. Old blog URLs return 404 after the redesign. Impact: lost links and traffic. Fix: add 301 redirects to the matching new posts.\n3. Filter pages create duplicate URLs. Impact: split signals. Fix: canonical to the main category.",
       "Ranked, specific and actionable. This is what a developer can actually schedule."),
    C("Advanced complete",
      "You can find and fix what stops a site from being crawled, indexed and shown well. Expert is about strategy: deciding what to build, at what scale, and how to prove it worked."),
])

# =====================================================================
# Expert: Search strategy at scale
# =====================================================================

SE1 = L("Topical authority and content strategy", KW + ["content strategy", "topical authority", "clusters", "pillar", "hub", "editorial"], [
    C("Cover a topic, not a keyword",
      "Sites that rank well across a subject tend to cover it thoroughly and connect the pieces: a hub page for the broad topic, focused pages for each subtopic, and links between them. The goal is not volume. It is being the most useful, complete source on a topic your audience cares about, written by people who know it."),
    M("Your recipe site wants to rank for baking. Which plan builds authority best?",
      ["Fifty near identical posts on chocolate cake", "A baking hub, linked guides on bread, cakes, pastry and techniques, each answering real questions in depth", "One huge page with every baking keyword", "Buying an expired baking domain"], 1,
      "Breadth across subtopics, depth in each, and links that make the structure clear."),
    M("Google's guidance on helpful content asks whether a page...",
      ["Uses the keyword in every paragraph", "Was written for people first and shows real experience or expertise", "Is longer than 2,000 words", "Was published recently"], 1,
      "Its self assessment questions ask about original value, expertise and whether readers leave satisfied. Word count is not on the list."),
    O("Build a topic cluster, in order.",
      ["Choose a topic your audience needs and you can genuinely cover", "Map the subtopics and questions people search", "Write the hub and the most important subtopic pages", "Link them both ways and fill gaps over time"],
      "Choose and map before writing. Linking is part of the build, not an afterthought."),
    WR("Plan a cluster for a topic you know (or use \"bread baking\"). Write the hub page on the first line starting with Hub:, then at least four subtopic pages starting with Page:, each with the question it answers.",
       [must("^hub:", "A hub line starting with Hub:", flags="im"),
        must("(^page:.*\\n?){4,}", "At least four lines starting with Page:", flags="im",
             hint="Put each subtopic on its own line beginning with Page:"),
        must("\\?", "Pages name the questions they answer"),
        words(30, 200)],
       "Hub: Bread baking at home, the complete guide\nPage: Sourdough starter, how do I make and keep one?\nPage: Flour, which flour should I use for which bread?\nPage: Kneading, how do I know the dough is ready?\nPage: Baking, why is my crust pale or my crumb dense?",
       "A cluster plan like this becomes the editorial calendar and the internal linking plan at the same time."),
    C("Prune as well as publish",
      "Old, thin or overlapping pages can dilute a topic. Merging them into one better page, with redirects, is often worth more than writing a new one."),
])

SE2 = L("Competitive gap analysis", KW + ["competitors", "gap analysis", "serp analysis", "content gap", "opportunity"], [
    C("Your search competitors are whoever ranks",
      "Your search competitors are the sites on page one for your target queries, which may be publishers, forums or video sites rather than your business rivals. A gap analysis compares the queries they win against yours, then asks why: better content, a better page type, stronger links, or simply that you have no page at all."),
    W("Read a results page like an analyst",
      "Example: the query \"sourdough starter not rising\" shows two forum threads, a video and two long guides on page one.",
      ["Forum threads rank, so searchers value real troubleshooting from people who hit the problem.",
       "The guides cover causes one by one: temperature, flour, feeding ratio.",
       "Nobody has a quick diagnostic: answer three questions, get the likely cause.",
       "The gap: a troubleshooting page with a simple checklist, real photos of each stage, and depth for each cause."],
      "The gap is rarely a missing keyword. It is a missing kind of help."),
    M("A competitor outranks you with a shorter page. What is the most likely reason worth investigating?",
      ["Google prefers short pages", "Their page satisfies the intent better or the site has stronger signals such as links and reputation", "Random luck", "Their meta keywords tag"], 1,
      "Length is not the goal. Compare how well each page solves the problem, then compare site level signals."),
    N("Example scoring: a gap query has 3,000 searches a month, you estimate you could win 4% of them, and each visit is worth an estimated 0.50 in revenue. What is the estimated monthly value?", 60,
      "3,000 times 0.04 is 120 visits, times 0.50 is 60. All three inputs are estimates, so treat the answer as a rough ranking score, not a forecast.",
      gen={"vars": {"s": [1000, 6000, 500], "c": [2, 8, 1]}, "answer": "s*c/100*0.5", "round": 2,
           "prompt": "Example scoring: a gap query has {s} searches a month, you estimate you could win {c}% of them, and each visit is worth an estimated 0.50 in revenue. What is the estimated monthly value?",
           "explain": "{s} times {c}% times 0.50 is {A}. Use it to rank opportunities against each other."}),
    O("Run a gap analysis, in order.",
      ["List the queries that matter to your business", "Record who ranks for each, and with what page type", "Mark where you are missing or weak", "Score each gap by value and effort, then pick the top few"],
      "Value and effort together decide the order. A huge gap you cannot realistically win is not the first project."),
    WR("Pick one query in a field you know. Write who ranks (page types), what they do well, the gap you see, and the page you would make. One line each, at least four lines.",
       [lines(4, "At least four lines"),
        must("forum|guide|video|product|tool|news|blog|page", "Names the page types that rank"),
        must("gap|missing|nobody|none|lack", "Names the gap"),
        must("would|will|plan|make|build|write", "Says what you would make"),
        words(30, 200)],
       "Query: sourdough starter not rising.\nWho ranks: forum threads, a video and two long guides.\nWhat they do well: real troubleshooting stories and causes explained.\nGap: nobody offers a quick diagnostic with photos of each stage.\nI would build a short checklist page with photos and a section per cause.",
       "Specific, grounded in the actual results, and ending in a page you can brief."),
    C("Do not copy the leader",
      "Rewriting the top result produces a page that is at best equal. Add something it lacks: original data, photos, a tool, real experience, or a clearer structure."),
])

SE3 = L("Forecasting traffic honestly", KW + ["forecast", "forecasting", "traffic", "ctr", "estimate", "range", "scenario"], [
    C("A forecast is a range with assumptions",
      "SEO forecasts multiply estimates: search volume, the share of clicks at a position, and the chance you reach that position at all. Each input is uncertain, so the honest output is a range with the assumptions written down, such as a low, middle and high case. Click shares by position vary a lot by query type and by how many ads and features sit above the results, so use your own Search Console data where you can."),
    X("Feel the sensitivity",
      "Example assumptions: 20,000 monthly searches across a cluster. Drag the click share to see how monthly visits change. Small changes in one assumption swing the result widely.",
      "20000 * x / 100", "x", 1, 20, 1, "Assumed click share (%)", "Monthly visits"),
    N("Example: 20,000 monthly searches with an assumed 6% click share. How many monthly visits does that forecast?", 1200,
      "20,000 times 0.06 is 1,200. Swap in 3% and it halves; that is why you show a range.",
      gen={"vars": {"s": [10000, 40000, 5000], "c": [2, 10, 1]}, "answer": "s*c/100", "round": 0,
           "prompt": "Example: {s} monthly searches with an assumed {c}% click share. How many monthly visits does that forecast?",
           "explain": "{s} times {c}% is {A}."}),
    N("Example low and high cases: 20,000 searches, click share between 2% and 8%. How many visits is the gap between the high and the low case?", 1200,
      "High: 1,600. Low: 400. The gap is 1,200, three times the low case. Reporting only the middle hides that.",
      gen={"vars": {"s": [10000, 40000, 5000], "lo": [1, 3, 1], "hi": [6, 10, 1]}, "answer": "s*(hi-lo)/100", "round": 0,
           "prompt": "Example low and high cases: {s} searches, click share between {lo}% and {hi}%. How many visits is the gap between the high and the low case?",
           "explain": "{s} times ({hi}% minus {lo}%) is {A}."}),
    M("Which forecast is most honest?",
      ["We will get 12,431 visits in June", "Between 400 and 1,600 monthly visits within a year, if we rank in the top five for most of the cluster; assumptions listed below", "Traffic will grow 300%", "No forecast is possible"], 1,
      "A range, a time frame, the condition it depends on and the assumptions. Precision you do not have reads as confidence you have not earned."),
    O("Build a forecast, in order.",
      ["List the target queries and their estimated volumes", "Choose click share assumptions, ideally from your own data", "Estimate how likely and how soon you reach those positions", "Report low, middle and high cases with the assumptions"],
      "Volumes, then shares, then likelihood, then a range. Skipping likelihood is the usual source of wildly optimistic forecasts."),
    C("Revisit forecasts with real data",
      "After a few months, compare the forecast with what Search Console shows and adjust the assumptions. The point is not to be right the first time. It is to get better at estimating."),
])

SE4 = L("Programmatic pages without thin content", KW + ["programmatic seo", "templates", "scale", "thin content", "scaled content", "database"], [
    C("Templates are fine; empty templates are not",
      "Programmatic SEO generates many pages from data: one page per city, product or recipe ingredient. It works when each page offers something genuinely different and useful because the data differs. Google's spam policies name scaled content abuse: producing many pages mainly to manipulate rankings, with little value, whether written by people, templates or AI."),
    M("Which programmatic project is most likely to be useful?",
      ["10,000 pages saying best plumber in town name, identical apart from the town", "A page per recipe ingredient showing real recipes that use it, substitutes, storage and seasonality from your database", "Pages for every keyword in a tool export", "AI rewrites of competitor pages"], 1,
      "Each ingredient page has its own data. Swapping a town name into the same text creates thousands of near duplicates."),
    M("You have 3,000 ingredient pages, but 1,200 have only one recipe. What is a sensible rule?",
      ["Publish all of them", "Only index pages that meet a minimum data threshold, such as three or more recipes, and noindex or skip the rest", "Pad them with filler text", "Delete the database"], 1,
      "Quality thresholds keep thin pages out while the data grows."),
    N("Example: 3,000 template pages, of which 40% fall below your quality threshold. How many pages should be indexable?", 1800,
      "40% of 3,000 is 1,200 below the bar, leaving 1,800 that meet it.",
      gen={"vars": {"t": [1000, 6000, 500], "p": [20, 60, 5]}, "answer": "t*(100-p)/100", "round": 0,
           "prompt": "Example: {t} template pages, of which {p}% fall below your quality threshold. How many pages should be indexable?",
           "explain": "{t} times (100 minus {p})% is {A}."}),
    WR("Write a spec for a programmatic page type. Name the page type, the unique data fields each page shows (at least three), and the quality threshold a page must meet to be indexed.",
       [must("page type|template|page:", "Names the page type"),
        must("field|data|shows|includes", "Lists the unique data fields"),
        lines(3, "At least three lines"),
        must("threshold|minimum|at least|only index|noindex", "States the quality threshold for indexing",
             hint="Say what makes a page good enough to index, such as at least three recipes."),
        words(20, 180)],
       "Page type: one page per ingredient.\nUnique data: recipes using it, best substitutes, how to store it, months it is in season.\nThreshold: index only pages with at least three recipes and storage advice; noindex the rest until the data grows.",
       "The threshold is the part most programmatic projects forget, and the part that keeps them from becoming thin content at scale."),
    O("Launch a programmatic section safely.",
      ["Prove the template is useful with a small hand checked batch", "Set the quality threshold for indexing", "Release in stages and watch indexing and engagement", "Expand only when the first batch performs"],
      "Small first. If the first hundred pages do not get indexed or used, ten thousand will not either."),
    C("Internal links at scale",
      "Generated pages need links in and out: from hubs and related pages, to related items. Without them they become thousands of orphans."),
])

SE5 = L("Faceted navigation and crawl traps", KW + ["faceted navigation", "filters", "parameters", "crawl trap", "ecommerce", "combinations"], [
    C("Filters multiply URLs",
      "Filters on a shop or recipe listing (color, size, diet, time) can each add a parameter. Combined, they produce far more URLs than there are products, most showing near duplicate lists. Crawlers can spend their time on these instead of your real pages, which is called a crawl trap. Decide which filter pages deserve to be indexed and keep the rest from multiplying."),
    N("Example: a listing has 3 filters. Diet has 4 options, time has 3, and cuisine has 6. Each filter can also be left unset. How many filter combinations are there?", 140,
      "Each filter has its options plus not set: 5 times 4 times 7 is 140, for one listing page.",
      gen={"vars": {"a": [2, 6, 1], "b": [2, 5, 1], "c": [3, 8, 1]}, "answer": "(a+1)*(b+1)*(c+1)", "round": 0,
           "prompt": "Example: a listing has 3 filters with {a}, {b} and {c} options. Each filter can also be left unset. How many filter combinations are there?",
           "explain": "({a} + 1) times ({b} + 1) times ({c} + 1) is {A}."}),
    M("Which filter pages usually deserve to be indexable?",
      ["Every combination", "Single filters that match real searches, such as vegan recipes or 30 minute dinners", "Sort orders", "Combinations of four filters"], 1,
      "Index pages with real search demand and give them unique titles and intros. Leave sort orders and deep combinations out."),
    M("Which tool is right for stopping crawlers from fetching endless sort and filter combinations?",
      ["A canonical tag alone", "robots.txt rules for those parameter patterns, plus links that do not point to them", "A noindex tag", "A sitemap"], 1,
      "Canonical and noindex still need the URL crawled to be seen. To save crawling, block the patterns and avoid linking to them."),
    WR("Write rules for a recipe listing's filters. For each of three URL patterns, say on one line whether it should be indexed, canonicalized, or blocked from crawling, and why. Use: /recipes?diet=vegan, /recipes?sort=newest, /recipes?diet=vegan&time=30&cuisine=thai&sort=rating.",
       [lines(3, "At least three lines, one per pattern"),
        must("diet=vegan[^\\n]*(index)", "The single diet filter is indexed",
             hint="Vegan recipes is a real search. That page deserves to be indexable."),
        must("sort=newest[^\\n]*(canonical|block|robots|noindex|disallow)", "The sort order is canonicalized or blocked"),
        must("cuisine=thai[^\\n]*(block|robots|disallow|noindex|canonical)", "The deep combination is kept out"),
        must("because|so|since|demand|search|duplicate", "Gives reasons")],
       "/recipes?diet=vegan: index, because people search for vegan recipes; give it its own title and intro.\n/recipes?sort=newest: canonical to /recipes, because it is the same list in another order.\n/recipes?diet=vegan&time=30&cuisine=thai&sort=rating: block the pattern in robots.txt and do not link to it, because deep combinations have no search demand.",
       "One rule per pattern, with a reason. This is the policy a developer can implement."),
    O("Tame faceted navigation, in order.",
      ["List every filter and how its URLs are formed", "Find which single filters match real searches", "Make those indexable with unique titles", "Block or canonicalize the rest and stop linking to deep combinations"],
      "Inventory, demand, then the rules. Blocking before knowing which filters have demand can hide your best category pages."),
    C("Order your parameters",
      "If filters can appear in any order (?diet=vegan&time=30 and ?time=30&diet=vegan), the same page gets two URLs. Always writing parameters in a fixed order halves the problem for free."),
])

SE6 = L("Log files and crawl data", KW + ["log files", "crawl stats", "googlebot", "server logs", "crawl analysis"], [
    C("Logs show what crawlers actually did",
      "Server logs record every request, including those from search engine crawlers. Analyzing them shows which URLs get crawled, how often, which status codes crawlers receive and where crawling is wasted. Search Console's Crawl stats report gives a summary; logs give the full detail. Verify real Googlebot by reverse DNS, because anyone can fake the user agent."),
    W("Read a log sample",
      "Example log summary for one week: 50,000 Googlebot requests. 22,000 were to URLs with ?sort=, 9,000 returned 404, and your 2,000 product pages got 3,000 requests between them.",
      ["Nearly half the requests, 22,000 of 50,000, went to sort parameters that duplicate other pages.",
       "9,000 requests hit missing pages, likely old links or broken internal links.",
       "Real product pages, the ones that make money, got only 3,000 requests, about 1.5 each.",
       "Action: block sort parameters, fix or redirect the 404 sources, and link products better."],
      "Logs turn a vague feeling of poor crawling into specific numbers you can act on."),
    N("Example: 50,000 crawler requests in a week, 22,000 of them to sort parameter URLs. What percent were spent on sort URLs?", 44,
      "22,000 divided by 50,000 is 0.44, so 44%.",
      gen={"vars": {"t": [20000, 80000, 10000], "p": [20, 60, 2]}, "show": {"w": "t*p/100"}, "answer": "p", "round": 0,
           "prompt": "Example: {t} crawler requests in a week, {w} of them to sort parameter URLs. What percent were spent on sort URLs?",
           "explain": "{w} divided by {t} is {A}%."}),
    M("A request in your logs says Googlebot in the user agent. Can you trust it is Google?",
      ["Yes, always", "Not by itself; verify with a reverse DNS lookup that resolves to Google's domains", "Only on weekends", "Only if it returns 200"], 1,
      "Scrapers fake the user agent. Google documents how to verify its crawlers."),
    O("Run a log analysis, in order.",
      ["Collect a few weeks of logs and filter to verified search engine crawlers", "Group requests by URL pattern and status code", "Compare what is crawled against what you want indexed", "Fix the biggest waste and measure again"],
      "Clean data first. Mixing fake bots into the analysis leads to the wrong conclusions."),
    WR("Write three findings from the example log summary above, each with the action you would take. One per line.",
       [lines(3, "At least three findings"),
        must("sort|parameter", "Covers the sort parameter waste"),
        must("404|missing|not found|broken", "Covers the 404 requests"),
        must("product", "Covers the under crawled product pages"),
        must("block|redirect|fix|link|robots", "Names actions")],
       "44% of crawling goes to sort parameters: block the pattern in robots.txt and remove links to it.\n9,000 requests hit 404s: find the linking sources, fix internal links and redirect old URLs.\nProduct pages get about 1.5 crawls each: link them from category pages and the sitemap.",
       "Finding, number, action. That is a log report people act on."),
    C("Crawl is not the goal",
      "More crawling is not automatically better. The aim is that crawlers spend their visits on pages that matter, and that changes to those pages get picked up quickly."),
])

SE7 = L("Experiments for SEO", KW + ["seo testing", "experiments", "split test", "control", "causation", "change log"], [
    C("You cannot A/B test searchers",
      "In a normal A/B test, users see different versions. In SEO the audience that matters is the search engine, which sees one version of each page. So SEO tests split pages instead: take many similar pages (say, all recipe pages), change half of them, and compare the changed group against the unchanged control group over the same weeks. Comparing to the same group before the change mixes in seasonality and algorithm updates."),
    M("Why is a before and after comparison of one page weak evidence?",
      ["It is not weak", "Traffic changes for many reasons at once, such as seasons, updates and news, and one page cannot separate them", "Search Console hides the data", "It takes too long"], 1,
      "A control group living through the same weeks absorbs those outside effects."),
    M("Which test design is strongest?",
      ["Change your best page and hope", "Randomly split 400 similar recipe pages into two groups, change one group's titles, compare the groups' clicks over several weeks", "Change all pages at once", "Change pages one by one each day"], 1,
      "Random assignment, many pages, a control and enough time. That is what makes the comparison fair."),
    N("Example: over four weeks the changed group's clicks rose 12% and the control group's rose 5% over the same weeks. What is the estimated effect of the change, in percentage points?", 7,
      "12 minus 5 is 7 points. Both groups rode the same seasonal rise; only the difference is attributable to the change, and only if it is larger than normal noise between groups.",
      gen={"vars": {"a": [6, 20, 1], "b": [0, 5, 1]}, "answer": "a-b", "round": 0,
           "prompt": "Example: over four weeks the changed group's clicks rose {a}% and the control group's rose {b}% over the same weeks. What is the estimated effect, in percentage points?",
           "explain": "{a} minus {b} is {A} points, the part the control group does not share."}),
    WR("Write a hypothesis for an SEO test in the form: If we change something on a group of pages, then a metric will move, because a reason. Name the control group too.",
       [must("\\bif\\b", "Starts with If"),
        must("\\bthen\\b", "Has a then"),
        must("\\bbecause\\b", "Gives a because"),
        must("control", "Names a control group"),
        must("click|ctr|impression|traffic|position|visits", "Names a measurable metric"),
        words(25, 120)],
       "If we add the cook time to the title of half our recipe pages, then their CTR will rise, because searchers want quick dinners and can see the time before clicking. The other half, chosen at random, is the control group.",
       "Every part is testable: the change, the metric, the reason and the comparison."),
    O("Run an SEO split test, in order.",
      ["Pick a template with many similar pages", "Randomly assign pages to test and control groups", "Change only the test group and log the date", "Compare the groups over several weeks and decide"],
      "Random assignment before the change is what makes the result trustworthy."),
    C("Keep a change log",
      "Write down every significant site change with a date. When traffic moves, a change log is the difference between a guess and an explanation."),
])

SE8 = L("Search beyond ten blue links", KW + ["ai search", "ai overviews", "answer engines", "zero click", "featured snippets", "future"], [
    C("Results pages keep changing",
      "Search results now mix many features: featured snippets, People also ask, videos, maps, shopping and, increasingly, AI generated summaries such as Google's AI Overviews that cite source pages. Some searches end without a click because the answer is on the results page. The durable strategy has not changed much: be a clear, trustworthy, original source that these systems want to cite, and build value that a summary cannot replace."),
    M("Which content is hardest for a results page summary to replace?",
      ["A one line definition", "Original testing, data, tools, and real experience, such as a recipe tested three ways with photos", "A list copied from other sites", "A page of synonyms"], 1,
      "Summaries are good at restating common facts. They send people to sources for depth, proof and things they can use."),
    M("A page is cited in an AI summary but clicks fell. What is a reasonable response?",
      ["Block all crawlers immediately", "Measure impressions and conversions, not only clicks, and strengthen what a visit offers beyond the summary", "Delete the page", "Stuff more keywords"], 1,
      "Visibility and visits are both worth tracking. Strengthening reasons to click is within your control."),
    O("Make a page easy to cite, in order.",
      ["Answer the question directly near the top", "Support it with clear evidence or experience", "Structure details under descriptive headings", "Keep facts current and dated"],
      "The direct answer is what gets quoted. Evidence and structure are why a system and a reader trust it."),
    WR("Rewrite this opening so it answers the question directly in the first sentence: \"Many people have wondered over the years about the question of how long cooked rice can safely stay in the fridge, and in this article we will explore it.\" Keep it under 45 words. Use \"3 to 4 days\" as the example answer from your food safety source.",
       [changed(),
        words(8, 45),
        must("3 to 4 days|three to four days", "Gives the answer",
             hint="Lead with the answer itself."),
        avoid("in this article|we will explore|many people have wondered", "No throat clearing",
              hint="Delete the setup and start with the answer.")],
       "Cooked rice keeps for 3 to 4 days in the fridge. Cool it quickly, store it covered, and reheat it until steaming hot.",
       "First sentence, the answer. That is what snippets, summaries and impatient readers all reward.",
       starter="Many people have wondered over the years about the question of how long cooked rice can safely stay in the fridge, and in this article we will explore it."),
    C("Diversify where attention comes from",
      "Search is one channel. An email list, a community and a recognizable brand mean a change on one platform cannot take everything at once."),
])

SE9 = L("Capstone: an SEO strategy memo", KW + ["capstone", "strategy", "memo", "roadmap", "priorities"], [
    C("Strategy is choosing",
      "A strategy memo says what you will do, what you will not, and how you will know it worked. It is short enough that people read it, specific enough that people can act on it, and honest about assumptions."),
    M("Which memo opening is strongest?",
      ["SEO is very important in today's digital landscape", "Goal: double sign ups from organic search within 12 months by owning weeknight cooking searches; three bets below", "We will do SEO", "This memo covers many things"], 1,
      "It names the outcome, a time frame and the plan's shape in one line."),
    O("Order a strategy memo.",
      ["Goal and time frame", "Where we stand today, with the key numbers", "Three bets, each with its reason", "How we will measure and when we will review", "Risks and what we will not do"],
      "Goal first so every later line can be judged against it. Measurement before risks so the plan is testable.",
      note="Some teams put risks before measurement. Either works if the goal comes first and the bets come before both."),
    N("Example: organic sign ups are 300 a month. The goal is to double them in 12 months. How many extra sign ups a month is that, on average, if growth were spread evenly?", 25,
      "Doubling adds 300 a month by month 12. Spread evenly over 12 months that is 25 more each month. Real growth is rarely even, so review quarterly.",
      gen={"vars": {"s": [120, 600, 60]}, "answer": "s/12", "round": 1,
           "prompt": "Example: organic sign ups are {s} a month. The goal is to double them in 12 months. How many extra sign ups a month is that, on average, if growth were spread evenly?",
           "explain": "Doubling adds {s} by month 12; {s} divided by 12 is {A} per month."}),
    WR("Write a one page strategy memo for a site you know or for Casa Verde. Include lines starting with Goal:, Today:, Bet 1:, Bet 2:, Bet 3:, Measure: and Not doing:.",
       [must("^goal:", "A Goal: line", flags="im"),
        must("^today:", "A Today: line", flags="im"),
        must("^bet 1:[\\s\\S]*^bet 2:[\\s\\S]*^bet 3:", "Three bets", flags="im"),
        must("^measure:", "A Measure: line", flags="im"),
        must("^not doing:", "A Not doing: line", flags="im",
             hint="Saying what you will not do is what makes it a strategy."),
        words(80, 350)],
       "Goal: double organic email sign ups, from about 300 to 600 a month, within 12 months.\nToday: most organic traffic lands on 40 recipe pages; guides get little traffic and have weak internal links.\nBet 1: build a weeknight dinners cluster with a hub and 12 tested guides, linked both ways.\nBet 2: fix technical debt on recipe templates: canonicals, Recipe structured data and image priority.\nBet 3: split test recipe titles that include cook time against a control group.\nMeasure: organic sign ups and CTR for the cluster, reviewed every quarter against a low, middle and high forecast.\nNot doing: programmatic city pages, link buying, or chasing broad terms like dinner.",
       "Goal, baseline, a few deliberate bets, measurement and limits. That is a strategy someone can fund."),

])
SE9["steps"].append(C("Expert complete",
    "You can now plan search work like a lead: pick topics, size opportunities honestly, scale without thin content, read crawl data, test changes and write the plan down."))


def add(courses, picks):
    courses.append(course("seo-intermediate", "SEO in practice", "Intermediate", "SEO you can ship", "seo", "SEO", 55,
        "Titles, headings, intent, research, links, images, local search and Search Console, on a real page.",
        [("Pages that earn the click", [SI1, SI2, SI3]), ("Content people search for", [SI4, SI5, SI6]),
         ("Local and measurement", [SI7, SI8, SI9])], "web"))
    courses.append(course("seo-advanced", "Technical SEO", "Advanced", "Technical SEO in depth", "seo-intermediate", "SEO in practice", 85,
        "Crawling, canonicals, sitemaps, structured data, Core Web Vitals, JavaScript, hreflang and migrations.",
        [("Crawling and indexing", [SA1, SA2, SA3]), ("Structured and fast", [SA4, SA5, SA6]),
         ("Sites that change", [SA7, SA8, SA9])], "web"))
    courses.append(course("seo-expert", "SEO strategy", "Expert", "Search strategy at scale", "seo-advanced", "Technical SEO", 85,
        "Topical authority, gap analysis, honest forecasts, programmatic pages, crawl data, SEO tests and strategy.",
        [("Strategy", [SE1, SE2, SE3]), ("Scale", [SE4, SE5, SE6]), ("Proof", [SE7, SE8, SE9])], "web"))
