"""JavaScript ladder: Intermediate, Advanced and Expert courses that follow
"JavaScript, by hand" (core-js). Every code step runs real tests: the
solution must pass all of them and the starter must fail at least one.
Rebuild with: python3 build_library.py
"""
from ladder_kit import C, W, M, O, K, T, L, P, course

KW = ["javascript", "js"]

# =====================================================================
# Intermediate: JavaScript that holds up
# =====================================================================

JI1 = L("Destructuring and defaults", KW + ["destructuring", "defaults", "parameters", "options", "rest"], [
    C("Unpack what you need",
      "Destructuring pulls named values out of an object or array in one line. It reads like a shape: the left side says where each value lands. Defaults fill any value that comes back undefined.",
      "const { name, role = \"guest\" } = { name: \"Ada\" };\n// name is \"Ada\", role is \"guest\"\nconst [first, , third] = [10, 20, 30];\n// first is 10, third is 30"),
    P("const { size = 3, color = \"red\" } = { color: \"blue\" };\nconsole.log(size + \" \" + color);", "3 blue",
      "size was missing, so its default 3 applied. color was present, so the default was ignored."),
    M("Which value does NOT trigger a destructuring default?",
      ["A missing key", "A key set to undefined", "A key set to null", "An empty object"], 2,
      "Defaults only fire for undefined. null is a real value, so { a = 1 } = { a: null } leaves a as null."),
    C("Options objects",
      "Functions with more than two settings read better with one options object than with a row of positional arguments. Destructure it in the parameter list and give every option a default, then give the whole object a default of {} so calling with nothing still works.",
      "function greet({ name = \"friend\", loud = false } = {}) {\n  const s = \"Hello, \" + name;\n  return loud ? s.toUpperCase() : s;\n}"),
    K("Write label(opts) that returns text like \"Coffee x2\". opts may carry name (default \"Item\") and qty (default 1). Calling label() with no argument must work too.",
      "function label(opts) {\n  return opts.name + \" x\" + opts.qty;\n}",
      "function label({ name = \"Item\", qty = 1 } = {}) {\n  return name + \" x\" + qty;\n}",
      [T("label({ name: \"Coffee\", qty: 2 })", "Coffee x2"), T("label({ name: \"Tea\" })", "Tea x1"), T("label()", "Item x1"), T("label({ qty: 0 })", "Item x0")],
      "Defaults in the parameter list handle the missing keys, and = {} handles the missing object. qty 0 stays 0 because only undefined triggers a default."),
    O("Order what happens when greet({ name: \"Ada\" }) runs with the signature above.",
      ["The call passes one object", "The parameter default {} is skipped because an object arrived", "name is read as \"Ada\"", "loud is undefined, so its default false applies", "The body runs with both names bound"],
      "The outer default only fires when the whole argument is undefined. Then each key is unpacked and defaulted on its own."),
    K("Write swapEnds(arr) that returns a new array with the first and last items swapped, using destructuring. Arrays shorter than 2 come back as copies.",
      "function swapEnds(arr) {\n  return arr;\n}",
      "function swapEnds(arr) {\n  if (arr.length < 2) return [...arr];\n  const [first, ...rest] = arr;\n  const last = rest.pop();\n  return [last, ...rest, first];\n}",
      [T("swapEnds([1, 2, 3, 4])", [4, 2, 3, 1]), T("swapEnds([\"a\", \"b\"])", ["b", "a"]), T("swapEnds([7])", [7]), T("(() => { const a = [1, 2, 3]; swapEnds(a); return a; })()", [1, 2, 3])],
      "The rest pattern collects the middle, pop takes the last, and the spread builds a new array so the caller's array is untouched."),
])

JI2 = L("Map, Set and fast lookups", KW + ["map", "set", "lookup", "unique", "dedupe", "frequency", "count"], [
    C("When an object is the wrong tool",
      "A Map is a key value store whose keys can be anything, keeps insertion order, and knows its size. A Set holds each value once. Both answer has() in constant time, which matters once lists get long.",
      "const seen = new Set([\"a\", \"b\", \"a\"]);\nseen.size;          // 2\nconst ages = new Map([[\"ada\", 36]]);\nages.get(\"ada\");    // 36"),
    P("const s = new Set([3, 1, 3, 2, 1]);\nconsole.log([...s].join(\",\"));", "3,1,2",
      "A Set keeps the first time it saw each value, in that order. Duplicates are dropped, not moved."),
    M("You need to count how often each word appears, and some words are \"constructor\" or \"toString\". Which store is safest?",
      ["A plain object {}", "A Map", "An array of pairs", "A Set"], 1,
      "A plain object inherits keys like toString from its prototype, so obj[\"toString\"] is already a function. A Map starts truly empty."),
    K("Write unique(list) that returns the items with duplicates removed, keeping the first occurrence order.",
      "function unique(list) {\n  return list;\n}",
      "function unique(list) {\n  return [...new Set(list)];\n}",
      [T("unique([1, 2, 2, 3, 1])", [1, 2, 3]), T("unique([\"b\", \"a\", \"b\"])", ["b", "a"]), T("unique([])", [])],
      "Spreading a Set back into an array is the shortest correct dedupe for primitive values."),
    K("Write wordCounts(text) that returns an array of [word, count] pairs in first-seen order. Lowercase the text and split on spaces.",
      "function wordCounts(text) {\n  const counts = {};\n  return counts;\n}",
      "function wordCounts(text) {\n  const counts = new Map();\n  for (const w of text.toLowerCase().split(\" \")) {\n    if (!w) continue;\n    counts.set(w, (counts.get(w) || 0) + 1);\n  }\n  return [...counts];\n}",
      [T("wordCounts(\"the cat and the hat\")", [["the", 2], ["cat", 1], ["and", 1], ["hat", 1]]), T("wordCounts(\"Constructor constructor\")", [["constructor", 2]]), T("wordCounts(\"\")", [])],
      "get(w) || 0 starts each new word at zero. Spreading a Map gives [key, value] pairs in insertion order."),
    O("Order the steps to find which ids appear in both lists in linear time.",
      ["Put every id from the first list into a Set", "Walk the second list", "Keep an id when the Set has it", "Return the kept ids"],
      "Building the Set costs one pass; each has() check is constant, so the whole job is one pass over each list instead of a nested loop."),
    C("Pick by the question you ask",
      "Ask \"is it in there?\" use a Set. Ask \"what goes with this key?\" use a Map. Need JSON out the door? Convert at the edge with Object.fromEntries(map) or [...set]."),
])

JI3 = L("Sorting without surprises", KW + ["sort", "sorting", "comparator", "order", "tosorted", "localecompare"], [
    C("sort compares strings unless told otherwise",
      "Array.prototype.sort with no argument converts items to strings and sorts by code units, so 10 lands before 9. Pass a comparator that returns a negative number, zero, or a positive number.",
      "[10, 9, 1].sort();              // [1, 10, 9]\n[10, 9, 1].sort((a, b) => a - b); // [1, 9, 10]"),
    P("console.log([25, 100, 3].sort().join(\" \"));", "100 25 3",
      "Compared as strings, \"1\" is less than \"2\" which is less than \"3\", so 100 comes first."),
    M("sort changes the array it is called on. Which call returns a sorted copy and leaves the original alone?",
      ["arr.sort()", "arr.toSorted((a, b) => a - b)", "arr.reverse()", "arr.sort().slice()"], 1,
      "toSorted is the non-mutating version. arr.sort().slice() still sorts arr in place first, then copies it."),
    K("Write byPrice(items) that returns a NEW array sorted by price ascending; equal prices keep their original order. Do not change the input.",
      "function byPrice(items) {\n  return items.sort();\n}",
      "function byPrice(items) {\n  return [...items].sort((a, b) => a.price - b.price);\n}",
      [T("byPrice([{n:\"b\",price:3},{n:\"a\",price:1},{n:\"c\",price:3}]).map(i => i.n)", ["a", "b", "c"]),
       T("(() => { const x = [{price:2},{price:1}]; byPrice(x); return x[0].price; })()", 2)],
      "Copy first, then sort with a numeric comparator. Modern engines sort stably, so b stays ahead of c."),
    K("Write rank(people) that sorts by score descending, then by name A to Z for ties. Return the names.",
      "function rank(people) {\n  return people.map(p => p.name);\n}",
      "function rank(people) {\n  return [...people]\n    .sort((a, b) => b.score - a.score || a.name.localeCompare(b.name))\n    .map(p => p.name);\n}",
      [T("rank([{name:\"Cy\",score:5},{name:\"Al\",score:9},{name:\"Bo\",score:5}])", ["Al", "Bo", "Cy"]), T("rank([])", [])],
      "When the scores tie, b.score - a.score is 0, which is falsy, so || moves on to the name comparison."),
    O("Order the parts of a multi-key comparator for \"newest first, then title A to Z\".",
      ["Compute the date difference, newer first", "If it is not zero, return it", "Otherwise compare titles with localeCompare", "Return that result"],
      "Each key only decides when every earlier key tied. That is all a multi-key sort is."),
    C("Sorting is a contract",
      "A comparator must be consistent: if a comes before b, b must not come before a. Random comparators like () => Math.random() - 0.5 break that contract and give biased shuffles. Shuffle with Fisher-Yates instead."),
])

JI4 = L("Strings and regular expressions", KW + ["strings", "regex", "regular", "expressions", "match", "replace", "validate", "parse"], [
    C("A pattern, not a string",
      "A regular expression describes text by shape. \\d is a digit, + means one or more, ^ and $ pin the start and end. test() asks yes or no, match() returns the pieces, and replace() rewrites what matches.",
      "/^\\d{5}$/.test(\"60614\");          // true\n\"a1b22\".match(/\\d+/g);           // [\"1\", \"22\"]\n\"2026-10-02\".replace(/-/g, \"/\");  // \"2026/10/02\""),
    P("console.log(\"red, green,blue\".split(/,\\s*/).length);", "3",
      "The pattern splits on a comma followed by any amount of whitespace, so both separators count."),
    M("What does the g flag change in \"aaa\".replace(/a/g, \"b\")?",
      ["Nothing, replace always changes every match", "It replaces every match instead of only the first", "It makes the match case-insensitive", "It makes the pattern greedy"], 1,
      "Without g, replace stops after the first match. The i flag is the case-insensitive one."),
    K("Write slugify(title) that lowercases, turns every run of characters that are not a-z or 0-9 into one hyphen, and trims hyphens from both ends.",
      "function slugify(title) {\n  return title.toLowerCase();\n}",
      "function slugify(title) {\n  return title\n    .toLowerCase()\n    .replace(/[^a-z0-9]+/g, \"-\")\n    .replace(/^-+|-+$/g, \"\");\n}",
      [T("slugify(\"Hello, World!\")", "hello-world"), T("slugify(\"  Ten  tips: CSS & JS  \")", "ten-tips-css-js"), T("slugify(\"2026 Plan\")", "2026-plan")],
      "One pattern collapses every run of junk into a single hyphen; a second anchored pattern trims the ends."),
    K("Write parseTime(s) that reads \"HH:MM\" (24 hour) and returns total minutes, or null when the text is not a valid time.",
      "function parseTime(s) {\n  const [h, m] = s.split(\":\");\n  return h * 60 + m;\n}",
      "function parseTime(s) {\n  const m = /^(\\d{2}):(\\d{2})$/.exec(s);\n  if (!m) return null;\n  const h = Number(m[1]), min = Number(m[2]);\n  if (h > 23 || min > 59) return null;\n  return h * 60 + min;\n}",
      [T("parseTime(\"09:30\")", 570), T("parseTime(\"23:59\")", 1439), T("parseTime(\"24:00\")", None), T("parseTime(\"9:30\")", None), T("parseTime(\"ab:cd\")", None)],
      "Capture groups pull out the parts, the anchors reject extra text, and a range check catches values the shape alone allows."),
    O("Order the safe way to read structured text from a user.",
      ["Match the whole string against an anchored pattern", "Reject it if there is no match", "Convert the captured parts to numbers", "Check the ranges", "Return the clean value"],
      "Shape first, then meaning. A pattern alone accepts 99:99; a range check alone accepts garbage."),
    C("Know when to stop",
      "Regular expressions are good at short, regular text: ids, dates, slugs. They are bad at nested formats like HTML or JSON. Use a real parser for those (DOMParser, JSON.parse)."),
])

JI5 = L("Numbers that do not lie", KW + ["numbers", "floating", "point", "rounding", "money", "cents", "integer", "nan"], [
    C("Floating point, in one example",
      "JavaScript numbers are binary floating point. Most decimal fractions cannot be stored exactly, so 0.1 + 0.2 is 0.30000000000000004. That is not a bug in JavaScript; every language using IEEE 754 doubles does the same.",
      "0.1 + 0.2 === 0.3;              // false\nMath.abs(0.1 + 0.2 - 0.3) < 1e-9; // true"),
    P("console.log(Number(\"12px\") + \" \" + parseInt(\"12px\", 10));", "NaN 12",
      "Number() needs the whole string to be numeric. parseInt reads digits until it hits something else."),
    M("You are adding up prices. What is the robust approach?",
      ["Add the floats and round at every step", "Store whole cents as integers and format at the edge", "Use toFixed(2) on every value", "Use parseFloat everywhere"], 1,
      "Integers below 2^53 are exact. Keep money in cents while you calculate, then divide by 100 only to display."),
    K("Write totalCents(prices) that takes prices as strings like \"4.10\" or \"3\" and returns the total in whole cents.",
      "function totalCents(prices) {\n  return prices.reduce((s, p) => s + parseFloat(p), 0);\n}",
      "function totalCents(prices) {\n  return prices.reduce((s, p) => s + Math.round(parseFloat(p) * 100), 0);\n}",
      [T("totalCents([\"0.10\", \"0.20\"])", 30), T("totalCents([\"4.10\", \"3\", \"0.99\"])", 809), T("totalCents([])", 0)],
      "Convert each price to cents once, rounding away the tiny float error, then add integers."),
    K("Write isValidQty(v) that returns true only for whole numbers from 1 to 99. Strings, NaN, decimals and Infinity are false.",
      "function isValidQty(v) {\n  return v > 0;\n}",
      "function isValidQty(v) {\n  return Number.isInteger(v) && v >= 1 && v <= 99;\n}",
      [T("isValidQty(3)", True), T("isValidQty(\"3\")", False), T("isValidQty(2.5)", False), T("isValidQty(NaN)", False), T("isValidQty(100)", False), T("isValidQty(Infinity)", False)],
      "Number.isInteger never coerces, so the string \"3\" fails, and it already rejects NaN and Infinity."),
    O("Order a safe price calculation for a cart line.",
      ["Parse the unit price into cents", "Check the quantity is a valid whole number", "Multiply cents by quantity", "Format the result for display only at the end"],
      "Parse and validate at the edge, calculate in integers, and format last. Formatting early turns numbers back into strings you then have to parse again.",
      groups=[[0, 1]], note="Parsing the price and checking the quantity can happen in either order."),
    C("NaN is contagious",
      "Any arithmetic with NaN gives NaN, and NaN !== NaN. Check with Number.isNaN(x), not x === NaN. Validate inputs where they enter, so one bad value does not quietly poison every total downstream."),
])

JI6 = L("Errors on purpose", KW + ["errors", "throw", "try", "catch", "finally", "validation", "custom", "error"], [
    C("Fail loudly, early, with a name",
      "Throw when a function cannot do its job, and say why. A subclass of Error gives the caller something to check with instanceof, so it can handle a bad input differently from a crash.",
      "class ValidationError extends Error {\n  constructor(field, msg) {\n    super(msg);\n    this.name = \"ValidationError\";\n    this.field = field;\n  }\n}"),
    P("function f() {\n  try { return \"try\"; }\n  finally { console.log(\"finally\"); }\n}\nf();", "finally",
      "finally runs on the way out even after a return. It is where cleanup belongs."),
    M("Which is the worst way to handle an error you cannot fix here?",
      ["Let it propagate to a caller who can", "Wrap it with more context and rethrow", "catch (e) {} and carry on", "Log it and rethrow"], 2,
      "An empty catch hides the failure. The program continues with bad state and the real cause is lost."),
    K("Write parseAge(v) that returns a number from 0 to 150. Throw a RangeError for numbers out of range and a TypeError when v is not a finite number. Strings are not numbers here.",
      "function parseAge(v) {\n  return v;\n}",
      "function parseAge(v) {\n  if (typeof v !== \"number\" || !Number.isFinite(v)) throw new TypeError(\"age must be a number\");\n  if (v < 0 || v > 150) throw new RangeError(\"age out of range\");\n  return v;\n}",
      [T("parseAge(30)", 30),
       T("(() => { try { parseAge(200); } catch (e) { return e.name; } })()", "RangeError"),
       T("(() => { try { parseAge(\"30\"); } catch (e) { return e.name; } })()", "TypeError"),
       T("(() => { try { parseAge(NaN); } catch (e) { return e.name; } })()", "TypeError")],
      "Different error types let the caller react differently: a TypeError is a programming mistake, a RangeError is bad data."),
    K("Write safeParse(text) that returns { ok: true, value } for valid JSON and { ok: false, error } with the error message for invalid JSON. It must never throw.",
      "function safeParse(text) {\n  return { ok: true, value: JSON.parse(text) };\n}",
      "function safeParse(text) {\n  try {\n    return { ok: true, value: JSON.parse(text) };\n  } catch (e) {\n    return { ok: false, error: e.message };\n  }\n}",
      [T("safeParse(\"[1,2]\")", {"ok": True, "value": [1, 2]}), T("safeParse(\"{bad\").ok", False), T("typeof safeParse(\"{bad\").error", "string")],
      "Turning an exception into a result value is useful at boundaries such as reading a file or a network response."),
    O("Order a try, catch, finally block that writes a file safely.",
      ["Open the file", "Write the data inside try", "In catch, add context and rethrow", "In finally, close the file"],
      "Open before try so finally only closes what was opened. finally runs whether the write worked or not."),
    C("Errors are part of the interface",
      "Document what a function throws the way you document what it returns. Callers who know a function throws ValidationError can show a helpful message instead of a generic crash screen."),
])

JI7 = L("Classes and prototypes", KW + ["classes", "class", "prototype", "inheritance", "private", "getter", "methods", "oop"], [
    C("A class is a prototype with nicer syntax",
      "class builds a constructor function and puts methods on its prototype, so every instance shares one copy of each method. Fields marked with # are private: code outside the class body cannot read them.",
      "class Counter {\n  #n = 0;\n  inc() { this.#n += 1; return this; }\n  get value() { return this.#n; }\n}\nnew Counter().inc().inc().value; // 2"),
    P("class A { hi() { return \"A\"; } }\nclass B extends A { hi() { return super.hi() + \"B\"; } }\nconsole.log(new B().hi());", "AB",
      "super.hi() calls the parent's version, then B adds to it."),
    M("Why does new Counter().inc().inc() work?",
      ["inc is static", "inc returns this, so the next call has an object to run on", "Counters are arrays", "JavaScript chains every method"], 1,
      "Returning this from a method enables chaining. Without it the second .inc() would run on undefined."),
    K("Write a class Stack with push(x), pop() and a size getter. pop() on an empty stack returns undefined. Keep the items in a private field.",
      "class Stack {\n  push(x) {}\n}",
      "class Stack {\n  #items = [];\n  push(x) { this.#items.push(x); return this; }\n  pop() { return this.#items.pop(); }\n  get size() { return this.#items.length; }\n}",
      [T("(() => { const s = new Stack(); s.push(1); s.push(2); return [s.pop(), s.size]; })()", [2, 1]),
       T("new Stack().pop() === undefined", True),
       T("(() => { const s = new Stack(); s.push(1); return Object.keys(s).length + s.size; })()", 1)],
      "The private field is invisible to Object.keys, which is the point: callers use the interface, not the internals."),
    K("Write class Temperature with a constructor taking celsius, a fahrenheit getter, and a fahrenheit setter that updates celsius. F = C * 9 / 5 + 32.",
      "class Temperature {\n  constructor(c) { this.c = c; }\n}",
      "class Temperature {\n  constructor(celsius) { this.celsius = celsius; }\n  get fahrenheit() { return this.celsius * 9 / 5 + 32; }\n  set fahrenheit(f) { this.celsius = (f - 32) * 5 / 9; }\n}",
      [T("new Temperature(100).fahrenheit", 212), T("(() => { const t = new Temperature(0); t.fahrenheit = 50; return t.celsius; })()", 10)],
      "Getters and setters let one stored value present itself in two units without the caller noticing."),
    O("Order what new Stack() does.",
      ["Create a fresh empty object", "Link it to Stack.prototype", "Set up private fields", "Run the constructor body", "Return the object"],
      "Linking to the prototype is why every Stack shares push and pop without copying them."),
    C("Prefer composition",
      "Inheritance chains get brittle past one level. When a class needs a capability, pass in an object that has it (a logger, a store) rather than extending a class that does. That is composition, and it is easier to test."),
])

JI8 = L("Pure functions and modules", KW + ["pure", "functions", "modules", "import", "export", "side", "effects", "refactor", "testing"], [
    C("Same input, same output, no side effects",
      "A pure function returns a value computed only from its arguments and changes nothing outside itself. Pure functions are trivial to test and safe to reuse. Push side effects (DOM, network, storage, time, randomness) to the edges of your program."),
    M("Which function is pure?",
      ["function now() { return Date.now(); }", "function add(a, b) { return a + b; }", "function save(x) { localStorage.setItem(\"x\", x); }", "function bump(o) { o.n++; return o; }"], 1,
      "Date.now changes over time, save writes to storage and bump mutates its argument. add depends only on a and b."),
    C("Modules keep files honest",
      "An ES module has its own scope. Only what you export can be imported elsewhere, so helpers stay private by default. A good module file has pure logic exported and a thin layer that touches the world.",
      "// cart.js\nexport function total(items) { /* pure */ }\n// main.js\nimport { total } from \"./cart.js\";"),
    K("Refactor: applyDiscount mutates the cart. Rewrite it so it returns a new cart and leaves the original unchanged. percent is a whole number like 10.",
      "function applyDiscount(cart, percent) {\n  cart.items.forEach(i => { i.price = i.price * (100 - percent) / 100; });\n  return cart;\n}",
      "function applyDiscount(cart, percent) {\n  return { ...cart, items: cart.items.map(i => ({ ...i, price: i.price * (100 - percent) / 100 })) };\n}",
      [T("applyDiscount({ items: [{ price: 200 }] }, 10).items[0].price", 180),
       T("(() => { const c = { items: [{ price: 200 }] }; applyDiscount(c, 50); return c.items[0].price; })()", 200),
       T("(() => { const c = { id: 7, items: [] }; return applyDiscount(c, 10).id; })()", 7)],
      "Copy each level you change: a new cart, a new items array, a new item. Untouched fields like id ride along in the spread."),
    K("Write makeIdGen(prefix) that returns a function producing \"prefix-1\", \"prefix-2\" and so on. Two generators must not share a counter.",
      "let n = 0;\nfunction makeIdGen(prefix) {\n  return () => prefix + \"-\" + (++n);\n}",
      "function makeIdGen(prefix) {\n  let n = 0;\n  return () => prefix + \"-\" + (++n);\n}",
      [T("(() => { const a = makeIdGen(\"a\"); a(); return a(); })()", "a-2"),
       T("(() => { const a = makeIdGen(\"a\"); const b = makeIdGen(\"b\"); a(); a(); return b(); })()", "b-1")],
      "Moving the counter inside the factory gives each generator its own state instead of one shared global."),
    O("Order how to make a messy function testable.",
      ["Find the side effects (DOM, fetch, storage, time)", "Move the calculation into a pure function", "Pass the values it needs in as arguments", "Call it from a thin function that does the side effects"],
      "This is the functional core, imperative shell pattern. The core gets unit tests; the shell stays too thin to break quietly."),
])

JI9 = L("Capstone: an expense ledger", KW + ["capstone", "project", "ledger", "csv", "parse", "report", "budget"], [
    C("The brief",
      "Build the logic for a small expense ledger. Input arrives as CSV text, one expense per line: date,category,amount. You will parse it safely, reject bad rows with reasons, and produce a report. This uses destructuring, Maps, sorting, regex, integer cents and errors from this course."),
    K("Step 1. Write parseLine(line) that returns { date, category, cents } for a valid row and throws an Error for a bad one. Trim each field and lowercase the category. Valid: date is YYYY-MM-DD, category is not empty, amount is a positive number with at most 2 decimals.",
      "function parseLine(line) {\n  const [date, category, amount] = line.split(\",\");\n  return { date, category, cents: amount * 100 };\n}",
      "function parseLine(line) {\n  const parts = line.split(\",\");\n  if (parts.length !== 3) throw new Error(\"expected 3 fields\");\n  const [date, rawCat, amount] = parts.map(p => p.trim());\n  if (!/^\\d{4}-\\d{2}-\\d{2}$/.test(date)) throw new Error(\"bad date\");\n  if (!rawCat) throw new Error(\"missing category\");\n  if (!/^\\d+(\\.\\d{1,2})?$/.test(amount) || Number(amount) <= 0) throw new Error(\"bad amount\");\n  return { date, category: rawCat.toLowerCase(), cents: Math.round(Number(amount) * 100) };\n}",
      [T("parseLine(\"2026-10-01,Food,12.50\")", {"date": "2026-10-01", "category": "food", "cents": 1250}),
       T("parseLine(\" 2026-10-02 , rent , 900 \").cents", 90000),
       T("(() => { try { parseLine(\"2026-10-01,,5\"); return \"no\"; } catch (e) { return \"threw\"; } })()", "threw"),
       T("(() => { try { parseLine(\"10/01/2026,food,5\"); return \"no\"; } catch (e) { return \"threw\"; } })()", "threw"),
       T("(() => { try { parseLine(\"2026-10-01,food,-5\"); return \"no\"; } catch (e) { return \"threw\"; } })()", "threw"),
       T("(() => { try { parseLine(\"2026-10-01,food,1.999\"); return \"no\"; } catch (e) { return \"threw\"; } })()", "threw")],
      "Every rule is a guard clause with a reason. Lowercasing the category now means Food and food add up together later."),
    K("Step 2. Write report(csv). Include your parseLine in the answer. Skip blank lines. Return { totals, rejected } where totals is an array of [category, cents] sorted by cents descending, then category A to Z, and rejected lists the 1-based line numbers that failed.",
      "function report(csv) {\n  return { totals: [], rejected: [] };\n}",
      "function parseLine(line) {\n  const parts = line.split(\",\");\n  if (parts.length !== 3) throw new Error(\"expected 3 fields\");\n  const [date, rawCat, amount] = parts.map(p => p.trim());\n  if (!/^\\d{4}-\\d{2}-\\d{2}$/.test(date)) throw new Error(\"bad date\");\n  if (!rawCat) throw new Error(\"missing category\");\n  if (!/^\\d+(\\.\\d{1,2})?$/.test(amount) || Number(amount) <= 0) throw new Error(\"bad amount\");\n  return { date, category: rawCat.toLowerCase(), cents: Math.round(Number(amount) * 100) };\n}\nfunction report(csv) {\n  const sums = new Map();\n  const rejected = [];\n  csv.split(\"\\n\").forEach((line, i) => {\n    if (!line.trim()) return;\n    try {\n      const { category, cents } = parseLine(line);\n      sums.set(category, (sums.get(category) || 0) + cents);\n    } catch (e) {\n      rejected.push(i + 1);\n    }\n  });\n  const totals = [...sums].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));\n  return { totals, rejected };\n}",
      [T("report(\"2026-10-01,food,10\\n2026-10-01,rent,900\\n2026-10-02,Food,2.5\")", {"totals": [["rent", 90000], ["food", 1250]], "rejected": []}),
       T("report(\"2026-10-01,food,5\\nbad line\\n\\n2026-10-03,fun,5\\n2026-13,x,1\").rejected", [2, 5]),
       T("report(\"2026-10-01,b,5\\n2026-10-01,a,5\").totals", [["a", 500], ["b", 500]]),
       T("report(\"\")", {"totals": [], "rejected": []})],
      "A try/catch per line keeps one bad row from sinking the whole file, and the rejected list tells the user exactly which rows to fix."),
    M("A user uploads a 50,000 line file and one line is bad. What should the ledger do?",
      ["Throw and show nothing", "Silently skip it", "Report everything it could parse and list the bad line number", "Guess the missing value"], 2,
      "Partial results plus a precise list of rejects is the most useful behavior. Silent skipping hides data loss; guessing invents it."),
    O("Order the ledger's pipeline.",
      ["Split the text into lines", "Parse and validate each line", "Collect rejects with line numbers", "Sum cents per category in a Map", "Sort and return the report"],
      "Parse, validate, aggregate, present. Each stage only trusts what the previous stage produced.",
      groups=[[2, 3]], note="Collecting rejects and summing the good rows happen in the same pass, so either can come first."),
    C("What you can do now",
      "You turned untrusted text into a correct report with integer money, clear errors and a stable sort. That pattern, parse at the edge and compute on clean data, carries into every program you write next."),
])

# =====================================================================
# Advanced: JavaScript under the hood
# =====================================================================

JA1 = L("The event loop", KW + ["event", "loop", "microtask", "macrotask", "settimeout", "promise", "async", "order"], [
    C("One thread, two queues",
      "JavaScript runs one piece of code at a time. When the current script finishes, the engine drains the microtask queue (promise callbacks, await continuations, queueMicrotask) completely, then takes ONE task from the task queue (setTimeout, events), and repeats.",
      "console.log(\"A\");\nsetTimeout(() => console.log(\"B\"), 0);\nPromise.resolve().then(() => console.log(\"C\"));\nconsole.log(\"D\");\n// A D C B"),
    M("In the code above, why does C print before B even though the timeout is 0 ms?",
      ["Promises are faster to create", "Microtasks run before the next task is taken from the task queue", "setTimeout(0) is rounded to 4 ms", "console.log is asynchronous"], 1,
      "The 0 ms timer only makes B eligible as a task. All microtasks, including C, run first."),
    P("(async () => {\n  const out = [];\n  out.push(1);\n  setTimeout(() => out.push(5), 0);\n  queueMicrotask(() => out.push(3));\n  Promise.resolve().then(() => out.push(4));\n  out.push(2);\n  await null;\n  console.log(out.join(\"\"));\n})();", "1234",
      "The two microtasks were queued before the await, so they run in order before the await continues. The timer is a task and has not run yet.",
      prompt="What does this print?"),
    K("Write order() that returns a promise of an array showing the order these labels are pushed: push \"sync\" now, \"micro\" in a promise then, and \"macro\" in a setTimeout of 0. Resolve with the array once \"macro\" is pushed.",
      "function order() {\n  const log = [];\n  setTimeout(() => log.push(\"macro\"), 0);\n  log.push(\"sync\");\n  return Promise.resolve(log);\n}",
      "function order() {\n  const log = [];\n  return new Promise(resolve => {\n    setTimeout(() => { log.push(\"macro\"); resolve(log); }, 0);\n    Promise.resolve().then(() => log.push(\"micro\"));\n    log.push(\"sync\");\n  });\n}",
      [T("order()", ["sync", "micro", "macro"])],
      "Resolving from inside the timer callback waits for the task; by then the microtask already ran."),
    O("Order what happens after a click handler awaits fetch().",
      ["The handler runs until the await", "The browser is free to paint and handle other events", "The response arrives and queues the continuation", "The microtask runs the rest of the handler"],
      "await splits a function in two. The second half is a microtask that runs only when the awaited promise settles."),
    M("A loop computes for 3 seconds on the main thread. What do users see?",
      ["Nothing, JavaScript is async", "The page freezes: no clicks, no paint, until it ends", "Only animations stop", "The browser moves it to a thread"], 1,
      "Long synchronous work blocks the loop. Split it into chunks, or move it to a Web Worker."),
    C("Reason about time with the queues",
      "When output order surprises you, label each line: sync, microtask or task. Run all sync code, then all microtasks, then one task, then all microtasks again. That rule predicts almost every async puzzle."),
])

JA2 = L("Promise combinators", KW + ["promise", "all", "allsettled", "race", "any", "parallel", "concurrency"], [
    C("Four ways to wait for many",
      "Promise.all resolves with every value or rejects on the first failure. allSettled always resolves with a status for each. race settles with whichever finishes first. any resolves with the first success and rejects only if all fail.",
      "await Promise.all([a(), b()]);        // [ra, rb] or throws\nawait Promise.allSettled([a(), b()]); // [{status, value|reason}, ...]"),
    M("You load a dashboard from 5 independent widgets and one service is down. Which combinator keeps the other 4 visible?",
      ["Promise.all", "Promise.allSettled", "Promise.race", "A for loop with await"], 1,
      "all would reject as soon as one fails. allSettled reports each result so you can render the 4 that worked and an error box for the fifth."),
    P("(async () => {\n  const p = Promise.any([Promise.reject(1), Promise.resolve(2), Promise.resolve(3)]);\n  console.log(await p);\n})();", "2",
      "any skips rejections and settles with the first fulfilled promise; here 2 is ready first.", prompt="What does this print?"),
    K("Write settledSummary(promises) that resolves with { ok, failed }: the count of fulfilled and rejected promises.",
      "async function settledSummary(promises) {\n  const values = await Promise.all(promises);\n  return { ok: values.length, failed: 0 };\n}",
      "async function settledSummary(promises) {\n  const results = await Promise.allSettled(promises);\n  const ok = results.filter(r => r.status === \"fulfilled\").length;\n  return { ok, failed: results.length - ok };\n}",
      [T("settledSummary([Promise.resolve(1), Promise.reject(new Error(\"x\")), Promise.resolve(3)])", {"ok": 2, "failed": 1}), T("settledSummary([])", {"ok": 0, "failed": 0})],
      "allSettled never rejects, so the summary always arrives."),
    K("Write mapLimit(items, limit, fn) that runs the async fn on every item with at most limit calls in flight, and resolves with results in the original order.",
      "async function mapLimit(items, limit, fn) {\n  return Promise.all(items.map(fn));\n}",
      "async function mapLimit(items, limit, fn) {\n  const results = new Array(items.length);\n  let next = 0;\n  async function worker() {\n    while (next < items.length) {\n      const i = next++;\n      results[i] = await fn(items[i]);\n    }\n  }\n  const n = Math.max(1, Math.min(limit, items.length));\n  await Promise.all(Array.from({ length: n }, worker));\n  return results;\n}",
      [T("mapLimit([1, 2, 3, 4], 2, async x => x * 10)", [10, 20, 30, 40]),
       T("(async () => { let live = 0, peak = 0; await mapLimit([1,2,3,4,5,6], 2, async x => { live++; peak = Math.max(peak, live); await new Promise(r => setTimeout(r, 1)); live--; return x; }); return peak; })()", 2),
       T("mapLimit([], 3, async x => x)", [])],
      "A fixed pool of workers pulls the next index from a shared counter. Writing by index keeps the order even when calls finish out of order."),
    O("Order a timeout wrapper built with Promise.race.",
      ["Create a promise that rejects after ms milliseconds", "Race it against the real work", "Return whichever settles first", "Clear the timer once either side settles"],
      "race does not cancel the loser, so clear the timer yourself or it fires later for nothing."),
    C("Parallel is not free",
      "Firing 500 requests at once can hit rate limits or exhaust memory. Batch with a limit, as mapLimit does, and treat partial failure as normal with allSettled."),
])

JA3 = L("Retries, timeouts and cancellation", KW + ["retry", "backoff", "timeout", "abort", "abortcontroller", "cancel", "resilience", "fetch"], [
    C("Networks fail, plan for it",
      "Real requests time out, drop, and return 503s. Resilient code retries transient failures with growing delays (exponential backoff), gives up after a limit, and can be cancelled when the user leaves. AbortController is the standard cancel button for fetch.",
      "const ctrl = new AbortController();\nfetch(url, { signal: ctrl.signal });\nctrl.abort(); // the fetch rejects with an AbortError"),
    M("Which failure should NOT be retried automatically?",
      ["A timeout", "A 503 Service Unavailable", "A 400 Bad Request", "A dropped connection"], 2,
      "A 400 means your request is wrong. Sending it again gets the same answer. Retry only failures that might succeed on another try."),
    K("Write retry(fn, attempts) that calls the async fn, and on failure tries again until it has made attempts calls in total. Resolve with the first success; if every call fails, reject with the last error.",
      "async function retry(fn, attempts) {\n  return fn();\n}",
      "async function retry(fn, attempts) {\n  let lastErr;\n  for (let i = 0; i < attempts; i++) {\n    try {\n      return await fn();\n    } catch (e) {\n      lastErr = e;\n    }\n  }\n  throw lastErr;\n}",
      [T("(async () => { let n = 0; return retry(async () => { n++; if (n < 3) throw new Error(\"x\"); return n; }, 5); })()", 3),
       T("(async () => { let n = 0; try { await retry(async () => { n++; throw new Error(\"e\" + n); }, 3); } catch (e) { return e.message + \" after \" + n; } })()", "e3 after 3")],
      "return await inside try is what makes the catch see async failures; a bare return fn() would skip it."),
    K("Write backoffDelays(base, n) returning the first n delays of exponential backoff capped at 30000 ms: base, 2*base, 4*base and so on.",
      "function backoffDelays(base, n) {\n  return Array(n).fill(base);\n}",
      "function backoffDelays(base, n) {\n  return Array.from({ length: n }, (_, i) => Math.min(30000, base * 2 ** i));\n}",
      [T("backoffDelays(500, 4)", [500, 1000, 2000, 4000]), T("backoffDelays(10000, 4)", [10000, 20000, 30000, 30000]), T("backoffDelays(100, 0)", [])],
      "Doubling spreads retries out so a struggling server can recover. The cap stops waits from growing absurd. Production code also adds random jitter so many clients do not retry in lockstep."),
    K("Write withTimeout(promise, ms) that resolves or rejects like promise, but rejects with an Error whose message is \"timeout\" if ms passes first.",
      "function withTimeout(promise, ms) {\n  return promise;\n}",
      "function withTimeout(promise, ms) {\n  let timer;\n  const t = new Promise((_, reject) => { timer = setTimeout(() => reject(new Error(\"timeout\")), ms); });\n  return Promise.race([promise, t]).finally(() => clearTimeout(timer));\n}",
      [T("withTimeout(Promise.resolve(\"ok\"), 50)", "ok"),
       T("withTimeout(new Promise(r => setTimeout(() => r(\"late\"), 50)), 5).catch(e => e.message)", "timeout")],
      "race picks the winner; finally clears the timer either way so nothing fires after the result."),
    O("Order a search box that cancels stale requests.",
      ["The user types a new character", "Abort the previous request's controller", "Create a new AbortController", "Start fetch with the new signal", "Ignore AbortError in the catch"],
      "Without cancellation, a slow old response can arrive after a fast new one and overwrite the right results."),
])

JA4 = L("Functions that build functions", KW + ["higher", "order", "compose", "pipe", "curry", "memoize", "partial", "functional"], [
    C("Functions are values, use that",
      "A higher-order function takes or returns a function. compose and pipe glue small functions into one, currying turns f(a, b) into f(a)(b) so you can pre-fill arguments, and memoize caches results of a pure function.",
      "const pipe = (...fns) => x => fns.reduce((v, f) => f(v), x);\nconst slug = pipe(s => s.trim(), s => s.toLowerCase());"),
    P("const pipe = (...fns) => x => fns.reduce((v, f) => f(v), x);\nconst f = pipe(x => x + 1, x => x * 10);\nconsole.log(f(2));", "30",
      "pipe runs left to right: 2 + 1 is 3, then 3 * 10 is 30. compose would run right to left and give 21."),
    K("Write compose(...fns) that runs functions right to left. compose() with no functions returns the identity function.",
      "function compose(...fns) {\n  return x => fns[0](x);\n}",
      "function compose(...fns) {\n  return x => fns.reduceRight((v, f) => f(v), x);\n}",
      [T("compose(x => x + 1, x => x * 10)(2)", 21), T("compose()(5)", 5), T("compose(s => s + \"!\", s => s.toUpperCase())(\"hi\")", "HI!")],
      "reduceRight walks from the last function to the first, threading the value through."),
    K("Write memoize(fn) for single-argument pure functions. The returned function must call fn only once per distinct argument.",
      "function memoize(fn) {\n  return fn;\n}",
      "function memoize(fn) {\n  const cache = new Map();\n  return arg => {\n    if (!cache.has(arg)) cache.set(arg, fn(arg));\n    return cache.get(arg);\n  };\n}",
      [T("(() => { let calls = 0; const sq = memoize(x => { calls++; return x * x; }); sq(4); sq(4); sq(5); return [sq(4), calls]; })()", [16, 2]),
       T("(() => { let calls = 0; const f = memoize(x => { calls++; return undefined; }); f(1); f(1); return calls; })()", 1)],
      "cache.has rather than a truthy check means results like 0 or undefined are cached too."),
    K("Write curry2(fn) that lets a two-argument function be called as f(a, b) or f(a)(b).",
      "function curry2(fn) {\n  return a => b => fn(a, b);\n}",
      "function curry2(fn) {\n  return function (a, b) {\n    if (arguments.length >= 2) return fn(a, b);\n    return b2 => fn(a, b2);\n  };\n}",
      [T("curry2((a, b) => a - b)(10)(3)", 7), T("curry2((a, b) => a - b)(10, 3)", 7), T("[1, 2, 3].map(curry2((a, b) => a * b)(5))", [5, 10, 15])],
      "Checking arguments.length makes the function flexible. In the map test, map passes extra arguments, but after pre-filling only the element reaches b2."),
    M("When is memoize a bad idea?",
      ["For a pure function called with the same inputs often", "For a function that reads the current time", "For a slow recursive calculation", "For parsing the same config many times"], 1,
      "Memoizing something impure returns stale answers. The cache is only correct when the same input always gives the same output."),
    O("Order how memoize answers a call.",
      ["Receive the argument", "Look it up in the cache", "On a miss, call fn and store the result", "Return the cached value"],
      "Every call returns from the cache; only misses pay for fn."),
])

JA5 = L("Iterators and generators", KW + ["iterator", "generator", "yield", "lazy", "iterable", "symbol", "sequence"], [
    C("Anything can be for...of'd",
      "An iterable has a Symbol.iterator method returning an object with next(), which hands back { value, done }. Generators (function*) write that object for you: each yield pauses the function and hands out one value.",
      "function* count(to) {\n  for (let i = 1; i <= to; i++) yield i;\n}\n[...count(3)]; // [1, 2, 3]"),
    P("function* g() { yield \"a\"; yield \"b\"; }\nconst it = g();\nit.next();\nconsole.log(it.next().value + it.next().done);", "btrue",
      "The second next() returns b. The third finds the generator finished, so done is true."),
    M("Why can a generator describe an infinite sequence without freezing?",
      ["It runs on another thread", "It only computes the next value when asked", "It stores values in a cache", "It stops after 1000 items"], 1,
      "Generators are lazy. Ask for 5 values and only 5 are computed."),
    K("Write a generator take(iterable, n) that yields at most n items from any iterable. The source may be endless, so stop reading it once you have n items.",
      "function* take(iterable, n) {\n  yield* iterable;\n}",
      "function* take(iterable, n) {\n  if (n <= 0) return;\n  let i = 0;\n  for (const x of iterable) {\n    yield x;\n    if (++i >= n) return;\n  }\n}",
      [T("[...take([1, 2, 3, 4], 2)]", [1, 2]), T("[...take(\"hello\", 3)]", ["h", "e", "l"]), T("[...take([1], 0)]", []),
       T("(() => { let pulled = 0; function* nat() { let i = 0; while (i < 1000) { pulled++; yield i++; } } const got = [...take(nat(), 4)]; return [got, pulled <= 5]; })()", [[0, 1, 2, 3], True])],
      "Returning after the nth item stops the loop, which also closes an infinite source cleanly."),
    K("Write a class Range with constructor(start, end) that is iterable: for...of yields start, start+1, up to end inclusive.",
      "class Range {\n  constructor(start, end) { this.start = start; this.end = end; }\n}",
      "class Range {\n  constructor(start, end) { this.start = start; this.end = end; }\n  *[Symbol.iterator]() {\n    for (let i = this.start; i <= this.end; i++) yield i;\n  }\n}",
      [T("[...new Range(2, 5)]", [2, 3, 4, 5]), T("[...new Range(3, 1)]", []), T("Array.from(new Range(0, 2), x => x * 2)", [0, 2, 4])],
      "A generator method under the Symbol.iterator key makes any object work with spread, for...of and Array.from."),
    O("Order what for (const x of thing) does.",
      ["Call thing[Symbol.iterator]()", "Call next() on the iterator", "Stop if done is true", "Otherwise bind value to x and run the body", "Go back to next()"],
      "That is the whole protocol. Spread, destructuring and Array.from all use the same loop."),
    C("Lazy pipelines",
      "Chain generators (map, filter, take) to process a huge file line by line without loading it all. Each value flows through the whole pipeline before the next is read."),
])

JA6 = L("this, bind, call and apply", KW + ["this", "bind", "call", "apply", "context", "arrow", "methods"], [
    C("this is decided by the call, not the definition",
      "In a regular function, this is whatever is left of the dot at call time: obj.f() sets this to obj. Pull the function off the object and the dot is gone, so this is undefined in strict mode. Arrow functions have no this of their own; they use the surrounding one.",
      "const user = { name: \"Ada\", hi() { return this.name; } };\nuser.hi();        // \"Ada\"\nconst f = user.hi;\n// f() loses this"),
    M("Why does setTimeout(user.hi, 0) not see user's name?",
      ["Timers run in another window", "The function is passed without its object, so the later call has no dot", "Arrow functions break timers", "this is always the global object"], 1,
      "setTimeout calls the bare function later. Use setTimeout(() => user.hi(), 0) or user.hi.bind(user)."),
    P("const o = { n: 1, f() { return [1, 2].map(() => this.n).join(\"\"); } };\nconsole.log(o.f());", "11",
      "The arrow callback borrows this from f, where this is o."),
    K("Write bindAll(obj, names) that replaces each named method with a copy bound to obj, and returns obj.",
      "function bindAll(obj, names) {\n  return obj;\n}",
      "function bindAll(obj, names) {\n  for (const n of names) obj[n] = obj[n].bind(obj);\n  return obj;\n}",
      [T("(() => { const o = bindAll({ v: 7, get() { return this && this.v; } }, [\"get\"]); const g = o.get; return g(); })()", 7)],
      "bind returns a new function with this fixed, so it survives being passed around."),
    K("Write sumWith(obj) that calls obj.total with call() so that this inside total is obj, and the numbers 1, 2 and 3 are passed as arguments. Then write maxOf(nums) using Math.max.apply.",
      "function sumWith(obj) {\n  const f = obj.total;\n  return f(1, 2, 3);\n}\nfunction maxOf(nums) {\n  return Math.max(nums);\n}",
      "function sumWith(obj) {\n  return obj.total.call(obj, 1, 2, 3);\n}\nfunction maxOf(nums) {\n  return Math.max.apply(null, nums);\n}",
      [T("sumWith({ base: 10, total(a, b, c) { return this.base + a + b + c; } })", 16), T("maxOf([3, 9, 2])", 9), T("maxOf([]) === -Infinity", True)],
      "call passes this and the arguments one by one; apply takes them as an array. Spread does the same job today, but you will meet both in older code."),
    O("Order how to find what this is in a regular function call.",
      ["Is it called with new? Then this is the new object", "Is it bound with bind, call or apply? Then the given object", "Is there an object left of the dot? Then that object", "Otherwise undefined in strict code"],
      "Check the rules in this order; the first that applies wins. Arrow functions skip all of them and use the outer this."),
])

JA7 = L("Immutability at depth", KW + ["immutable", "immutability", "freeze", "structuredclone", "deep", "copy", "update", "nested"], [
    C("Shallow copies share the inside",
      "Spread copies one level. Nested objects are still shared, so changing copy.address.city changes the original. structuredClone makes a deep copy of plain data. Object.freeze stops changes, but only one level deep.",
      "const a = { tags: [\"x\"] };\nconst b = { ...a };\nb.tags.push(\"y\");\na.tags; // [\"x\", \"y\"]"),
    P("const a = Object.freeze({ inner: { n: 1 } });\na.inner.n = 2;\nconsole.log(a.inner.n);", "2",
      "freeze is shallow. a itself cannot change, but the object stored in inner is not frozen."),
    M("Which value can structuredClone NOT copy?",
      ["A Date", "A Map", "A function", "A nested array"], 2,
      "structuredClone copies data, including Dates, Maps and Sets. Functions are behavior, and it throws on them."),
    K("Write setIn(obj, path, value) that returns a new object with the value at the path (an array of keys) replaced, copying only the objects along the path. Missing objects on the path are created. The original must not change.",
      "function setIn(obj, path, value) {\n  let o = obj;\n  for (const k of path.slice(0, -1)) o = o[k];\n  o[path[path.length - 1]] = value;\n  return obj;\n}",
      "function setIn(obj, path, value) {\n  if (path.length === 0) return value;\n  const [k, ...rest] = path;\n  const child = obj == null ? undefined : obj[k];\n  return { ...obj, [k]: setIn(child == null ? {} : child, rest, value) };\n}",
      [T("setIn({ a: { b: 1, c: 2 } }, [\"a\", \"b\"], 9)", {"a": {"b": 9, "c": 2}}),
       T("(() => { const o = { a: { b: 1 } }; setIn(o, [\"a\", \"b\"], 9); return o.a.b; })()", 1),
       T("(() => { const o = { a: { b: 1 }, z: { y: 1 } }; return setIn(o, [\"a\", \"b\"], 2).z === o.z; })()", True),
       T("setIn({}, [\"x\", \"y\"], 1)", {"x": {"y": 1}})],
      "Copy the path, share the rest. That structural sharing is why immutable updates stay cheap and why z === o.z."),
    K("Write deepFreeze(obj) that freezes an object and every object nested inside it, then returns it. Watch out: an object may refer back to itself.",
      "function deepFreeze(obj) {\n  return Object.freeze(obj);\n}",
      "function deepFreeze(obj) {\n  Object.freeze(obj);\n  for (const v of Object.values(obj)) {\n    if (v && typeof v === \"object\" && !Object.isFrozen(v)) deepFreeze(v);\n  }\n  return obj;\n}",
      [T("(() => { const o = deepFreeze({ a: { b: [1] } }); return Object.isFrozen(o.a) && Object.isFrozen(o.a.b); })()", True),
       T("(() => { const o = deepFreeze({ a: { b: 1 } }); try { o.a.b = 2; } catch (e) {} return o.a.b; })()", 1),
       T("(() => { const o = { n: 1 }; o.self = o; deepFreeze(o); return Object.isFrozen(o); })()", True)],
      "Freezing the parent first and skipping anything already frozen is what stops an object that points at itself from looping forever."),
    O("Order an immutable update of state.user.address.city.",
      ["Copy state", "Copy state.user into the new state", "Copy the address into the new user", "Set city on the new address"],
      "Every object on the path gets a fresh copy; everything off the path is shared with the old state."),
])

JA8 = L("Recursion and trees", KW + ["recursion", "recursive", "tree", "nested", "flatten", "walk", "json", "depth"], [
    C("A function that trusts itself",
      "Recursion solves a problem by solving a smaller copy of it. Every recursive function needs a base case that stops, and a step that moves toward it. Trees (folders, comments, the DOM, JSON) are recursive data, so recursive code fits them.",
      "function depth(node) {\n  if (!node.children || !node.children.length) return 1;\n  return 1 + Math.max(...node.children.map(depth));\n}"),
    P("function sum(n) { return n === 0 ? 0 : n + sum(n - 1); }\nconsole.log(sum(4));", "10",
      "4 + 3 + 2 + 1 + 0. The base case n === 0 stops the chain."),
    M("What happens when a recursive function has no reachable base case?",
      ["It returns undefined", "It loops forever quietly", "It throws a RangeError: Maximum call stack size exceeded", "JavaScript optimizes it away"], 2,
      "Each call adds a stack frame. With no base case the stack overflows."),
    K("Write flatten(arr) that flattens arrays nested to any depth, without using Array.prototype.flat.",
      "function flatten(arr) {\n  return arr;\n}",
      "function flatten(arr) {\n  const out = [];\n  for (const x of arr) {\n    if (Array.isArray(x)) out.push(...flatten(x));\n    else out.push(x);\n  }\n  return out;\n}",
      [T("flatten([1, [2, [3, [4]]], 5])", [1, 2, 3, 4, 5]), T("flatten([])", []), T("flatten([[[]]])", [])],
      "Base case: a non-array item is pushed as is. Recursive step: an array is flattened, then spread in."),
    K("Write findPaths(tree, name) that returns every path (names joined by \"/\") to a node whose name matches. Nodes look like { name, children? }. Each path starts with the root's name.",
      "function findPaths(tree, name) {\n  return tree.name === name ? [tree.name] : [];\n}",
      "function findPaths(tree, name, prefix = \"\") {\n  const here = prefix ? prefix + \"/\" + tree.name : tree.name;\n  const hits = tree.name === name ? [here] : [];\n  for (const c of tree.children || []) hits.push(...findPaths(c, name, here));\n  return hits;\n}",
      [T("findPaths({ name: \"root\", children: [{ name: \"a\", children: [{ name: \"x\" }] }, { name: \"x\" }] }, \"x\")", ["root/a/x", "root/x"]),
       T("findPaths({ name: \"x\" }, \"x\")", ["x"]), T("findPaths({ name: \"r\", children: [] }, \"q\")", [])],
      "Carry the path so far as an argument. Each level adds its own name and asks the children."),
    O("Order how to write any recursive tree function.",
      ["Decide the answer for a leaf (the base case)", "Assume the call works on each child", "Combine the children's answers with this node", "Return the combined answer"],
      "Trusting the recursive call on a smaller input is the leap. You only design one level."),
    C("Know the limit",
      "Deep recursion (tens of thousands of levels) can overflow the stack. For very deep data, switch to an explicit stack array and a while loop. Same logic, no stack limit."),
])

JA9 = L("Capstone: an event-driven task queue", KW + ["capstone", "project", "queue", "events", "emitter", "async", "concurrency", "jobs"], [
    C("The brief",
      "Build a small job queue like the ones that send emails or resize images in real apps. It emits events, runs async jobs with a concurrency limit, retries failures, and reports results. You will use closures, classes, promises, retry and the event loop from this course."),
    K("Step 1. Write class Emitter with on(event, fn) that returns an unsubscribe function, and emit(event, ...args) that calls every listener in the order added.",
      "class Emitter {\n  on(event, fn) {}\n  emit(event, ...args) {}\n}",
      "class Emitter {\n  #map = new Map();\n  on(event, fn) {\n    if (!this.#map.has(event)) this.#map.set(event, []);\n    this.#map.get(event).push(fn);\n    return () => {\n      const list = this.#map.get(event);\n      const i = list.indexOf(fn);\n      if (i >= 0) list.splice(i, 1);\n    };\n  }\n  emit(event, ...args) {\n    for (const fn of [...(this.#map.get(event) || [])]) fn(...args);\n  }\n}",
      [T("(() => { const e = new Emitter(); const log = []; e.on(\"x\", v => log.push(\"a\" + v)); e.on(\"x\", v => log.push(\"b\" + v)); e.emit(\"x\", 1); return log; })()", ["a1", "b1"]),
       T("(() => { const e = new Emitter(); let n = 0; const off = e.on(\"x\", () => n++); e.emit(\"x\"); off(); e.emit(\"x\"); return n; })()", 1),
       T("(() => { const e = new Emitter(); e.emit(\"nobody\"); return \"ok\"; })()", "ok")],
      "Copying the list before calling lets a listener unsubscribe itself mid-emit without skipping the next one."),
    K("Step 2. Write class Queue with constructor(concurrency, retries). add(job) takes an async function and returns a promise of its result. At most concurrency jobs run at once. A failing job is retried up to retries more times before its promise rejects.",
      "class Queue {\n  constructor(concurrency, retries) {}\n  add(job) { return job(); }\n}",
      "class Queue {\n  constructor(concurrency, retries = 0) {\n    this.concurrency = concurrency;\n    this.retries = retries;\n    this.running = 0;\n    this.waiting = [];\n  }\n  add(job) {\n    return new Promise((resolve, reject) => {\n      this.waiting.push({ job, resolve, reject });\n      this.#pump();\n    });\n  }\n  #pump() {\n    while (this.running < this.concurrency && this.waiting.length) {\n      const { job, resolve, reject } = this.waiting.shift();\n      this.running++;\n      this.#attempt(job, this.retries)\n        .then(resolve, reject)\n        .finally(() => { this.running--; this.#pump(); });\n    }\n  }\n  async #attempt(job, left) {\n    try {\n      return await job();\n    } catch (e) {\n      if (left > 0) return this.#attempt(job, left - 1);\n      throw e;\n    }\n  }\n}",
      [T("(async () => { const q = new Queue(2, 0); return Promise.all([q.add(async () => 1), q.add(async () => 2), q.add(async () => 3)]); })()", [1, 2, 3]),
       T("(async () => { const q = new Queue(2, 0); let live = 0, peak = 0; const job = async () => { live++; peak = Math.max(peak, live); await new Promise(r => setTimeout(r, 2)); live--; }; await Promise.all([1,2,3,4,5].map(() => q.add(job))); return peak; })()", 2),
       T("(async () => { const q = new Queue(1, 2); let n = 0; return q.add(async () => { n++; if (n < 3) throw new Error(\"x\"); return \"ok after \" + n; }); })()", "ok after 3"),
       T("(async () => { const q = new Queue(1, 1); let n = 0; try { await q.add(async () => { n++; throw new Error(\"no\"); }); } catch (e) { return e.message + n; } })()", "no2")],
      "A waiting list plus a running count is the whole scheduler. finally frees the slot whether the job worked or not, then pumps the next one."),
    M("A job hangs forever and never settles. What happens to your queue?",
      ["Nothing, other jobs carry on at full speed", "It permanently holds one slot; with enough hung jobs the queue stalls", "It is retried automatically", "JavaScript times it out after 30 seconds"], 1,
      "Nothing in the queue limits time. Real queues wrap each attempt in a timeout like withTimeout from lesson 3."),
    O("Order the life of one job in your queue.",
      ["add() puts it on the waiting list", "pump() starts it when a slot is free", "A failure is retried while retries remain", "The promise from add() settles", "The slot is released and pump() runs again"],
      "Each stage hands off to the next through promises, so the main thread is never blocked."),
    C("What you can do now",
      "You built a scheduler with backpressure, retries and events: the core of job runners, upload managers and crawlers. Add timeouts and persistence and it is production shaped."),
])

# =====================================================================
# Expert: JavaScript engineering
# =====================================================================

JE1 = L("Complexity you can feel", KW + ["big", "complexity", "performance", "algorithm", "quadratic", "linear", "time", "space"], [
    C("Count the work, not the seconds",
      "Big O describes how work grows with input size n. One pass is O(n). A loop inside a loop over the same data is O(n squared): 10 times the data means 100 times the work. A Map or Set lookup is about O(1), which is why it turns nested loops into one pass.",
      "// O(n^2): for each a, scan all of b\nlist.filter(a => other.includes(a));\n// O(n): build a Set once\nconst s = new Set(other);\nlist.filter(a => s.has(a));"),
    M("An O(n squared) function takes 1 second for 1,000 items. Roughly how long for 10,000?",
      ["2 seconds", "10 seconds", "100 seconds", "1,000 seconds"], 2,
      "10 times the input squared is 100 times the work. That is why quadratic code that felt fine in testing falls over in production."),
    M("What is the time complexity of arr.indexOf(x) on an unsorted array?",
      ["O(1)", "O(log n)", "O(n)", "O(n log n)"], 2,
      "It may have to look at every element. A sorted array allows binary search in O(log n)."),
    K("Write hasPairWithSum(nums, target) that returns true if numbers at two different positions add to target. It must be O(n): 15,000 items has to finish in under 100 ms.",
      "function hasPairWithSum(nums, target) {\n  for (let i = 0; i < nums.length; i++)\n    for (let j = 0; j < nums.length; j++)\n      if (nums[i] + nums[j] === target) return true;\n  return false;\n}",
      "function hasPairWithSum(nums, target) {\n  const seen = new Set();\n  for (const n of nums) {\n    if (seen.has(target - n)) return true;\n    seen.add(n);\n  }\n  return false;\n}",
      [T("hasPairWithSum([3, 8, 1, 5], 9)", True), T("hasPairWithSum([4], 8)", False), T("hasPairWithSum([4, 4], 8)", True), T("hasPairWithSum([1, 2, 3], 7)", False),
       T("(() => { const a = Array.from({ length: 15000 }, (_, i) => i * 2); const t0 = Date.now(); const r = hasPairWithSum(a, -1); return [r, Date.now() - t0 < 100]; })()", [False, True])],
      "For each number, ask whether its partner was already seen. The starter also fails [4] with 8 because it pairs a position with itself."),
    K("Write binarySearch(sorted, x) returning the index of x or -1, in O(log n).",
      "function binarySearch(sorted, x) {\n  return sorted.indexOf(x);\n}",
      "function binarySearch(sorted, x) {\n  let lo = 0, hi = sorted.length - 1;\n  while (lo <= hi) {\n    const mid = (lo + hi) >> 1;\n    if (sorted[mid] === x) return mid;\n    if (sorted[mid] < x) lo = mid + 1;\n    else hi = mid - 1;\n  }\n  return -1;\n}",
      [T("binarySearch([1, 3, 5, 7, 9], 7)", 3), T("binarySearch([1, 3, 5], 4)", -1), T("binarySearch([], 1)", -1),
       T("(() => { let reads = 0; const p = new Proxy(Array.from({ length: 100000 }, (_, i) => i), { get(t, k) { if (typeof k === \"string\" && /^\\d+$/.test(k)) reads++; return t[k]; } }); const i = binarySearch(p, 76543); return [i, reads < 60]; })()", [76543, True])],
      "Each step halves the range. 100,000 items take about 17 comparisons; the last test counts reads to prove it."),
    O("Order how to fix a slow function.",
      ["Measure with realistic data to confirm it is slow", "Find the hot loop with a profiler", "Work out its complexity", "Pick a better data structure or algorithm", "Measure again"],
      "Measure before and after. Guessing at the bottleneck is how people optimize the wrong thing."),
])

JE2 = L("Graphs and search", KW + ["graph", "bfs", "dfs", "shortest", "path", "topological", "sort", "dependencies"], [
    C("Things and the links between them",
      "A graph is nodes plus edges: routes between cities, imports between files, follows between users. Store it as an adjacency list, a map from each node to its neighbors. Breadth-first search (BFS) explores in rings and finds the fewest-edges path.",
      "const g = { a: [\"b\", \"c\"], b: [\"d\"], c: [\"d\"], d: [] };"),
    M("Why does BFS find the shortest path in an unweighted graph?",
      ["It tries random paths", "It visits every node at distance 1 before any at distance 2", "It always goes deepest first", "It sorts the edges"], 1,
      "BFS uses a queue, so nodes come out in order of distance. The first time it reaches the goal is by the fewest edges."),
    K("Write shortestPath(graph, from, to) returning the list of nodes on a fewest-edges path, or null. graph is an object of neighbor arrays; visit neighbors in array order.",
      "function shortestPath(graph, from, to) {\n  return [from, to];\n}",
      "function shortestPath(graph, from, to) {\n  const prev = new Map([[from, null]]);\n  const queue = [from];\n  while (queue.length) {\n    const n = queue.shift();\n    if (n === to) {\n      const path = [];\n      for (let c = to; c !== null; c = prev.get(c)) path.unshift(c);\n      return path;\n    }\n    for (const m of graph[n] || []) {\n      if (!prev.has(m)) { prev.set(m, n); queue.push(m); }\n    }\n  }\n  return null;\n}",
      [T("shortestPath({ a: [\"b\", \"c\"], b: [\"d\"], c: [\"e\"], e: [\"d\"], d: [] }, \"a\", \"d\")", ["a", "b", "d"]),
       T("shortestPath({ a: [\"b\"], b: [] }, \"b\", \"a\")", None), T("shortestPath({ a: [] }, \"a\", \"a\")", ["a"]),
       T("shortestPath({ a: [\"b\"], b: [\"a\", \"c\"], c: [] }, \"a\", \"c\")", ["a", "b", "c"])],
      "prev records how each node was first reached, which both marks it visited and lets you walk the path back."),
    K("Write topoSort(deps) where deps maps each task to the tasks it needs first. Return an order where every task comes after its needs, or throw an Error if there is a cycle. Visit tasks in the object's key order.",
      "function topoSort(deps) {\n  return Object.keys(deps);\n}",
      "function topoSort(deps) {\n  const out = [], state = new Map();\n  const visit = (t) => {\n    if (state.get(t) === \"done\") return;\n    if (state.get(t) === \"active\") throw new Error(\"cycle at \" + t);\n    state.set(t, \"active\");\n    for (const d of deps[t] || []) visit(d);\n    state.set(t, \"done\");\n    out.push(t);\n  };\n  Object.keys(deps).forEach(visit);\n  return out;\n}",
      [T("topoSort({ app: [\"lib\", \"ui\"], ui: [\"lib\"], lib: [] })", ["lib", "ui", "app"]),
       T("(() => { try { topoSort({ a: [\"b\"], b: [\"a\"] }); return \"no\"; } catch (e) { return \"cycle\"; } })()", "cycle"),
       T("topoSort({ x: [] })", ["x"])],
      "Depth-first, emit a task after its needs. A task still active when you meet it again means you went round in a loop."),
    O("Order BFS.",
      ["Put the start node in a queue and mark it seen", "Take the next node from the front", "Stop if it is the goal", "Add its unseen neighbors to the back and mark them", "Repeat until the queue is empty"],
      "Marking when you enqueue, not when you dequeue, stops a node being queued twice."),
    C("Where you have already met graphs",
      "npm resolving dependencies, a bundler ordering modules, a spreadsheet recalculating cells and a router matching links all run graph algorithms. Recognising the graph is most of the work."),
])

JE3 = L("Dynamic programming", KW + ["dynamic", "programming", "memoization", "tabulation", "optimization", "subproblems", "coins"], [
    C("Solve each small problem once",
      "Dynamic programming works when a big problem breaks into overlapping smaller ones. Top-down: write the recursion and memoize it. Bottom-up: fill a table from the smallest case upward. Both turn exponential brute force into polynomial time.",
      "// fib(n) with a table: O(n) instead of O(2^n)\nconst f = [0, 1];\nfor (let i = 2; i <= n; i++) f[i] = f[i - 1] + f[i - 2];"),
    M("Naive recursive fib(40) makes hundreds of millions of calls. Why?",
      ["JavaScript recursion is slow", "It recomputes the same subproblems again and again", "40 is too large for a number", "It has no base case"], 1,
      "fib(38) is computed twice, fib(37) three times, and so on. Caching each answer once makes it linear."),
    K("Write minCoins(coins, amount) returning the fewest coins that make the amount exactly, or -1 if impossible. Coins can be reused.",
      "function minCoins(coins, amount) {\n  let n = 0;\n  const sorted = [...coins].sort((a, b) => b - a);\n  for (const c of sorted) while (amount >= c) { amount -= c; n++; }\n  return amount === 0 ? n : -1;\n}",
      "function minCoins(coins, amount) {\n  const best = new Array(amount + 1).fill(Infinity);\n  best[0] = 0;\n  for (let a = 1; a <= amount; a++) {\n    for (const c of coins) {\n      if (c <= a && best[a - c] + 1 < best[a]) best[a] = best[a - c] + 1;\n    }\n  }\n  return best[amount] === Infinity ? -1 : best[amount];\n}",
      [T("minCoins([1, 5, 10], 27)", 5), T("minCoins([1, 3, 4], 6)", 2), T("minCoins([2], 3)", -1), T("minCoins([5], 0)", 0)],
      "Greedy (the starter) takes 4 then 1 then 1 for 6, three coins. The table finds 3 plus 3. best[a] holds the answer for every smaller amount, built once."),
    K("Write lcsLength(a, b) returning the length of the longest common subsequence of two strings (characters in order, not necessarily adjacent).",
      "function lcsLength(a, b) {\n  let n = 0;\n  for (const ch of a) if (b.includes(ch)) n++;\n  return n;\n}",
      "function lcsLength(a, b) {\n  const dp = Array.from({ length: a.length + 1 }, () => new Array(b.length + 1).fill(0));\n  for (let i = 1; i <= a.length; i++) {\n    for (let j = 1; j <= b.length; j++) {\n      dp[i][j] = a[i - 1] === b[j - 1] ? dp[i - 1][j - 1] + 1 : Math.max(dp[i - 1][j], dp[i][j - 1]);\n    }\n  }\n  return dp[a.length][b.length];\n}",
      [T("lcsLength(\"ABCBDAB\", \"BDCABA\")", 4), T("lcsLength(\"abc\", \"cba\")", 1), T("lcsLength(\"\", \"abc\")", 0), T("lcsLength(\"kitten\", \"sitting\")", 4)],
      "dp[i][j] answers the problem for the first i and j characters. Diff tools are built on this idea."),
    O("Order the steps to design a dynamic programming solution.",
      ["Define what one subproblem's answer means", "Write the recurrence that combines smaller answers", "Set the base cases", "Choose a fill order where smaller answers come first", "Read the final answer from the table"],
      "The definition is the hard part. Once dp[i] has a precise meaning, the code nearly writes itself."),
    C("Greedy versus exact",
      "Greedy algorithms are fast and often right, but not always (the 1, 3, 4 coins show it). When a greedy choice can block a better total later, reach for dynamic programming."),
])

JE4 = L("A tokenizer and parser", KW + ["parser", "tokenizer", "lexer", "ast", "expression", "evaluate", "precedence", "grammar"], [
    C("Text in, tree out",
      "A tokenizer turns characters into tokens (numbers, operators, parentheses). A parser turns tokens into structure that encodes precedence: in 2 + 3 * 4 the multiply binds tighter, so it is computed first. Recursive descent writes one function per precedence level.",
      "expr   = term (('+' | '-') term)*\nterm   = factor (('*' | '/') factor)*\nfactor = number | '(' expr ')' | '-' factor"),
    M("Why is eval(userText) the wrong way to build a calculator?",
      ["It is slow", "It runs any JavaScript the user types, including code that steals data", "It cannot do multiplication", "It is not supported in browsers"], 1,
      "eval executes arbitrary code. A parser that only understands arithmetic cannot be tricked into doing anything else."),
    K("Write tokenize(src) returning an array of tokens: numbers as numbers (decimals allowed) and the characters + - * / ( ) as strings. Skip spaces. Throw an Error on any other character.",
      "function tokenize(src) {\n  return src.split(\"\");\n}",
      "function tokenize(src) {\n  const out = [];\n  let i = 0;\n  while (i < src.length) {\n    const ch = src[i];\n    if (ch === \" \") { i++; continue; }\n    if (\"+-*/()\".includes(ch)) { out.push(ch); i++; continue; }\n    const m = /^\\d+(\\.\\d+)?/.exec(src.slice(i));\n    if (m) { out.push(Number(m[0])); i += m[0].length; continue; }\n    throw new Error(\"unexpected \" + ch);\n  }\n  return out;\n}",
      [T("tokenize(\"12 + 3.5*(2-1)\")", [12, "+", 3.5, "*", "(", 2, "-", 1, ")"]), T("tokenize(\"\")", []),
       T("(() => { try { tokenize(\"2 ^ 3\"); return \"no\"; } catch (e) { return \"threw\"; } })()", "threw")],
      "Read one token at a time. Numbers need a pattern because they span several characters."),
    K("Write calc(src) that evaluates + - * / with correct precedence, parentheses and unary minus. Include your tokenizer. Throw on malformed input such as \"2 +\" or \"(1\".",
      "function calc(src) {\n  return Number(src);\n}",
      "function tokenize(src) {\n  const out = [];\n  let i = 0;\n  while (i < src.length) {\n    const ch = src[i];\n    if (ch === \" \") { i++; continue; }\n    if (\"+-*/()\".includes(ch)) { out.push(ch); i++; continue; }\n    const m = /^\\d+(\\.\\d+)?/.exec(src.slice(i));\n    if (m) { out.push(Number(m[0])); i += m[0].length; continue; }\n    throw new Error(\"unexpected \" + ch);\n  }\n  return out;\n}\nfunction calc(src) {\n  const t = tokenize(src);\n  let i = 0;\n  const peek = () => t[i];\n  const take = () => t[i++];\n  function expr() {\n    let v = term();\n    while (peek() === \"+\" || peek() === \"-\") v = take() === \"+\" ? v + term() : v - term();\n    return v;\n  }\n  function term() {\n    let v = factor();\n    while (peek() === \"*\" || peek() === \"/\") v = take() === \"*\" ? v * factor() : v / factor();\n    return v;\n  }\n  function factor() {\n    const tok = take();\n    if (typeof tok === \"number\") return tok;\n    if (tok === \"-\") return -factor();\n    if (tok === \"(\") {\n      const v = expr();\n      if (take() !== \")\") throw new Error(\"missing )\");\n      return v;\n    }\n    throw new Error(\"unexpected \" + tok);\n  }\n  const v = expr();\n  if (i !== t.length) throw new Error(\"extra input\");\n  return v;\n}",
      [T("calc(\"2 + 3 * 4\")", 14), T("calc(\"(2 + 3) * 4\")", 20), T("calc(\"10 - 4 - 3\")", 3), T("calc(\"-2 * -(1 + 1)\")", 4), T("calc(\"8 / 2 / 2\")", 2),
       T("(() => { try { calc(\"2 +\"); return \"no\"; } catch (e) { return \"threw\"; } })()", "threw"),
       T("(() => { try { calc(\"(1\"); return \"no\"; } catch (e) { return \"threw\"; } })()", "threw")],
      "One function per precedence level, and loops (not recursion) for + and - keep 10 - 4 - 3 left-associative."),
    O("Order the stages from source text to answer.",
      ["Tokenize the characters", "Parse tokens by precedence", "Check that every token was used", "Return the value"],
      "Compilers and template engines follow the same stages, with a tree in the middle instead of a number."),
    C("Grammars scale",
      "Add a level to the grammar and you add a feature: a power operator, function calls, comparisons. The same shape parses JSON, CSS selectors and programming languages."),
])

JE5 = L("State machines and reducers", KW + ["state", "machine", "reducer", "fsm", "transitions", "redux", "events", "ui"], [
    C("Make impossible states impossible",
      "UI bugs often come from flags that disagree: loading is true and error is set at the same time. A finite state machine allows exactly one state at a time and lists the legal transitions. A reducer is a pure function (state, event) => newState that enforces them.",
      "const machine = {\n  idle:    { FETCH: \"loading\" },\n  loading: { OK: \"success\", FAIL: \"error\" },\n  error:   { RETRY: \"loading\" },\n  success: {}\n};"),
    M("With the machine above, what should happen when the state is success and a FETCH event arrives?",
      ["Go to loading", "Throw", "Stay in success, the event is not allowed there", "Go to idle"], 2,
      "Events a state does not list are ignored. That is how a double-click cannot start a second request."),
    K("Write transition(machine, state, event) that returns the next state, or the same state if the event is not allowed.",
      "function transition(machine, state, event) {\n  return machine[state][event];\n}",
      "function transition(machine, state, event) {\n  const next = (machine[state] || {})[event];\n  return next === undefined ? state : next;\n}",
      [T("transition({ idle: { GO: \"run\" }, run: {} }, \"idle\", \"GO\")", "run"), T("transition({ idle: { GO: \"run\" }, run: {} }, \"run\", \"GO\")", "run"), T("transition({ idle: {} }, \"idle\", \"STOP\")", "idle")],
      "Unknown events fall through to the current state instead of producing undefined."),
    K("Write reducer(state, action) for a form with state { status, data, error }. SUBMIT from \"editing\" goes to \"saving\" and clears error. SAVED from \"saving\" goes to \"done\" with action.data. FAILED from \"saving\" goes back to \"editing\" with action.error. Anything else returns the same state object. Never mutate state.",
      "function reducer(state, action) {\n  state.status = \"saving\";\n  return state;\n}",
      "function reducer(state, action) {\n  switch (state.status + \":\" + action.type) {\n    case \"editing:SUBMIT\": return { ...state, status: \"saving\", error: null };\n    case \"saving:SAVED\": return { ...state, status: \"done\", data: action.data };\n    case \"saving:FAILED\": return { ...state, status: \"editing\", error: action.error };\n    default: return state;\n  }\n}",
      [T("reducer({ status: \"editing\", data: null, error: \"old\" }, { type: \"SUBMIT\" })", {"status": "saving", "data": None, "error": None}),
       T("reducer({ status: \"saving\", data: null, error: null }, { type: \"SAVED\", data: 5 }).data", 5),
       T("reducer({ status: \"saving\", data: null, error: null }, { type: \"FAILED\", error: \"net\" })", {"status": "editing", "data": None, "error": "net"}),
       T("(() => { const s = { status: \"done\", data: 1, error: null }; return reducer(s, { type: \"SUBMIT\" }) === s; })()", True),
       T("(() => { const s = { status: \"editing\", data: null, error: null }; reducer(s, { type: \"SUBMIT\" }); return s.status; })()", "editing")],
      "Switching on state plus event names every legal pair. Returning the same object when nothing changed lets UIs skip work."),
    O("Order how a reducer-driven UI handles a click.",
      ["The click dispatches an action", "The reducer computes the next state", "The store saves the new state", "The view re-renders from the state"],
      "Data flows one way. The view never edits state directly, which is what makes bugs reproducible: replay the actions."),
    C("Draw it first",
      "Before coding a tricky flow (checkout, upload, onboarding), draw the states as boxes and the events as arrows. Missing arrows are bugs you just found without running anything."),
])

JE6 = L("Reactive state", KW + ["reactive", "store", "subscribe", "observable", "signals", "derived", "computed", "state"], [
    C("Tell me when it changes",
      "A store holds state and notifies subscribers when it changes. Signals go further: a computed value tracks which signals it read and recomputes only when one of them changes. Most UI frameworks are built on a version of this.",
      "const count = signal(1);\nconst double = computed(() => count.get() * 2);\ncount.set(5);\ndouble.get(); // 10"),
    M("Why should a store skip notifying subscribers when set() is called with the same value?",
      ["To save memory", "To avoid pointless re-renders and possible update loops", "Because subscribers would throw", "It should always notify"], 1,
      "Notifying on no change wastes work and can trigger a subscriber that sets the value again, forever."),
    K("Write createStore(initial) returning { get, set, subscribe }. set(v) changes the value and calls every subscriber with the new value, unless v is identical (Object.is) to the current value. subscribe returns an unsubscribe function.",
      "function createStore(initial) {\n  let value = initial;\n  return { get: () => value, set: v => { value = v; }, subscribe: () => () => {} };\n}",
      "function createStore(initial) {\n  let value = initial;\n  const subs = new Set();\n  return {\n    get: () => value,\n    set(v) {\n      if (Object.is(v, value)) return;\n      value = v;\n      for (const fn of [...subs]) fn(value);\n    },\n    subscribe(fn) {\n      subs.add(fn);\n      return () => subs.delete(fn);\n    },\n  };\n}",
      [T("(() => { const s = createStore(1); const seen = []; s.subscribe(v => seen.push(v)); s.set(2); s.set(2); s.set(3); return seen; })()", [2, 3]),
       T("(() => { const s = createStore(0); let n = 0; const off = s.subscribe(() => n++); s.set(1); off(); s.set(2); return [n, s.get()]; })()", [1, 2]),
       T("(() => { const s = createStore(NaN); let n = 0; s.subscribe(() => n++); s.set(NaN); return n; })()", 0)],
      "Object.is treats NaN as equal to itself, which === does not. A Set of subscribers makes double subscribing harmless."),
    K("Write signal(v) returning { get, set } and computed(fn) returning { get }. A computed caches its value and recomputes only after a signal it read has changed. Track dependencies automatically through get().",
      "function signal(v) {\n  return { get: () => v, set: n => { v = n; } };\n}\nfunction computed(fn) {\n  return { get: fn };\n}",
      "let current = null;\nfunction signal(v) {\n  const readers = new Set();\n  return {\n    get() { if (current) readers.add(current); return v; },\n    set(n) { if (Object.is(n, v)) return; v = n; for (const r of [...readers]) r.dirty = true; },\n  };\n}\nfunction computed(fn) {\n  const node = { dirty: true, value: undefined };\n  return {\n    get() {\n      if (node.dirty) {\n        const prev = current;\n        current = node;\n        try { node.value = fn(); } finally { current = prev; }\n        node.dirty = false;\n      }\n      return node.value;\n    },\n  };\n}",
      [T("(() => { const a = signal(2); const sq = computed(() => a.get() * a.get()); const x = sq.get(); a.set(3); return [x, sq.get()]; })()", [4, 9]),
       T("(() => { const a = signal(1); let runs = 0; const c = computed(() => { runs++; return a.get(); }); c.get(); c.get(); c.get(); return runs; })()", 1),
       T("(() => { const a = signal(1), b = signal(10); let runs = 0; const c = computed(() => { runs++; return a.get(); }); c.get(); b.set(20); c.get(); return runs; })()", 1)],
      "A shared pointer to whatever is computing right now lets each signal record its readers. Setting a signal only marks its own readers dirty, so unrelated changes cost nothing."),
    O("Order what happens when a signal used by a computed changes.",
      ["set() stores the new value", "set() marks every reader dirty", "Nothing recomputes yet", "The next get() on the computed reruns fn and caches the result"],
      "Lazy recomputation means a value nobody reads never costs anything."),
    P("const subs = new Set();\nconst f = () => {};\nsubs.add(f);\nsubs.add(f);\nconsole.log(subs.size);", "1",
      "A Set ignores a second add of the same function, which is why stores keep subscribers in one."),
    C("The cost of magic",
      "Automatic tracking is convenient, but a computed that reads a signal inside a condition only tracks it on runs where that branch executes. When a reactive value seems stale, check which signals it actually read on its last run."),
])

JE7 = L("Testing your own code", KW + ["testing", "tests", "unit", "assert", "runner", "property", "mocks", "tdd"], [
    C("A test is a claim you can rerun",
      "A unit test calls code with known input and asserts the output. A test runner collects tests, runs each in isolation, and reports which failed and why. Property-based tests go further: they check that a rule holds for many generated inputs, like \"sorting twice equals sorting once\"."),
    M("A test passes on your machine and fails in CI every few runs. The most likely cause?",
      ["CI computers are broken", "The test depends on time, randomness, order or a network, so it is flaky", "The test is too short", "JavaScript is nondeterministic"], 1,
      "Flaky tests usually depend on something outside the code under test. Control it: fake the clock, seed the random generator, stub the network."),
    K("Write a tiny runner: run(tests) takes an object of name to function and resolves with { passed, failed } where failed is an array of { name, message }. A test fails if it throws or returns a rejected promise. Run tests one after another.",
      "async function run(tests) {\n  return { passed: Object.keys(tests).length, failed: [] };\n}",
      "async function run(tests) {\n  let passed = 0;\n  const failed = [];\n  for (const [name, fn] of Object.entries(tests)) {\n    try {\n      await fn();\n      passed++;\n    } catch (e) {\n      failed.push({ name, message: e && e.message ? e.message : String(e) });\n    }\n  }\n  return { passed, failed };\n}",
      [T("run({ a() {}, b() { throw new Error(\"nope\"); }, async c() {} })", {"passed": 2, "failed": [{"name": "b", "message": "nope"}]}),
       T("run({ async d() { throw new Error(\"later\"); } })", {"passed": 0, "failed": [{"name": "d", "message": "later"}]})],
      "await fn() handles sync and async tests the same way, and one failure never stops the rest."),
    K("Write checkProperty(gen, prop, runs) that calls gen(i) to make an input for each i from 0 to runs - 1 and returns the first input where prop(input) is false, or null if all pass.",
      "function checkProperty(gen, prop, runs) {\n  return null;\n}",
      "function checkProperty(gen, prop, runs) {\n  for (let i = 0; i < runs; i++) {\n    const input = gen(i);\n    if (!prop(input)) return input;\n  }\n  return null;\n}",
      [T("checkProperty(i => i, n => n * 2 >= n, 50)", None),
       T("checkProperty(i => [i, -i], ([a, b]) => a + b === 0 && a < 10, 100)", [10, -10]),
       T("checkProperty(i => i * 3, n => n % 2 === 0 || n < 20, 30)", 21)],
      "Real property testing libraries add random generation and shrinking (finding the smallest failing input), but the core loop is this."),
    O("Order a good unit test.",
      ["Arrange: set up the input and any fakes", "Act: call the code once", "Assert: compare the result with the expected value", "Clean up anything the test changed"],
      "One act per test keeps a failure pointing at one behavior."),
    M("What is the main cost of mocking everything in a unit test?",
      ["Tests run slower", "Tests can pass while the real pieces do not fit together", "Mocks use too much memory", "Mocks cannot return values"], 1,
      "Heavy mocking tests your assumptions about collaborators, not the collaborators. Keep a few integration tests that use the real things."),
])

JE8 = L("Performance and memory", KW + ["performance", "debounce", "throttle", "cache", "lru", "memory", "weakmap", "leaks"], [
    C("Do less, less often, and let go",
      "Most front end slowness is doing work too often (a handler on every keystroke or scroll) or keeping things too long (caches that only grow, listeners never removed). Debounce waits for a pause, throttle caps the rate, an LRU cache keeps only recent entries, and a WeakMap lets its keys be garbage collected."),
    M("A search box should query the server once the user stops typing for 300 ms. Which tool?",
      ["Throttle", "Debounce", "setInterval", "A WeakMap"], 1,
      "Debounce restarts its timer on every call and only fires after a quiet gap. Throttle would still fire during typing."),
    K("Write debounce(fn, ms) that delays fn until ms have passed with no new call, then calls it once with the latest arguments.",
      "function debounce(fn, ms) {\n  return (...args) => fn(...args);\n}",
      "function debounce(fn, ms) {\n  let timer;\n  return (...args) => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), ms);\n  };\n}",
      [T("(async () => { const got = []; const d = debounce(v => got.push(v), 10); d(1); d(2); d(3); await new Promise(r => setTimeout(r, 40)); return got; })()", [3]),
       T("(async () => { const got = []; const d = debounce(v => got.push(v), 5); d(\"a\"); await new Promise(r => setTimeout(r, 30)); d(\"b\"); await new Promise(r => setTimeout(r, 30)); return got; })()", ["a", "b"])],
      "Each call cancels the pending one, so only the last call in a burst survives."),
    K("Write class LRU(limit) with get(key) and set(key, value). When adding a key would exceed limit, evict the least recently used key. get returns undefined for a missing key and counts as a use.",
      "class LRU {\n  constructor(limit) { this.map = new Map(); }\n  get(k) { return this.map.get(k); }\n  set(k, v) { this.map.set(k, v); }\n}",
      "class LRU {\n  constructor(limit) { this.limit = limit; this.map = new Map(); }\n  get(k) {\n    if (!this.map.has(k)) return undefined;\n    const v = this.map.get(k);\n    this.map.delete(k);\n    this.map.set(k, v);\n    return v;\n  }\n  set(k, v) {\n    if (this.map.has(k)) this.map.delete(k);\n    this.map.set(k, v);\n    if (this.map.size > this.limit) this.map.delete(this.map.keys().next().value);\n  }\n}",
      [T("(() => { const c = new LRU(2); c.set(\"a\", 1); c.set(\"b\", 2); c.get(\"a\"); c.set(\"c\", 3); return [c.get(\"a\"), c.get(\"b\"), c.get(\"c\")]; })()", [1, None, 3]),
       T("(() => { const c = new LRU(1); c.set(\"x\", 1); c.set(\"x\", 2); return [c.get(\"x\"), c.map.size]; })()", [2, 1])],
      "A Map remembers insertion order, so delete then set moves a key to the newest end, and keys().next() is always the oldest."),
    O("Order how to find a memory leak in a page.",
      ["Take a heap snapshot", "Repeat the suspect action several times", "Take another snapshot", "Compare which objects keep growing", "Find what still references them"],
      "Growth across repeats points at the leak; the retainer path shows the listener, cache or closure keeping it alive."),
    M("You attach extra data to DOM nodes in a Map keyed by the node. The nodes are removed from the page. What happens?",
      ["They are collected normally", "The Map keeps them alive, a leak", "The Map throws", "The browser clears the Map"], 1,
      "A Map holds strong references. A WeakMap would let removed nodes be garbage collected along with their data."),
])

JE9 = L("Capstone: a tiny spreadsheet engine", KW + ["capstone", "project", "spreadsheet", "engine", "formulas", "dependencies", "cycles", "recalculate"], [
    C("The brief",
      "Build the core of a spreadsheet: cells hold numbers or formulas like =A1+B2*2, formulas reference other cells, results calculate in dependency order, and a cycle is reported instead of hanging. This combines your parser, graph search, topological order and caching."),
    K("Step 1. Write refsOf(formula) returning the unique cell references in a formula string, uppercase, in first-seen order. A reference is one or more letters followed by digits, like A1 or bc12. Anything that is not a string starting with = has none.",
      "function refsOf(formula) {\n  return formula.match(/[A-Z]+\\d+/g);\n}",
      "function refsOf(formula) {\n  if (typeof formula !== \"string\" || !formula.startsWith(\"=\")) return [];\n  const found = formula.slice(1).match(/[A-Za-z]+\\d+/g) || [];\n  return [...new Set(found.map(r => r.toUpperCase()))];\n}",
      [T("refsOf(\"=A1+b2*A1\")", ["A1", "B2"]), T("refsOf(\"42\")", []), T("refsOf(\"=3*4\")", []), T("refsOf(5)", [])],
      "Normalising case and deduping now means the graph never has two nodes for one cell."),
    K("Step 2. Write evaluateSheet(cells) where cells maps names to numbers or formula strings. Formulas use + - * / and parentheses with numbers and cell names; empty or missing cells count as 0. Return an object with every given cell's value, using \"#CYCLE\" for any cell in a cycle or depending on one.",
      "function evaluateSheet(cells) {\n  return cells;\n}",
      "function evaluateSheet(cells) {\n  const norm = {};\n  for (const [k, v] of Object.entries(cells)) norm[k.toUpperCase()] = v;\n  const out = {}, state = {};\n  function value(name) {\n    if (state[name] === \"done\") {\n      if (out[name] === \"#CYCLE\") throw new Error(\"#CYCLE\");\n      return out[name];\n    }\n    if (state[name] === \"active\") throw new Error(\"#CYCLE\");\n    state[name] = \"active\";\n    let v;\n    try {\n      const raw = norm[name];\n      if (raw === undefined || raw === \"\") v = 0;\n      else if (typeof raw === \"number\") v = raw;\n      else if (String(raw).startsWith(\"=\")) v = calc(String(raw).slice(1));\n      else v = Number(raw);\n    } catch (e) {\n      state[name] = \"done\";\n      out[name] = \"#CYCLE\";\n      throw e;\n    }\n    state[name] = \"done\";\n    out[name] = v;\n    return v;\n  }\n  function calc(src) {\n    const t = src.match(/\\d+(\\.\\d+)?|[A-Za-z]+\\d+|[-+*\\/()]/g) || [];\n    let i = 0;\n    const expr = () => { let v = term(); while (t[i] === \"+\" || t[i] === \"-\") v = t[i++] === \"+\" ? v + term() : v - term(); return v; };\n    const term = () => { let v = factor(); while (t[i] === \"*\" || t[i] === \"/\") v = t[i++] === \"*\" ? v * factor() : v / factor(); return v; };\n    const factor = () => {\n      const tok = t[i++];\n      if (tok === \"-\") return -factor();\n      if (tok === \"(\") { const v = expr(); i++; return v; }\n      if (/^[A-Za-z]/.test(tok)) return value(tok.toUpperCase());\n      return Number(tok);\n    };\n    return expr();\n  }\n  const result = {};\n  for (const name of Object.keys(norm)) {\n    try { result[name] = value(name); } catch (e) { result[name] = \"#CYCLE\"; }\n  }\n  return result;\n}",
      [T("evaluateSheet({ A1: 2, B1: \"=A1*3\", C1: \"=A1+B1\" })", {"A1": 2, "B1": 6, "C1": 8}),
       T("evaluateSheet({ A1: \"=B1+1\", B1: \"=A1+1\", C1: 5 })", {"A1": "#CYCLE", "B1": "#CYCLE", "C1": 5}),
       T("evaluateSheet({ A1: \"=Z9+4\" })", {"A1": 4}),
       T("evaluateSheet({ A1: \"=(1+2)*-B1\", B1: 2 })", {"A1": -6, "B1": 2}),
       T("evaluateSheet({ A1: \"=B1\", B1: \"=B1\", C1: \"=A1+1\" })", {"A1": "#CYCLE", "B1": "#CYCLE", "C1": "#CYCLE"})],
      "Evaluating on demand with active and done marks is a depth-first topological order with cycle detection built in. Each cell is computed once."),
    M("A user edits A1 in a sheet of 100,000 cells. What should recalculation touch?",
      ["Every cell, top to bottom", "Only A1", "A1 and the cells that depend on it, directly or indirectly, in dependency order", "Cells near A1 on screen"], 2,
      "Real engines keep the reverse graph (who depends on me) and recompute only that downstream set, in topological order."),
    O("Order what your engine does for one formula cell.",
      ["Mark the cell active", "Tokenize and parse its formula", "Evaluate each referenced cell first", "Combine the values", "Mark it done and cache the result"],
      "Hitting an active cell during step 3 means the formula depends on itself: a cycle."),
    C("What you can do now",
      "You built a parser, a dependency graph, cycle detection and caching into one working engine. Those same parts power build tools, reactive frameworks and databases. You are writing the kind of code other code runs on."),
])

COURSES = [
    course("js-intermediate", "JavaScript patterns", "Intermediate", "JavaScript that holds up", "core-js", "JavaScript", 55,
           "Destructuring, Map and Set, sorting, regex, safe numbers, errors, classes, pure functions.",
           [("Data in motion", [JI1, JI2, JI3]), ("Text, numbers, errors", [JI4, JI5, JI6]), ("Programs with shape", [JI7, JI8, JI9])], "code"),
    course("js-advanced", "Advanced JavaScript", "Advanced", "JavaScript under the hood", "js-intermediate", "JavaScript patterns", 85,
           "Event loop, promise combinators, retries, higher-order functions, generators, this, immutability, recursion.",
           [("Async for real", [JA1, JA2, JA3]), ("Functions as tools", [JA4, JA5, JA6]), ("Robust data", [JA7, JA8, JA9])], "code"),
    course("js-expert", "JavaScript engineering", "Expert", "JavaScript engineering", "js-advanced", "Advanced JavaScript", 85,
           "Complexity, graphs, dynamic programming, parsers, state machines, reactivity, testing, performance.",
           [("Algorithms that scale", [JE1, JE2, JE3]), ("Building tools", [JE4, JE5, JE6]), ("Production code", [JE7, JE8, JE9])], "code"),
]


def add(courses, picks):
    courses.extend(COURSES)
