"""Website design ladder: Intermediate, Advanced and Expert courses that
follow "Websites that work" (site-design). Build steps grow the same
Workshop site as the web ladder, so every check targets classes these
lessons introduce (.hero, .prose, .callout, .benefits, .plan and so on)
and never fights earlier work. Contrast, size and spacing checks measure
the rendered preview. Research and strategy work uses write steps.
Rebuild with: python3 build_library.py
"""
from ladder_kit import (C, W, M, O, B, L, N, NEED, WR, course, has, count, attr, css, html, style, none, rx,
                        confirm, contrast, at_most, text_max, px, words, must, avoid, max_sentence, lines,
                        changed, self_check)

KW = ["design", "website", "web", "ux"]

# =====================================================================
# Intermediate: Websites people use
# =====================================================================

DI1 = L("Spacing with a scale", KW + ["spacing", "scale", "rhythm", "whitespace", "padding", "layout", "tokens"], [
    C("Pick five numbers, use only those",
      "Random spacing (13px here, 22px there) is the most common reason a page looks amateur. Pick a short scale, such as 4, 8, 16, 24, 32, 48 and 64 pixels, and use nothing else. Related things sit close together; unrelated groups get more space between them. That is the proximity principle doing the layout for you."),
    M("A card has 8px between its heading and text, and 8px between it and the next card. What reads wrong?",
      ["Nothing, consistent is good", "The cards blur together because the gap between groups equals the gap inside a group", "8px is too large", "Headings need no space"], 1,
      "Space between groups must be larger than space inside a group, or the eye cannot tell where one group ends."),
    N("Your base unit is 8px and the scale steps are 1, 2, 3, 4 and 6 times the base. How many pixels is the step-6 space?", 48,
      "6 times 8 is 48. Every space on the page is now a multiple of 8, which is why it looks deliberate.",
      gen={"vars": {"b": [4, 8, 4], "k": [3, 6, 1]}, "answer": "b*k", "round": 0,
           "prompt": "Your base unit is {b}px. How many pixels is a space of {k} units?", "explain": "{k} times {b} is {A}. Every space is a multiple of the base."}),
    O("Order these gaps from smallest to largest on a well spaced page.",
      ["Between a label and its input", "Between paragraphs in one section", "Between a section heading and the section above it", "Between two page sections"],
      "Each level of grouping gets a bigger gap. The ladder of spaces is what makes structure visible without lines or boxes."),
    B("Add a spacing scale to your site. In your CSS, declare at least three custom properties named --space-something on :root, then wrap one part of your page in a section with class section and give it top and bottom padding of at least 32px using your scale.",
      "<section class=\"section\">\n  <h2>Why Casa Verde</h2>\n  <p>Weeknight recipes that work the first time.</p>\n</section>\n\n/* CSS */\n:root {\n  --space-1: 8px;\n  --space-2: 16px;\n  --space-3: 24px;\n  --space-4: 32px;\n  --space-6: 48px;\n}\n.section { padding-block: var(--space-6); }\n.section h2 { margin-bottom: var(--space-2); }",
      "One scale, used everywhere. From now on every margin and padding you add can be a var(--space-n).",
      [css("--space-", "Spacing custom properties declared in your CSS"),
       css("var(--space-", "Your CSS uses the scale with var(--space-...)"),
       has("section.section", "A section with class section"),
       px("section.section", "paddingTop", "The section has at least 32px top padding", lo=32),
       px("section.section", "paddingBottom", "The section has at least 32px bottom padding", lo=32)]),
    C("Whitespace is not wasted space",
      "Generous space around the most important element makes it more noticeable, not less. When a page feels cluttered, the fix is usually to remove things and add space, not to shrink everything."),
])

DI2 = L("Text people can read", KW + ["typography", "readability", "line", "length", "measure", "line-height", "font", "size"], [
    C("Three numbers decide readability",
      "Body text needs a comfortable size (16px is the usual floor on screens), a line height around 1.4 to 1.6 times the font size, and a line length of roughly 45 to 75 characters. Long lines make the eye lose its place when jumping back; tight lines make paragraphs look like a wall."),
    N("Body text is 18px with line-height 1.5. How many pixels tall is each line?", 27,
      "18 times 1.5 is 27px. Unitless line-height scales with the font, which is why it is the safe choice.",
      gen={"vars": {"f": [16, 20, 1]}, "answer": "f*1.5", "round": 1,
           "prompt": "Body text is {f}px with line-height 1.5. How many pixels tall is each line?", "explain": "{f} times 1.5 is {A}px."}),
    M("Which CSS limits a paragraph to a readable line length whatever the screen width?",
      ["width: 100%", "max-width: 65ch", "font-size: 2vw", "text-align: justify"], 1,
      "The ch unit is about the width of one character, so 65ch caps the line near 65 characters and still shrinks on narrow screens."),
    M("Why prefer a unitless line-height (1.5) over a fixed one (24px)?",
      ["It loads faster", "It scales with each element's own font size, so headings and small text stay proportional", "Browsers ignore px line heights", "It is required for accessibility"], 1,
      "A fixed 24px is fine for 16px text and cramped for a 40px heading. A ratio adjusts itself."),
    B("Make your main reading text comfortable. Wrap your longest text in an element with class prose. Give .prose a max-width between 30em and 75ch (no wider than 760px), body text of at least 16px, and a line-height of at least 1.4.",
      "<div class=\"prose\">\n  <p>Casa Verde started as a notebook of dinners that worked on a Tuesday...</p>\n  <p>Every recipe is tested twice before it goes up.</p>\n</div>\n\n/* CSS */\n.prose {\n  max-width: 65ch;\n  font-size: 1.125rem;\n  line-height: 1.6;\n}",
      "Your text now reads like a book page instead of a banner. Most of a site's value is in its text, so this is the cheapest big upgrade there is.",
      [has(".prose p", "A .prose block with at least one paragraph"),
       px(".prose", "maxWidth", "The .prose line length is capped (max-width between 240px and 760px)", lo=240, hi=760,
          hint="Use max-width in ch or em, for example max-width: 65ch. A width in % or vw does not cap the line."),
       px(".prose p", "fontSize", "Body text at least 16px", lo=16),
       px(".prose p", "lineHeight", "Line height at least 1.4 times a 16px font (22px or more)", lo=22,
          hint="Set line-height: 1.5 (no unit) on .prose. The browser default is usually too tight.")]),
    O("Order the decisions for a page's body text.",
      ["Choose a readable typeface at 16px or more", "Set line-height around 1.5", "Cap the line length near 65 characters", "Check it on a phone and a wide screen"],
      "Size first, because line height and line length both depend on it. Then check at both extremes."),
    C("Contrast with restraint",
      "Two typefaces is plenty: one for headings, one for text, or one family in two weights. Hierarchy comes from size, weight and space far more than from new fonts."),
])

DI3 = L("Color that passes", KW + ["color", "contrast", "wcag", "accessibility", "palette", "ratio", "buttons"], [
    C("Contrast is a number, not a vibe",
      "WCAG, the web's accessibility standard, measures text contrast as a ratio from 1:1 (invisible) to 21:1 (black on white). Level AA asks for at least 4.5:1 for normal text and 3:1 for large text (about 24px, or about 19px bold). Light gray text on white usually fails, and so do many brand colors used as button backgrounds with white text."),
    M("Your button is white text on a light orange. A contrast checker says 2.6:1. What is the fix that keeps the brand?",
      ["Make the text bigger", "Darken the orange until white text reaches 4.5:1, or use dark text on the light orange", "Add a shadow", "Nothing, buttons are exempt"], 1,
      "Buttons are text and need 4.5:1 too. Darkening the shade or switching to dark text keeps the hue."),
    M("Which statement about color and meaning is right?",
      ["Red text alone is enough to mark an error", "Color should never be the only way information is shown; add an icon or words", "Green means success in every culture", "Color-blind users see in black and white"], 1,
      "About 1 in 12 men has some form of color vision deficiency. Pair color with text or a symbol so nobody misses the meaning."),
    O("Order a quick palette check.",
      ["Pick a text color and a background", "Measure the contrast ratio", "Adjust lightness until it reaches 4.5:1 for body text", "Repeat for buttons, links and text on images"],
      "Every text and background pair is its own check. One passing pair says nothing about the others."),
    B("Add a highlighted callout and make it pass. Add an element with class callout that has a colored background (not white) and text, and a link or button inside it with class btn-primary that has its own background color. Both must reach 4.5:1 contrast; Prexis measures the real colors in your preview.",
      "<aside class=\"callout\">\n  <p>New this week: five dinners under 30 minutes.</p>\n  <a class=\"btn-primary\" href=\"#recipes\">See the recipes</a>\n</aside>\n\n/* CSS */\n.callout {\n  background: #fff4d6;\n  color: #3b2f00;\n  padding: var(--space-3, 24px);\n  border-radius: 8px;\n}\n.btn-primary {\n  background: #1f5f3a;\n  color: #ffffff;\n  padding: 12px 20px;\n  border-radius: 6px;\n  text-decoration: none;\n  display: inline-block;\n}",
      "You now measure color instead of guessing. Run the same check on every new pair you add.",
      [has(".callout", "A .callout element"),
       style(".callout", "backgroundColor", "The callout has a background color", **{"not": "rgba(0, 0, 0, 0)"}),
       contrast(".callout p, .callout", 4.5, "Callout text reaches 4.5:1", hint="Darken the text or lighten the background. Very pale text on a pale tint is the usual failure."),
       has(".callout .btn-primary", "A .btn-primary inside the callout"),
       style(".btn-primary", "backgroundColor", "The primary button has its own background", **{"not": "rgba(0, 0, 0, 0)"}),
       contrast(".btn-primary", 4.5, "Every .btn-primary reaches 4.5:1", hint="White text needs a dark background. Try a deeper shade of your brand color.")]),
    C("Design the palette in roles",
      "Name colors by job, not by hue: text, muted text, surface, accent, danger. Then a rebrand changes one value per role, and every pair you already checked stays checkable."),
])

DI4 = L("A hero that explains itself", KW + ["hero", "headline", "homepage", "cta", "value", "proposition", "above", "fold"], [
    C("Five seconds to answer three questions",
      "A visitor landing on your homepage needs to know what this is, who it is for, and what to do next, fast. The hero (the first screen) answers with a specific headline, one supporting sentence, and one primary action. Clever slogans that need decoding lose people who are skimming."),
    M("Which headline works best for a recipe site?",
      ["Welcome to Casa Verde", "Taste the difference", "Weeknight dinners that work the first time", "Innovative culinary solutions"], 2,
      "It says what you get and hints at who it is for. The others could belong to any site."),
    M("The hero has three equally loud buttons: Sign up, Learn more, Contact. What is the problem?",
      ["Too few buttons", "No clear next step: when everything is primary, nothing is", "Buttons should be links", "Contact should come first"], 1,
      "One primary action, styled loudest. Secondary options can exist, quieter."),
    O("Order a hero's content from top to bottom.",
      ["A specific headline", "One sentence that supports it", "The primary action", "A quieter secondary link or proof"],
      "Read order follows importance. The action comes after the reason to take it."),
    B("Build a hero. Add a section with class hero containing an h1 of 70 characters or fewer, a p that supports it, and exactly one link or button with class btn-primary. A secondary action is fine if it has class btn-secondary instead.",
      "<section class=\"hero\">\n  <h1>Weeknight dinners that work the first time</h1>\n  <p>Tested recipes, 30 minutes or less, with a shopping list you can send to your phone.</p>\n  <a class=\"btn-primary\" href=\"#recipes\">Browse recipes</a>\n  <a class=\"btn-secondary\" href=\"#about\">How we test</a>\n</section>\n\n/* CSS */\n.hero { padding-block: var(--space-6, 48px); }\n.hero h1 { font-size: 2.5rem; line-height: 1.1; max-width: 20ch; }\n.btn-secondary { color: #1f5f3a; }",
      "A hero that answers what, who and what next. Everything else on the page now supports one clear action.",
      [has("section.hero", "A section with class hero"),
       text_max(".hero h1", 70, "A hero h1 of 70 characters or fewer", hint="Shorten the headline to one specific promise. Move details into the supporting sentence."),
       has(".hero p", "A supporting sentence"),
       at_most(".hero .btn-primary", 1, "Exactly one .btn-primary in the hero", hint="Keep one primary action. Give any other button the class btn-secondary."),
       contrast(".hero h1", 4.5, "The headline is readable against its background")]),
    C("Test it on a stranger",
      "Show the hero to someone for five seconds, hide it, and ask what the site offers and what they would click. If they cannot say, the headline is not done."),
])

DI5 = L("Navigation people understand", KW + ["navigation", "nav", "menu", "information", "labels", "aria-current", "links"], [
    C("Labels people would use",
      "Navigation should use the words your visitors use, not your internal names. Keep the top menu short; a handful of clear choices is easier to scan than a dozen. Show where people are, with a visible style and aria-current=\"page\" on the current link so screen readers announce it too."),
    M("Which menu label is clearest for a bakery?",
      ["Solutions", "Our Offerings", "Order a cake", "Explore"], 2,
      "It names the task people came to do. Vague labels make people click to find out what they mean."),
    M("What does aria-current=\"page\" do?",
      ["Bolds the link", "Tells assistive technology which link is the page you are on", "Makes the link open in a new tab", "Hides the link"], 1,
      "It adds meaning, not looks. Style it with a selector like [aria-current=\"page\"] so sighted users see the same thing."),
    O("Order how to design a site's navigation.",
      ["List the tasks visitors come to do", "Group them and name each group in visitors' words", "Keep the top level to a few items", "Mark the current page clearly"],
      "Tasks first, then labels. Menus designed from the org chart mirror the company, not the visitor."),
    B("Tidy your navigation. Your nav needs between 2 and 7 links, one of them marked aria-current=\"page\", and a CSS rule that styles [aria-current] so the current page is visible.",
      "<nav aria-label=\"Main\">\n  <a href=\"index.html\" aria-current=\"page\">Recipes</a>\n  <a href=\"plans.html\">Meal plans</a>\n  <a href=\"about.html\">How we test</a>\n</nav>\n\n/* CSS */\nnav a[aria-current=\"page\"] {\n  font-weight: 700;\n  text-decoration: underline;\n  text-underline-offset: 4px;\n}",
      "A short, plainly labeled menu that says where you are. That alone fixes a large share of the \"I couldn't find it\" complaints sites get.",
      [has("nav", "A nav element"),
       at_most("nav a", 7, "Between 2 and 7 links in your nav", at_least=2, hint="Move rarer links into the footer. The top menu is for the main tasks."),
       has("nav a[aria-current=\"page\"]", "One nav link marked aria-current=\"page\""),
       css("aria-current", "A CSS rule styles the current link")]),
    C("Footers are navigation too",
      "People who reach the bottom are looking for something: contact, policies, the full list of pages. A tidy footer catches them. It is the right home for links that are important but not frequent."),
])

DI6 = L("Forms people finish", KW + ["forms", "inputs", "labels", "autocomplete", "validation", "signup", "fields"], [
    C("Every field costs you people",
      "Each extra field is another reason to quit. Ask only for what you need now. Give every input a visible label (placeholders vanish as you type), the right type so phones show the right keyboard, and autocomplete so browsers can fill it in."),
    M("Why is placeholder text a poor replacement for a label?",
      ["It is too small", "It disappears as soon as you type, so people forget what the field was for, and many screen readers treat it inconsistently", "It cannot be styled", "It is not valid HTML"], 1,
      "A real label stays visible and is announced reliably. Use the placeholder for an example at most."),
    M("Which input gives phone users the right keyboard for an email address?",
      ["<input type=\"text\">", "<input type=\"email\">", "<input type=\"string\">", "<input inputmode=\"none\">"], 1,
      "type=\"email\" brings up a keyboard with @ and validates the basic shape for free."),
    O("Order a good error experience when a field is wrong.",
      ["Let the person finish typing", "Check the value when they leave the field or submit", "Show a specific message next to the field", "Keep everything they already typed"],
      "Do not shout while people are still typing, and never wipe the form. Say what is wrong and how to fix it."),
    B("Build a short signup form. Add a form with class signup containing an email input with a label whose for matches the input id, type=\"email\", autocomplete=\"email\" and required, and a button with type=\"submit\". Keep it to 3 inputs or fewer.",
      "<form class=\"signup\">\n  <label for=\"signup-email\">Email</label>\n  <input id=\"signup-email\" name=\"email\" type=\"email\" autocomplete=\"email\" required>\n  <button type=\"submit\" class=\"btn-primary\">Get the weekly recipes</button>\n</form>\n\n/* CSS */\n.signup { display: grid; gap: var(--space-1, 8px); max-width: 28rem; }\n.signup input { font-size: 1rem; padding: 10px 12px; }",
      "One field, one clear button, a label that stays, and a browser that can fill it in. That is about as short as a form gets.",
      [has("form.signup", "A form with class signup"),
       has("form.signup input[type=\"email\"][autocomplete=\"email\"][required]", "An email input with type, autocomplete and required"),
       has("form.signup label[for]", "A label with a for attribute"),
       rx("for=\"([\\w-]+)\"[\\s\\S]*id=\"\\1\"|id=\"([\\w-]+)\"[\\s\\S]*for=\"\\2\"", "The label's for matches an input's id",
          hint="Give the input an id, for example id=\"signup-email\", and put the same value in the label's for attribute."),
       has("form.signup button[type=\"submit\"]", "A submit button"),
       at_most("form.signup input", 3, "Three inputs or fewer")]),
    C("Say what happens next",
      "The button text should finish the sentence \"I want to...\": \"Get the weekly recipes\" beats \"Submit\". After submitting, confirm what happened and when to expect the next step."),
])

DI7 = L("Proof people believe", KW + ["trust", "testimonials", "social", "proof", "reviews", "credibility", "quotes"], [
    C("Specific beats glowing",
      "\"Great service!\" persuades nobody. A testimonial works when it is specific (what problem, what result), attributed (a real name and context), and placed next to the claim it supports. Logos, numbers and guarantees work the same way: concrete and checkable."),
    M("Which testimonial is most convincing?",
      ["\"Amazing! Five stars!\" (Anonymous)", "\"Best site ever.\" (J.)", "\"I cook three of these a week now. The shopping list alone saves me a trip.\" (Priya N., nurse, Leeds)", "\"We are the leading recipe platform.\" (Casa Verde team)"], 2,
      "It is specific, sounds like a person, and has a name and context. The last one is a claim, not proof."),
    M("Where should a testimonial about speed go?",
      ["In the footer", "On a separate testimonials page", "Next to the claim that the recipes take 30 minutes", "In a pop-up"], 2,
      "Proof works at the moment of doubt, right next to the claim it backs up."),
    O("Order how to collect a usable testimonial.",
      ["Ask a real user after they got a result", "Ask what they were struggling with before", "Ask what changed", "Get permission to use their name and context"],
      "Asking about before and after produces specifics. Permission makes it honest and usable."),
    B("Add a testimonial. Use a figure with class testimonial containing a blockquote of at least 60 characters and a figcaption with the person's name.",
      "<figure class=\"testimonial\">\n  <blockquote>I cook three of these a week now. The shopping list alone saves me a trip to the store.</blockquote>\n  <figcaption>Priya N., nurse, Leeds</figcaption>\n</figure>\n\n/* CSS */\n.testimonial { margin: 0; padding: var(--space-3, 24px); border-left: 4px solid #1f5f3a; }\n.testimonial blockquote { margin: 0 0 var(--space-1, 8px); font-size: 1.125rem; }",
      "The right elements (figure, blockquote, figcaption) tie the quote to its source for every reader, including screen readers.",
      [has("figure.testimonial blockquote", "A figure.testimonial with a blockquote"),
       {"sel": "figure.testimonial blockquote", "textMin": 60, "label": "The quote is specific (60 characters or more)"},
       has("figure.testimonial figcaption", "A figcaption naming the person"),
       contrast("figure.testimonial blockquote", 4.5, "The quote is readable")]),
    C("Never invent proof",
      "Made-up reviews are dishonest and in many places illegal under consumer protection law. If you have no testimonials yet, use what is true: how you test, a guarantee, or a free sample."),
])

DI8 = L("Thumbs, not cursors", KW + ["mobile", "touch", "tap", "targets", "responsive", "thumb", "phone"], [
    C("Design for the thumb",
      "On phones, people tap with a thumb, not a precise cursor. WCAG 2.2 asks for targets of at least 24 by 24 CSS pixels (level AA) and recommends 44 by 44 (level AAA), which matches long-standing platform guidance from Apple. Keep tappable things apart so a near miss does not hit the neighbor."),
    M("Two 30px icons sit 2px apart. What is the risk?",
      ["None, 30px is big enough", "Misses hit the neighbor; size and spacing both matter", "Icons cannot be tapped", "They will overflow"], 1,
      "Even passable sizes fail if targets touch. Give them space or merge them into a bigger control."),
    N("A button's text is 20px tall and it has 12px padding top and bottom. How tall is the tap target in px?", 44,
      "20 + 12 + 12 = 44px, right at the comfortable size. Padding is the easy way to grow a target without growing the text.",
      gen={"vars": {"t": [16, 24, 2], "p": [8, 16, 2]}, "answer": "t+2*p", "round": 0,
           "prompt": "A button's text is {t}px tall with {p}px padding top and bottom. How tall is the tap target in px?", "explain": "{t} + {p} + {p} = {A}px."}),
    O("Order a quick mobile check of a page.",
      ["Open it at phone width", "Try every button and link with a thumb", "Look for text you must zoom to read", "Check nothing scrolls sideways"],
      "Real thumbs on a real phone find problems a desktop resize misses."),
    B("Make your primary buttons thumb sized. Give every .btn-primary display: inline-block (or block, flex or inline-flex) and a min-height of at least 44px, and add a @media rule for narrow screens.",
      "/* CSS */\n.btn-primary {\n  display: inline-flex;\n  align-items: center;\n  min-height: 44px;\n  padding: 0 20px;\n}\n@media (max-width: 600px) {\n  .btn-primary { width: 100%; justify-content: center; }\n}",
      "Your main action is now easy to hit with a thumb, and it stretches full width on phones where that helps.",
      [has(".btn-primary", "A .btn-primary on the page"),
       px(".btn-primary", "minHeight", "Every .btn-primary is at least 44px tall (min-height)", lo=44, every=True,
          hint="Inline links ignore height. Add display: inline-flex or inline-block, then min-height: 44px."),
       style(".btn-primary", "display", "No .btn-primary is display: inline", every=True, **{"not": "inline"},
             hint="A link is inline by default, so its height is ignored. Give .btn-primary display: inline-flex or inline-block."),
       css("@media", "A @media rule for narrow screens")]),
    C("Reachability",
      "The bottom of a phone screen is easier to reach than the top corners. Apps put key actions in bottom bars for this reason. On a long page, repeat the primary action near the bottom so nobody scrolls back up to act."),
])

DI9 = L("Capstone: a landing page that works", KW + ["capstone", "landing", "page", "conversion", "redesign", "project"], [
    C("The brief",
      "Turn your site into a landing page that would survive a real launch. Everything here comes from this course: a hero with one action, benefits people can scan, proof, a short form, readable text, passing contrast and thumb sized targets."),
    M("You have room for one more element above the form. Which helps most?",
      ["An animated background", "A specific testimonial that answers the main doubt", "A second headline", "Social media icons"], 1,
      "Proof at the point of decision removes the last reason to hesitate."),
    O("Order the sections of a classic landing page.",
      ["Hero with the main promise and action", "Benefits that back the promise", "Proof from real people", "The form or final action"],
      "Promise, reasons, proof, action. Each section answers the doubt the previous one raised."),
    B("Assemble the landing page. It needs: a .hero with a short h1 and one .btn-primary; a section with class benefits holding at least three items with class benefit, each with an h3; a figure.testimonial; your form.signup; a .prose block; and contrast and size that pass.",
      "<section class=\"benefits\">\n  <div class=\"benefit\"><h3>30 minutes or less</h3><p>Every recipe is timed by a tester.</p></div>\n  <div class=\"benefit\"><h3>One shopping list</h3><p>Send it to your phone in one tap.</p></div>\n  <div class=\"benefit\"><h3>Tested twice</h3><p>Two cooks, two kitchens, before it goes up.</p></div>\n</section>\n\n/* CSS */\n.benefits { display: grid; gap: var(--space-3, 24px); grid-template-columns: repeat(auto-fit, minmax(14rem, 1fr)); }",
      "A complete, honest landing page: clear promise, scannable reasons, real proof, an easy action, and text everyone can read.",
      [text_max(".hero h1", 70, "Hero headline of 70 characters or fewer"),
       at_most(".hero .btn-primary", 1, "One primary action in the hero"),
       count(".benefits .benefit h3", 3, "Three or more benefits, each with an h3"),
       has("figure.testimonial figcaption", "A testimonial with a named source"),
       has("form.signup input[type=\"email\"][required]", "The signup form"),
       px(".prose", "maxWidth", "Readable line length in .prose", lo=240, hi=760),
       contrast(".btn-primary", 4.5, "Primary buttons pass 4.5:1"),
       px(".btn-primary", "minHeight", "Every primary button is at least 44px tall", lo=44, every=True)]),
    WR("Write the one-sentence brief you would give a designer for this page: who it is for, what it promises, and the one action you want.",
       [words(12, 45), must("\\bfor\\b", "Says who it is for (use the word for)"), must("\\b(sign ?up|join|buy|book|subscribe|order|download|start|get|browse|try)\\b", "Names the one action"),
        self_check("A stranger could tell what this page is for from this sentence alone")],
       "A landing page for busy parents who cook on weeknights, promising tested 30-minute dinners, with one action: sign up for the weekly recipe email.",
       "A one-sentence brief keeps every later decision honest: anything that does not serve the audience, the promise or the action can go."),
    C("What you can do now",
      "You can take a page from vague to working: hierarchy, readable type, measured contrast, clear navigation, a short form, believable proof and mobile-ready targets. That is the craft most sites skip."),
])

# =====================================================================
# Advanced: Design with evidence
# =====================================================================

DA1 = L("Interviews that do not lead", KW + ["research", "interviews", "users", "questions", "discovery", "bias"], [
    C("Ask about the past, not the future",
      "People are poor at predicting what they would do and good at describing what they did. Ask about the last time something happened (\"Tell me about the last time you planned dinner\"), not hypotheticals (\"Would you use an app that...?\"). Avoid questions that suggest the answer you want."),
    M("Which question is leading?",
      ["Tell me about the last time you cooked on a weeknight.", "What was hard about it?", "Don't you think a shopping list feature would be useful?", "What did you do next?"], 2,
      "It suggests the answer and asks for an opinion about your idea. People are polite and will say yes."),
    M("A participant says \"I would definitely pay for that.\" How much weight should that get?",
      ["A lot, they said definitely", "Little; stated future intent is a weak signal compared with what people already do and pay for", "None, never listen to users", "It proves the market"], 1,
      "Past behavior (what they already spend time or money on) is far stronger evidence than a polite prediction."),
    O("Order a good interview.",
      ["Explain the purpose and that there are no wrong answers", "Ask about a recent real example", "Follow up with why and what happened next", "Ask what they tried before", "Thank them and note quotes right away"],
      "Warm up, go concrete, dig, then capture. Notes written an hour later lose the exact words that matter."),
    WR("Rewrite these leading questions into neutral ones about past behavior. Keep one question per line.",
       [lines(3, "Three questions, one per line"), changed(), avoid("\\b(would you|don't you|wouldn't you|do you like|isn't it|love)\\b", "No hypothetical or leading phrases (would you, don't you, love...)"),
        must("\\b(last time|recently|tell me about|walk me through|what happened)\\b", "At least one question anchors on a real past event")],
       "Tell me about the last time you planned a weeknight dinner.\nWhat was the hardest part of that?\nWhat have you tried to make it easier?",
       "Neutral questions about real events get stories, and stories show the problems worth solving.",
       starter="Would you use an app that plans your dinners?\nDon't you hate grocery shopping?\nWould you love a feature that sends a shopping list to your phone?"),
    C("Synthesize, then decide",
      "After five or six interviews, write each observation on its own note and group them. Patterns that show up across several people are findings; a single vivid story is an anecdote to check."),
])

DA2 = L("Usability tests on a budget", KW + ["usability", "testing", "tasks", "success", "rate", "observation", "think", "aloud"], [
    C("Watch, do not ask",
      "In a usability test you give someone a realistic task, ask them to think aloud, and watch where they hesitate. A widely cited heuristic from Nielsen Norman Group is that about five participants per round reveals most of the big problems; several small rounds with fixes in between beat one large study."),
    M("Which task scenario is best?",
      ["Click the Meal plans link", "Find the meal plans page", "You have 20 minutes and chicken in the fridge. Find something to cook tonight.", "Rate our navigation from 1 to 5"], 2,
      "It sets a real goal without naming the link. The first two give away the answer in the words they use."),
    N("7 of 10 participants completed the checkout task. What is the task success rate in percent?", 70,
      "7 divided by 10 is 70%. With small samples, treat this as a direction, not a precise number.",
      gen={"vars": {"s": [2, 9, 1]}, "answer": "s*10", "round": 0,
           "prompt": "{s} of 10 participants completed the task. What is the success rate in percent?", "explain": "{s} divided by 10 is {A}%."}),
    M("A participant is stuck for a minute. What should the facilitator do?",
      ["Point to the right button", "Ask \"What are you looking for?\" and let them keep trying", "End the test", "Explain how the site works"], 1,
      "Helping hides the problem you came to find. Prompt them to think aloud; step in only if they are truly stuck and note where."),
    O("Order a small usability round.",
      ["Write 3 to 5 realistic tasks", "Recruit about five people who match your visitors", "Run sessions and note where people struggle", "Rank problems by how many hit them and how badly", "Fix the worst and test again"],
      "Test, fix, retest. The second round tells you whether the fix worked."),
    WR("Write two task scenarios for testing your landing page. Each should give a goal and context but must not use the words on your buttons or links.",
       [lines(2, "Two scenarios, one per line"), words(20, 90), avoid("\\b(click|tap|press|button|link|menu)\\b", "No interface words (click, button, link, menu)"),
        self_check("Neither scenario uses the exact label of the thing you want them to find")],
       "You want easy dinners this week and you are happy to get an email about them. Set that up.\nYou have chicken and rice at home and 25 minutes. Find something to cook tonight.",
       "Scenarios that describe goals let you see whether people can find the path, instead of whether they can match words."),
])

DA3 = L("Funnels and the numbers behind them", KW + ["analytics", "funnel", "conversion", "rate", "drop-off", "events", "metrics"], [
    C("A funnel shows where people leave",
      "A funnel lists the steps to a goal (visit, view recipe, sign up) and how many people reach each. The biggest drop between two steps is usually the best place to look first. Rates are counts divided by the step before (step conversion) or by the first step (overall conversion)."),
    N("2,000 people visit, 500 open a recipe, 50 sign up. What is the overall conversion rate from visit to sign up, in percent?", 2.5,
      "50 divided by 2,000 is 0.025, or 2.5%.", tol=0.01,
      gen={"vars": {"v": [1000, 5000, 1000], "s": [20, 100, 10]}, "answer": "s/v*100", "round": 2,
           "prompt": "{v} people visit and {s} sign up. What is the overall conversion rate in percent?", "explain": "{s} divided by {v} is {A}%."}),
    N("Same funnel: of the 500 who opened a recipe, 50 signed up. What is that step's conversion rate in percent?", 10,
      "50 divided by 500 is 10%. Step rates show which step leaks, overall rates show the total effect."),
    M("Visits doubled this month but sign ups stayed flat. What is the most useful first question?",
      ["Is the site down?", "Where did the new visitors come from, and do they match the people who sign up?", "Should we redesign the form?", "Is analytics broken?"], 1,
      "New traffic from a different audience often converts worse. Segment by source before changing the design."),
    O("Order how to investigate a drop in sign ups.",
      ["Confirm the drop is real and not a tracking change", "Find which funnel step changed", "Segment by device and traffic source", "Watch sessions or test that step", "Form a hypothesis and test a fix"],
      "Check the measurement first. Many \"drops\" are a broken tag or a changed definition."),
    B("Tag your key actions for analytics. Give your hero's .btn-primary and your signup form's submit button a data-event attribute naming the action, for example data-event=\"hero_cta\" and data-event=\"signup_submit\". Use lowercase words joined by underscores.",
      "<a class=\"btn-primary\" href=\"#recipes\" data-event=\"hero_cta\">Browse recipes</a>\n...\n<button type=\"submit\" class=\"btn-primary\" data-event=\"signup_submit\">Get the weekly recipes</button>",
      "Named events let any analytics tool count the steps of your funnel. Consistent names now save a cleanup later.",
      [attr(".hero .btn-primary", "data-event", "The hero action has a data-event name", match="^[a-z]+(_[a-z]+)+$",
            hint="Use lowercase words joined by underscores, for example hero_cta."),
       attr("form.signup button[type=\"submit\"]", "data-event", "The signup submit has a data-event name", match="^[a-z]+(_[a-z]+)+$")]),
])

DA4 = L("A/B tests without fooling yourself", KW + ["ab", "testing", "experiment", "split", "lift", "significance", "sample"], [
    C("An experiment, not a vote",
      "An A/B test shows two versions to randomly split visitors and compares one metric chosen in advance. Small samples swing wildly by chance, so decide the sample size before starting, run until you reach it, and do not stop the moment the numbers look good. Stopping early on a lucky streak is called peeking, and it produces false wins."),
    N("Version A converts at 4%. Version B converts at 5%. What is B's relative lift over A, in percent?", 25,
      "The difference is 1 percentage point. Relative to A's 4%, that is 1 divided by 4 = 25%. Always say which one you mean.",
      gen={"vars": {"a": [2, 8, 1], "d": [1, 2, 1]}, "answer": "d/a*100", "round": 1,
           "prompt": "Version A converts at {a}%. Version B converts at {b}%. What is B's relative lift over A, in percent?",
           "show": {"b": "a+d"}, "explain": "The gap is {d} point(s). Divided by A's {a}%, that is {A}%."}),
    M("After two days B is ahead 12 sign ups to 7. What should you do?",
      ["Ship B, it is clearly better", "Keep running to the sample size you planned; numbers this small are easily chance", "Stop and restart", "Switch the metric"], 1,
      "With 19 events in total, a 12 to 7 split can easily happen by chance. Planned sample sizes protect you from yourself."),
    M("You test a new headline and check 15 different metrics. One improves. What is the risk?",
      ["None, a win is a win", "With many metrics, some will move by chance alone; pick the primary metric before the test", "Headlines cannot be tested", "The test was too short"], 1,
      "Check enough numbers and one will look significant by luck. That is why the primary metric is chosen first."),
    O("Order a trustworthy A/B test.",
      ["Write a hypothesis and pick one primary metric", "Estimate the sample size you need", "Split traffic randomly and run until you reach it", "Compare results once, at the end", "Ship the winner or learn from the loss"],
      "Every step before launch exists to stop you from reading meaning into noise later."),
    WR("Write a hypothesis for one test on your landing page in the form: If we change X, then metric Y will improve, because Z.",
       [must("\\bif\\b", "Starts from a change (If...)"), must("\\bthen\\b", "Predicts an outcome (then...)"), must("\\bbecause\\b", "Gives a reason (because...)"),
        words(15, 60), must("\\d|rate|sign ?ups?|clicks?|conversion", "Names a measurable metric")],
       "If we replace the generic \"Submit\" button with \"Get the weekly recipes\", then the signup conversion rate will rise, because people will know exactly what they are agreeing to.",
       "A reason turns a test into learning: even a loss tells you the reason was wrong."),
])

DA5 = L("Information architecture", KW + ["information", "architecture", "ia", "card", "sorting", "sitemap", "breadcrumbs", "structure"], [
    C("Structure people can predict",
      "Information architecture is how content is grouped and labeled so people can find it. Card sorting asks users to group topics themselves, showing their mental model. Tree testing checks whether people can find items in a proposed structure before you build it. Breadcrumbs show where a page sits in that structure."),
    M("Users keep looking for \"returns\" under Help, but it lives under Orders. What does that tell you?",
      ["Users are wrong", "Your structure does not match their mental model; move it or link it from both", "Delete the Help section", "Add a search box and stop there"], 1,
      "Put things where people look. Cross-links are fine when an item honestly belongs in two places."),
    M("What does a tree test measure?",
      ["Visual design", "Whether people can find items using only the structure and labels, without visual design", "Page speed", "SEO rankings"], 1,
      "Stripping the visuals isolates the structure, so you know the labels and grouping are the problem, not the colors."),
    O("Order an IA project.",
      ["Inventory the content you have", "Run a card sort with real users", "Draft a structure and labels", "Tree test the draft", "Build navigation and breadcrumbs from it"],
      "Know what you have, learn how people group it, then test before you build."),
    B("Add breadcrumbs to your page. Use a nav with aria-label=\"Breadcrumb\" containing an ol with at least two li items. Earlier items are links; the last item is the current page, marked aria-current=\"page\".",
      "<nav aria-label=\"Breadcrumb\" class=\"crumbs\">\n  <ol>\n    <li><a href=\"index.html\">Home</a></li>\n    <li><a href=\"recipes.html\">Recipes</a></li>\n    <li aria-current=\"page\">Lemon chicken</li>\n  </ol>\n</nav>\n\n/* CSS */\n.crumbs ol { display: flex; gap: 8px; list-style: none; padding: 0; }\n.crumbs li + li::before { content: \"/\"; margin-right: 8px; color: #666; }",
      "Breadcrumbs make the structure visible and give people a one-tap way up a level.",
      [has("nav[aria-label=\"Breadcrumb\"] ol", "A nav labeled Breadcrumb with an ordered list"),
       count("nav[aria-label=\"Breadcrumb\"] li", 2, "At least two breadcrumb items"),
       has("nav[aria-label=\"Breadcrumb\"] li a", "Earlier items are links"),
       has("nav[aria-label=\"Breadcrumb\"] [aria-current=\"page\"]", "The current page is marked aria-current=\"page\""),
       none("nav[aria-label=\"Breadcrumb\"] a[aria-current]", "The current page is not a link to itself",
            hint="Put aria-current=\"page\" on the last li and leave its text unlinked.")]),
    C("Labels are the interface",
      "Most navigation problems are label problems. Test labels with the words your users said in interviews; jargon that is obvious inside the company is noise to everyone else."),
])

DA6 = L("Accessible by design", KW + ["accessibility", "a11y", "focus", "keyboard", "motion", "reduced", "inclusive"], [
    C("Design decisions that include people",
      "Accessibility is mostly design, not code: visible keyboard focus, motion that can be turned off, links that look like links, and meaning not carried by color alone. WCAG requires a visible focus indicator (2.4.7), and operating systems let people ask for reduced motion, which CSS can read with prefers-reduced-motion."),
    M("A designer removes focus outlines because they look ugly. Who is hurt?",
      ["Nobody", "Keyboard users, who can no longer see where they are on the page", "Only mouse users", "Search engines"], 1,
      "Restyle focus to match the brand with :focus-visible, but never remove it."),
    M("What does @media (prefers-reduced-motion: reduce) let you do?",
      ["Speed up animations", "Tone down or remove motion for people who set that preference, for example people with vestibular disorders", "Block videos", "Detect slow phones"], 1,
      "Large moving effects can cause dizziness or nausea for some people. Respect the system setting."),
    O("Order a quick keyboard test of your page.",
      ["Put the mouse away", "Press Tab from the top of the page", "Check each focused item is clearly visible", "Check you can reach and use every control", "Check focus never gets stuck"],
      "If you cannot do it with Tab, Enter and Space, some of your visitors cannot do it at all."),
    B("Make your design accessible by default. Add a :focus-visible style with an outline, a @media (prefers-reduced-motion: reduce) block, and make links inside .prose underlined.",
      "/* CSS */\n:focus-visible {\n  outline: 3px solid #1f5f3a;\n  outline-offset: 2px;\n}\n@media (prefers-reduced-motion: reduce) {\n  * { animation-duration: 0.01ms !important; transition-duration: 0.01ms !important; scroll-behavior: auto !important; }\n}\n.prose a { text-decoration: underline; }\n\n<!-- HTML: a link inside your prose block -->\n<p>Read <a href=\"about.html\">how we test recipes</a>.</p>",
      "Focus you can see, motion you can switch off, links that look like links. These help everyone, not just people with disabilities.",
      [css(":focus-visible", "A :focus-visible rule"),
       css("outline", "Focus uses an outline"),
       css("prefers-reduced-motion", "A prefers-reduced-motion media query"),
       has(".prose a", "A link inside .prose"),
       style(".prose a", "textDecorationLine", "Links in .prose are underlined", equals="underline")]),
    C("Test with real assistive tech",
      "Automated checkers catch only part of the problems. Spend ten minutes with the screen reader built into your device (VoiceOver on Apple, TalkBack on Android, Narrator on Windows) and you will find issues no tool reports."),
])

DA7 = L("Components with every state", KW + ["components", "states", "buttons", "hover", "disabled", "loading", "focus", "ui"], [
    C("A component is all its states",
      "A button is not one picture. It is default, hover, focus, active, disabled and sometimes loading. Designing only the default leaves developers to guess the rest, and guesses are inconsistent. List the states for every component before calling it done."),
    M("Which state is most often forgotten, and hurts keyboard users most?",
      ["Hover", "Focus", "Default", "Active"], 1,
      "Hover gets designed because designers use a mouse. Focus is what keyboard users rely on to see where they are."),
    M("A disabled button gives no reason. What is better?",
      ["Hide the button", "Keep it enabled and explain what is missing when pressed, or show the reason next to it", "Make it red", "Remove the form"], 1,
      "Silent disabled buttons leave people stuck. Tell them what to fix."),
    O("Order the states a button moves through when someone submits a form.",
      ["Default", "Hover or focus", "Active (pressed)", "Loading", "Success or error message"],
      "Each state answers a question: can I press this, did it register, is it working, did it work."),
    B("Design every state of a .btn class. Add a button with classes btn and btn-primary, plus one disabled button with class btn. In CSS, style .btn:hover, .btn:focus-visible and .btn:disabled (for example lower opacity and cursor: not-allowed).",
      "<button class=\"btn btn-primary\" type=\"button\">Save recipe</button>\n<button class=\"btn\" type=\"button\" disabled>Saved</button>\n\n/* CSS */\n.btn { min-height: 44px; padding: 0 18px; border-radius: 6px; border: 2px solid #1f5f3a; background: #fff; color: #1f5f3a; }\n.btn:hover { background: #e8f3ec; }\n.btn:focus-visible { outline: 3px solid #1f5f3a; outline-offset: 2px; }\n.btn:disabled { opacity: 0.55; cursor: not-allowed; }",
      "Every state is designed, so the button behaves the same everywhere it appears.",
      [has("button.btn.btn-primary", "A button with classes btn and btn-primary"),
       has("button.btn[disabled]", "A disabled .btn"),
       css(".btn:hover", "A .btn:hover style"),
       css(".btn:focus-visible", "A .btn:focus-visible style"),
       css(".btn:disabled", "A .btn:disabled style"),
       style("button.btn[disabled]", "cursor", "Disabled buttons show cursor: not-allowed", equals="not-allowed")]),
    C("Document as you go",
      "Write the states down where developers will see them: a short page listing each component, its states and when to use it. That page is the start of a design system."),
])

DA8 = L("Empty, error and loading states", KW + ["empty", "states", "errors", "messages", "microcopy", "loading", "content", "design"], [
    C("The screens nobody designs",
      "A new account has no data. A search finds nothing. A network call fails. These moments decide whether people stay. A good empty state explains what will appear and gives one action to start. A good error message says what happened, why if known, and what to do, in plain words."),
    M("Which error message is best?",
      ["Error 422", "Something went wrong.", "That card was declined by your bank. Try another card or contact your bank.", "Invalid input!!!"], 2,
      "It says what happened, who can fix it and what to do next, without blame or codes."),
    M("A search returns no results. What should the page show?",
      ["A blank page", "\"0 results\" only", "What was searched, a suggestion (check spelling, fewer words) and popular links", "An error icon"], 2,
      "Turn the dead end into a next step."),
    O("Order the parts of a good error message.",
      ["What happened", "Why, if you know", "What the person can do now", "A way to get help if that fails"],
      "Plain facts, then the fix. Leave apologies short and blame out entirely."),
    B("Add an empty state. Create an element with class empty-state containing an h3, a p of explanation, and one link or button with class btn-primary. Mark a status region for messages with role=\"status\".",
      "<div class=\"empty-state\">\n  <h3>No saved recipes yet</h3>\n  <p>Tap the heart on any recipe and it will wait for you here.</p>\n  <a class=\"btn-primary\" href=\"#recipes\">Find a recipe</a>\n</div>\n<p role=\"status\" class=\"status\"></p>",
      "An empty screen that teaches and invites, and a status region screen readers will announce when you put a message in it.",
      [has(".empty-state h3", "An empty state with a heading"),
       has(".empty-state p", "An explanation"),
       at_most(".empty-state .btn-primary", 1, "Exactly one primary action"),
       has("[role=\"status\"]", "A role=\"status\" region for messages")]),
    WR("Rewrite this error message so it says what happened and what to do. Keep it under 30 words.",
       [changed(), words(6, 30), avoid("\\b(error|invalid|failed|oops)\\b", "No jargon like error, invalid or failed"),
        must("\\b(try|check|use|enter|contact|choose|add)\\b", "Tells the person what to do next")],
       "We could not find that email address. Check the spelling, or create a new account with it.",
       "Plain words and a next step turn a dead end into a path. Notice the rewrite never blames the reader.",
       starter="Error: invalid user. Authentication failed (code 401)."),
])

DA9 = L("Capstone: a pricing page", KW + ["capstone", "pricing", "plans", "comparison", "faq", "conversion", "project"], [
    C("The brief",
      "Design a pricing section people can decide from in under a minute. Three plans at most, one recommended, prices and the main differences easy to compare, an action per plan, and answers to the questions that stop people from paying. The plans here are an example for practice, not real pricing advice."),
    M("Why highlight one plan as recommended?",
      ["To hide the others", "It reduces choice overload by giving a sensible default for most people", "It is required by law", "It makes the page longer"], 1,
      "A clear default helps people decide. It must be honestly the best fit for most visitors."),
    M("Which detail most often stops people at a pricing page?",
      ["The font", "Unclear terms: what happens after a trial, how to cancel, whether the price is per month or per year", "The number of plans", "The page color"], 1,
      "Uncertainty blocks payment. Answer the cancel and billing questions right there."),
    O("Order a pricing card's content.",
      ["Plan name and who it is for", "Price with its period (per month or per year)", "The few features that differ", "The action button"],
      "People compare names and prices first, then differences. The button comes after the reason."),
    B("Build the pricing section. Add a section with class pricing holding 2 or 3 elements with class plan. Each plan needs a heading, an element with class price, and a .btn-primary or .btn. Mark exactly one plan with class featured and include a visible label inside it, for example a span with class badge. Add at least two details elements (with summary) answering common questions.",
      "<section class=\"pricing\">\n  <div class=\"plan\"><h3>Free</h3><p class=\"price\">$0 <small>per month</small></p><a class=\"btn\" href=\"#signup\">Start free</a></div>\n  <div class=\"plan featured\"><span class=\"badge\">Most popular</span><h3>Home cook</h3><p class=\"price\">$4 <small>per month</small></p><a class=\"btn-primary\" href=\"#signup\">Choose Home cook</a></div>\n  <div class=\"plan\"><h3>Family</h3><p class=\"price\">$7 <small>per month</small></p><a class=\"btn\" href=\"#signup\">Choose Family</a></div>\n</section>\n<details><summary>Can I cancel anytime?</summary><p>Yes, in one click from your account page.</p></details>\n<details><summary>Is there a free trial?</summary><p>The Free plan never expires.</p></details>\n\n/* CSS */\n.pricing { display: grid; gap: 16px; grid-template-columns: repeat(auto-fit, minmax(14rem, 1fr)); }\n.plan { border: 1px solid #ccc; border-radius: 8px; padding: 20px; }\n.plan.featured { border: 2px solid #1f5f3a; }",
      "A pricing section with a clear default, comparable prices and the doubts answered in place. That is most of what makes people comfortable paying.",
      [at_most(".pricing .plan", 3, "Two or three plans", at_least=2),
       at_most(".pricing .plan.featured", 1, "Exactly one featured plan"),
       has(".plan.featured .badge", "A visible label in the featured plan"),
       count(".pricing .plan .price", 2, "Each plan shows a price"),
       count(".pricing .plan :is(h2, h3, h4)", 2, "Each plan has a heading"),
       count(".pricing .plan :is(.btn-primary, .btn)", 2, "Each plan has an action"),
       count("details summary", 2, "Two or more FAQ items with details and summary"),
       contrast(".pricing .btn-primary", 4.5, "Primary actions pass 4.5:1")]),
    WR("Write the FAQ answer for \"What happens when my trial ends?\" Be specific and calm, in 40 words or fewer.",
       [words(8, 40), must("\\b(charge|bill|pay|free|cancel|remind|email)", "Says what happens with billing"),
        avoid("\\b(simply|just|easy|obviously)\\b", "No minimizing words (simply, just, easy, obviously)")],
       "Nothing is charged without warning. We email you 3 days before the trial ends. If you do nothing, your plan renews at $4 per month; cancel in one click before then and you pay nothing.",
       "Specific, calm answers to billing questions build the trust that makes people comfortable paying."),
    C("What you can do now",
      "You can find out what people need, test whether your design delivers it, measure the result honestly, and design the components and pages that convert. That is evidence-led design."),
])

# =====================================================================
# Expert: Design systems and strategy
# =====================================================================

DE1 = L("Tokens in tiers", KW + ["design", "system", "tokens", "semantic", "theming", "dark", "mode", "variables"], [
    C("Primitives, meanings, components",
      "Mature design systems layer their tokens. Primitive tokens are raw values (--green-700: #1f5f3a). Semantic tokens give them a job (--color-action: var(--green-700)). Components use only semantic tokens. To add a dark theme or rebrand, you remap the semantic layer and no component changes."),
    M("A button uses var(--green-700) directly. What breaks when you add a dark theme?",
      ["Nothing", "You must hunt down every component that used the primitive, because nothing says what the green was for", "The button disappears", "CSS variables do not work in dark mode"], 1,
      "Components bound to primitives cannot be re-themed by role. Bind them to semantic names instead."),
    M("Which token name is semantic?",
      ["--blue-500", "--size-16", "--color-text-muted", "--hex-1f5f3a"], 2,
      "It names the job (muted text), so it can point at a different primitive per theme."),
    O("Order how to introduce theming to an existing site.",
      ["Collect the raw colors in use as primitive tokens", "Define semantic tokens that point at primitives", "Replace raw values in components with semantic tokens", "Add a dark theme by remapping only the semantic tokens"],
      "Each layer depends on the one before. The payoff, a one-block dark theme, comes last."),
    B("Tier your tokens. In :root, declare at least two primitive color tokens and at least two semantic tokens named --color-something that use var() to point at primitives. Use a semantic token for body text or background. Then add @media (prefers-color-scheme: dark) that remaps the semantic tokens only.",
      "/* CSS */\n:root {\n  --green-700: #1f5f3a;\n  --gray-950: #141414;\n  --gray-50: #fafaf7;\n  --color-text: var(--gray-950);\n  --color-surface: var(--gray-50);\n  --color-action: var(--green-700);\n}\n@media (prefers-color-scheme: dark) {\n  :root {\n    --color-text: var(--gray-50);\n    --color-surface: var(--gray-950);\n  }\n}\nbody { color: var(--color-text); background: var(--color-surface); }",
      "One remap block themes the whole site. Components never learn which theme they are in.",
      [css("prefers-color-scheme: dark", "A prefers-color-scheme: dark block"),
       {"cssContains": "--color-", "label": "Semantic tokens named --color-..."},
       css(": var(--", "Tokens that point at other tokens with var()",
           hint="Semantic tokens should reference primitives, for example --color-text: var(--gray-950);"),
       css("var(--color-", "Your styles use the semantic tokens")]),
    C("Name for intent, version for change",
      "When a design system is shared across teams, treat token names as an API: add new ones freely, rename rarely, and announce removals ahead of time with a deprecation period."),
])

DE2 = L("Fluid type and container queries", KW + ["fluid", "typography", "clamp", "container", "queries", "responsive", "components"], [
    C("Respond to the space, not just the screen",
      "clamp(min, preferred, max) lets a size grow smoothly with the viewport within limits, so headings scale without a pile of breakpoints. Container queries let a component respond to the width of its own container, so the same card works in a sidebar and in a wide grid."),
    M("What does font-size: clamp(1.75rem, 1rem + 3vw, 3rem) do?",
      ["Always 3rem", "Grows with the viewport but never below 1.75rem or above 3rem", "Shrinks as the screen grows", "Only works on phones"], 1,
      "The middle value tracks the viewport; the outer values are floor and ceiling."),
    M("Why use a container query instead of a media query for a card?",
      ["Media queries are deprecated", "The card's layout should depend on how wide its slot is, which differs by page, not on the window", "Container queries are faster", "Cards cannot use media queries"], 1,
      "The same card can sit in a narrow column on a wide screen. Only the container knows the real space."),
    N("A heading uses clamp(24px, 4vw, 48px). How many px is it on a 900px wide viewport?", 36,
      "4vw of 900px is 36px, which is between 24 and 48, so 36px applies.",
      gen={"vars": {"w": [400, 1400, 100]}, "answer": "min(48, max(24, w*0.04))", "round": 1,
           "prompt": "A heading uses clamp(24px, 4vw, 48px). How many px is it on a {w}px wide viewport?", "explain": "4vw of {w}px, kept between 24 and 48, gives {A}px."}),
    B("Make your hero headline fluid and your benefits respond to their container. Use clamp() for .hero h1 font-size, set container-type: inline-size on .benefits, and add an @container rule that changes the .benefit layout.",
      "/* CSS */\n.hero h1 { font-size: clamp(1.75rem, 1rem + 3vw, 3rem); }\n.benefits { container-type: inline-size; }\n@container (min-width: 40rem) {\n  .benefit { display: grid; grid-template-columns: auto 1fr; gap: 12px; }\n}",
      "Type scales without breakpoints and components adapt to wherever they are placed.",
      [css("clamp(", "A clamp() size"),
       px(".hero h1", "fontSize", "The hero headline renders at 24px or more", lo=24),
       css("container-type", "A container-type declaration"),
       css("@container", "An @container rule"),
       has(".benefits .benefit", "Your .benefits section from the Intermediate capstone",
           hint="Add a section with class benefits holding items with class benefit (see Capstone: a landing page that works).")]),
    O("Order how to make a component responsive the modern way.",
      ["Give its wrapper container-type: inline-size", "Design the narrow layout as the default", "Add @container rules for wider slots", "Use clamp() for sizes that should scale smoothly"],
      "Narrow first, then enhance as space allows.",
      groups=[[2, 3]], note="Container rules and clamp() sizes are independent, so either can come third."),
])

DE3 = L("Performance as a design constraint", KW + ["performance", "core", "web", "vitals", "lcp", "cls", "inp", "speed", "images"], [
    C("Three numbers Google publishes",
      "Core Web Vitals measure loading, responsiveness and visual stability. Google's published thresholds for a good experience are Largest Contentful Paint at or under 2.5 seconds, Interaction to Next Paint at or under 200 milliseconds, and Cumulative Layout Shift at or under 0.1, measured at the 75th percentile of real visits. Design choices (huge hero images, web fonts, late-loading banners) move these numbers more than code tweaks."),
    M("A cookie banner slides in after load and pushes the page down. Which metric suffers?",
      ["LCP", "INP", "CLS", "None"], 2,
      "Content moving after it appears is layout shift. Reserve the space or overlay the banner instead."),
    M("Which design change most reliably improves LCP on a page with a big hero photo?",
      ["Adding more fonts", "Serving a properly sized, compressed hero image and not lazy-loading it", "Lazy-loading the hero image", "Adding a carousel"], 1,
      "The hero is usually the largest element. Make it small in bytes and load it first; lazy-loading it delays it."),
    M("Of 100 sampled page loads, 80 have LCP at or under 2.5 s. Does the page meet the good LCP threshold at the 75th percentile?",
      ["Yes, at least 75% of loads are at or under 2.5 s", "No, every load must be under 2.5 s", "No, the average must be under 1 s", "It cannot be known from this"], 0,
      "The 75th percentile is good when at least 75% of loads are good. 80% are, so it passes."),
    B("Stop your images from shifting the layout. Make sure there is at least one image below your hero (an https image URL works). Every img on your page needs width and height attributes, and every image outside the hero needs loading=\"lazy\".",
      "<img src=\"https://picsum.photos/id/292/800/450\" width=\"800\" height=\"450\" alt=\"Ingredients on a table\">\n<img src=\"https://picsum.photos/id/429/600/400\" width=\"600\" height=\"400\" loading=\"lazy\" alt=\"A finished dish\">",
      "With dimensions the browser reserves space before the image arrives, so nothing jumps. Lazy loading keeps offscreen images from competing with the hero.",
      [has("img", "At least one image on the page"),
       attr("img", "width", "Every image has a width", every=True, match="^\\d+$"),
       attr("img", "height", "Every image has a height", every=True, match="^\\d+$"),
       none(".hero img[loading=\"lazy\"]", "The hero image is not lazy-loaded",
            hint="Lazy-loading the largest image delays LCP. Keep loading=\"lazy\" for images further down."),
       attr("img:not(.hero img)", "loading", "Images outside the hero use loading=\"lazy\"", every=True, match="^lazy$")]),
    O("Order a performance budget for a new page.",
      ["Agree target numbers (for example LCP at or under 2.5 s)", "Set a byte budget for images, fonts and scripts", "Design within it and check as you go", "Measure real visits after launch"],
      "A budget agreed before design is far cheaper than shaving bytes after launch."),
])

DE4 = L("Jobs to be done and positioning", KW + ["strategy", "jobs", "positioning", "value", "proposition", "competitors", "product"], [
    C("People hire products for a job",
      "Jobs to be done frames demand as progress people want in a situation: \"When I get home tired on a weeknight, I want dinner sorted fast, so I can rest.\" The real competition is whatever people do today for that job, often not a direct rival. Positioning states who you are for, the job, and why you beat the alternative they use now."),
    M("For a weeknight recipe site, what is often the strongest competitor?",
      ["Other recipe sites only", "Takeout, frozen meals and cooking the same three dishes", "Cookbooks from the 1990s", "Social networks"], 1,
      "People compare you with what they already do for the job. Design and messaging must beat that habit."),
    M("Which is a job statement rather than a feature?",
      ["Has a shopping list button", "When I'm planning the week, I want to buy everything in one trip, so I don't waste evenings", "Uses a modern design", "Loads in 2 seconds"], 1,
      "It names the situation, the motivation and the outcome. Features are only means to that end."),
    O("Order the parts of a positioning statement.",
      ["For (the specific audience)", "Who (the job or problem)", "Our product is (the category)", "That (the key benefit)", "Unlike (the main alternative)"],
      "This classic template forces you to name both the audience and the real alternative."),
    WR("Write a positioning statement for your site using the template: For [audience] who [job], [product] is a [category] that [benefit]. Unlike [alternative], it [difference].",
       [must("^\\s*for\\b", "Starts with For"), must("\\bwho\\b", "Names the job with who"), must("\\bthat\\b", "States the benefit with that"),
        must("\\bunlike\\b", "Names the alternative with unlike"), words(25, 80),
        self_check("The alternative is what people really do today, not just a direct competitor")],
       "For working parents who need dinner sorted on weeknights, Casa Verde is a recipe site that gets a tested meal on the table in 30 minutes. Unlike takeout, it costs less and you know what is in it.",
       "A precise positioning statement settles arguments about headlines, features and visuals: does this help this audience get this job done better than their alternative?"),
    C("Let positioning drive the page",
      "Your hero headline is the benefit. Your benefits section is the difference from the alternative. Your proof shows people like the audience getting the job done. A page that follows its positioning rarely needs a redesign; it needs better evidence."),
])

DE5 = L("Metrics that matter", KW + ["metrics", "north", "star", "guardrails", "goodhart", "retention", "cohorts", "measurement"], [
    C("One goal, a few guardrails",
      "A north star metric captures the value users get (for a recipe site, perhaps recipes cooked per week, not page views). Guardrail metrics stop you from winning the wrong way: unsubscribes, complaints, page speed. Goodhart's law warns that when a measure becomes a target, people find ways to move it that stop it meaning anything."),
    M("A team is rewarded for time on site. Which design change games it?",
      ["Faster recipe search", "Hiding the ingredient list behind extra clicks", "A clearer shopping list", "Bigger buttons"], 1,
      "Making people work harder increases time on site while making the product worse. That is Goodhart's law in action."),
    N("Of 400 people who signed up in March, 120 cooked a recipe in their fourth week. What is week-4 retention for the March cohort, in percent?", 30,
      "120 divided by 400 is 30%. Cohorts compare like with like: people who started at the same time.",
      gen={"vars": {"n": [200, 1000, 100], "r": [10, 50, 5]}, "answer": "r", "round": 0, "show": {"k": "n*r/100"},
           "prompt": "Of {n} people who signed up in March, {k} were active in week 4. What is week-4 retention, in percent?", "explain": "{k} divided by {n} is {A}%."}),
    M("Why measure retention by cohort instead of total active users?",
      ["It is simpler", "Totals can grow from new sign ups even while each group of users drifts away faster", "Cohorts are required by analytics tools", "Totals are always wrong"], 1,
      "A growing total can hide a leaking bucket. Cohorts show whether people keep getting value."),
    WR("Define a north star metric for your site and two guardrail metrics. Put each on its own line, starting with North star:, Guardrail:, Guardrail:.",
       [must("north star\\s*:", "A line starting North star:"), must("guardrail\\s*:[\\s\\S]*guardrail\\s*:", "Two Guardrail: lines"), lines(3, "Three lines"),
        avoid("north star\\s*:[^\\n]*(page ?views|visits|time on site|sessions)", "The north star is not a raw traffic number"),
        self_check("The north star measures value a user got, not attention you captured")],
       "North star: recipes marked as cooked per active user per week\nGuardrail: email unsubscribe rate\nGuardrail: median page load time on phones",
       "A value-based north star with guardrails keeps the team honest: you can only win by helping people."),
    O("Order how to choose a product metric.",
      ["Describe the value users get in words", "Find a behavior that shows they got it", "Make it a countable metric", "Add guardrails for the ways it could be gamed", "Review it after a few months"],
      "Words first. Teams that start from what is easy to count end up optimizing what is easy, not what matters."),
])

DE6 = L("Design for every language", KW + ["internationalization", "i18n", "localization", "language", "rtl", "logical", "properties", "inclusive"], [
    C("Text grows, direction flips",
      "Translated text is often longer than English (German and Finnish labels can be much longer), and Arabic and Hebrew read right to left. Designs that fit English exactly will break. Leave room for text to grow, avoid text baked into images, and use CSS logical properties (margin-inline-start instead of margin-left) so layouts flip correctly with dir=\"rtl\"."),
    M("Why use padding-inline-start instead of padding-left?",
      ["It is shorter", "It follows the text direction, so in right-to-left languages it becomes the right side automatically", "padding-left is deprecated", "It is faster"], 1,
      "Logical properties map to start and end of the text flow, not to fixed physical sides."),
    M("A quote in Spanish appears on an English page. What markup helps screen readers pronounce it correctly?",
      ["<i>", "lang=\"es\" on the element containing the quote", "translate=\"no\"", "A Spanish font"], 1,
      "WCAG 3.1.2 asks you to mark changes of language so assistive technology switches pronunciation."),
    O("Order the steps to make a page ready for translation.",
      ["Move all text out of images", "Leave room for text to grow in buttons and labels", "Switch physical CSS sides to logical properties", "Mark the page and any passages with lang", "Test with a long language and a right-to-left one"],
      "Each step removes one way translation breaks the layout. The final test proves it.",
      groups=[[0, 1, 2, 3]], note="The first four fixes are independent; do them in any order, then test last."),
    B("Make your page translation ready. Add a short passage in another language marked with a lang attribute (for example a quote with lang=\"es\"), and use at least one CSS logical property such as margin-inline, padding-inline-start or inset-inline-start.",
      "<blockquote lang=\"es\">Cocinar en casa es más fácil de lo que parece.</blockquote>\n\n/* CSS */\n.benefit { padding-inline-start: var(--space-2, 16px); border-inline-start: 4px solid var(--color-action, #1f5f3a); }",
      "Marked language changes and direction-aware spacing. The page is ready for a right-to-left version without a rewrite.",
      [has("[lang]:not(html)", "An element with a lang attribute"),
       attr("[lang]:not(html)", "lang", "The lang value is a language code", match="^[a-z]{2,3}(-[A-Za-z0-9]{2,8})*$"),
       {"cssContains": "-inline", "label": "A CSS logical property (for example padding-inline-start)"}]),
    C("Localization is more than words",
      "Dates, numbers, currencies, names and addresses vary by region. Let the platform format them (Intl in JavaScript) and design forms that accept names and addresses that do not look like yours."),
])

DE7 = L("Critique and handoff", KW + ["critique", "feedback", "handoff", "review", "collaboration", "specs", "developers"], [
    C("Critique the work against the goal",
      "Useful critique starts from the goal and the audience, describes what you observe, and asks questions before prescribing fixes. \"I like it\" and \"make it pop\" help nobody. Handoff is the same discipline aimed at developers: every state, spacing and token named, edge cases listed, and decisions explained so they are not re-litigated in code."),
    M("Which piece of feedback is most useful?",
      ["I don't love the green.", "Make it pop more.", "The goal is sign ups, but my eye lands on the logo first; could the headline or button be the strongest element?", "Looks great!"], 2,
      "It ties an observation to the goal and invites a solution instead of dictating one."),
    M("What most often goes missing in a design handoff?",
      ["The logo", "Empty, error, loading and long-content states", "The brand color", "The page title"], 1,
      "The happy path is always designed. Edge states are where developers have to guess."),
    O("Order a design critique session.",
      ["The designer states the goal and the audience", "Reviewers look silently for a few minutes", "Reviewers share observations tied to the goal", "The designer asks clarifying questions", "Agree next steps and owners"],
      "Starting from the goal keeps the session about outcomes, not taste."),
    WR("Write critique for this hero, aimed at its goal of email sign ups. Headline: \"Innovation in every bite\". Three equal buttons: Sign up, Learn more, Our story. Use three lines: one observation, one question, one suggestion.",
       [lines(3, "Three lines"), must("\\?", "At least one question"), avoid("\\b(i (don't )?like|ugly|pretty|pop)\\b", "No taste words (I like, ugly, pretty, pop)"),
        must("\\b(goal|sign ?ups?|signup|email)\\b", "Ties the feedback to the sign up goal")],
       "Observation: the headline does not say what the site offers, and three equal buttons compete for attention.\nQuestion: which single action matters most for the sign up goal?\nSuggestion: try a specific headline about weeknight dinners and make Sign up the only primary button.",
       "Observation, question, suggestion, tied to the goal: critique the designer can act on without feeling judged."),
    C("Write decisions down",
      "A short decision log (what we chose, why, what we rejected) saves weeks. When someone asks in six months why the button is green, the answer is a link, not a meeting."),
])

DE8 = L("Dark patterns and design ethics", KW + ["ethics", "dark", "patterns", "deceptive", "consent", "manipulation", "trust"], [
    C("Persuasion versus manipulation",
      "Dark patterns are designs that trick people into choices they would not make knowingly: hiding the cancel path, pre-ticked add-ons, shaming decline buttons (\"No thanks, I hate saving money\"), fake countdown timers. They can lift a metric briefly while destroying trust, and regulators in several regions treat many of them as unlawful. Good design makes the honest choice the easy one."),
    M("Signing up takes one click but cancelling needs a phone call during office hours. What is this pattern often called?",
      ["A funnel", "A roach motel: easy to get in, hard to get out", "Progressive disclosure", "A guardrail"], 1,
      "Cancellation should be about as easy as sign up. Many regulators now say so explicitly."),
    M("Which is honest persuasion rather than a dark pattern?",
      ["A timer that resets on every visit", "A pre-ticked box adding insurance to the cart", "A clear comparison table with the recommended plan highlighted", "A decline link styled as tiny gray text"], 2,
      "Highlighting a genuinely good default with full information helps people decide. The others hide or pressure."),
    O("Order an ethics check for a new flow.",
      ["Write down what the user is agreeing to", "Check the honest choice is as easy as the business choice", "Remove pressure that is not true (fake scarcity, false urgency)", "Ask: would we be comfortable if users saw how this works?"],
      "If explaining the design to users would embarrass you, it is a dark pattern."),
    WR("Rewrite this confirmshaming pop-up so both choices are respectful and clear.",
       [changed(), avoid("\\b(hate|stupid|lose out|miss out|regret|i don't want to)\\b", "No shaming or guilt words"),
        must("\\bno thanks\\b|\\bnot now\\b|\\bmaybe later\\b|\\bno,? thank you\\b", "A plain, neutral decline option"), words(8, 40)],
       "Get one tested weeknight recipe by email every Friday.\n[Subscribe]   [No thanks]",
       "Respectful choices keep the people who say yes for the right reasons, and the people who say no will come back.",
       starter="Get our weekly recipes!\n[Yes, I want to eat better]   [No, I hate delicious food]"),
    C("Ethics is a design skill",
      "Every metric you are asked to move can be moved honestly or dishonestly. Naming the dark pattern in a review, with a better alternative ready, is one of the most valuable things a senior designer does."),
])

DE9 = L("Capstone: ship a design system page", KW + ["capstone", "design", "system", "audit", "project", "launch", "tokens"], [
    C("The brief",
      "Bring the whole ladder together into a page you could hand to a team: tiered tokens with a dark theme, fluid type, responsive components, accessibility defaults, stable images, marked language changes, and evidence from real people. Prexis checks the page; you confirm the research you ran outside it."),
    M("A stakeholder asks for a fake \"Only 2 left!\" badge to lift sign ups. Your best response?",
      ["Add it, metrics matter", "Decline and offer an honest alternative, such as a real testimonial or a clearer benefit, and test that", "Add it only on mobile", "Add it and remove it later"], 1,
      "Offer a better, honest lever and evidence. That is the senior move."),
    O("Order a design release.",
      ["Audit the current page against the goal", "Run a small usability round", "Fix the worst problems with system components", "Check accessibility and performance budgets", "Ship and watch the north star and guardrails"],
      "Evidence, then fixes, then quality gates, then measurement."),
    B("Ship the system page. Your site needs: semantic --color tokens with a prefers-color-scheme: dark remap; a clamp() hero headline; a container query; a :focus-visible style and a prefers-reduced-motion block; every img with width and height; a passage marked with lang; a .hero with one .btn-primary that passes contrast; and confirm the research you ran.",
      "Use your work from this course and the Intermediate and Advanced courses.",
      "Tokens, fluid layout, accessibility, performance and evidence in one page. You can now lead design, not just do it.",
      [css("var(--color-", "Components use semantic tokens"),
       css("prefers-color-scheme: dark", "A dark theme remap"),
       css("clamp(", "Fluid type with clamp()"),
       css("@container", "A container query"),
       css(":focus-visible", "Visible focus"),
       css("prefers-reduced-motion", "Reduced motion respected"),
       attr("img", "width", "Every image has width", every=True, match="^\\d+$"),
       attr("img", "height", "Every image has height", every=True, match="^\\d+$"),
       has("[lang]:not(html)", "A language change marked with lang"),
       at_most(".hero .btn-primary", 1, "One primary action in the hero"),
       contrast(".hero .btn-primary", 4.5, "The hero action passes 4.5:1"),
       confirm("I ran a usability round with at least three people and fixed the worst problem"),
       confirm("I checked contrast in both light and dark themes")]),
    WR("Write a short release note for your team: what changed, the evidence behind it, and the metric you will watch. Under 80 words.",
       [words(25, 80), must("\\b(tested|interview|usability|participants?|users?|people)\\b", "Mentions the evidence"),
        must("\\b(metric|rate|retention|conversion|north star|guardrail|watch|measure)\\b", "Names what you will measure")],
       "We rebuilt the landing page on the new tokens with a dark theme. In a usability round, 4 of 5 people missed the old signup button, so the hero now has one primary action. We will watch the signup conversion rate and the unsubscribe guardrail for four weeks.",
       "Linking the change to evidence and to a metric is how design earns trust in a team."),
    C("What you can do now",
      "You can build and run a design system, ground decisions in research and metrics, design for every language and ability, and argue for the honest choice with evidence. That is design leadership."),
])

COURSES = [
    course("design-intermediate", "Web design in practice", "Intermediate", "Websites people use", "site-design", "Website design", 55,
           "Spacing, readable type, contrast, heroes, navigation, forms, proof, mobile targets.",
           [("Layout and type", [DI1, DI2, DI3]), ("Pages with a job", [DI4, DI5, DI6]), ("Trust and touch", [DI7, DI8, DI9])], "web"),
    course("design-advanced", "UX and conversion", "Advanced", "Design with evidence", "design-intermediate", "Web design in practice", 85,
           "Interviews, usability tests, funnels, A/B tests, information architecture, accessible design, component states.",
           [("Learn from people", [DA1, DA2, DA3]), ("Test and structure", [DA4, DA5, DA6]), ("Components and content", [DA7, DA8, DA9])], "web"),
    course("design-expert", "Product design", "Expert", "Design systems and strategy", "design-advanced", "UX and conversion", 85,
           "Tiered tokens, fluid layout, performance budgets, positioning, metrics, internationalization, critique, ethics.",
           [("Systems", [DE1, DE2, DE3]), ("Strategy", [DE4, DE5, DE6]), ("Leading design", [DE7, DE8, DE9])], "web"),
]


def add(courses, picks):
    courses.extend(COURSES)
