"""Money ladder: Intermediate, Advanced and Expert courses that follow
"Money that behaves" (money). Lessons teach general, well established
principles with worked problems, numeric problems that re-roll, sliders
and short written plans. Every figure is a labeled example, not a
statistic or a recommendation; tax and account rules differ by country,
so lessons describe how they generally work and point to official
sources for local details. Nothing here is personal financial advice.
Rebuild with: python3 build_library.py
"""
from ladder_kit import C, W, M, O, L, X, WR, NQ, course, words, must, avoid, lines

KW = ["money", "finance", "personal finance"]

NOTE = C("Examples, not advice",
         "Numbers in this course are made up examples chosen to make the math clear. Rules for taxes, accounts and benefits differ by country and change over time. Use the principles here, then check your local official sources or a qualified, independent adviser before acting on a specific decision.")

# =====================================================================
# Intermediate: Money with a plan
# =====================================================================

MOI1 = L("A budget that survives real life", KW + ["budget", "budgeting", "zero based", "spending plan", "categories"], [
    NOTE,
    C("Give every unit of income a job",
      "A budget is a plan for money before the month starts, not a record of where it went. Zero based budgeting assigns all expected income to categories (bills, food, savings, fun) until nothing is unassigned. Rules of thumb such as splitting take home pay roughly 50% needs, 30% wants and 20% savings and debt payments are starting points, not laws; the right split depends on your costs and goals."),
    W("A zero based month",
      "Example: take home pay 3,000. Fixed bills 1,450. Groceries 450. Transport 200.",
      ["Bills, groceries and transport: 1,450 + 450 + 200 = 2,100.",
       "Left to assign: 3,000 minus 2,100 = 900.",
       "Example assignments: 300 to the emergency fund, 250 to extra debt payments, 150 to irregular costs such as gifts and repairs, 200 to fun money.",
       "Unassigned: 0. Every unit has a job, including the fun."],
      "Income minus planned spending equals zero, with savings as a planned category."),
    NQ("Example: take home pay is {i}. Needs come to {n}. Using a 50/30/20 starting point, how much would go to savings and debt payments?",
       "20% of {i} is {A}. Needs at {n} are {np}% of income, so the split may need adjusting.",
       {"i": [2000, 6000, 250], "n": [900, 3500, 100]}, "i*0.2", {"i": 3000, "n": 1500}, rnd=2, show={"np": "n/i*100"}),
    M("You overspend on groceries most months. What is the most useful budget change?",
      ["Stop budgeting", "Raise the grocery category to what you actually spend and cut somewhere else, or find specific ways to spend less", "Ignore it", "Put groceries on a credit card"], 1,
      "A budget that ignores reality fails every month. Plan for real numbers, then decide what to change."),
    O("Set up a monthly budget, in order.",
      ["Write down expected take home income", "List fixed bills and their amounts", "Plan variable categories from recent real spending", "Assign what is left to savings, debt and fun until nothing is unassigned"],
      "Fixed costs first because they are not negotiable this month; savings get a planned amount, not whatever is left."),
    WR("Write a one month zero based plan for a real or example income. One category per line in the form Category: amount, with a Total: line that equals the income.",
       [lines(5, "At least four categories and a total"),
        must("^total:\\s*[\\d,.]+", "A Total: line", flags="im"),
        must("(sav|emergency|invest|debt)", "Includes savings or debt payments"),
        must("(fun|treat|personal|entertainment|eating out|hobbies)", "Includes some fun money", hint="Budgets with no fun tend to break. Plan a small amount."),
        words(10, 120)],
       "Rent and bills: 1,450\nGroceries: 450\nTransport: 200\nEmergency fund: 300\nExtra debt payment: 250\nIrregular costs: 150\nFun: 200\nTotal: 3,000",
       "A plan you will follow beats a perfect one you will not. Review it at the end of the month."),
])

MOI2 = L("Irregular costs and irregular income", KW + ["sinking funds", "irregular", "freelance", "variable income", "smoothing"], [
    C("Turn surprises into monthly costs",
      "Many money emergencies are predictable: car repairs, annual subscriptions, holidays, gifts. A sinking fund saves a little each month for a known future cost, so it arrives as a planned payment rather than a crisis. If your income varies, budget on a conservative baseline month, and hold a buffer so good months fund the lean ones."),
    W("Plan for an annual bill",
      "Example: car insurance of 840 is due in 7 months, and a holiday costing 1,200 is in 10 months.",
      ["Insurance: 840 / 7 = 120 a month.",
       "Holiday: 1,200 / 10 = 120 a month.",
       "Together: 240 a month into two labeled savings pots.",
       "When the bills arrive, the money is waiting and the regular budget is untouched."],
      "Divide the cost by the months until it is due."),
    NQ("Example: a cost of {c} is due in {m} months. How much do you set aside each month? (Two decimals.)",
       "{c} / {m} = {A}.",
       {"c": [300, 2400, 20], "m": [2, 12, 1]}, "c/m", {"c": 840, "m": 7}, rnd=2, tol=0.01),
    NQ("Example: a freelancer earned {a}, {b}, {c} and {d} in four months. Budgeting on the lowest month, what monthly baseline is that?",
       "The lowest of the four is {A}. Income above it goes first to the buffer.",
       {"a": [1500, 4000, 500], "b": [1500, 4000, 500], "c": [1500, 4000, 500], "d": [1500, 4000, 500]}, "min(a,b,c,d)", {"a": 3000, "b": 2000, "c": 3500, "d": 2500}, rnd=0),
    M("Which approach handles variable income most safely?",
      ["Budget on the best month", "Budget on a conservative month and keep a buffer so good months top it up", "Spend whatever arrives", "Borrow in lean months"], 1,
      "A low baseline means most months beat the plan. The buffer turns uneven income into a steady paycheck."),
    O("Set up sinking funds, in order.",
      ["List predictable irregular costs for the next year", "Estimate each cost and its due date", "Divide to get a monthly amount for each", "Automate transfers into labeled pots"],
      "Listing is the step that matters. Most people underestimate irregular costs until they write them down."),
    C("A buffer is not an emergency fund",
      "A buffer smooths normal ups and downs in income or spending. An emergency fund is for real shocks such as job loss. Keeping them separate stops the buffer from quietly eating the safety net."),
])

MOI3 = L("Paying off debt: avalanche and snowball", KW + ["debt", "avalanche", "snowball", "payoff", "interest", "credit card"], [
    C("Two orders for the same plan",
      "With several debts, pay the minimum on all of them and put every extra unit toward one target. The avalanche method targets the highest interest rate first, which costs the least interest overall. The snowball method targets the smallest balance first, which gives quick wins that keep many people going. Both work far better than spreading extra payments thinly."),
    W("Which goes first?",
      "Example debts: card A 1,200 at 24% a year; card B 3,000 at 18%; loan C 6,000 at 7%.",
      ["Avalanche order: A (24%), then B (18%), then C (7%).",
       "Snowball order: A (1,200), then B (3,000), then C (6,000).",
       "Here both start with card A, since it is the smallest and most expensive.",
       "When the orders differ, avalanche saves more interest; snowball may be easier to stick with."],
      "Highest rate first saves most; smallest balance first motivates most."),
    NQ("Example: a card balance of {b} at {r}% a year. About how much interest does it cost in one month, using rate divided by 12? (Two decimals.)",
       "{b} times {r}% / 12 = {A}.",
       {"b": [500, 6000, 250], "r": [12, 30, 1]}, "b*r/100/12", {"b": 3000, "r": 24}, rnd=2, tol=0.01),
    NQ("Example: you pay {p} a month on a {b} balance with no interest. How many months to clear it? (Round up.)",
       "{b} / {p}, rounded up, is {A} months. With interest it takes longer.",
       {"b": [600, 6000, 200], "p": [50, 400, 25]}, "ceil(b/p)", {"b": 3000, "p": 200}, rnd=0),
    X("Minimum payments stretch time",
      "Example: a 3,000 card balance at 24% a year (2% a month). Drag the monthly payment and see roughly how many months it takes to clear. Payments near the monthly interest of 60 take almost forever.",
      "-log(1-0.02*3000/x)/log(1.02)", "x", 70, 400, 10, "Monthly payment", "Months to pay off"),
    M("Debts are a 9% car loan and a 22% card. You have 200 extra each month. Avalanche says...",
      ["Split 100 and 100", "Pay minimums on both and put the 200 extra on the 22% card", "Put it on the car loan", "Save it instead, always"], 1,
      "The extra goes where interest is highest. Whether to also build savings first depends on your emergency fund, which is a separate decision."),
    O("Run a debt payoff plan, in order.",
      ["List every debt with balance, rate and minimum", "Choose avalanche or snowball", "Pay all minimums and put every extra unit on the target", "When the target is cleared, roll its payment into the next one"],
      "The roll over step is what makes payoff accelerate: each cleared debt frees more money for the next."),
])

MOI4 = L("Credit reports and scores", KW + ["credit score", "credit report", "utilization", "payment history", "credit"], [
    C("What lenders look at",
      "A credit report lists your accounts, balances and payment history. Scores summarize it; models differ by country and company, but the factors that matter most are broadly similar: paying on time, how much of your available credit you use (utilization), how long your accounts have been open, the mix of credit, and recent applications. You can usually check your report for free through official channels, and you should dispute errors."),
    M("Which habit most reliably helps a credit score over time?",
      ["Opening many new cards", "Paying every bill on time", "Carrying a balance to show activity", "Checking your own score often"], 1,
      "Payment history is among the most heavily weighted factors in common scoring models. Checking your own report does not hurt your score."),
    NQ("Example: your cards have limits of {a} and {b} and balances of {x} and {y}. What is your overall utilization, in percent? (One decimal.)",
       "({x} + {y}) / ({a} + {b}), times 100, is {A}%.",
       {"a": [1000, 5000, 500], "b": [1000, 8000, 500], "x": [0, 900, 100], "y": [0, 2000, 100]}, "(x+y)/(a+b)*100", {"a": 2000, "b": 3000, "x": 500, "y": 1000}, rnd=1),
    M("You carry no balance and pay in full monthly. Do you need to pay interest to build credit?",
      ["Yes, interest builds credit", "No. On time payments and low reported balances build credit without paying interest", "Only on store cards", "Only in the first year"], 1,
      "Carrying a balance costs interest and raises utilization. Using a card lightly and paying it in full is a common way to build history."),
    O("Check and fix your credit report, in order.",
      ["Get your report from an official free source", "Check every account and balance is yours and correct", "Dispute errors with the credit bureau and the lender", "Set up automatic payments so nothing is missed"],
      "Errors are common enough that checking at least once a year is worthwhile."),
    C("Beware of credit repair promises",
      "No one can legally remove accurate negative information from your report. Services that promise to wipe your record for a fee are a common scam. You can dispute real errors yourself for free."),
])

MOI5 = L("Interest rates: APR, APY and compounding", KW + ["apr", "apy", "interest rate", "compounding", "effective rate", "savings rate"], [
    C("Same rate, different words",
      "An annual percentage rate (APR) is a yearly rate before compounding. Annual percentage yield (APY), or effective annual rate, includes compounding: what you actually earn or pay over a year. With monthly compounding, APY = (1 + APR / 12) to the power 12, minus 1. Loans often advertise APR and savings accounts APY, so compare like with like. Some loan APRs also include fees, depending on local rules."),
    NQ("Example: an APR of {r}% compounded monthly. What is the APY, in percent? (Two decimals.)",
       "(1 + {r}% / 12) to the power 12, minus 1, is {A}%.",
       {"r": [2, 30, 1]}, "((1+r/1200)^12-1)*100", {"r": 24}, rnd=2, tol=0.01),
    W("Card versus savings",
      "Example: a card charges 24% APR monthly. A savings account pays 4% APY.",
      ["Card APY: (1.02) to the power 12, minus 1, about 26.8%.",
       "Savings: 4% already includes compounding.",
       "Every unit of card debt costs about 26.8% a year; every unit saved earns 4%.",
       "Paying off high interest debt is usually a much higher, guaranteed return than saving at a low rate, once you have a basic emergency buffer."],
      "Compare effective rates."),
    NQ("Example: {p} saved at {r}% APY for {y} years. What is it worth? (Round to whole units.)",
       "{p} times {g} to the power {y} is about {A}.",
       {"p": [1000, 10000, 1000], "r": [1, 6, 1], "y": [1, 10, 1]}, "p*(1+r/100)^y", {"p": 5000, "r": 4, "y": 5}, rnd=0, tol=1, show={"g": "1+r/100"}),
    M("Two savings accounts: 4.0% APR compounded daily or 4.05% APY. Which pays more?",
      ["The 4.0% APR compounded daily, slightly", "The 4.05% APY", "They are identical", "Cannot compare"], 0,
      "4.0% compounded daily is about 4.08% APY, a little more than 4.05%. Convert both to APY before you compare."),
    O("Compare two rates fairly, in order.",
      ["Check whether each is quoted as APR or APY", "Convert both to an effective annual rate", "Include fees that change the real cost", "Compare the effective numbers"],
      "Advertised rates are often chosen to look good. Converting puts them on the same footing."),
    C("Inflation is the hidden rate",
      "If savings earn 3% while prices rise 4%, your money buys less each year even though the balance grows. The real return is roughly the interest rate minus inflation."),
])

MOI6 = L("Saving for goals", KW + ["goals", "saving", "target", "monthly saving", "timeline", "down payment"], [
    C("Work back from the goal",
      "A goal becomes a plan when it has an amount, a date and a monthly number. For short goals (a few years or less), the monthly amount is roughly the target divided by the months, and the money usually belongs somewhere safe and accessible, because there is no time to recover from a market fall. Longer goals can consider growth, with more risk."),
    NQ("Example: you want {t} in {y} years, saving monthly with no growth. How much a month? (Two decimals.)",
       "{t} / ({y} times 12) = {A}.",
       {"t": [2000, 30000, 1000], "y": [1, 5, 1]}, "t/(y*12)", {"t": 12000, "y": 2}, rnd=2, tol=0.01),
    NQ("Example: same goal of {t} in {y} years, but savings earn {r}% a year compounded monthly. What monthly saving reaches it? (Two decimals.)",
       "Monthly saving = target times monthly rate / ((1 + monthly rate) to the power months, minus 1), about {A}.",
       {"t": [2000, 30000, 1000], "y": [1, 5, 1], "r": [1, 5, 1]}, "t*(r/1200)/((1+r/1200)^(y*12)-1)", {"t": 12000, "y": 2, "r": 4}, rnd=2, tol=0.05),
    M("You are saving for a house deposit needed in 18 months. Where is it generally sensible to keep it?",
      ["In volatile shares for higher returns", "In a safe, accessible account, since a fall just before you need it could delay the purchase", "In cash at home", "In a long term locked product"], 1,
      "Short time horizons leave no room to recover from a downturn. This is a general principle, not a product recommendation."),
    WR("Write a plan for one savings goal. Include lines starting with Goal:, Amount:, Date:, Monthly: and Where:. Show how you got the monthly number.",
       [must("^goal:", "Goal:", flags="im"),
        must("^amount:\\s*\\S*\\d", "Amount: with a number", flags="im"),
        must("^date:", "Date:", flags="im"),
        must("^monthly:.*\\d.*(/|divided|over|months)", "Monthly: with the calculation", flags="im",
             hint="Show it, for example 6,000 / 24 months = 250."),
        must("^where:", "Where: the kind of account", flags="im"),
        words(20, 150)],
       "Goal: replace the car without a loan.\nAmount: 6,000 (example estimate).\nDate: in 24 months.\nMonthly: 6,000 / 24 months = 250.\nWhere: a separate easy access savings account, because I need it in two years.",
       "Amount, date and monthly number turn a wish into a plan you can check each month."),
    O("Plan several goals at once, in order.",
      ["Build a basic emergency fund first", "List the other goals with amounts and dates", "Compute the monthly amount for each", "Prioritize if the total is more than you can save, and adjust dates"],
      "When everything cannot fit, moving a date is often easier than cutting a goal."),
])

MOI7 = L("Paychecks and tax basics", KW + ["tax", "income tax", "marginal rate", "effective rate", "paycheck", "brackets", "gross", "net"], [
    C("Marginal and effective rates",
      "Many countries tax income in brackets: each band of income is taxed at its own rate. Your marginal rate is the rate on your next unit of income; your effective rate is total tax divided by total income, which is lower. A raise that moves you into a higher bracket only taxes the part above the threshold at the higher rate, so earning more does not reduce take home pay in a standard bracket system. Real systems add allowances, credits and other contributions."),
    W("A made up bracket system",
      "Example brackets (invented for practice): 0% on the first 10,000, 20% from 10,000 to 40,000, 40% above 40,000. Income: 50,000.",
      ["First 10,000: 0.",
       "Next 30,000 at 20%: 6,000.",
       "Last 10,000 at 40%: 4,000.",
       "Total tax 10,000. Marginal rate 40%, effective rate 10,000 / 50,000 = 20%."],
      "Each band at its own rate; effective rate is total tax over income."),
    NQ("Example brackets (invented): 0% to 10,000, 20% from 10,000 to 40,000, 40% above. What is the total tax on an income of {i}?",
       "0 on the first 10,000, 20% of the next 30,000 (6,000), and 40% of the {o} above 40,000. Total: {A}.",
       {"i": [42000, 90000, 2000]}, "6000+(i-40000)*0.4", {"i": 50000}, rnd=0, show={"o": "i-40000"}),
    NQ("Same invented brackets, income {i}. What is the effective tax rate, in percent? (One decimal.)",
       "Tax {t} divided by {i}, times 100, is {A}%.",
       {"i": [42000, 90000, 2000]}, "(6000+(i-40000)*0.4)/i*100", {"i": 60000}, rnd=1, show={"t": "6000+(i-40000)*0.4"}),
    M("With the invented brackets, a raise from 39,000 to 41,000 means...",
      ["All income is now taxed at 40%", "Only the 1,000 above 40,000 is taxed at 40%; take home pay still rises", "Take home pay falls", "Tax doubles"], 1,
      "A common myth. In a standard bracket system, crossing a threshold changes the rate only on the income above it."),
    O("Read a payslip, in order.",
      ["Find gross pay", "List each deduction: income tax, social contributions, retirement contributions and others", "Subtract them to check net pay", "Check the tax code or allowance is right for you"],
      "Errors in tax codes and allowances do happen. Checking once a year, or after a job change, is worthwhile."),
    C("Check official sources",
      "Real brackets, allowances and credits change with each budget and differ by country and region. Your national tax authority's website is the source to trust."),
])

MOI8 = L("Insurance: premiums and deductibles", KW + ["insurance", "deductible", "premium", "excess", "coverage", "risk"], [
    C("Pay a little to avoid a lot",
      "Insurance swaps a small, certain cost (the premium) for protection against a large, uncertain one. The deductible (or excess) is what you pay before the insurer pays. A higher deductible usually means a lower premium. The general principle: insure against losses you could not afford, and consider covering small, affordable losses yourself from savings."),
    W("Compare two policies",
      "Example: Policy A costs 600 a year with a 250 deductible. Policy B costs 450 a year with a 1,000 deductible.",
      ["B saves 150 a year in premium.",
       "If you claim, B costs 750 more in deductible.",
       "Break even: B is cheaper unless you claim more than once every 5 years (750 / 150).",
       "B suits someone with savings to cover 1,000 and few expected claims."],
      "Premium saved per year versus extra deductible per claim."),
    NQ("Example: Policy A costs {pa} a year with a {da} deductible; Policy B costs {pb} with a {db} deductible. How many years of premium savings does one claim's extra deductible on B equal?",
       "Extra deductible {xd} divided by yearly saving {s} is {A} years.",
       {"pa": [500, 900, 50], "pb": [300, 450, 50], "da": [100, 300, 50], "db": [800, 1500, 100]}, "(db-da)/(pa-pb)", {"pa": 600, "pb": 450, "da": 250, "db": 1000}, rnd=1, tol=0.1,
       show={"xd": "db-da", "s": "pa-pb"}),
    NQ("Example: a phone costing {c} has a {p}% chance a year of being broken. An extended warranty costs {w} a year. What is the expected yearly loss without it?",
       "{pp} times {c} = {A}, compared with a warranty price of {w}.",
       {"c": [300, 1200, 100], "p": [5, 20, 5], "w": [60, 150, 10]}, "p/100*c", {"c": 800, "p": 10, "w": 120}, rnd=2, show={"pp": "p/100"}),
    M("Which loss is the strongest case for insurance?",
      ["A lost umbrella", "A large liability claim or the loss of your home, which you could not pay from savings", "A scratched phone screen", "A late train"], 1,
      "Insurance is most valuable for losses that would be financially devastating. Small losses are often cheaper to self insure."),
    O("Choose a policy, in order.",
      ["Decide which losses you could not afford", "Compare coverage, exclusions and limits, not only price", "Pick a deductible your savings can cover", "Review the policy each year"],
      "A cheap policy that excludes your main risk is not cheap."),
])

MOI9 = L("Capstone: a money plan for one month", KW + ["capstone", "plan", "budget", "debt", "savings", "goals"], [
    C("Put the level together",
      "You will build a one month money plan from this level's tools: a zero based budget, sinking funds for irregular costs, a debt payoff target, a savings goal with a monthly number, and a check that insurance deductibles are covered."),
    W("An example plan",
      "Example: take home 3,200. Bills 1,500, groceries 450, transport 220. Card debt 2,400 at 22%. Car insurance 600 due in 6 months. Goal: 3,000 emergency fund in 12 months, starting from 600.",
      ["Fixed and variable spending: 2,170. Left: 1,030.",
       "Sinking fund: 600 / 6 = 100. Emergency goal: (3,000 minus 600) / 12 = 200.",
       "Extra on the card (avalanche target): 450. Fun: 180. Irregular costs: 100.",
       "Total assigned: 2,170 + 100 + 200 + 450 + 180 + 100 = 3,200. Unassigned: 0."],
      "Every unit has a job, with debt, savings and fun all planned."),
    NQ("Example: take home {i}, spending {s}, sinking funds {f}, savings {v}. How much is left for extra debt payments and fun?",
       "{i} minus {s} minus {f} minus {v} = {A}.",
       {"i": [2500, 6000, 100], "s": [1500, 3000, 10], "f": [50, 300, 50], "v": [100, 500, 50]}, "i-s-f-v", {"i": 3200, "s": 2170, "f": 100, "v": 200}, rnd=0),
    NQ("Example: an emergency fund of {h} with a goal of {g} in {m} months. Monthly saving needed? (Two decimals.)",
       "({g} minus {h}) / {m} = {A}.",
       {"h": [0, 1500, 100], "g": [2000, 6000, 500], "m": [6, 24, 6]}, "(g-h)/m", {"h": 600, "g": 3000, "m": 12}, rnd=2),
    O("Build the plan, in order.",
      ["Write take home income", "Plan fixed and variable spending", "Add sinking funds and the savings goal", "Assign the rest to the debt target and fun until nothing is left"],
      "Savings and sinking funds before the debt extra keeps the plan resilient, so the next surprise does not go back on the card."),
    WR("Write your own one month plan (real or example). Use lines starting with Income:, Spending:, Sinking funds:, Savings goal:, Debt target:, Fun: and Unassigned:. Unassigned should be 0. Label example numbers as examples.",
       [must("^income:", "Income:", flags="im"),
        must("^spending:", "Spending:", flags="im"),
        must("^sinking funds:", "Sinking funds:", flags="im"),
        must("^savings goal:", "Savings goal:", flags="im"),
        must("^debt target:", "Debt target:", flags="im"),
        must("^fun:", "Fun:", flags="im"),
        must("^unassigned:\\s*0\\b", "Unassigned: 0", flags="im", hint="Keep assigning until nothing is left."),
        words(25, 200)],
       "Income: 3,200 take home (example).\nSpending: 2,170 for bills, groceries and transport.\nSinking funds: 100 for car insurance due in 6 months.\nSavings goal: 200 toward a 3,000 emergency fund.\nDebt target: 450 extra on the 22% card.\nFun: 180.\nUnassigned: 0, after 100 for irregular costs.",
       "A complete plan: spending, future costs, safety, debt and enjoyment, all decided in advance."),
    C("Intermediate complete",
      "You can plan a month, smooth the bumps, pay down debt in a smart order and compare rates and policies. Advanced moves to investing: risk, diversification, fees and behavior."),
])

# =====================================================================
# Advanced: Investing with eyes open
# =====================================================================

MOA1 = L("Risk and return", KW + ["investing", "risk", "return", "volatility", "stocks", "bonds", "cash"], [
    NOTE,
    C("Higher expected return comes with bumpier rides",
      "Over long periods, assets with more uncertain results, such as shares, have historically tended to earn more than safer ones such as cash, as payment for that uncertainty. Tended to is the key phrase: there is no guarantee, returns vary widely from year to year, and there have been long stretches when riskier assets did worse. Risk here means both volatility (how much values swing) and the chance of a permanent loss."),
    M("Which statement is accurate?",
      ["Shares always beat cash over any five year period", "Riskier assets have historically tended to earn more over long periods, with no guarantee and with large swings along the way", "Higher risk guarantees higher return", "Cash has no risk at all"], 1,
      "Even cash has a risk: inflation can erode what it buys. Shares carry the risk of large falls."),
    W("Same average, different journeys",
      "Example: two investments both average 6% a year over two years. A returns 6% and 6%. B returns 30% then minus 18%.",
      ["A: 1,000 times 1.06 times 1.06 = 1,123.60.",
       "B: 1,000 times 1.30 times 0.82 = 1,066.",
       "Same simple average return, but B ends lower because losses hit a bigger base after gains.",
       "Volatility itself drags down compound growth."],
      "Averages hide the path; the path changes the result."),
    NQ("Example: 1,000 rises {u}% and then falls {d}%. What is it worth after both years?",
       "1,000 times {gu} times {gd} = {A}.",
       {"u": [10, 40, 5], "d": [2, 30, 2]}, "1000*(1+u/100)*(1-d/100)", {"u": 30, "d": 18}, rnd=2, show={"gu": "1+u/100", "gd": "1-d/100"}),
    NQ("Example: an investment falls {d}%. What percent gain is needed to get back to the starting value? (One decimal.)",
       "1 / {k} minus 1, times 100, is {A}%.",
       {"d": [10, 60, 10]}, "(1/(1-d/100)-1)*100", {"d": 30}, rnd=1, tol=0.1, show={"k": "1-d/100"}),
    O("Match risk to a goal, in order.",
      ["Name the goal and when you need the money", "Decide how large a temporary fall you could live through without selling", "Choose a mix of assets consistent with both", "Write the decision down so you can hold to it in a downturn"],
      "Time horizon and tolerance for falls come first. The asset mix follows from them, not from last year's returns."),
])

MOA2 = L("Diversification", KW + ["diversification", "index funds", "correlation", "concentration", "single stock"], [
    C("Do not depend on one thing",
      "Owning many different investments spreads the risk that any single company, sector or country does badly. Diversification reduces risk most when the investments do not move together (low correlation). Broad index funds hold hundreds or thousands of companies in one product. Diversification cannot remove the risk of the whole market falling; it removes the extra risk of betting on a few names."),
    M("An employee holds most of their savings in their employer's shares. What is the main concern?",
      ["Nothing, they know the company", "Their job and savings depend on the same company, so one bad event could hit both", "Shares are illegal for employees", "Too many shares"], 1,
      "Concentration in your employer doubles up the risk. This is a general principle; the right action depends on your situation and any restrictions on selling."),
    W("Why many beats few",
      "Example: each company has, say, a 2% chance a year of a collapse. You own either 1 company or 100 equal stakes.",
      ["With 1 company, a collapse can wipe out the whole position.",
       "With 100 equal stakes, one collapse costs 1% of the portfolio.",
       "If collapses are fairly independent, the chance that many happen at once is small.",
       "Spread holdings turn a possible catastrophe into a small, survivable loss."],
      "Many independent small risks are safer than one big one."),
    NQ("Example: you hold {n} equal stakes and one of them goes to zero. What percent of the portfolio is lost? (Two decimals.)",
       "1 / {n}, times 100, is {A}%.",
       {"n": [5, 500, 5]}, "100/n", {"n": 100}, rnd=2),
    NQ("Example: a portfolio is {a}% in one company. That company falls {d}% and the rest is flat. How much does the portfolio fall, in percent?",
       "{a}% times {d}% = {A}% of the whole.",
       {"a": [5, 60, 5], "d": [20, 80, 10]}, "a*d/100", {"a": 40, "d": 50}, rnd=1),
    O("Check how diversified you are, in order.",
      ["List every holding, including employer shares and pension funds", "Group by company, sector and country", "Find the largest single exposure", "Decide whether that exposure is a deliberate choice"],
      "Many people discover their biggest exposure is something they never chose, such as a fund that is mostly one sector."),
    C("Overlapping funds are not extra diversification",
      "Two funds tracking similar indexes hold mostly the same companies. Owning both adds little spread and can add cost."),
])

MOA3 = L("Asset allocation and rebalancing", KW + ["asset allocation", "rebalancing", "portfolio", "stocks and bonds", "target mix"], [
    C("Pick a mix, then keep it",
      "Asset allocation is the split between broad types, such as shares, bonds and cash. It drives most of a diversified portfolio's ups and downs. Over time, faster growing parts become a bigger share, which raises risk. Rebalancing moves the mix back to target, either on a schedule (say once a year) or when a part drifts beyond a band. It is a disciplined way to sell some of what has risen and buy what has lagged."),
    W("Rebalance a drifted portfolio",
      "Example target: 60% shares, 40% bonds. After a strong year: shares 78,000 and bonds 42,000.",
      ["Total: 120,000. Target shares: 60% of 120,000 = 72,000.",
       "Shares are 6,000 above target; bonds 6,000 below.",
       "Rebalance by moving 6,000 from shares to bonds, or direct new contributions to bonds until the mix is back.",
       "Using new money avoids selling, which may matter where selling has tax consequences."],
      "Compute targets from the total, then move the difference."),
    NQ("Example: target {t}% shares. Shares are worth {s} and bonds {b}. How much would you move from shares to reach the target?",
       "Total {tot}; target shares {ts}; move {s} minus {ts} = {A}.",
       {"t": [40, 60, 10], "s": [70000, 100000, 2000], "b": [20000, 44000, 2000]}, "s-t/100*(s+b)", {"t": 60, "s": 78000, "b": 42000}, rnd=0,
       show={"tot": "s+b", "ts": "t/100*(s+b)"}),
    NQ("Example: shares {s} and bonds {b}. What percent of the portfolio is in shares? (One decimal.)",
       "{s} / ({s} + {b}), times 100, is {A}%.",
       {"s": [30000, 100000, 2000], "b": [20000, 80000, 2000]}, "s/(s+b)*100", {"s": 78000, "b": 42000}, rnd=1),
    M("Why does rebalancing feel hard in practice?",
      ["It is complicated maths", "It means selling what has been doing well and buying what has been doing badly, which goes against instinct", "It is illegal", "It costs nothing"], 1,
      "That discomfort is exactly why a written rule helps: the decision is made in advance."),
    O("Set up a rebalancing rule, in order.",
      ["Write the target mix", "Choose a schedule or a drift band, such as 5 percentage points", "Decide to use new contributions first", "Check and act on the schedule, not on headlines"],
      "A rule that runs on a calendar does not depend on how you feel about the market that week."),
])

MOA4 = L("Fees and the cost of investing", KW + ["fees", "expense ratio", "costs", "fund fees", "advice fees", "drag"], [
    C("Small percentages, big amounts",
      "Investment costs are usually quoted as a yearly percentage of what you hold: a fund's ongoing charge or expense ratio, platform fees, adviser fees. Because they are charged every year on the whole balance, they compound against you. Lower cost does not guarantee a better fund, but cost is one of the few things you know in advance and control, and it is a reliable drag on net returns."),
    X("The fee gap over time",
      "Example: 10,000 invested for 30 years at 6% a year before fees. Drag the yearly fee to see the ending value.",
      "10000*(1+0.06-x/100)^30", "x", 0, 2.5, 0.1, "Yearly fee (%)", "Value after 30 years"),
    NQ("Example: 10,000 grows at {r}% a year for {y} years. What is it worth with a {f}% yearly fee? (Round to whole units.)",
       "10,000 times (1 + {r}% minus {f}%) to the power {y} is about {A}.",
       {"r": [4, 8, 1], "y": [10, 40, 5], "f": [0.1, 2, 0.1]}, "10000*(1+r/100-f/100)^y", {"r": 6, "y": 30, "f": 1}, rnd=0, tol=1),
    NQ("Example: the same 10,000 at {r}% for {y} years, with fees of {lo}% versus {hi}%. How much more does the low fee option end with? (Round.)",
       "Low fee ends near {a}; high fee near {b}. Difference: about {A}.",
       {"r": [4, 8, 1], "y": [10, 40, 5], "lo": [0.1, 0.5, 0.1], "hi": [1, 2, 0.5]}, "10000*(1+r/100-lo/100)^y-10000*(1+r/100-hi/100)^y", {"r": 6, "y": 30, "lo": 0.2, "hi": 1.5}, rnd=0, tol=1,
       show={"a": "10000*(1+r/100-lo/100)^y", "b": "10000*(1+r/100-hi/100)^y"}),
    M("A fund charges 1.5% a year and the market returns 6% before costs. Roughly what share of the gross return goes to fees each year?",
      ["1.5%", "About a quarter", "Nothing", "Half"], 1,
      "1.5 out of 6 is a quarter of the return, every year."),
    O("Find out what you actually pay, in order.",
      ["List every product you hold", "Find each fund's ongoing charge", "Add platform and adviser fees", "Compute the total yearly cost as a percentage and as money"],
      "Seeing the cost as money, not only a percentage, is often what prompts a review."),
])

MOA5 = L("Inflation and real returns", KW + ["inflation", "real return", "purchasing power", "nominal", "cash"], [
    C("What your money can buy",
      "Inflation is the general rise in prices over time. A nominal return is the change in the number of units of money; a real return is the change in what that money can buy. Roughly, real return = nominal return minus inflation; exactly, (1 + nominal) / (1 + inflation) minus 1. Over decades, even modest inflation significantly reduces what a fixed sum buys."),
    NQ("Example: an account pays {n}% and inflation is {i}%. What is the exact real return, in percent? (Two decimals.)",
       "(1 + {n}%) / (1 + {i}%) minus 1, times 100, is {A}%.",
       {"n": [1, 8, 0.5], "i": [1, 6, 0.5]}, "((1+n/100)/(1+i/100)-1)*100", {"n": 4, "i": 3}, rnd=2, tol=0.01),
    NQ("Example: prices rise {i}% a year for {y} years. What will 1,000 buy then, in today's money? (Round.)",
       "1,000 / (1 + {i}%) to the power {y} is about {A}.",
       {"i": [1, 6, 0.5], "y": [5, 30, 5]}, "1000/(1+i/100)^y", {"i": 3, "y": 20}, rnd=0, tol=1),
    X("Inflation over a lifetime",
      "Example: drag the number of years. The value shows what 1,000 buys after that many years of 3% inflation, in today's money.",
      "1000/(1.03)^x", "x", 0, 50, 1, "Years", "Buying power of 1,000"),
    M("Cash in an account paying 1% while inflation is 4%. What is happening?",
      ["It is growing safely", "The balance grows but its buying power falls by roughly 3% a year", "It is losing units of money", "Nothing"], 1,
      "Safe from market falls is not the same as safe from inflation."),
    O("Think in real terms, in order.",
      ["Write the goal in today's money", "Estimate a plausible range for inflation", "Use real returns, not nominal ones, to plan", "Revisit the plan as prices change"],
      "Planning in today's money keeps goals understandable: 300,000 in 30 years means little without knowing what it will buy."),
])

MOA6 = L("Bonds and interest rates", KW + ["bonds", "interest rates", "yield", "duration", "fixed income", "prices"], [
    C("Why bond prices move",
      "A bond is a loan: you receive fixed payments (coupons) and your money back at maturity. If market interest rates rise, new bonds pay more, so existing bonds with lower coupons become less attractive and their prices fall. When rates fall, existing bond prices rise. Longer bonds are more sensitive to rate changes. Holding a high quality bond to maturity returns its face value, barring default, whatever happens to its price on the way."),
    W("Price a one year bond",
      "Example: a bond pays 1,000 plus a 40 coupon in one year. Market rates for similar bonds are 5%.",
      ["The bond pays 1,040 in a year.",
       "Price today = 1,040 / 1.05, about 990.48.",
       "If market rates were 3%, price = 1,040 / 1.03, about 1,009.71.",
       "Higher rates, lower price; lower rates, higher price."],
      "Price is the payments discounted at the market rate."),
    NQ("Example: a bond pays {c} in coupon plus 1,000 in one year. The market rate is {r}%. What is its price today? (Two decimals.)",
       "(1,000 + {c}) / (1 + {r}%) = {A}.",
       {"c": [20, 80, 10], "r": [1, 8, 0.5]}, "(1000+c)/(1+r/100)", {"c": 40, "r": 5}, rnd=2, tol=0.01),
    NQ("Example: a two year bond pays {c} at the end of each year and 1,000 at the end of year two. The market rate is {r}%. What is its price? (Two decimals.)",
       "{c} / (1 + {r}%) + (1,000 + {c}) / (1 + {r}%) squared = {A}.",
       {"c": [20, 80, 10], "r": [1, 8, 0.5]}, "c/(1+r/100)+(1000+c)/(1+r/100)^2", {"c": 40, "r": 5}, rnd=2, tol=0.01),
    M("Rates rise sharply. Which bond's price is likely to fall most?",
      ["A one year bond", "A 20 year bond", "Both fall equally", "Neither"], 1,
      "Longer bonds lock in the old rate for longer, so their prices react more."),
    O("Understand a bond fund, in order.",
      ["Check the average credit quality of its bonds", "Check its duration, a measure of rate sensitivity", "Check its costs", "Match it to when you need the money"],
      "Duration is roughly how much the price moves, in percent, for a 1 point change in rates. Shorter needs, shorter duration."),
])

MOA7 = L("Tax advantaged accounts", KW + ["tax", "retirement accounts", "pensions", "tax advantaged", "tax drag", "employer match"], [
    C("Let the account do some of the work",
      "Many countries offer accounts with tax advantages for retirement or long term saving: contributions may be tax deductible, growth may be untaxed, or withdrawals may be tax free, with limits and rules on when you can take money out. Employer schemes sometimes add matching contributions, which are an immediate return on the money you put in. Names, limits and rules vary widely, so check your country's official guidance."),
    W("Tax drag on growth (invented rates)",
      "Example: 10,000 grows at 6% a year for 20 years. In one account, a made up 25% tax is taken from growth each year. In another, growth is untaxed.",
      ["Untaxed: 10,000 times 1.06 to the power 20, about 32,071.",
       "Taxed each year: growth becomes 6% times 0.75 = 4.5%, so 10,000 times 1.045 to the power 20, about 24,117.",
       "Difference: about 7,954, from tax drag compounding over 20 years.",
       "Real outcomes depend on the actual rules, including any tax when money comes out."],
      "Taxes taken every year compound against you, like fees."),
    NQ("Example: your employer matches {m}% of your contributions up to a limit. You contribute {c} a year within the limit. How much does the employer add?",
       "{m}% of {c} = {A}, an immediate addition before any investment return.",
       {"m": [25, 100, 25], "c": [1000, 6000, 500]}, "m/100*c", {"m": 50, "c": 3000}, rnd=0),
    NQ("Example (invented tax rate): 10,000 grows {r}% a year for {y} years, with {t}% of each year's growth taxed. What is it worth? (Round.)",
       "Growth after tax is {r}% times {k} = {net}% a year, so about {A}.",
       {"r": [4, 8, 1], "y": [10, 30, 5], "t": [10, 40, 5]}, "10000*(1+r/100*(1-t/100))^y", {"r": 6, "y": 20, "t": 25}, rnd=0, tol=1,
       show={"k": "1-t/100", "net": "r*(1-t/100)"}),
    M("An employer offers to match contributions. What is the general principle?",
      ["Ignore it", "A match is extra money for saving; it is commonly worth understanding and capturing if you can afford to, after checking the scheme's rules", "Matches are taxed at 100%", "Only executives get matches"], 1,
      "General principle, not personal advice: matched money is a strong incentive, but check vesting and access rules."),
    O("Learn your options, in order.",
      ["Find your country's official guide to tax advantaged accounts", "Check any employer scheme and its match", "Note limits and when money can be accessed", "Decide what fits your goals, with independent advice if unsure"],
      "Official sources first. Many costly mistakes come from rules remembered from another country or another year."),
])

MOA8 = L("Behavior: the investor's biggest risk", KW + ["behavioral finance", "panic selling", "market timing", "dollar cost averaging", "discipline"], [
    C("The gap between investments and investors",
      "Studies of fund flows have often found that investors' actual returns trail the funds they hold, because money tends to flow in after good runs and out after falls. Common traps: selling in a panic, chasing last year's winners, checking too often, and trying to time the market. A written plan, automatic contributions and fewer decisions are the usual remedies."),
    M("Markets fall 25%. Your plan has a 20 year horizon. What does a written plan generally say?",
      ["Sell everything until it is safe", "Stick to the plan and rebalance if the mix has drifted, since you do not need the money soon", "Move to the best fund of last year", "Stop contributing forever"], 1,
      "Falls are expected along the way for long horizons. The plan exists for exactly this moment."),
    W("Regular investing through ups and downs",
      "Example: investing 300 a month at prices of 10, 6 and 12 over three months.",
      ["Month 1: 300 / 10 = 30 units. Month 2: 300 / 6 = 50 units. Month 3: 300 / 12 = 25 units.",
       "Total: 105 units for 900, an average cost of about 8.57 a unit.",
       "The average price over the three months was 9.33.",
       "Fixed amounts buy more units when prices are low, which lowers the average cost."],
      "Regular fixed amounts automatically buy more when prices are low."),
    NQ("Example: you invest {a} each month at prices {p1}, {p2} and {p3}. What is your average cost per unit? (Two decimals.)",
       "Units: {u}. Average cost: {t} / {u}, about {A}.",
       {"a": [100, 500, 100], "p1": [8, 14, 2], "p2": [4, 8, 2], "p3": [10, 16, 2]}, "3*a/(a/p1+a/p2+a/p3)", {"a": 300, "p1": 10, "p2": 6, "p3": 12}, rnd=2, tol=0.01,
       show={"u": "a/p1+a/p2+a/p3", "t": "3*a"}),
    WR("Write three rules for yourself that would stop a panic decision in a market fall. One per line.",
       [lines(3, "Three rules"),
        must("(wait|sleep|24 hours|48 hours|week|pause)", "One rule adds a delay before acting"),
        must("(plan|written|policy|rule)", "One rule refers back to a written plan"),
        avoid("(sell everything|\\ball in\\b|guaranteed)", "No all or nothing rules"),
        words(15, 100)],
       "Wait at least a week before selling anything during a fall.\nReread my written plan and its time horizon first.\nOnly rebalance back to my target mix, never a full exit.",
       "Rules written in calm times are what you follow in stormy ones."),
    O("Reduce behavioral mistakes, in order.",
      ["Write a plan with goals, horizon and target mix", "Automate contributions", "Limit how often you check", "Review on a schedule and only change the plan for life changes, not headlines"],
      "Most of the benefit comes from fewer, pre committed decisions."),
])

MOA9 = L("Capstone: an investment policy statement", KW + ["capstone", "investment policy", "ips", "plan", "allocation", "rules"], [
    C("Your rules, written down",
      "An investment policy statement is a short document stating your goals, time horizon, target allocation, rebalancing rule, contribution plan, costs you accept, and how you will behave in a downturn. Writing it in calm times is one of the most effective protections against your own worst decisions. This is an educational exercise in structure, not a recommendation of any particular mix."),
    M("Which line belongs in an investment policy statement?",
      ["I will buy whatever is trending", "Rebalance to target once a year, or when any part drifts more than 5 points", "I will check prices hourly", "Returns of 15% a year are expected"], 1,
      "A clear, checkable rule. The others are impulses or promises nobody can keep."),
    NQ("Example: your target is {s}% shares. After a fall, shares are {a} and the rest is {b}. How far has the shares share drifted from target, in percentage points? (One decimal.)",
       "Shares are now {now}%, so the drift is {A} points (negative means below target).",
       {"s": [40, 80, 10], "a": [20000, 80000, 2000], "b": [20000, 60000, 2000]}, "a/(a+b)*100-s", {"s": 60, "a": 48000, "b": 42000}, rnd=1, tol=0.1,
       show={"now": "a/(a+b)*100"}),
    O("Write the statement, in order.",
      ["Goals and time horizon", "Target allocation", "Contribution and rebalancing rules", "Cost limits", "What you will do in a large fall"],
      "Goals come first because everything else is chosen to serve them."),
    WR("Write your investment policy statement (real or for an example person). Use lines starting with Goal:, Horizon:, Mix:, Contributions:, Rebalancing:, Costs: and In a fall:. Label it as an example if it is not real.",
       [must("^goal:", "Goal:", flags="im"),
        must("^horizon:", "Horizon:", flags="im"),
        must("^mix:.*\\d", "Mix: with percentages", flags="im"),
        must("^contributions:", "Contributions:", flags="im"),
        must("^rebalancing:", "Rebalancing:", flags="im"),
        must("^costs:", "Costs:", flags="im"),
        must("^in a fall:", "In a fall:", flags="im"),
        avoid("guarantee", "No guarantees promised"),
        words(50, 250)],
       "Example only.\nGoal: retirement savings, plus a growing safety margin.\nHorizon: 25 years.\nMix: 70% broad global shares, 30% high quality bonds, via low cost index funds.\nContributions: 400 a month by automatic transfer on payday.\nRebalancing: once a year in January, or if any part drifts more than 5 points.\nCosts: total yearly costs below an agreed limit; review fees each year.\nIn a fall: no selling; reread this page; rebalance only by the rule above.",
       "Clear, specific and written before it is needed. Review it once a year or after a big life change."),
    C("Advanced complete",
      "You understand risk, diversification, costs, inflation, bonds, tax wrappers and your own behavior. Expert brings it together: balance sheets, mortgages, retirement math and a full financial plan."),
])

# =====================================================================
# Expert: Planning the long game
# =====================================================================

MOE1 = L("Net worth and your balance sheet", KW + ["net worth", "balance sheet", "assets", "liabilities", "cash flow"], [
    NOTE,
    C("Two statements, one picture",
      "A personal balance sheet lists what you own (assets) and what you owe (liabilities) at one moment. Net worth is assets minus liabilities. A cash flow statement shows money in and out over a period. Net worth tells you where you stand; cash flow tells you where you are heading. Tracking both once a quarter or once a year shows progress that monthly budgets can hide."),
    W("Build a balance sheet",
      "Example: savings 6,000; retirement account 24,000; car worth 8,000. Card debt 2,000; car loan 5,000; student loan 15,000.",
      ["Assets: 6,000 + 24,000 + 8,000 = 38,000.",
       "Liabilities: 2,000 + 5,000 + 15,000 = 22,000.",
       "Net worth: 38,000 minus 22,000 = 16,000.",
       "Note the car is valued at what it would sell for, not what it cost."],
      "Value assets at realistic sale prices; include every debt."),
    NQ("Example: assets total {a} and liabilities total {l}. What is net worth?",
       "{a} minus {l} = {A}.",
       {"a": [10000, 400000, 5000], "l": [5000, 300000, 5000]}, "a-l", {"a": 40000, "l": 25000}, rnd=0),
    NQ("Example: liquid savings are {s} and essential spending is {e} a month. How many months could savings cover? (One decimal.)",
       "{s} / {e} = {A} months.",
       {"s": [1000, 30000, 1000], "e": [800, 4000, 100]}, "s/e", {"s": 6000, "e": 2000}, rnd=1, tol=0.1),
    M("Net worth fell this year while you paid down debt. What could explain it?",
      ["Paying debt always lowers net worth", "An asset, such as a car or investments, fell in value by more than you repaid", "Net worth cannot fall", "A math error, always"], 1,
      "Repaying debt with cash leaves net worth unchanged on the day; changes in asset values move it."),
    O("Review your finances each year, in order.",
      ["List assets at realistic values", "List all debts with rates", "Compute net worth and compare to last year", "Note what drove the change: saving, debt repayment or asset values"],
      "Separating saving from market moves shows what you control."),
])

MOE2 = L("Time value of money", KW + ["time value of money", "present value", "future value", "discounting", "annuity"], [
    C("Money now versus money later",
      "A sum today can be invested, so it is worth more than the same sum later. Future value: FV = PV times (1 + r) to the power n. Present value reverses it: PV = FV / (1 + r) to the power n. A series of equal payments (an annuity) has a present value of payment times (1 minus (1 + r) to the power minus n) / r. These formulas underpin loans, pensions and every comparison of money across time."),
    NQ("Example: what is {f} received in {n} years worth today, at {r}% a year? (Round.)",
       "{f} / (1 + {r}%) to the power {n} is about {A}.",
       {"f": [1000, 20000, 1000], "n": [1, 30, 1], "r": [1, 8, 0.5]}, "f/(1+r/100)^n", {"f": 10000, "n": 10, "r": 5}, rnd=0, tol=1),
    NQ("Example: what is the present value of {p} a year for {n} years at {r}%? (Round.)",
       "{p} times (1 minus (1 + {r}%) to the power minus {n}) / {r}% is about {A}.",
       {"p": [500, 5000, 500], "n": [5, 30, 1], "r": [1, 8, 0.5]}, "p*(1-(1+r/100)^(-n))/(r/100)", {"p": 1000, "n": 10, "r": 5}, rnd=0, tol=1),
    M("Option A: 10,000 now. Option B: 11,000 in two years. With a 5% yearly return available, which is worth more today?",
      ["A, because 11,000 in two years is worth about 9,977 today", "B, because 11,000 is bigger", "They are equal", "Cannot tell"], 0,
      "11,000 / 1.05 squared is about 9,977, a little less than 10,000. At lower rates B could win: the rate decides."),
    W("Saving toward a future amount",
      "Example: you want 20,000 in 5 years and expect 4% a year. How much is needed today?",
      ["PV = 20,000 / 1.04 to the power 5.",
       "1.04 to the power 5 is about 1.2167.",
       "PV is about 16,438.",
       "If the return is lower, more is needed today: the expected rate is an assumption, not a promise."],
      "Discount the goal back to today."),
    O("Compare money across time, in order.",
      ["Write each amount and when it arrives", "Choose a reasonable rate for the comparison", "Convert everything to present value", "Compare, and test how the answer changes with the rate"],
      "If the decision flips at plausible rates, it is close and other factors should weigh more."),
])

MOE3 = L("Mortgages and amortization", KW + ["mortgage", "amortization", "home loan", "interest", "payment", "overpayment"], [
    C("How a repayment loan works",
      "A repayment mortgage has a fixed payment (for a fixed rate) that covers that month's interest plus some principal. Early on most of the payment is interest; later most is principal. The monthly payment is P times i / (1 minus (1 + i) to the power minus n), where i is the monthly rate and n the number of months. Extra payments reduce principal directly and shorten the loan, subject to the lender's rules."),
    NQ("Example: borrow {p} at {r}% a year for {y} years with monthly payments. What is the monthly payment? (Two decimals.)",
       "Monthly rate about {i}%; {n} months. Payment is about {A}.",
       {"p": [50000, 400000, 10000], "r": [2, 8, 0.5], "y": [10, 30, 5]}, "p*(r/1200)/(1-(1+r/1200)^(-12*y))", {"p": 200000, "r": 5, "y": 25}, rnd=2, tol=0.05,
       show={"i": "r/1200*100", "n": "12*y"}),
    W("Split the first payment",
      "Example: 200,000 at 5% for 25 years. Payment about 1,169.18.",
      ["Monthly rate: 5% / 12, about 0.4167%.",
       "First month's interest: 200,000 times 0.004167, about 833.33.",
       "Principal repaid: 1,169.18 minus 833.33 = 335.85.",
       "Most of the early payment is interest; the split shifts each month as the balance falls."],
      "Interest is charged on the remaining balance."),
    NQ("Example: the balance is {b} at {r}% a year. How much of this month's payment is interest? (Two decimals.)",
       "{b} times {r}% / 12 = {A}.",
       {"b": [50000, 400000, 10000], "r": [2, 8, 0.5]}, "b*r/1200", {"b": 200000, "r": 5}, rnd=2, tol=0.01),
    NQ("Example: borrow {p} at {r}% for {y} years. What is the total interest paid over the loan? (Round.)",
       "Payment {m} times {n} months, minus {p}, is about {A}.",
       {"p": [50000, 400000, 10000], "r": [2, 8, 0.5], "y": [10, 30, 5]}, "12*y*p*(r/1200)/(1-(1+r/1200)^(-12*y))-p", {"p": 200000, "r": 5, "y": 25}, rnd=0, tol=5,
       show={"m": "p*(r/1200)/(1-(1+r/1200)^(-12*y))", "n": "12*y"}),
    M("Same loan, 25 versus 30 years. Which is true?",
      ["30 years has a lower payment and more total interest", "30 years has a higher payment", "Total interest is the same", "25 years costs more in total"], 0,
      "Spreading over longer lowers each payment but you pay interest for longer."),
    O("Compare mortgage offers, in order.",
      ["Note the rate, type and how long any fixed period lasts", "Add all fees", "Compute payment and total cost over the period you expect to keep it", "Check overpayment rules and penalties"],
      "A lower rate with large fees can cost more over a short holding period."),
])

MOE4 = L("Rent or buy: a framework", KW + ["rent or buy", "renting", "buying a home", "unrecoverable costs", "opportunity cost"], [
    C("Compare the money you never get back",
      "Rent is an unrecoverable cost. Owning has its own: mortgage interest, property taxes, maintenance, insurance and the return the down payment could have earned elsewhere (opportunity cost), plus large buying and selling costs. A fair comparison sets yearly unrecoverable costs side by side and accounts for how long you will stay. Neither option is always better; it depends on prices, rates, costs and your plans."),
    W("Unrecoverable costs, side by side",
      "Example: home price 300,000; down payment 60,000; loan 240,000 at 5%. Property tax and insurance 3,000 a year; maintenance 1% of price; the down payment could earn 4% elsewhere. Similar rent: 1,400 a month.",
      ["Interest, first year roughly: 240,000 times 5% = 12,000.",
       "Taxes and insurance 3,000; maintenance 3,000; opportunity cost 60,000 times 4% = 2,400.",
       "Owning: about 20,400 a year unrecoverable, before buying and selling costs.",
       "Renting: 1,400 times 12 = 16,800. In this example renting costs less each year; changes in home prices could shift that."],
      "Compare unrecoverable costs, not rent versus the whole mortgage payment."),
    NQ("Example: loan {l} at {r}%, taxes and insurance {t}, maintenance {m}, down payment {d} that could earn {o}%. What are the yearly unrecoverable costs of owning? (Round.)",
       "{l} times {r}% + {t} + {m} + {d} times {o}% = {A}.",
       {"l": [100000, 400000, 20000], "r": [2, 8, 1], "t": [1000, 6000, 1000], "m": [1000, 6000, 1000], "d": [20000, 100000, 20000], "o": [2, 6, 1]},
       "l*r/100+t+m+d*o/100", {"l": 240000, "r": 5, "t": 3000, "m": 3000, "d": 60000, "o": 4}, rnd=0),
    NQ("Example: buying and selling costs total {c}. Owning saves {s} a year in unrecoverable costs versus renting. How many years to recover the transaction costs? (One decimal.)",
       "{c} / {s} = {A} years.",
       {"c": [10000, 40000, 2000], "s": [1000, 8000, 500]}, "c/s", {"c": 24000, "s": 3000}, rnd=1, tol=0.1),
    M("Which factor most favors renting, all else equal?",
      ["Planning to stay 20 years", "Expecting to move within two or three years", "Low mortgage rates", "Rising rents"], 1,
      "Short stays leave too little time to recover buying and selling costs."),
    O("Decide rent or buy, in order.",
      ["Estimate how long you will stay", "Compute yearly unrecoverable costs for both", "Add buying and selling costs spread over your stay", "Test different home price and rate assumptions", "Weigh non money factors such as flexibility and control"],
      "The money comparison informs the decision; it does not make it."),
])

MOE5 = L("Retirement math: how much is enough", KW + ["retirement", "withdrawal rate", "safe withdrawal", "4 percent rule", "pension"], [
    C("From a pot to an income",
      "One way to frame retirement is the yearly spending you need from savings, after any pensions. A withdrawal rate is the share of the starting pot taken in year one, often then adjusted for inflation. Studies of historical US market returns gave rise to the widely quoted 4% rule of thumb for 30 years; it is a starting point for discussion, not a guarantee. Results depend on markets, costs, taxes, flexibility and how long retirement lasts, and many planners use lower or flexible rates."),
    NQ("Example: you need {s} a year from savings and plan on a {w}% initial withdrawal rate. What starting pot does that imply? (Round.)",
       "{s} / {w}% = {A}.",
       {"s": [10000, 60000, 2000], "w": [2.5, 5, 0.5]}, "s/(w/100)", {"s": 30000, "w": 4}, rnd=0),
    NQ("Example: you want {s} a year in retirement and a pension covers {p}. At a {w}% withdrawal rate, what pot is needed? (Round.)",
       "Gap {g}; {g} / {w}% = {A}.",
       {"s": [20000, 70000, 2000], "p": [0, 18000, 2000], "w": [2.5, 5, 0.5]}, "(s-p)/(w/100)", {"s": 36000, "p": 12000, "w": 4}, rnd=0,
       show={"g": "s-p"}),
    X("Withdrawal rate and the size of the pot",
      "Example: drag the withdrawal rate to see the pot needed for 30,000 a year.",
      "30000/(x/100)", "x", 2, 6, 0.25, "Withdrawal rate (%)", "Pot needed"),
    M("Which statement about the 4% rule is fair?",
      ["It guarantees money will last forever", "It is a rule of thumb from historical US data that may not hold in other markets, eras or for longer retirements", "It applies only to cash savings", "It is a law"], 1,
      "Treat it as a rough starting point and plan for flexibility."),
    O("Estimate a retirement target, in order.",
      ["Estimate yearly spending in today's money", "Subtract expected pensions and other income", "Divide the gap by a cautious withdrawal rate", "Plan how you would adjust spending in bad years"],
      "Flexibility in spending is one of the strongest protections a retiree has."),
])

MOE6 = L("Sequence of returns risk", KW + ["sequence risk", "sequence of returns", "retirement", "withdrawals", "cash buffer"], [
    C("When the bad years come matters",
      "While you are only saving, the order of good and bad years matters little for the final result. Once you withdraw money, it matters a lot: big losses early force you to sell more units at low prices, leaving less to recover. This is sequence of returns risk. Common responses include flexible spending, a cash or bond buffer, and a cautious starting withdrawal rate."),
    W("Same returns, different order (example)",
      "Example: a 100,000 pot, withdrawing 10,000 at the start of each of two years. Returns are minus 20% then plus 20%, or the reverse.",
      ["Bad first: (100,000 minus 10,000) times 0.8 = 72,000; (72,000 minus 10,000) times 1.2 = 74,400.",
       "Good first: (100,000 minus 10,000) times 1.2 = 108,000; (108,000 minus 10,000) times 0.8 = 78,400.",
       "Same two returns, same withdrawals: 4,000 difference after two years.",
       "Without withdrawals both would end at 96,000."],
      "Withdrawals during a fall lock in losses."),
    NQ("Example: pot 100,000, withdraw {w} at the start of each year. Year one returns minus {d}%, year two plus {d}%. What is left? (Round.)",
       "((100,000 minus {w}) times {lo} minus {w}) times {hi} = {A}.",
       {"w": [2000, 12000, 1000], "d": [10, 30, 5]}, "((100000-w)*(1-d/100)-w)*(1+d/100)", {"w": 10000, "d": 20}, rnd=0, show={"lo": "1-d/100", "hi": "1+d/100"}),
    NQ("Example: pot 100,000, withdraw {w} at the start of each year. This time year one returns plus {d}% and year two minus {d}%. What is left? (Round.)",
       "((100,000 minus {w}) times {hi} minus {w}) times {lo} = {A}.",
       {"w": [2000, 12000, 1000], "d": [10, 30, 5]}, "((100000-w)*(1+d/100)-w)*(1-d/100)", {"w": 10000, "d": 20}, rnd=0, show={"lo": "1-d/100", "hi": "1+d/100"}),
    M("Which response targets sequence risk directly?",
      ["Picking the best fund", "Holding a cash or bond buffer to draw from after a fall, and cutting spending a little in bad years", "Withdrawing more after a fall", "Ignoring it"], 1,
      "Both reduce how many units you sell at low prices."),
    O("Plan for a bad start, in order.",
      ["Identify the years just before and after retiring as the risky window", "Decide on a buffer of safer assets", "Set rules for trimming spending after a fall", "Write when and how you will refill the buffer"],
      "The plan is about the risky window, not every year forever."),
])

MOE7 = L("Insuring against big risks", KW + ["insurance", "life insurance", "disability insurance", "income protection", "needs analysis"], [
    C("Insure what you cannot afford to lose",
      "Insurance makes most sense for large losses you could not absorb: losing your income through illness, dying while others depend on you, liability claims, or losing your home. Small, affordable losses are often cheaper to cover from savings. A needs analysis estimates how much cover is required, rather than buying a round number. Products, tax treatment and state benefits vary by country."),
    W("A simple life cover needs estimate",
      "Example: dependents would need 25,000 a year for 15 years, there is a 150,000 mortgage, and existing savings are 30,000.",
      ["Income replacement, ignoring growth for simplicity: 25,000 times 15 = 375,000.",
       "Add the mortgage: 375,000 + 150,000 = 525,000.",
       "Subtract existing savings: 525,000 minus 30,000 = 495,000.",
       "A fuller estimate would discount future needs and include other benefits; this sets the order of magnitude."],
      "Needs minus resources, with stated simplifications."),
    NQ("Example: dependents need {n} a year for {y} years, debts are {d}, and savings are {s}. What simple cover estimate results?",
       "{n} times {y} + {d} minus {s} = {A}.",
       {"n": [10000, 50000, 5000], "y": [5, 25, 5], "d": [0, 300000, 10000], "s": [0, 100000, 10000]}, "n*y+d-s", {"n": 25000, "y": 15, "d": 150000, "s": 30000}, rnd=0),
    NQ("Example: income protection pays {p}% of a salary of {i}. What is the yearly benefit?",
       "{p}% of {i} = {A}.",
       {"p": [50, 75, 5], "i": [20000, 100000, 5000]}, "p/100*i", {"p": 60, "i": 40000}, rnd=0),
    M("Which is generally a stronger case for insurance?",
      ["Covering a 50 phone screen", "Covering years of lost income if illness stops you working", "Covering a lost umbrella", "Extended warranty on a kettle"], 1,
      "Insure large, unaffordable risks; self insure small ones from savings."),
    O("Review your cover, in order.",
      ["List the big risks: income, death with dependents, liability, home", "Check what work and state benefits already provide", "Estimate the gap for each", "Compare policies on cover, exclusions and cost"],
      "Existing cover through work or the state is often missed, leading to over or under insuring."),
])

MOE8 = L("Estate basics: wills and beneficiaries", KW + ["estate planning", "will", "beneficiaries", "power of attorney", "guardianship"], [
    C("Plans for when you cannot decide",
      "Estate planning covers what happens to your money and dependents if you die or cannot make decisions. Common pieces: a will naming who inherits and, where relevant, guardians for children; beneficiary nominations on pensions and insurance, which in many places pass outside the will; and a power of attorney for financial and health decisions. Rules differ greatly by country and state, so this is general orientation; a qualified local professional is the right source for specifics."),
    M("Your pension beneficiary form names a former partner, but your will leaves everything to your children. In many systems, what happens to the pension?",
      ["The will always overrides it", "The beneficiary nomination may take priority for that account, so it should be kept up to date", "It is split automatically", "It goes to the state"], 1,
      "In many places nominations control those accounts. Review them after any life event."),
    W("A simple document inventory",
      "Example: list what someone helping you would need to find.",
      ["Where the will is kept, and who the executor is.",
       "Accounts, pensions and policies, with providers and beneficiaries.",
       "Debts and regular bills.",
       "Who holds power of attorney, and how to contact your advisers."],
      "An inventory saves your family weeks of searching."),
    WR("Write a short checklist of the estate documents you would review, with one line for each. Cover a will, beneficiaries and power of attorney. Do not include real account numbers.",
       [lines(3, "At least three lines"),
        must("will", "Mentions a will"),
        must("beneficiar", "Mentions beneficiaries"),
        must("power of attorney|attorney|proxy", "Mentions power of attorney"),
        avoid("\\d{8,}", "No long account numbers"),
        words(15, 120)],
       "Will: check it exists, is current and names guardians.\nBeneficiaries: review pension and insurance nominations.\nPower of attorney: name someone for money and health decisions.\nInventory: list accounts and where documents are kept.",
       "Short, practical and safe to share with family."),
    O("Put basics in place, in order.",
      ["List assets, accounts and dependents", "Check and update beneficiary nominations", "Make or update a will with qualified local help", "Set up powers of attorney", "Tell the right people where documents are"],
      "Nominations are fast to fix and often the most out of date."),
    C("Review triggers",
      "Revisit estate documents after marriage, separation, a birth, a death in the family, a move to another country or a large change in assets."),
])

MOE9 = L("Capstone: a personal financial plan", KW + ["capstone", "financial plan", "goals", "net worth", "retirement", "plan"], [
    C("One page that ties it together",
      "A personal financial plan states where you are (net worth, cash flow), where you want to go (goals with dates and amounts in today's money), and how you will get there (saving rate, debt plan, investment policy, insurance, estate basics), with the assumptions stated and a date to review. This is an educational template; for major decisions, independent qualified advice can add a lot."),
    NQ("Example: you need {t} in today's money in {y} years and expect a real return of {r}%. How much a month must you save? (Two decimals.)",
       "With a monthly rate of {r}% / 12 over {n} months, the payment is {t} times i / ((1 + i) to the power {n} minus 1), about {A}.",
       {"t": [10000, 200000, 10000], "y": [5, 30, 5], "r": [1, 5, 0.5]}, "t*(r/1200)/((1+r/1200)^(12*y)-1)", {"t": 100000, "y": 20, "r": 3}, rnd=2, tol=0.05,
       show={"n": "12*y"}),
    M("Which assumption is most important to state in a long term plan?",
      ["The color of the spreadsheet", "Expected real return and inflation, since small changes compound over decades", "Today's share prices", "Last year's best fund"], 1,
      "State the rate and test a lower one; plans that only work at optimistic rates are fragile."),
    O("Write the plan, in order.",
      ["Where you are: net worth and monthly cash flow", "Goals with amounts, dates and priorities", "Actions: saving, debt, investing", "Protection: emergency fund, insurance, estate basics", "Assumptions and review date"],
      "Goals before actions; assumptions written so you can tell later what changed."),
    WR("Write a one page plan (real or for an example person). Use lines starting with Net worth:, Cash flow:, Goals:, Saving:, Debt:, Investing:, Protection:, Assumptions: and Review:. Label it as an example if not real.",
       [must("^net worth:.*\\d", "Net worth: with a number", flags="im"),
        must("^cash flow:", "Cash flow:", flags="im"),
        must("^goals:.*\\d", "Goals: with amounts or dates", flags="im"),
        must("^saving:", "Saving:", flags="im"),
        must("^debt:", "Debt:", flags="im"),
        must("^investing:", "Investing:", flags="im"),
        must("^protection:", "Protection:", flags="im"),
        must("^assumptions:.*\\d", "Assumptions: with rates", flags="im"),
        must("^review:", "Review:", flags="im"),
        avoid("guarantee", "No guarantees promised"),
        words(70, 300)],
       "Example only.\nNet worth: 16,000 (assets 38,000, debts 22,000).\nCash flow: take home 3,200 a month; spending 2,700; 500 free.\nGoals: 6 month emergency fund (12,000) in 2 years; card cleared in 8 months; retirement saving ongoing.\nSaving: 250 a month to the emergency fund by automatic transfer.\nDebt: 250 a month extra to the card, avalanche order after.\nInvesting: follow my investment policy statement; 70/30 mix; low costs.\nProtection: review income protection through work; update pension beneficiaries; make a will this year.\nAssumptions: 3% real return, 2.5% inflation, income flat in real terms.\nReview: every January and after any big life change.",
       "A plan you can check: numbers, dates, actions and stated assumptions."),
    C("Expert complete",
      "You can read your balance sheet, compare money across time, understand loans and housing choices, estimate retirement needs with honest caveats, and write a plan that ties it together. Keep the habits: examples labeled, assumptions stated, official sources checked."),
])


def add(courses, picks):
    courses.append(course("money-intermediate", "Money management", "Intermediate", "Money with a plan", "money", "Personal finance", 55,
        "Budgets that last, irregular costs, debt payoff, credit, interest, goals, paychecks and insurance.",
        [("Plan the month", [MOI1, MOI2, MOI3]), ("Credit and interest", [MOI4, MOI5, MOI6]),
         ("Income and protection", [MOI7, MOI8, MOI9])], "money"))
    courses.append(course("money-advanced", "Investing", "Advanced", "Investing with eyes open", "money-intermediate", "Money management", 85,
        "Risk, diversification, allocation, fees, inflation, bonds, tax wrappers and investor behavior.",
        [("Risk and spread", [MOA1, MOA2, MOA3]), ("Costs and rates", [MOA4, MOA5, MOA6]),
         ("Accounts and behavior", [MOA7, MOA8, MOA9])], "money"))
    courses.append(course("money-expert", "Financial planning", "Expert", "Planning the long game", "money-advanced", "Investing", 85,
        "Balance sheets, time value, mortgages, rent or buy, retirement math, sequence risk, insurance, estates and a full plan.",
        [("Where you stand", [MOE1, MOE2, MOE3]), ("Big decisions", [MOE4, MOE5, MOE6]),
         ("Protect and plan", [MOE7, MOE8, MOE9])], "money"))
