"""Spreadsheet ladder: Intermediate, Advanced and Expert courses that
follow "Spreadsheet thinking" (sheets). Learners write real formulas in
write steps (checked for the function, the references and the shape of
the formula, with a model answer), predict results in numeric steps that
re-roll, and reason about tables with worked examples and order steps.
Formulas follow the shared syntax of Google Sheets and current Excel;
where they differ, the lesson says so.
Rebuild with: python3 build_library.py
"""
from ladder_kit import C, W, M, O, L, X, WR, NQ, course, words, must, avoid, lines

KW = ["spreadsheet", "excel", "sheets", "formulas"]


def F(prompt, checks, example, explain):
    """A formula exercise: one formula, starting with =, plus its checks."""
    return WR(prompt, [must("^\\s*=", "Starts with =", hint="Every formula begins with an equals sign.")] + checks
              + [avoid("\\n\\s*\\S", "One formula only, on one line", hint="Write just the formula, nothing on a second line.")],
              example, explain)


# =====================================================================
# Intermediate: Spreadsheets that scale
# =====================================================================

SHI1 = L("Lookups that find the right row", KW + ["xlookup", "vlookup", "lookup", "match", "find"], [
    C("Look it up instead of copying it",
      "A lookup finds a value in one column and returns the matching value from another. XLOOKUP(what, where to look, what to return, if not found) works in current Excel and Google Sheets. The older VLOOKUP(what, table, column number, FALSE) still appears everywhere; its last argument must be FALSE for an exact match, and it can only look to the right of the key column."),
    W("Price a product by its code",
      "Example: Products!A2:A500 holds codes, Products!C2:C500 holds prices. In an order sheet, B2 holds a code.",
      ["XLOOKUP: =XLOOKUP(B2, Products!A2:A500, Products!C2:C500, \"Not found\").",
       "VLOOKUP version: =VLOOKUP(B2, Products!A2:C500, 3, FALSE).",
       "The 3 means the third column of the table A to C.",
       "Without FALSE, VLOOKUP assumes sorted data and can silently return a wrong row."],
      "Exact match, every time, unless you specifically need a range lookup."),
    M("=VLOOKUP(B2, A2:D100, 2) returns a plausible but wrong price. What is the most likely cause?",
      ["The table is too big", "The match type is missing, so it defaults to an approximate match on unsorted data", "Column 2 does not exist", "B2 is text"], 1,
      "The default approximate match quietly returns the nearest smaller key. Add FALSE or use XLOOKUP."),
    F("Write an XLOOKUP that finds the employee ID in A2 within Staff!A:A and returns their department from Staff!D:D, showing Unknown if the ID is missing.",
      [must("xlookup\\(", "Uses XLOOKUP"),
       must("xlookup\\(\\s*\\$?a\\$?2\\s*,", "Looks up the ID in A2"),
       must("staff!\\$?a\\$?:\\$?a", "Searches Staff!A:A"),
       must("staff!\\$?d\\$?:\\$?d", "Returns from Staff!D:D"),
       must("\"unknown\"", "Shows Unknown when not found", hint="The fourth argument is what to show if nothing matches, in quotes.")],
      "=XLOOKUP(A2, Staff!A:A, Staff!D:D, \"Unknown\")",
      "Lookup value, where to look, what to return, and a friendly result when nothing matches."),
    NQ("Example: =VLOOKUP(\"P7\", C2:H50, {k}, FALSE). The table starts at column C, which is column 3 of the sheet. Which sheet column number does it return from?",
       "Column {k} of a table that starts at sheet column 3 is sheet column {A}. VLOOKUP counts from the table's first column, not from A.",
       {"k": [2, 6, 1]}, "k+2", {"k": 4}, rnd=0),
    O("Debug a lookup that returns N/A, in order.",
      ["Check the lookup value really exists in the search column", "Check for extra spaces or numbers stored as text", "Check the ranges cover all the rows", "Check the match type is exact"],
      "Most N/A errors are data problems, not formula problems: a trailing space or a number stored as text."),
    C("Lookups need unique keys",
      "If a code appears twice, a lookup returns the first match and ignores the other. Check uniqueness with COUNTIF(range, value) > 1 before you trust lookups on a column."),
])

SHI2 = L("Text functions that clean data", KW + ["text", "trim", "left", "right", "split", "concatenate", "proper"], [
    C("Text is data too",
      "Imported data often arrives messy: extra spaces, inconsistent capitals, names and codes jammed together. TRIM removes extra spaces, UPPER, LOWER and PROPER fix case, LEFT, RIGHT and MID take pieces, LEN counts characters, FIND locates a character, and the & operator (or TEXTJOIN) joins text. Clean in a new column so the original stays untouched."),
    W("Split a full name",
      "Example: A2 holds \"  ada LOVELACE \". Produce \"Ada Lovelace\" and the first name alone.",
      ["Clean first: =PROPER(TRIM(A2)) gives \"Ada Lovelace\".",
       "Find the space: =FIND(\" \", PROPER(TRIM(A2))) gives 4.",
       "First name: =LEFT(PROPER(TRIM(A2)), FIND(\" \", PROPER(TRIM(A2))) minus 1) gives \"Ada\".",
       "Many spreadsheets also offer SPLIT or Text to columns for simple cases."],
      "Trim and fix case first, then cut."),
    NQ("Example: A2 holds a product code of {n} characters with {k} extra spaces at the end. What does =LEN(TRIM(A2)) return?",
       "TRIM removes the trailing spaces, leaving {A} characters. LEN(A2) alone would give {t}.",
       {"n": [4, 12, 1], "k": [1, 3, 1]}, "n", {"n": 8, "k": 2}, rnd=0, show={"t": "n+k"}),
    F("Write a formula that joins the first name in B2 and the last name in C2 with a single space between them, with extra spaces removed from both.",
      [must("trim\\(", "Uses TRIM"),
       must("b2", "Uses B2"),
       must("c2", "Uses C2"),
       must("(&\\s*\" \"\\s*&|textjoin\\(\\s*\" \"|concat)", "Puts a space between the names", hint="Join with & \" \" & or TEXTJOIN(\" \", ...).")],
      "=TRIM(B2) & \" \" & TRIM(C2)",
      "Trim each part, then join with a space. Joining before trimming can leave double spaces."),
    M("=LEFT(\"INV-2026-0042\", 3) returns...",
      ["INV", "0042", "2026", "INV-"], 0,
      "LEFT takes characters from the start. RIGHT(\"INV-2026-0042\", 4) would give 0042."),
    O("Clean an imported column of names, in order.",
      ["Copy the original into a safe column", "Remove extra spaces with TRIM", "Fix capitals with PROPER", "Check a sample by eye for names PROPER gets wrong, like McDonald"],
      "Automated cleaning is fast and imperfect. A human check on a sample catches the edge cases."),
    C("Numbers stored as text",
      "A column of numbers aligned to the left, or a green triangle in the corner, often means text. Lookups and sums will ignore or mismatch them. VALUE(A2) converts, and so does multiplying by 1."),
])

SHI3 = L("Dates and times", KW + ["dates", "times", "datedif", "networkdays", "eomonth", "weekday"], [
    C("Dates are numbers in disguise",
      "Spreadsheets store dates as day counts from a starting point, formatted to look like dates. That is why you can subtract one date from another to get days, and add 30 to get a date 30 days later. Useful functions: TODAY(), EDATE(date, months), EOMONTH(date, months) for month ends, WEEKDAY, and NETWORKDAYS(start, end) for working days excluding weekends."),
    W("Days overdue",
      "Example: B2 holds an invoice due date. How many days late is it today, showing 0 if not yet due?",
      ["Days since due: =TODAY() minus B2.",
       "Negative means not due yet, so cap at zero: =MAX(0, TODAY() minus B2).",
       "Format the result as a number, not a date, or it will show a strange date.",
       "For working days instead: =NETWORKDAYS(B2, TODAY()) minus 1, if the due date has passed."],
      "Subtract dates for days; wrap in MAX to avoid negatives."),
    NQ("Example: A2 is 1 March and B2 is {d} days later. What does =B2 minus A2 return?",
       "Subtracting dates gives the number of days between them: {A}.",
       {"d": [5, 60, 5]}, "d", {"d": 30}, rnd=0),
    F("Write a formula for the last day of the month that is one month after the date in A2.",
      [must("eomonth\\(", "Uses EOMONTH"),
       must("eomonth\\(\\s*\\$?a\\$?2\\s*,\\s*1\\s*\\)", "Uses A2 and 1 month ahead", hint="EOMONTH(start date, number of months).")],
      "=EOMONTH(A2, 1)",
      "EOMONTH handles 28, 30 and 31 day months and leap years for you."),
    M("A date column shows numbers like 46080 instead of dates. What happened?",
      ["The data is corrupt", "The cells are formatted as numbers; the values are dates stored as day counts", "The year is wrong", "It is a time zone issue"], 1,
      "Change the format to a date format. The underlying values are fine."),
    O("Calculate a payment due date 30 days after an invoice, skipping weekends, in order.",
      ["Put the invoice date in a cell", "Decide whether you mean 30 calendar days or 30 working days", "Use date + 30 for calendar days or WORKDAY(date, 30) for working days", "Format the result as a date"],
      "The business rule decides the function. Ask before you build."),
    C("Text that looks like a date",
      "Imported dates such as 03/04/2026 can mean 3 April or 4 March depending on the region, and may arrive as text. Convert them deliberately, and spot check a few with day numbers above 12."),
])

SHI4 = L("Conditional totals with several conditions", KW + ["sumifs", "countifs", "averageifs", "conditions", "criteria"], [
    C("Totals that answer real questions",
      "SUMIFS(sum range, criteria range 1, criteria 1, criteria range 2, criteria 2, ...) adds only the rows that meet every condition. COUNTIFS and AVERAGEIFS work the same way. Criteria can be values (\"North\"), comparisons (\">=100\"), or built from cells (\">=\" & F1). Note the argument order: SUMIFS puts the sum range first, unlike the older SUMIF."),
    W("Sales by region and month",
      "Example: column A is region, B is month, C is amount. Total North sales in March.",
      ["=SUMIFS(C:C, A:A, \"North\", B:B, \"March\").",
       "With the region in F1 and month in G1: =SUMIFS(C:C, A:A, F1, B:B, G1).",
       "Sales of at least 500 in the North: =SUMIFS(C:C, A:A, \"North\", C:C, \">=500\").",
       "Building criteria from cells makes one formula answer many questions."],
      "Sum range first, then pairs of range and condition."),
    F("Write a formula that counts orders in column B with status \"Shipped\" and an amount in column C over 100.",
      [must("countifs\\(", "Uses COUNTIFS"),
       must("b:b\\s*,\\s*\"shipped\"|b\\$?\\d+:\\$?b\\$?\\d+\\s*,\\s*\"shipped\"", "Status in column B is Shipped"),
       must("c:c\\s*,\\s*\">100\"|c\\$?\\d+:\\$?c\\$?\\d+\\s*,\\s*\">100\"", "Amount in column C is over 100", hint="Comparisons go in quotes: \">100\".")],
      "=COUNTIFS(B:B, \"Shipped\", C:C, \">100\")",
      "Each pair is a range and a condition, and a row counts only if it meets all of them."),
    NQ("Example: amounts for North rows are 120, 80, {a} and {b}. Other regions have different amounts. What does =SUMIFS(C:C, A:A, \"North\", C:C, \">100\") return if {a} and {b} are both over 100?",
       "Only North rows over 100 count: 120 + {a} + {b} = {A}.",
       {"a": [110, 300, 10], "b": [150, 500, 50]}, "120+a+b", {"a": 200, "b": 250}, rnd=0),
    M("=SUMIFS(A:A, \"North\", C:C) returns an error. Why?",
      ["SUMIFS does not exist", "The arguments are in the wrong order: sum range first, then range and criteria pairs", "North needs no quotes", "Column C is empty"], 1,
      "=SUMIFS(C:C, A:A, \"North\") is the right shape."),
    O("Answer a question like total online sales over 50 in Q1, in order.",
      ["Identify the column to add up", "List each condition and the column it applies to", "Write each condition as a range and criteria pair", "Check the result against a filtered view"],
      "Filtering the table by hand once is the fastest check that the formula is right."),
    C("Criteria from cells",
      "Put the condition values in cells and refer to them, such as \">=\" & F1. The report becomes adjustable without editing formulas, and nobody has to hunt for a hardcoded 50 later."),
])

SHI5 = L("Validation keeps data clean", KW + ["data validation", "dropdowns", "clean data", "errors", "input"], [
    C("Stop bad data at the door",
      "Most spreadsheet errors start as data entry: a typo in a category, a date in the wrong format, a negative quantity. Data validation restricts what a cell accepts: a dropdown list, a number range, dates only, or a custom rule. It is far cheaper to stop a bad value than to find it in a total later."),
    M("Your Status column has Shipped, shipped, Shiped and SHIPPED. Which fix prevents this in future?",
      ["Ask people to be careful", "A dropdown list of allowed statuses with data validation", "Bold the column", "Sort it"], 1,
      "Constrained choices remove the possibility of variants. Fix the old values once, then validate."),
    F("Write a custom validation formula for cell C2 that only allows whole numbers from 1 to 100.",
      [must("and\\(", "Combines conditions with AND"),
       must("c2\\s*>=\\s*1|1\\s*<=\\s*c2", "At least 1"),
       must("c2\\s*<=\\s*100|100\\s*>=\\s*c2", "At most 100"),
       must("int\\(\\s*c2\\s*\\)\\s*=\\s*c2|c2\\s*=\\s*int\\(\\s*c2\\s*\\)|mod\\(\\s*c2\\s*,\\s*1\\s*\\)\\s*=\\s*0", "A whole number", hint="INT(C2)=C2 is true only for whole numbers.")],
      "=AND(C2>=1, C2<=100, INT(C2)=C2)",
      "A custom rule must return TRUE for allowed values. This one checks range and wholeness together."),
    NQ("Example: a column of {n} entries had {e} typos in a category before validation. What percent were wrong?",
       "{e} / {n}, times 100, is {A}%.",
       {"n": [200, 1000, 100], "e": [4, 40, 4]}, "e/n*100", {"n": 400, "e": 12}, rnd=1),
    O("Add validation to an existing sheet, in order.",
      ["Find the columns where bad values cause the most trouble", "Clean the existing values first", "Add validation rules with a helpful message", "Test by entering a bad value"],
      "Validation does not fix values already there. Clean, then protect."),
    C("Helpful error messages",
      "Most tools let you write the message shown when a value is rejected. Enter a whole number from 1 to 100 helps more than Invalid."),
])

SHI6 = L("Conditional formatting that informs", KW + ["conditional formatting", "highlight", "color scales", "rules", "visual"], [
    C("Color that carries meaning",
      "Conditional formatting changes a cell's look based on its value: red when overdue, a color scale across sales, a bar inside each cell. Used sparingly it draws the eye to what needs action. Used everywhere it becomes noise. A custom formula rule is written for the top left cell of the range and applied relative to every other cell, so the dollar signs matter just as in normal formulas."),
    W("Highlight whole rows that are overdue",
      "Example: rows 2 to 200, the due date in column D, and a Status in E. Highlight the whole row when it is past due and not Paid.",
      ["Select A2:F200 and add a custom formula rule.",
       "Write it for row 2: =AND($D2 < TODAY(), $E2 <> \"Paid\").",
       "The $ before D and E locks the columns, so every cell in the row checks the same columns.",
       "No $ before 2, so each row checks its own date."],
      "Lock the column, leave the row free."),
    F("Write a custom formatting formula, applied to A2:F100, that highlights a row when the amount in column C is greater than 1000.",
      [must("\\$c\\s*2|\\$c2", "Locks column C but not the row ($C2)", hint="Use $C2: the column stays fixed, the row moves."),
       avoid("\\$c\\$2", "Does not lock the row", hint="$C$2 would check row 2 for every row."),
       must(">\\s*1000", "Compares with 1000")],
      "=$C2>1000",
      "Mixed references are the key skill for formatting rules."),
    M("A rule using =$C$2>1000 on A2:F100 highlights all rows or none. Why?",
      ["The formula is wrong", "$C$2 is fully locked, so every cell checks row 2 only", "Formatting is broken", "1000 is too large"], 1,
      "Unlock the row: $C2."),
    NQ("Example: a color scale runs from {lo} (white) to {hi} (dark). Where does a value of {v} sit, as a percent of the way from low to high?",
       "({v} minus {lo}) / ({hi} minus {lo}), times 100, is {A}%.",
       {"lo": [0, 100, 50], "hi": [500, 1000, 100], "v": [200, 450, 50]}, "(v-lo)/(hi-lo)*100", {"lo": 0, "hi": 1000, "v": 250}, rnd=1),
    O("Design formatting for a report, in order.",
      ["Decide what the reader must notice", "Pick one rule per message, such as overdue rows", "Use a calm palette with one strong alert color", "Check it still reads for color blind users, for example with an icon or a status word too"],
      "Formatting is communication. One clear signal beats five competing ones."),
    C("Do not hide logic in color",
      "If a color means something important, put the same fact in a column too, such as Overdue: Yes. Colors cannot be filtered in every tool, summed, or seen by everyone."),
])

SHI7 = L("Charts that tell the truth", KW + ["charts", "graphs", "visualization", "axis", "bar chart", "line chart"], [
    C("Pick the chart for the question",
      "Line charts show change over time. Bar charts compare categories. Scatter plots show the relationship between two measures. Pie charts work only for a few parts of one whole. Bar charts should start at zero, because the bar's length encodes the value; truncating the axis exaggerates differences. Line charts can zoom in, but label the axis clearly."),
    M("Monthly revenue over two years. Which chart?",
      ["Pie chart", "Line chart", "Scatter plot", "Donut chart"], 1,
      "Time on the horizontal axis, a line for the trend."),
    M("A bar chart's axis starts at 95, so a bar for 98 looks three times as long as one for 96. What is wrong?",
      ["Nothing", "Bars must start at zero, or lengths mislead", "The colors", "It needs a legend"], 1,
      "Readers compare bar lengths. A truncated axis turns a 2% difference into an apparent 3x one."),
    NQ("Example: bars for {a} and {b} on an axis starting at {s}. How many times longer does the second bar look than the first?",
       "Visible lengths: {la} and {lb}. Ratio: {A}, even though the real ratio is {rr}.",
       {"s": [90, 95, 1], "a": [96, 97, 1], "b": [98, 99, 1]}, "(b-s)/(a-s)", {"s": 95, "a": 96, "b": 98}, rnd=2,
       show={"la": "a-s", "lb": "b-s", "rr": "b/a"}),
    WR("Write a chart title that states the finding, not just the topic, for a line chart of support tickets falling from about 400 a week in January to about 250 in June. Keep it under 15 words.",
       [words(4, 15),
        must("(fell|dropped|down|decreased|fewer|cut|halved|declined)", "States the direction of change"),
        must("\\d|january|june|six months|since", "Includes a number or time frame"),
        avoid("^\\s*(support )?tickets( per week| by week)?\\s*$", "Not just the topic")],
       "Support tickets fell from 400 to 250 a week since January",
       "A finding title tells the reader what to see. The chart then proves it."),
    O("Make a chart, in order.",
      ["Write the question the chart answers", "Pick the chart type for that question", "Remove clutter: gridlines, 3D, extra colors", "Title it with the finding and label the axes"],
      "Question first. Most bad charts are good charts of the wrong question."),
    C("Direct labels beat legends",
      "Label lines at their ends instead of using a legend. Readers stop jumping between the legend and the plot."),
])

SHI8 = L("Tables and named ranges", KW + ["tables", "named ranges", "structured references", "ranges", "readability"], [
    C("Give your data a name",
      "Formatting a range as a table (Excel) or using named ranges (both tools) makes formulas easier to read and harder to break. =SUM(Sales[Amount]) or =SUM(Amounts) says what it adds; =SUM(C2:C847) does not, and breaks when row 848 is added outside the range. Tables also expand automatically as you add rows, and formulas in a column fill down by themselves."),
    M("Why does =SUM(C2:C500) give the wrong total after you add 50 new rows at the bottom?",
      ["SUM has a limit", "The fixed range does not include the new rows", "The rows are text", "It is a rounding error"], 1,
      "Tables and named dynamic ranges grow with the data; fixed ranges do not."),
    F("Write a formula that averages the Amount column of a table named Orders, using a structured reference.",
      [must("average\\(", "Uses AVERAGE"),
       must("orders\\[\\s*amount\\s*\\]", "Uses the structured reference Orders[Amount]", hint="Table name, then the column in square brackets.")],
      "=AVERAGE(Orders[Amount])",
      "Readable formulas are maintainable formulas. Anyone can see what this averages."),
    NQ("Example: a table had {r} rows; you add {n} more at the bottom. How many rows does a formula over the whole table column now include?",
       "Tables expand: {r} + {n} = {A}.",
       {"r": [100, 900, 100], "n": [5, 50, 5]}, "r+n", {"r": 500, "n": 20}, rnd=0),
    O("Convert a messy range into a table, in order.",
      ["Make sure there is one header row with unique names", "Remove blank rows and merged cells", "Format the range as a table and name it", "Rewrite key formulas with structured references"],
      "Tables need clean rectangular data: one header row, one record per row, no gaps."),
    C("One table per thing",
      "Keep orders in one table, customers in another, products in a third, and connect them with lookups on IDs. Mixing them in one wide sheet duplicates data and invites inconsistency."),
])

SHI9 = L("Capstone: a budget tracker", KW + ["capstone", "budget", "tracker", "categories", "monthly", "template"], [
    C("Put the level together",
      "A good budget tracker uses everything from this level: a clean transactions table, validated categories, dates you can group by month, conditional totals per category and month, a lookup for each category's budget, formatting that flags overspending, and a chart with a finding. You will design it and write its key formulas."),
    W("The structure",
      "Example layout: a Transactions table with Date, Description, Category, Amount, and a Budgets table with Category and Monthly limit.",
      ["Category in Transactions uses a dropdown from Budgets[Category].",
       "A Month column: =EOMONTH([@Date], -1) + 1 gives the first day of each month.",
       "Spent per category and month: =SUMIFS(Transactions[Amount], Transactions[Category], A2, Transactions[Month], B1).",
       "Remaining: =XLOOKUP(A2, Budgets[Category], Budgets[Monthly limit]) minus that total."],
      "Tables, validation, dates, SUMIFS and a lookup, working together."),
    F("Write the formula for spending in the category in A5 during the month in C1, from a Transactions table with Amount, Category and Month columns.",
      [must("sumifs\\(", "Uses SUMIFS"),
       must("sumifs\\(\\s*transactions\\[\\s*amount\\s*\\]", "Sums Transactions[Amount] first"),
       must("transactions\\[\\s*category\\s*\\]\\s*,\\s*\\$?a\\$?5", "Category matches A5"),
       must("transactions\\[\\s*month\\s*\\]\\s*,\\s*\\$?c\\$?1", "Month matches C1")],
      "=SUMIFS(Transactions[Amount], Transactions[Category], $A5, Transactions[Month], C$1)",
      "Mixed references ($A5 and C$1) let this one formula fill a whole category by month grid."),
    NQ("Example: the Food budget is {b} and spending so far is {s}. What percent of the budget is used? (One decimal.)",
       "{s} / {b}, times 100, is {A}%.",
       {"b": [300, 800, 50], "s": [100, 900, 20]}, "s/b*100", {"b": 500, "s": 420}, rnd=1),
    F("Write a conditional formatting rule for the grid starting at B5 that turns a cell red when spending is more than the budget in column K of the same row.",
      [must("b5", "Refers to B5, the top left cell"),
       must("\\$k5|\\$k\\s*5", "Compares with $K5, column locked", hint="Lock the budget column with $K but let the row move."),
       must(">", "Uses greater than")],
      "=B5>$K5",
      "The rule is written for the top left cell and applies relatively to the rest."),
    O("Build the tracker, in order.",
      ["Create the Budgets table", "Create the Transactions table with a category dropdown", "Add the Month column and the category by month SUMIFS grid", "Add formatting for overspending and a chart with a finding title"],
      "Reference data first, then the data that points at it, then the summaries."),
    C("Intermediate complete",
      "You can build sheets that stay correct as they grow. Advanced moves to analysis: pivots, dynamic arrays, scenarios and financial functions."),
])

# =====================================================================
# Advanced: Spreadsheet analysis
# =====================================================================

SHA1 = L("Pivot tables that answer questions", KW + ["pivot table", "pivot", "summarize", "group", "rows", "values"], [
    C("Summaries without formulas",
      "A pivot table groups rows by one or more fields and summarizes a value: sum of sales by region and month, count of tickets by priority, average order by channel. It needs clean tabular data: one header row, one record per row, consistent categories. The skill is choosing which field goes in rows, columns, values and filters for the question you have."),
    W("Design a pivot",
      "Example question: which product category grew most between Q1 and Q2?",
      ["Rows: Category.",
       "Columns: Quarter (grouped from the order date).",
       "Values: Sum of Amount.",
       "Add a calculated difference column, or show values as a difference from Q1, then sort by it."],
      "Rows for the things you compare, columns for the dimension you compare across."),
    M("A pivot shows Shipped and shipped as separate rows. What is the fix?",
      ["Change the pivot layout", "Clean the source data so the category is consistent, then refresh", "Hide one row", "Use a chart instead"], 1,
      "Pivots summarize exactly what is in the data. Clean upstream."),
    NQ("Example: a pivot shows North {n}, South {s} and West {w} in sales. What percent of the total is North? (One decimal.)",
       "{n} / ({n} + {s} + {w}), times 100, is {A}%. Most pivots can show this directly as percent of total.",
       {"n": [1000, 5000, 500], "s": [1000, 5000, 500], "w": [1000, 5000, 500]}, "n/(n+s+w)*100", {"n": 3000, "s": 2000, "w": 5000}, rnd=1),
    O("Build a pivot for a question, in order.",
      ["Write the question in one sentence", "Check the source is a clean table", "Place fields in rows, columns and values", "Sort, format and check one number against the raw data"],
      "Checking one cell by filtering the source catches most pivot mistakes, such as a value summed when it should be counted."),
    WR("You have a table of support tickets with columns Date, Team, Priority, and Hours to resolve. Describe a pivot that answers: which team is slowest on high priority tickets? Use lines starting with Rows:, Columns:, Values: and Filter:.",
       [must("^rows:.*team", "Teams in rows", flags="im"),
        must("^values:.*(average|mean|median)[^\\n]*hours", "Values: an average (or median) of Hours", flags="im",
             hint="Slowest means typical time, so average Hours, not a sum."),
        must("^filter:.*(priority|high)", "Filter to high priority", flags="im"),
        must("^columns:", "A Columns: line (it can say none)", flags="im")],
       "Rows: Team\nColumns: none\nValues: Average of Hours to resolve\nFilter: Priority = High",
       "Sum of hours would reward teams with fewer tickets. Average or median answers slowest."),
    C("Pivots are for exploring, formulas for reports",
      "Pivots are fast for answering questions. For a report that must look the same every month, a formula grid (SUMIFS) or a pivot with locked layout is easier to keep stable."),
])

SHA2 = L("Dynamic arrays: FILTER, SORT, UNIQUE", KW + ["filter", "sort", "unique", "dynamic arrays", "spill", "array formulas"], [
    C("One formula, many results",
      "Dynamic array functions return a whole range that spills into neighboring cells. FILTER(range, condition) returns matching rows; SORT(range, column, order) sorts; UNIQUE(range) removes duplicates. They work in Google Sheets and current Excel. They update as data changes, which replaces many manual sort and copy steps. A spill needs empty cells to land in, or it shows an error."),
    W("A live list of late orders",
      "Example: Orders in A2:D500, status in column D, due date in C.",
      ["Late orders: =FILTER(A2:D500, (D2:D500 <> \"Delivered\") * (C2:C500 < TODAY())).",
       "Multiplying conditions means AND; adding them means OR.",
       "Sorted by due date: =SORT(FILTER(...), 3, TRUE).",
       "Distinct customers among them: =UNIQUE(INDEX(FILTER(...), 0, 1))."],
      "Conditions multiply for AND; wrap with SORT and UNIQUE as needed."),
    F("Write a FILTER formula that returns rows of A2:E300 where the region in column B is \"North\" and the amount in column E is at least 500.",
      [must("filter\\(", "Uses FILTER"),
       must("a2:e300", "Returns A2:E300"),
       must("\\(\\s*b2:b300\\s*=\\s*\"north\"\\s*\\)", "Condition: B2:B300 = \"North\" in brackets"),
       must("\\(\\s*e2:e300\\s*>=\\s*500\\s*\\)", "Condition: E2:E300 >= 500 in brackets"),
       must("\\)\\s*\\*\\s*\\(", "Conditions multiplied for AND", hint="Put each condition in brackets and multiply them.")],
      "=FILTER(A2:E300, (B2:B300=\"North\") * (E2:E300>=500))",
      "Each condition gives TRUE or FALSE per row; multiplying keeps rows where both are TRUE."),
    NQ("Example: a column has {n} values of which {d} are repeats of earlier values. How many rows does UNIQUE return?",
       "{n} minus {d} = {A}.",
       {"n": [20, 200, 10], "d": [2, 18, 2]}, "n-d", {"n": 50, "d": 12}, rnd=0),
    M("A FILTER formula shows a spill error. What is the most likely cause?",
      ["FILTER is not supported", "Something is in the cells where the results need to spill", "Too many conditions", "The range is sorted"], 1,
      "Clear the cells below and to the right, or move the formula."),
    O("Replace a manual weekly copy and sort job, in order.",
      ["Describe the rows you want and their order", "Write FILTER for the rows", "Wrap it in SORT", "Put it on its own sheet with nothing below it"],
      "A formula that rebuilds the list every time removes the weekly chance of a copy mistake."),
    C("FILTER with no matches",
      "If nothing matches, FILTER returns an error. Its optional third argument sets what to show instead, such as \"No late orders\"."),
])

SHA3 = L("INDEX and MATCH in two dimensions", KW + ["index", "match", "two way lookup", "xmatch", "lookup"], [
    C("Find the row, find the column, return the cell",
      "INDEX(range, row number, column number) returns the cell at that position. MATCH(value, range, 0) returns the position of a value in a row or column (0 means exact). Together they make a two way lookup: =INDEX(B2:M20, MATCH(product, A2:A20, 0), MATCH(month, B1:M1, 0)). XMATCH is a newer version of MATCH. This pattern works in every spreadsheet tool and does not break when columns are inserted."),
    W("Price for a size and color",
      "Example: B2:E6 holds prices, sizes in A2:A6, colors in B1:E1. Find the price of size M in Blue.",
      ["Row: =MATCH(\"M\", A2:A6, 0), say 3.",
       "Column: =MATCH(\"Blue\", B1:E1, 0), say 2.",
       "Price: =INDEX(B2:E6, 3, 2).",
       "All together: =INDEX(B2:E6, MATCH(\"M\", A2:A6, 0), MATCH(\"Blue\", B1:E1, 0))."],
      "Two MATCHes give the coordinates; INDEX fetches the cell."),
    F("Write a two way lookup that returns the value from B2:M50 for the product in P1 (products listed in A2:A50) and the month in P2 (months listed in B1:M1).",
      [must("index\\(\\s*\\$?b\\$?2:\\$?m\\$?50", "INDEX over B2:M50"),
       must("match\\(\\s*\\$?p\\$?1\\s*,\\s*\\$?a\\$?2:\\$?a\\$?50\\s*,\\s*0\\s*\\)", "MATCH the product in A2:A50, exact"),
       must("match\\(\\s*\\$?p\\$?2\\s*,\\s*\\$?b\\$?1:\\$?m\\$?1\\s*,\\s*0\\s*\\)", "MATCH the month in B1:M1, exact")],
      "=INDEX(B2:M50, MATCH(P1, A2:A50, 0), MATCH(P2, B1:M1, 0))",
      "Row from the products, column from the months, value from the grid."),
    NQ("Example: =MATCH(\"Apr\", B1:M1, 0) where B1:M1 holds Jan to Dec. If the month were the {k}th month, what would MATCH return?",
       "MATCH returns the position within the range: {A}.",
       {"k": [1, 12, 1]}, "k", {"k": 4}, rnd=0),
    M("Why can INDEX MATCH be safer than VLOOKUP with a column number?",
      ["It is faster to type", "Inserting a column inside the table does not shift what it returns, because it refers to the return range directly", "It works only on sorted data", "It ignores blanks"], 1,
      "VLOOKUP's hard coded 3 points at whatever is now the third column."),
    O("Build a two way lookup, in order.",
      ["Identify the grid of values", "Identify the row labels and column labels", "Write a MATCH for each, with exact matching", "Wrap both in INDEX over the grid"],
      "Make sure the label ranges line up with the grid's edges, or every result is shifted by one."),
    C("Labels must line up",
      "If the grid starts at row 2, the row labels must start at row 2 too. An off by one range is the classic INDEX MATCH bug, and it returns plausible wrong values."),
])

SHA4 = L("What if: scenarios and goal seek", KW + ["what if", "scenarios", "goal seek", "data table", "assumptions", "inputs"], [
    C("Inputs in one place, then play",
      "Put assumptions in clearly labeled input cells and point every formula at them. Then you can ask what if: change the price and watch profit. Goal seek works backwards: find the input that makes an output hit a target. A data table or a simple grid of formulas shows the output across a range of one or two inputs at once."),
    W("Break even by goal seek",
      "Example: B1 price, B2 units, B3 unit cost, B4 fixed cost. Profit in B5: =B2*(B1 minus B3) minus B4. Find the units that make profit zero.",
      ["Goal seek: set B5 to 0 by changing B2.",
       "With price 25, cost 15, fixed 4,000, it finds B2 = 400.",
       "Check: 400 times 10 minus 4,000 = 0.",
       "The same answer comes from algebra: fixed / (price minus cost)."],
      "Goal seek solves the equation for you; check it with a quick calculation."),
    NQ("Example: profit = units times ({p} minus {c}) minus {f}. Goal seek sets profit to 0 by changing units. What value does it find?",
       "{f} / ({p} minus {c}) = {A}.",
       {"p": [20, 40, 5], "c": [5, 15, 5], "f": [2000, 8000, 1000]}, "f/(p-c)", {"p": 25, "c": 15, "f": 4000}, rnd=2, tol=0.01),
    F("Write the profit formula for B5 using inputs: price in B1, units in B2, unit cost in B3, fixed cost in B4.",
      [must("b2", "Uses units B2"),
       must("\\(\\s*b1\\s*-\\s*b3\\s*\\)", "Price minus unit cost in brackets"),
       must("-\\s*b4\\s*$", "Subtracts fixed cost B4 at the end"),
       avoid("\\b\\d{2,}\\b", "No hardcoded numbers", hint="Point at the input cells instead of typing numbers.")],
      "=B2*(B1-B3)-B4",
      "No numbers inside the formula: every assumption lives in a labeled cell."),
    M("Why keep assumptions out of formulas?",
      ["It looks nicer", "So changing an assumption updates everything, and nobody misses a hardcoded number buried in a formula", "Formulas cannot hold numbers", "It is faster to calculate"], 1,
      "Hardcoded numbers are the most common source of stale, inconsistent models."),
    O("Run a what if analysis, in order.",
      ["Move every assumption into labeled input cells", "Point formulas at those cells", "Change one input at a time, or build a small grid of cases", "Write down which inputs move the result most"],
      "Inputs first. Scenario analysis on a sheet full of hardcoded numbers is a hunt, not an analysis."),
    C("Color your inputs",
      "A common convention: inputs in one color (often blue text), formulas in black. Anyone can see at a glance what they are allowed to change."),
])

SHA5 = L("Financial functions: PMT, FV, NPV", KW + ["pmt", "fv", "npv", "loan", "payment", "present value", "financial functions"], [
    C("Time value of money, built in",
      "PMT(rate per period, number of periods, present value) gives a loan payment. FV(rate, periods, payment, present value) gives a future value of regular saving. NPV(rate, cash flows) discounts future cash flows to today. Two rules prevent most mistakes: use the rate per period (an annual rate divided by 12 for monthly payments) and the number of periods in the same unit. Money you pay out is negative by convention, so PMT returns a negative number for a loan you receive."),
    W("A car loan payment",
      "Example: borrow 20,000 at 6% a year for 5 years, paid monthly.",
      ["Rate per month: 6% / 12 = 0.5%.",
       "Periods: 5 times 12 = 60.",
       "=PMT(0.06/12, 60, 20000) returns about minus 386.66.",
       "Total paid: 60 times 386.66, about 23,200, so about 3,200 is interest."],
      "Monthly rate, monthly periods, and expect a negative sign."),
    NQ("Example: =PMT({r}%/12, {y}*12, {p}). What is the monthly payment, as a positive number? (Two decimals.)",
       "With monthly rate {mr} and {n} payments, the payment is about {A}.",
       {"r": [3, 9, 1], "y": [3, 6, 1], "p": [10000, 30000, 5000]}, "p*(r/1200)/(1-(1+r/1200)^(-y*12))", {"r": 6, "y": 5, "p": 20000}, rnd=2, tol=0.05,
       show={"mr": "r/1200", "n": "y*12"}),
    F("Write a formula for the future value of saving 200 a month for 10 years at 5% a year, compounded monthly, starting from zero. Treat the deposits as money paid out.",
      [must("fv\\(", "Uses FV"),
       must("fv\\(\\s*(0?\\.05|5%)\\s*/\\s*12", "Monthly rate: 5% / 12"),
       must(",\\s*(10\\s*\\*\\s*12|120)\\s*,", "120 monthly periods"),
       must(",\\s*-\\s*200", "Payment of minus 200 (paid out)", hint="Deposits leave your pocket, so enter them as negative to get a positive future value.")],
      "=FV(5%/12, 120, -200, 0)",
      "About 31,056. The sign convention trips everyone once; now you know why."),
    NQ("Example: =NPV({r}%, {c}, {c}, {c}) for three yearly cash flows of {c} starting one year from now. What is the present value? (Two decimals.)",
       "{c} discounted for 1, 2 and 3 years at {r}% adds up to about {A}.",
       {"r": [3, 10, 1], "c": [500, 3000, 500]}, "c/(1+r/100)+c/(1+r/100)^2+c/(1+r/100)^3", {"r": 5, "c": 1000}, rnd=2, tol=0.05),
    M("NPV in spreadsheets assumes the first cash flow comes...",
      ["Today", "One period from now", "At the end of the project", "It depends on the sign"], 1,
      "That is why an upfront cost today is usually added outside: =NPV(rate, later flows) + initial flow."),
    O("Price a loan, in order.",
      ["Convert the annual rate to a rate per payment period", "Convert the term to the number of payments", "Use PMT with the amount borrowed", "Multiply the payment by the number of payments to see total interest"],
      "Matching units is the whole game. Annual rate with monthly periods gives a payment twelve times too high."),
])

SHA6 = L("Errors you expect and errors you hide", KW + ["iferror", "ifna", "errors", "na", "div0", "error handling"], [
    C("Handle expected errors, surface unexpected ones",
      "Spreadsheet errors are signals: N/A means a lookup found nothing, DIV/0 means you divided by zero, VALUE means wrong data type, REF means a reference was deleted. IFNA(formula, fallback) handles only N/A, which is usually what you expect from lookups. IFERROR catches everything, including real mistakes, so wrapping every formula in IFERROR can hide broken references and wrong data."),
    M("A lookup returns N/A for new products that are not in the price list yet. Which handling is best?",
      ["IFERROR(..., 0)", "IFNA(..., \"Not priced\")", "Delete the formula", "Ignore it"], 1,
      "IFNA catches the expected missing case with a clear label and still lets other errors show. A silent 0 would quietly understate totals."),
    F("Write a formula that divides the total in B2 by the count in C2, showing a blank (\"\") when C2 is zero, without using IFERROR.",
      [must("if\\(", "Uses IF"),
       must("c2\\s*=\\s*0|c2\\s*<>\\s*0|c2\\s*>\\s*0", "Tests C2 for zero"),
       must("b2\\s*/\\s*c2", "Divides B2 by C2"),
       must("\"\"", "Shows a blank"),
       avoid("iferror", "Does not use IFERROR")],
      "=IF(C2=0, \"\", B2/C2)",
      "Testing the specific condition documents the intent and lets any other error still show."),
    NQ("Example: a report has {n} lookup rows; {m} products are missing from the price list. If each missing price were silently replaced by 0 with IFERROR, how many rows would show a wrong 0?",
       "All {A} missing rows would show 0 and quietly understate totals.",
       {"n": [100, 500, 50], "m": [2, 30, 2]}, "m", {"n": 200, "m": 8}, rnd=0),
    O("Clean up a sheet full of IFERROR, in order.",
      ["Remove the IFERROR wrappers temporarily", "See which errors appear and why", "Fix the real causes, such as bad references", "Add targeted handling (IFNA or IF tests) only for expected cases"],
      "Errors are information. Hiding them all at once removes the sheet's own warning system."),
    C("Count your errors",
      "A check cell such as =SUMPRODUCT(--ISERROR(A2:Z500)) counts errors in a range. Put it at the top of a model; it should say zero."),
])

SHA7 = L("Cleaning messy imports", KW + ["cleaning", "imports", "csv", "duplicates", "split", "data quality"], [
    C("Most analysis time is cleaning",
      "Exports from other systems arrive with merged headers, totals rows in the middle, inconsistent dates, duplicates, trailing spaces and numbers stored as text. A repeatable cleaning process beats heroic manual fixes: keep the raw import untouched on one sheet, and build a clean version with formulas or a documented series of steps, so next month's import can follow the same path."),
    W("A typical cleaning pass",
      "Example import: 2,000 rows, a header on row 3, a subtotal every 50 rows, amounts like \"1,234.50 \" as text.",
      ["Keep Raw as it came. Work in a Clean sheet.",
       "Remove subtotal rows: FILTER rows where the ID column is not blank and not \"Subtotal\".",
       "Convert amounts: =VALUE(TRIM(SUBSTITUTE(D2, \",\", \"\"))).",
       "Remove duplicates by ID with UNIQUE or a COUNTIF check, then compare row counts and totals with the source."],
      "Raw stays raw; clean with steps you can repeat; reconcile totals."),
    NQ("Example: the raw file has {r} rows including {s} subtotal rows and {d} exact duplicates. How many rows should the clean table have?",
       "{r} minus {s} minus {d} = {A}.",
       {"r": [500, 3000, 100], "s": [5, 60, 5], "d": [0, 20, 2]}, "r-s-d", {"r": 2000, "s": 40, "d": 6}, rnd=0),
    F("Write a formula that converts the text amount in D2, which may contain thousands commas and trailing spaces, into a number.",
      [must("value\\(", "Uses VALUE (or a numeric conversion)"),
       must("trim\\(", "Removes spaces with TRIM"),
       must("substitute\\(\\s*\\$?d\\$?2\\s*,\\s*\",\"\\s*,\\s*\"\"\\s*\\)|substitute\\(\\s*trim\\(\\s*\\$?d\\$?2\\s*\\)\\s*,\\s*\",\"\\s*,\\s*\"\"\\s*\\)", "Removes the commas with SUBSTITUTE", hint="SUBSTITUTE(D2, \",\", \"\") deletes every comma.")],
      "=VALUE(TRIM(SUBSTITUTE(D2, \",\", \"\")))",
      "Remove the characters that block conversion, then convert."),
    M("After cleaning, the total of the Amount column differs from the source system's total by 1,250. What next?",
      ["Adjust a number to make it match", "Find which rows explain the gap, for example removed duplicates or a row that failed to convert", "Ignore it", "Round everything"], 1,
      "Reconciliation is how you prove the cleaning did not lose or invent data. Every difference needs an explanation."),
    O("Clean an import, in order.",
      ["Keep the raw data untouched", "Remove non data rows such as headers and subtotals", "Fix types and formats", "Remove duplicates and reconcile counts and totals with the source"],
      "Reconciliation is last because every earlier step can change the totals."),
    C("Write the steps down",
      "A short list of cleaning steps at the top of the sheet turns next month's job from an hour of remembering into ten minutes of following."),
])

SHA8 = L("Dashboards people read", KW + ["dashboard", "kpi", "report", "layout", "summary", "visual"], [
    C("A dashboard answers a few questions fast",
      "A useful dashboard shows a small number of key figures, compared with something (target, last period), with the most important at the top left where eyes land first. Each chart has a finding title. Everything else (filters, detail tables) goes below or on another sheet. If it needs a guided tour, it is too busy."),
    M("Which key figure is most useful on a dashboard?",
      ["Revenue: 84,210", "Revenue: 84,210, 6% above target, up 3% on last month", "Revenue (see sheet 4)", "A table of every order"], 1,
      "A number needs a comparison to mean anything at a glance."),
    NQ("Example: revenue is {r} against a target of {t}. What percent of target is that? (One decimal.)",
       "{r} / {t}, times 100, is {A}%.",
       {"r": [60000, 120000, 2000], "t": [80000, 100000, 5000]}, "r/t*100", {"r": 84000, "t": 80000}, rnd=1),
    F("Write a formula for a dashboard cell that shows the change from last month (B3) to this month (B2) as a percentage, as a number, not text.",
      [must("b2", "Uses this month B2"),
       must("b3", "Uses last month B3"),
       must("\\(\\s*b2\\s*-\\s*b3\\s*\\)\\s*/\\s*b3|b2\\s*/\\s*b3\\s*-\\s*1", "Change divided by last month", hint="(this minus last) / last, then format as percent.")],
      "=(B2-B3)/B3",
      "Keep it a number and format it as a percent, so it can be colored, charted and compared."),
    O("Design a one screen dashboard, in order.",
      ["List the three to five questions it must answer", "Choose one key figure or chart per question", "Place the most important at the top left", "Add comparisons and finding titles, then cut anything that answers no question"],
      "Start from questions, not from available data. Available data is endless; attention is not."),
    WR("List the key figures for a dashboard for a small online shop's owner, one per line, each with its comparison, such as: Orders this week, versus last week.",
       [lines(3, "At least three key figures"),
        must("(versus|vs|compared|against|target|last)", "Each has a comparison"),
        words(12, 120)],
       "Revenue this week, versus last week and target\nOrders this week, versus last week\nConversion rate, versus the last four weeks' average\nRefunds this week, versus last week",
       "Each figure answers is this good or bad, which is the point of a dashboard."),
    C("Same layout every time",
      "Readers learn where things are. Keep positions stable between versions; move things only when the questions change."),
])

SHA9 = L("Capstone: a sales analysis", KW + ["capstone", "analysis", "sales", "report", "insight"], [
    C("Put the level together",
      "You will analyze a sales table from question to recommendation: clean it, summarize it with a pivot or SUMIFS, pull the details with FILTER and lookups, model a what if, and write up the finding with a chart title and a number."),
    W("From question to answer",
      "Example question: which channel should get more marketing budget next quarter?",
      ["Clean the orders table and reconcile its total with the source.",
       "Pivot: revenue and orders by channel and month; add average order value.",
       "What if: if each channel's spend rose 10%, what return would you expect at its current revenue per unit of spend?",
       "Finding: email has the highest revenue per unit of spend and stable growth; recommend shifting some budget to it, and test before going further."],
      "Question, clean, summarize, model, recommend."),
    NQ("Example: a channel had {s} in spend and {r} in revenue. What is revenue per unit of spend? (Two decimals.)",
       "{r} / {s} = {A}.",
       {"s": [1000, 8000, 500], "r": [2000, 40000, 1000]}, "r/s", {"s": 4000, "r": 18000}, rnd=2),
    F("Write a formula for average order value for the channel in A2: total of Orders[Amount] for that channel divided by the number of its orders.",
      [must("sumifs\\(\\s*orders\\[\\s*amount\\s*\\]\\s*,\\s*orders\\[\\s*channel\\s*\\]\\s*,\\s*\\$?a\\$?2\\s*\\)", "SUMIFS of Amount for the channel in A2"),
       must("countifs?\\(\\s*orders\\[\\s*channel\\s*\\]\\s*,\\s*\\$?a\\$?2\\s*\\)", "COUNTIFS of orders for the channel"),
       must("\\)\\s*/\\s*countif", "Divides the total by the count")],
      "=SUMIFS(Orders[Amount], Orders[Channel], A2) / COUNTIFS(Orders[Channel], A2)",
      "A total over a count. AVERAGEIFS would give the same answer in one function."),
    O("Present the analysis, in order.",
      ["The recommendation in one sentence", "The key number that supports it", "The chart with a finding title", "Caveats and the next test"],
      "Answer first. Readers who need the method will find it below."),
    WR("Write the summary of a sales analysis (real or using the example) in 40 to 120 words. Include the recommendation, at least one number, one caveat and the next step.",
       [words(40, 120),
        must("(recommend|should|suggest|propose)", "Gives a recommendation"),
        must("\\d", "Includes a number"),
        must("(caveat|however|but|although|note that|assum|limit)", "Includes a caveat"),
        must("(next|test|trial|pilot|check)", "Names the next step")],
       "We recommend moving some paid social budget to email next quarter. Email returned 4.50 in revenue per unit of spend, against 2.10 for paid social, and grew every month. However, email depends on our list size, which may not scale with more spend. Next, we will test a 10% budget shift for one month and compare.",
       "Recommendation, evidence, honest limits and a test. That is analysis people can act on."),
    C("Advanced complete",
      "You can turn raw tables into decisions. Expert is about building spreadsheets that others can trust and maintain: structure, LET and LAMBDA, checks and forecasting."),
])

# =====================================================================
# Expert: Spreadsheet engineering
# =====================================================================

SHE1 = L("Model structure: inputs, calculations, outputs", KW + ["model structure", "inputs", "outputs", "layout", "financial model", "best practice"], [
    C("Separate what you assume from what you compute",
      "Reliable models keep three things apart: inputs (assumptions, clearly labeled, one place each), calculations (formulas only, no typed numbers), and outputs (the results people read). Flow runs one way, inputs to calculations to outputs, usually left to right or top to bottom. Each row uses one consistent formula across its columns, so a single check of one cell tells you the whole row is right."),
    M("A model has the tax rate typed into 14 different formulas. What is the main risk?",
      ["Slower calculation", "When the rate changes, someone updates 13 of them and the model is silently inconsistent", "The file gets bigger", "None"], 1,
      "One assumption, one cell. Every formula refers to it."),
    M("Which layout rule makes a model easiest to check?",
      ["Different formulas in each column for flexibility", "One consistent formula per row across all time periods", "Hide the calculation sheet", "Merge cells for headings"], 1,
      "Consistent rows mean reviewing one cell reviews the row. A break in the pattern is a red flag worth investigating."),
    WR("Sketch the structure of a model for a small subscription business. Use lines starting with Inputs:, Calculations: and Outputs:, and list at least three items in each.",
       [must("^inputs:[^\\n]*,[^\\n]*,", "At least three inputs", flags="im"),
        must("^calculations:[^\\n]*,[^\\n]*,", "At least three calculations", flags="im"),
        must("^outputs:[^\\n]*,[^\\n]*,", "At least three outputs", flags="im"),
        words(20, 150)],
       "Inputs: price per month, new customers per month, monthly churn rate, cost per customer, fixed costs\nCalculations: active customers, revenue, variable costs, profit by month\nOutputs: monthly profit chart, break even month, customers after 12 months",
       "Inputs you can argue about, calculations nobody types into, outputs people read."),
    NQ("Example: a model has {r} calculation rows over {c} monthly columns. If every row uses one consistent formula, how many distinct formulas must a reviewer check?",
       "One per row: {A}, instead of {t} cells.",
       {"r": [10, 60, 5], "c": [12, 60, 12]}, "r", {"r": 25, "c": 36}, rnd=0, show={"t": "r*c"}),
    O("Restructure a messy model, in order.",
      ["Find every typed number inside formulas", "Move each one into a labeled input cell", "Make each calculation row consistent across columns", "Add an outputs section that only references calculations"],
      "Inputs first, because consistency is impossible while assumptions are scattered through formulas."),
    C("Document as you go",
      "A short notes column beside inputs, with source and date (customer survey, March), saves every future reader from guessing where a number came from."),
])

SHE2 = L("LET and LAMBDA", KW + ["let", "lambda", "named functions", "reuse", "readability", "custom functions"], [
    C("Name the parts of a formula",
      "LET(name, value, ..., result) names intermediate values inside a formula, so a long formula reads like steps and repeated parts are computed once. LAMBDA(parameters, calculation) defines a reusable function; saved with a name (Name Manager in Excel, Named functions in Google Sheets), it can be called like a built in function. Both work in current Excel and Google Sheets."),
    W("LET makes a formula readable",
      "Example: price after discount and tax, where the discount applies only over 100.",
      ["Without LET: =IF(B2>100, B2*0.9, B2)*1.2.",
       "With LET: =LET(base, B2, discounted, IF(base>100, base*0.9, base), discounted*1.2).",
       "Each step has a name, and base is read once.",
       "As a LAMBDA named FINALPRICE: =LAMBDA(p, LET(d, IF(p>100, p*0.9, p), d*1.2)), then =FINALPRICE(B2)."],
      "LET names the steps; LAMBDA makes them reusable."),
    F("Write a LET formula that names the total in B2 as total and the count in C2 as n, and returns total divided by n.",
      [must("let\\(", "Uses LET"),
       must("let\\(\\s*total\\s*,\\s*\\$?b\\$?2", "Names total as B2"),
       must("n\\s*,\\s*\\$?c\\$?2", "Names n as C2"),
       must("total\\s*/\\s*n\\s*\\)\\s*$", "Returns total / n")],
      "=LET(total, B2, n, C2, total / n)",
      "Short here, but the same pattern turns a 300 character formula into something a colleague can read."),
    NQ("Example: =LET(x, {a}, y, x*{b}, y+x). What does it return?",
       "x is {a}, y is {a} times {b} = {y}, and y + x = {A}.",
       {"a": [2, 20, 1], "b": [2, 9, 1]}, "a*b+a", {"a": 5, "b": 3}, rnd=0, show={"y": "a*b"}),
    M("When is a named LAMBDA most worthwhile?",
      ["For a calculation used once", "For a business rule used in many places, so it is defined once and changed once", "To hide formulas from colleagues", "Never"], 1,
      "One definition of how we calculate commission beats forty copies of the formula drifting apart."),
    O("Turn a repeated formula into a named function, in order.",
      ["Find the calculation repeated across the workbook", "Rewrite it with LET so the steps are named", "Wrap it in LAMBDA with parameters and test it in a cell", "Save it with a name and replace the copies"],
      "Test before naming. A LAMBDA tried in a cell with sample arguments is easy to debug; a saved one is harder."),
    C("Readable beats clever",
      "Dense one cell formulas impress nobody six months later. Names, steps and a helper column are often the professional choice."),
])

SHE3 = L("Thinking in arrays", KW + ["arrays", "sumproduct", "array formulas", "byrow", "map", "vectorized"], [
    C("Operate on whole ranges at once",
      "Array thinking means writing one formula that operates on whole ranges instead of filling a helper column. SUMPRODUCT(range1, range2) multiplies pairs and adds them, which gives weighted totals in one cell. Comparisons on ranges produce arrays of TRUE and FALSE that you can multiply as 1s and 0s. Newer functions like MAP and BYROW apply a LAMBDA to each element or row."),
    W("Revenue without a helper column",
      "Example: quantities in B2:B100 and prices in C2:C100.",
      ["Helper approach: D2 = B2*C2, filled down, then =SUM(D2:D100).",
       "Array approach: =SUMPRODUCT(B2:B100, C2:C100).",
       "With a condition, only region North in A: =SUMPRODUCT((A2:A100=\"North\") * B2:B100 * C2:C100).",
       "The TRUE and FALSE from the comparison act as 1 and 0, keeping only North rows."],
      "Multiply ranges, let conditions act as 1 and 0."),
    NQ("Example: quantities {a}, {b}, {c} and prices 2, 5, 10. What does SUMPRODUCT of the two ranges return?",
       "{a} times 2 + {b} times 5 + {c} times 10 = {A}.",
       {"a": [1, 10, 1], "b": [1, 10, 1], "c": [1, 10, 1]}, "2*a+5*b+10*c", {"a": 3, "b": 4, "c": 2}, rnd=0),
    F("Write a SUMPRODUCT formula for the weighted average score: scores in B2:B20, weights in C2:C20.",
      [must("sumproduct\\(\\s*\\$?b\\$?2:\\$?b\\$?20\\s*,\\s*\\$?c\\$?2:\\$?c\\$?20\\s*\\)|sumproduct\\(\\s*\\$?c\\$?2:\\$?c\\$?20\\s*,\\s*\\$?b\\$?2:\\$?b\\$?20\\s*\\)", "SUMPRODUCT of scores and weights"),
       must("/\\s*sum\\(\\s*\\$?c\\$?2:\\$?c\\$?20\\s*\\)", "Divided by the sum of the weights")],
      "=SUMPRODUCT(B2:B20, C2:C20) / SUM(C2:C20)",
      "Weighted total over total weight. One cell, no helper column."),
    M("What does =SUM((A2:A10>5)*1) compute in a spreadsheet that evaluates arrays?",
      ["The sum of values over 5", "How many values are over 5", "The largest value", "An error always"], 1,
      "Each comparison is TRUE or FALSE; times 1 makes 1 or 0; the sum counts the TRUEs. COUNTIF does the same more readably."),
    O("Replace a helper column with an array formula, in order.",
      ["Write what the helper column computes per row", "Express it as an operation on whole ranges", "Wrap it in the aggregate you need, such as SUM", "Check it against the helper column before deleting it"],
      "Keep the helper until the array version matches it exactly."),
    C("Arrays are not always better",
      "A visible helper column is easier to audit than a dense array formula. Choose arrays when they make the logic clearer or the sheet smaller, not to show off."),
])

SHE4 = L("Checks and auditing", KW + ["auditing", "checks", "errors", "reconciliation", "trace precedents", "testing"], [
    C("Make the model check itself",
      "Real spreadsheets contain errors far more often than their authors expect, so professionals build checks into the model: totals that must match (sum of regions equals the grand total), balances that must be zero, row counts that must equal the source, and a single check cell that shows OK only when every check passes. Trace precedents and dependents tools show where a cell's inputs come from."),
    W("A check panel",
      "Example: a model with regional sales and a grand total.",
      ["Check 1: =ABS(SUM(Regions) minus GrandTotal) < 0.01.",
       "Check 2: =COUNTA(Clean[ID]) = COUNTA(Raw[ID]) minus removed rows.",
       "Check 3: =SUMPRODUCT(--ISERROR(Calc!A1:Z500)) = 0.",
       "Master: =IF(AND(Check1, Check2, Check3), \"OK\", \"CHECK FAILED\"), shown at the top of every sheet."],
      "Small tolerance for rounding, a count reconciliation, an error count, one master cell."),
    F("Write a check formula that returns TRUE when the sum of B2:B10 equals the total in B11 to within 0.01.",
      [must("abs\\(", "Uses ABS for the difference"),
       must("sum\\(\\s*\\$?b\\$?2:\\$?b\\$?10\\s*\\)", "Sums B2:B10"),
       must("b11", "Compares with B11"),
       must("<\\s*0?\\.01", "Within 0.01")],
      "=ABS(SUM(B2:B10)-B11)<0.01",
      "Comparing decimals exactly can fail on rounding; a tolerance avoids false alarms."),
    NQ("Example: a check panel has {n} independent checks. If each one has a {p}% chance of catching a given kind of error, what is the chance at least one catches it? (One decimal.)",
       "Chance all miss: ({q}) to the power {n}. At least one catches: {A}%.",
       {"n": [2, 5, 1], "p": [30, 70, 10]}, "(1-(1-p/100)^n)*100", {"n": 3, "p": 50}, rnd=1, show={"q": "1-p/100"}),
    M("A total looks right but you suspect a formula skipped a row. What is the fastest way to find it?",
      ["Retype everything", "Look for breaks in the formula pattern down the column, for example with a formula view or trace precedents", "Delete the column", "Trust it"], 1,
      "Showing formulas (Ctrl plus backtick in many tools) reveals the odd one out immediately."),
    O("Review someone else's model, in order.",
      ["Read the inputs and their sources", "Check that formulas are consistent along each row", "Trace the key outputs back to their inputs", "Test extreme inputs, such as zero sales, and see if outputs make sense"],
      "Extreme inputs are a great test: a model that shows profit with zero sales has a bug."),
    C("A second pair of eyes",
      "Have someone else review any model a real decision depends on. Authors read what they meant to write; reviewers read what is there."),
])

SHE5 = L("Versions, documentation and handover", KW + ["documentation", "versions", "handover", "change log", "collaboration", "maintenance"], [
    C("A model outlives its author",
      "Spreadsheets get passed on. A model that only its author understands is a risk. Good practice: a cover sheet with purpose, owner, how to update it and known limits; a change log with date, change and author; clear sheet names in flow order; and saved versions or version history before big changes. If several people edit, agree who owns which sheet."),
    M("Which cover sheet line is most useful to a new owner?",
      ["Made with care", "To update: paste the monthly export into Raw, then check the master cell says OK", "Version final_FINAL_v3", "Do not touch"], 1,
      "Instructions for the routine job are what the next person needs most."),
    WR("Write a cover sheet for a spreadsheet you use or have built. Include lines starting with Purpose:, Owner:, Update steps:, Checks: and Known limits:.",
       [must("^purpose:", "Purpose:", flags="im"),
        must("^owner:", "Owner:", flags="im"),
        must("^update steps:", "Update steps:", flags="im"),
        must("^checks:", "Checks:", flags="im"),
        must("^known limits:", "Known limits:", flags="im"),
        words(30, 200)],
       "Purpose: monthly sales report for the leadership meeting.\nOwner: Sales operations (Priya).\nUpdate steps: export last month's orders as CSV, paste into Raw, refresh the pivot, check the master cell.\nChecks: master cell at the top of Summary must say OK; totals reconcile with the billing system.\nKnown limits: refunds appear in the month they are processed, not the month of the sale.",
       "A five line cover sheet is the cheapest insurance a spreadsheet can have."),
    NQ("Example: a monthly report takes the owner {a} minutes to update and a newcomer without notes {b} minutes. Over {m} monthly updates by a newcomer, how many minutes would good notes save, if they made the newcomer as fast as the owner?",
       "({b} minus {a}) times {m} = {A} minutes.",
       {"a": [10, 30, 5], "b": [60, 180, 30], "m": [3, 12, 3]}, "(b-a)*m", {"a": 20, "b": 90, "m": 6}, rnd=0),
    O("Hand over a spreadsheet, in order.",
      ["Write or update the cover sheet", "Walk the new owner through one real update", "Let them do the next update while you watch", "Record the handover in the change log"],
      "Doing it once under supervision surfaces the steps that only lived in your head."),
    C("Know when a spreadsheet should become something else",
      "When many people edit the same data at once, when it needs permissions per row, or when it drives an automated process, a database or application may be the safer home."),
])

SHE6 = L("Performance at scale", KW + ["performance", "slow", "volatile", "recalculation", "large data", "speed"], [
    C("Why big sheets get slow",
      "Spreadsheets slow down when they recalculate too much. Common causes: whole column references in heavy formulas over large data, volatile functions such as NOW, TODAY, RAND, OFFSET and INDIRECT that recalculate on every change, long chains of lookups repeated in every row, and excess formatting. Fixes: bounded ranges or tables, computing a value once and referencing it, replacing repeated lookups with one keyed join, and moving very large data to a database or query tool."),
    M("Which function forces recalculation on every edit?",
      ["SUM", "INDIRECT", "XLOOKUP", "ROUND"], 1,
      "INDIRECT and OFFSET are volatile. Used in thousands of cells, they make every keystroke slow."),
    NQ("Example: {r} rows each run a lookup over a {n} row table. If each lookup scans on average half the table, about how many comparisons is that, in millions? (One decimal.)",
       "{r} times {n} / 2 = {t} comparisons, about {A} million.",
       {"r": [5000, 50000, 5000], "n": [1000, 20000, 1000]}, "r*n/2/1000000", {"r": 20000, "n": 10000}, rnd=1, tol=0.1, show={"t": "r*n/2"}),
    M("Every row calls TODAY() to compute an age. What is a cheap improvement?",
      ["Remove the ages", "Put TODAY() in one input cell and reference it", "Use NOW() instead", "Add more rows"], 1,
      "One volatile cell instead of thousands. It also makes the as of date explicit and easy to freeze for a report."),
    O("Speed up a slow workbook, in order.",
      ["Find which sheets and formulas are slow", "Replace volatile functions and whole column references in heavy formulas", "Compute repeated values once and reference them", "Move raw data that is too big into a better tool"],
      "Measure first. Optimizing a formula that is not the bottleneck changes nothing."),
    C("Fast enough is the goal",
      "Do not trade readability for speed you do not need. Optimize when people are waiting."),
])

SHE7 = L("Forecasting in a sheet", KW + ["forecasting", "trend", "seasonality", "moving average", "forecast", "growth"], [
    C("Simple forecasts, honestly labeled",
      "Spreadsheet forecasting starts simple: a moving average to smooth noise, a trend line (TREND or FORECAST.LINEAR) for steady change, and seasonal factors when months differ predictably. Always compare a forecast method against a naive one, such as next month equals this month, on past data. If the fancy method does not beat naive on history, do not trust it on the future. Show forecasts as ranges."),
    W("A three month moving average",
      "Example: sales of 120, 135, 128, 142, 150.",
      ["Average of months 1 to 3: (120 + 135 + 128) / 3 = 127.67.",
       "Months 2 to 4: (135 + 128 + 142) / 3 = 135.",
       "Months 3 to 5: (128 + 142 + 150) / 3 = 140.",
       "The smoothed series shows the upward trend with less month to month noise."],
      "Average a sliding window to see the trend through the noise."),
    NQ("Example: the last three months were {a}, {b} and {c}. What is the three month moving average? (Two decimals.)",
       "({a} + {b} + {c}) / 3 = {A}.",
       {"a": [100, 200, 2], "b": [100, 200, 2], "c": [100, 200, 2]}, "(a+b+c)/3", {"a": 128, "b": 142, "c": 150}, rnd=2),
    NQ("Example: December sales are usually {s}% of an average month. If an average month is forecast at {m}, what is the December forecast?",
       "{m} times {ss} = {A}.",
       {"s": [110, 180, 10], "m": [1000, 5000, 500]}, "m*s/100", {"s": 140, "m": 2000}, rnd=0, show={"ss": "s/100"}),
    F("Write a formula that forecasts the value for period 13 from periods in A2:A13 and values in B2:B13 using a straight line trend. Use FORECAST.LINEAR (or FORECAST).",
      [must("forecast(\\.linear)?\\(", "Uses FORECAST.LINEAR or FORECAST"),
       must("forecast(\\.linear)?\\(\\s*13\\s*,", "Forecasts period 13"),
       must("\\$?b\\$?2:\\$?b\\$?13\\s*,\\s*\\$?a\\$?2:\\$?a\\$?13", "Known values B2:B13 then known periods A2:A13", hint="The order is target, known values (y), known periods (x).")],
      "=FORECAST.LINEAR(13, B2:B13, A2:A13)",
      "Note the order: the values you know (y) come before the periods (x)."),
    O("Build a forecast you can defend, in order.",
      ["Plot the history and look for trend and seasonality", "Fit a simple method", "Compare it with a naive forecast on past periods", "Present the forecast as a range with its method"],
      "The naive comparison is what keeps a forecaster honest."),
    C("Forecasts are not targets",
      "A forecast says what is likely; a target says what you want. Mixing them produces forecasts that drift toward hope."),
])

SHE8 = L("Simulation in a spreadsheet", KW + ["monte carlo", "simulation", "rand", "scenarios", "risk", "distribution"], [
    C("Thousands of what ifs",
      "With RAND() you can run a simple Monte Carlo simulation in a sheet: each row draws random inputs from their ranges, computes the outcome, and the summary counts how often outcomes are bad. A uniform draw between low and high is low + RAND() * (high minus low). Because RAND recalculates on every edit, freeze results by copying values when you need a stable report, or use a fixed seed in tools that support one."),
    W("Will the project go over budget?",
      "Example: three cost items, each uniform between a low and a high. Budget 100,000.",
      ["Row formula for item 1: =20000 + RAND() * (35000 minus 20000), similar for items 2 and 3.",
       "Total in the next column; fill 5,000 rows.",
       "Chance over budget: =COUNTIF(TotalColumn, \">100000\") / 5000.",
       "Also report the 90th percentile: =PERCENTILE(TotalColumn, 0.9)."],
      "Random inputs per row, outcome per row, then count and percentiles."),
    F("Write a formula that draws a random value uniformly between the low in B1 and the high in C1.",
      [must("rand\\(\\s*\\)", "Uses RAND()"),
       must("\\$?b\\$?1\\s*\\+\\s*rand\\(\\s*\\)\\s*\\*\\s*\\(\\s*\\$?c\\$?1\\s*-\\s*\\$?b\\$?1\\s*\\)|rand\\(\\s*\\)\\s*\\*\\s*\\(\\s*\\$?c\\$?1\\s*-\\s*\\$?b\\$?1\\s*\\)\\s*\\+\\s*\\$?b\\$?1", "Low plus RAND times the range", hint="low + RAND() * (high minus low).")],
      "=$B$1 + RAND() * ($C$1 - $B$1)",
      "Absolute references so the formula can fill down thousands of rows. RANDBETWEEN works for whole numbers."),
    NQ("Example: in {n} simulated rows, {k} totals exceed the budget. What is the estimated chance of going over, in percent?",
       "{k} / {n}, times 100, is {A}%.",
       {"n": [1000, 10000, 1000], "p": [5, 50, 5]}, "p", {"n": 5000, "p": 20}, rnd=1, show={"k": "n*p/100"}),
    NQ("Example: each item is uniform from {lo} to {hi}. What is its average value?",
       "The midpoint: ({lo} + {hi}) / 2 = {A}.",
       {"lo": [10000, 30000, 5000], "hi": [35000, 60000, 5000]}, "(lo+hi)/2", {"lo": 20000, "hi": 35000}, rnd=0),
    O("Run a spreadsheet simulation, in order.",
      ["Put each uncertain input's low and high in input cells", "Write one row that draws inputs and computes the outcome", "Fill thousands of rows", "Summarize the chance of bad outcomes and key percentiles, then freeze the values for the report"],
      "Freezing matters: a report whose numbers change every time someone clicks is hard to discuss."),
    C("Independence is an assumption",
      "Separate RAND() calls are independent. If two costs tend to rise together, such as labor and overtime, independent draws understate the risk of a bad total."),
])

SHE9 = L("Capstone: a unit economics model", KW + ["capstone", "unit economics", "ltv", "cac", "churn", "subscription", "model"], [
    C("Put the level together",
      "You will build the logic of a small subscription model the way a professional would: inputs separated, consistent calculations, named steps, checks, a sensitivity view and a cover note. The core is unit economics: how much one customer is worth compared with what it costs to win them."),
    W("Customer value from three inputs",
      "Example inputs: price 20 a month, gross margin 75%, monthly churn 5%. Cost to acquire a customer: 150.",
      ["Margin per customer per month: 20 times 0.75 = 15.",
       "Average lifetime in months, in this simple model: 1 / churn = 1 / 0.05 = 20.",
       "Lifetime value: 15 times 20 = 300.",
       "Value to acquisition cost ratio: 300 / 150 = 2, and payback takes 150 / 15 = 10 months."],
      "Margin per month, times expected months, compared with the cost to acquire."),
    NQ("Example: price {p} a month, margin {g}%, monthly churn {c}%. In the simple model, what is lifetime value?",
       "Margin {m} a month times expected lifetime {life} months = {A}.",
       {"p": [10, 50, 5], "g": [50, 90, 5], "c": [2, 10, 1]}, "p*g/100/(c/100)", {"p": 20, "g": 75, "c": 5}, rnd=2,
       show={"m": "p*g/100", "life": "100/c"}),
    NQ("Example: margin per customer is {m} a month and it costs {a} to acquire one. How many months until the acquisition cost is paid back?",
       "{a} / {m} = {A} months.",
       {"m": [5, 30, 5], "a": [50, 400, 50]}, "a/m", {"m": 15, "a": 150}, rnd=1),
    F("Write a LET formula for lifetime value with price in B1, margin percent (as a decimal) in B2 and monthly churn (as a decimal) in B3.",
      [must("let\\(", "Uses LET"),
       must("\\$?b\\$?1", "Uses price B1"),
       must("\\$?b\\$?2", "Uses margin B2"),
       must("\\$?b\\$?3", "Uses churn B3"),
       must("/\\s*\\w+\\s*\\)\\s*$|/\\s*\\$?b\\$?3\\s*\\)\\s*$", "Divides by churn at the end")],
      "=LET(price, B1, margin, B2, churn, B3, monthly, price*margin, monthly/churn)",
      "Named steps make the model's logic readable at a glance."),
    O("Build the model, in order.",
      ["Inputs: price, margin, churn, acquisition cost, with sources", "Calculations: margin per month, lifetime, lifetime value, payback", "Checks: churn between 0 and 1, outputs positive", "Outputs: value to cost ratio, payback, and a sensitivity grid for churn"],
      "Checks before outputs, so nothing leaves the model unverified."),
    WR("Write the model's cover note. Use lines starting with Purpose:, Key inputs:, Result:, Most sensitive: and Caveat:. Label numbers as examples or estimates.",
       [must("^purpose:", "Purpose:", flags="im"),
        must("^key inputs:", "Key inputs:", flags="im"),
        must("^result:", "Result:", flags="im"),
        must("^most sensitive:.*churn", "Most sensitive: names churn", flags="im",
             hint="Lifetime is 1 / churn, so small changes in churn move value most."),
        must("^caveat:", "Caveat:", flags="im"),
        must("example|estimate|assum", "Labels numbers as examples or estimates"),
        words(40, 200)],
       "Purpose: decide whether paid ads can pay for themselves.\nKey inputs: example price 20 a month, margin 75% (estimate), churn 5% a month (last quarter), acquisition cost 150 (estimate from a test campaign).\nResult: lifetime value about 300, twice the acquisition cost, with a 10 month payback.\nMost sensitive: churn; at 8% a month, value falls to about 188.\nCaveat: the simple model assumes constant churn and price; real churn is often higher in the first months.",
       "Purpose, inputs with sources, result, the driver and an honest caveat."),
    C("Expert complete",
      "You can build spreadsheets that others can trust, maintain and challenge. That is rarer, and more valuable, than knowing every function."),
])


def add(courses, picks):
    courses.append(course("sheets-intermediate", "Spreadsheet skills", "Intermediate", "Spreadsheets that scale", "sheets", "Spreadsheets", 55,
        "Lookups, text and dates, conditional totals, validation, formatting, honest charts, tables and a budget tracker.",
        [("Find and clean", [SHI1, SHI2, SHI3]), ("Rules and totals", [SHI4, SHI5, SHI6]),
         ("Present and organize", [SHI7, SHI8, SHI9])], "quant"))
    courses.append(course("sheets-advanced", "Spreadsheet analysis", "Advanced", "Spreadsheet analysis", "sheets-intermediate", "Spreadsheet skills", 85,
        "Pivots, dynamic arrays, two way lookups, what if, financial functions, error handling, cleaning and dashboards.",
        [("Summarize and extract", [SHA1, SHA2, SHA3]), ("Model and handle", [SHA4, SHA5, SHA6]),
         ("From data to decisions", [SHA7, SHA8, SHA9])], "quant"))
    courses.append(course("sheets-expert", "Spreadsheet modeling", "Expert", "Spreadsheet engineering", "sheets-advanced", "Spreadsheet analysis", 85,
        "Model structure, LET and LAMBDA, arrays, checks, documentation, performance, forecasting and simulation.",
        [("Build it right", [SHE1, SHE2, SHE3]), ("Keep it right", [SHE4, SHE5, SHE6]),
         ("Look ahead", [SHE7, SHE8, SHE9])], "quant"))
