"""Writing ladder: Intermediate, Advanced and Expert courses that follow
"Writing that works" (writing). Every lesson has at least one write step:
the learner writes or rewrites real text, and plain checks (length,
sentence length, required and banned phrases, a real rewrite of the
draft, self checks) grade it, with a model answer to compare against.
Rebuild with: python3 build_library.py
"""
from ladder_kit import (C, W, M, O, L, WR, course, words, must, avoid, max_sentence, lines, changed,
                        self_check)

KW = ["writing", "write", "words"]

# =====================================================================
# Intermediate: Writing people act on
# =====================================================================

WI1 = L("Verbs that do the work", KW + ["verbs", "active voice", "passive", "nominalization", "clarity"], [
    C("Find the action, make it the verb",
      "Weak sentences hide the action in a noun: we conducted an analysis, they made a decision, there was a reduction in costs. Strong sentences put it back in a verb: we analyzed, they decided, costs fell. The fix also tends to bring the actor forward, which turns passive sentences (the report was approved by the board) into active ones (the board approved the report)."),
    W("Two edits, one sentence",
      "\"An investigation into the cause of the outage was carried out by the support team.\"",
      ["Find the action hiding as a noun: investigation. The verb is investigated.",
       "Find the actor: the support team.",
       "Put actor, verb, object in order: The support team investigated the cause of the outage.",
       "Fourteen words became nine, and the reader knows who did what."],
      "Ask who did what, and write that."),
    M("Which sentence is active and direct?",
      ["The decision was reached to postpone the launch", "A postponement of the launch occurred", "We postponed the launch", "It was felt that postponing was best"], 2,
      "Actor, verb, object. The others hide who decided, which readers tend to distrust."),
    M("When is passive voice the right choice?",
      ["Never", "When the actor is unknown or unimportant, as in the server was restarted overnight", "Always in formal writing", "When you want to sound smart"], 1,
      "Passive is a tool. Use it on purpose when the actor does not matter, not by habit."),
    WR("Rewrite these three sentences so each uses a strong verb and names who acts. Keep one sentence per line.",
       [changed(),
        lines(3, "Three sentences, one per line"),
        avoid("\\b(was|were|been|being)\\s+\\w+ed\\s+by\\b", "No passive constructions with by",
              hint="Move the actor after by to the front of the sentence."),
        avoid("\\b(made a decision|conducted an analysis|gave approval|carried out)\\b", "No buried verbs",
              hint="made a decision becomes decided; conducted an analysis becomes analyzed."),
        max_sentence(14, "Each sentence is 14 words or fewer")],
       "The committee decided to raise the fee.\nThe team analyzed last quarter's returns.\nThe manager approved the new schedule.",
       "Every sentence now starts with someone doing something. That is the whole trick, used over and over.",
       starter="A decision was made by the committee to raise the fee.\nAn analysis of last quarter's returns was conducted by the team.\nApproval for the new schedule was given by the manager."),
    O("Edit a foggy paragraph, in order.",
      ["Underline the main action in each sentence", "Turn action nouns back into verbs", "Put the actor at the front", "Cut the words that are left with no job"],
      "Find, convert, reorder, trim. The cutting is easy once the verbs are back."),
    C("Watch for there is and it is",
      "There are many users who complain becomes many users complain. It is important to note that usually deletes cleanly. Openers like these push the real subject later and add words that carry nothing."),
])

WI2 = L("Rhythm and sentence length", KW + ["rhythm", "sentence length", "variety", "flow", "readability"], [
    C("Vary the beat",
      "Sentences of the same length in a row sound like a drum machine. Mix them. Use short sentences for emphasis and longer ones to carry connected ideas, with the main point near the end where readers feel the stress. If a sentence runs past about 25 words, check whether it is really two."),
    M("Which paragraph uses rhythm best?",
      ["We tested it. It failed. We fixed it. It passed. We shipped it.", "We tested the new checkout for a week with real customers, and it failed on older phones. We fixed it. It passed.", "We tested the new checkout for a week with real customers and it failed on older phones and so we fixed it and then it passed and we shipped it.", "Testing was done and failure occurred and a fix was made."], 1,
      "A longer sentence sets up the story; two short ones land the result."),
    M("Where in a sentence do readers feel the most emphasis?",
      ["At the start", "In the middle", "At the end", "Nowhere in particular"], 2,
      "Put the new or important information last: not we hired her for her experience, but what we hired her for was her experience. Or simply: her experience got her the job."),
    WR("Rewrite this one long sentence into a short paragraph of two to four sentences, with at least one sentence of eight words or fewer. Keep all the facts.",
       [changed(),
        max_sentence(25, "No sentence longer than 25 words"),
        must("(^|[.!?]\\s+)(\\S+\\s+){0,7}\\S+[.!?]", "At least one short sentence of eight words or fewer",
             hint="End with a short sentence that lands the point."),
        must("tuesday", "Keeps the day"),
        must("refund", "Keeps the refund"),
        words(25, 70)],
       "Our payment provider had an outage on Tuesday, so about 200 orders were charged twice. We noticed within an hour and refunded every duplicate charge the same day. Nobody needs to do anything.",
       "Same facts, three sentences, and the last one tells readers what they most want to know.",
       starter="Due to an outage at our payment provider that occurred on Tuesday approximately 200 orders were charged twice and although we noticed within an hour and processed a refund for every duplicate charge on the same day we wanted to let you know that you do not need to take any action."),
    O("Revise for rhythm, in order.",
      ["Read the draft aloud", "Mark sentences that run together or drone", "Split the long ones and join the choppy ones", "Read it aloud again"],
      "Your ear finds rhythm problems faster than your eye. Read aloud before and after."),
    C("Punctuation as pacing",
      "A period is a full stop. A comma is a short breath. A colon promises what comes next: here it is. Choosing among them is choosing how fast the reader moves."),
])

WI3 = L("Precise words", KW + ["precision", "vague", "specific", "concrete", "word choice", "jargon"], [
    C("Specific beats general",
      "Vague words make readers guess: things, stuff, very, really, soon, a lot, significant. Specific words carry information: three bugs, by Friday, cut load time from 4 seconds to 2. When you catch a vague word, ask what exactly you mean, and write that instead."),
    M("Which sentence gives the reader the most information?",
      ["Sales went up a lot recently", "Sales rose significantly in the recent period", "Sales rose 18% in March compared with February", "Sales were very good"], 2,
      "A number, a period and a comparison. Readers can check it, remember it and act on it."),
    M("Your draft says the new process is much better. What is the best revision?",
      ["The new process is very much better", "The new process is significantly improved", "The new process takes two approvals instead of five", "The new process is better in many ways"], 2,
      "Show what changed. Intensifiers like very and significantly do not add facts."),
    WR("Rewrite this message so every vague phrase becomes something specific. You may invent reasonable example details (times, numbers, names).",
       [changed(),
        avoid("\\b(soon|asap|a lot|some things|stuff|very|really|a few issues)\\b", "No vague words left: soon, asap, a lot, some things, stuff, very, really, a few issues",
              hint="Replace each one with a time, a number or a named thing."),
        must("\\d|monday|tuesday|wednesday|thursday|friday|saturday|sunday|noon", "Includes at least one number, day or time"),
        words(15, 70)],
       "The report is late because two data sources broke on Monday. I fixed the first one; the second will be fixed by 3 pm Thursday. You will have the report by Friday at 10 am.",
       "Every claim is now checkable. Notice how much calmer it reads: specifics reduce worry.",
       starter="The report will be ready soon. We had a few issues with some things in the data, and it was really a lot of stuff to fix, but it is very close now."),
    O("Replace a vague word, in order.",
      ["Notice the vague word", "Ask what exactly you mean", "Find the number, name or example that says it", "Rewrite the sentence around it"],
      "The question in the middle is the real work. The rewrite follows naturally."),
    C("Jargon is a precision problem too",
      "Jargon is precise for insiders and vague for everyone else. If a reader outside your team might read it, use the plain word or explain the term the first time."),
])

WI4 = L("Subject lines and first sentences", KW + ["subject line", "email", "opening", "bluf", "headline", "lead"], [
    C("Most readers read the top and decide",
      "Many people read the subject line and the first sentence, then decide whether to read the rest. Put the point there. A good subject line says what the message is about and, if there is one, what you need: Decision needed by Friday: venue for the offsite. The first sentence states the main point or request; context comes after."),
    M("Which subject line is most useful?",
      ["Quick question", "Update", "Approval needed by Thu: 2 extra days for the launch", "Hi!"], 2,
      "It says what, what you need and by when. The reader can prioritize it without opening it."),
    M("Which opening is strongest for a request?",
      ["I hope this email finds you well.", "As you may know, we have been working on the budget for some time now.", "Can you approve 1,200 for the new laptops by Thursday?", "I wanted to reach out about something."], 2,
      "The ask comes first. Pleasantries and background can follow, briefly."),
    WR("Write a subject line and the first sentence for this situation: you need your manager to approve moving the client demo from Tuesday to Thursday because the new feature will not be ready. Put the subject on the first line starting with Subject:, and the first sentence on the next line.",
       [must("^subject:", "A Subject: line", flags="im"),
        must("^subject:.*(thu|thursday)", "The subject says what changes", flags="im"),
        must("^subject:.*(approv|ok|decision|need)", "The subject says what you need", flags="im",
             hint="Add the action, such as Approval needed."),
        lines(2, "A subject line and a first sentence"),
        avoid("hope this (email|message) finds you|wanted to reach out|just checking in", "No warm up opener"),
        words(15, 60)],
       "Subject: Approval needed: move client demo to Thursday\nCan you approve moving Tuesday's client demo to Thursday, since the new export feature will not be ready until Wednesday?",
       "The manager can say yes from the preview pane. That is the standard to aim for."),
    O("Write an email, in order.",
      ["Decide the one thing you want the reader to know or do", "Write the subject line around it", "Write the first sentence stating it", "Add only the context they need to act"],
      "The point comes before the words. If you cannot say it in a sentence, you are not ready to write the email."),
    C("Update the subject when the topic changes",
      "Long threads drift. When a reply is about something new, change the subject line so people can find it later."),
])

WI5 = L("Asking for things", KW + ["requests", "asks", "deadlines", "favors", "follow up", "email"], [
    C("A good ask is easy to say yes to",
      "Requests fail when the reader cannot tell exactly what is wanted, by when, or why. A good ask names the specific action, the deadline, the reason, and anything that makes it easier, such as a draft to approve or a link to the file. Make the yes cheap."),
    M("Which request is most likely to get a fast yes?",
      ["Let me know your thoughts on the deck when you get a chance.", "Could you review slides 4 to 6 of the attached deck for accuracy by Wednesday noon? A yes or a list of fixes both work.", "Thoughts?", "Please review everything."], 1,
      "Scope, deadline and the form of the answer. The reader knows exactly how much effort it costs."),
    M("You need help from someone outside your team who owes you nothing. What matters most?",
      ["Writing a long background", "Making the ask small, specific and easy, with a clear reason it matters", "Copying their boss", "Asking several things at once"], 1,
      "A small, clear ask with a reason respects their time. Bundling several asks often gets none."),
    WR("Write a short request email body to a colleague asking them to send last month's sales figures. Include the exact thing you need, a deadline with a day or date, the reason, and a thank you. Keep it under 70 words.",
       [words(20, 70),
        must("monday|tuesday|wednesday|thursday|friday|saturday|sunday|\\d{1,2}(:\\d{2})?\\s?(am|pm)|tomorrow|\\bby\\b", "Includes a deadline",
             hint="Name a day or time, such as by Thursday at noon."),
        must("because|so that|so I|for the|to prepare|for my", "Gives the reason"),
        must("thank", "Says thank you"),
        must("sales", "Names exactly what you need")],
       "Hi Sam, could you send me last month's sales figures by region by Thursday at noon? I need them for the quarterly review deck on Friday. A spreadsheet export is perfect. Thank you!",
       "What, by when, why and what format. The reader can do it in five minutes without writing back."),
    O("Follow up on an unanswered request.",
      ["Wait a reasonable time for the deadline you set", "Reply in the same thread so the context is there", "Restate the ask in one line and offer to make it easier", "Thank them, whatever the answer"],
      "Same thread, shorter ask. A follow up that repeats the whole first email rarely helps."),
    C("One ask per message",
      "When a message asks for three things, people answer the easiest one. If the asks go to different people or have different deadlines, send separate messages."),
])

WI6 = L("Bad news, delivered well", KW + ["bad news", "apology", "difficult message", "tone", "customer"], [
    C("Say it early, say it plainly",
      "Bad news buried under three paragraphs of warm up reads as evasive. Lead with the news, then the reason, then what you are doing about it and what it means for the reader. Apologize once, sincerely, if it is your fault. Avoid hedging words that blur responsibility, like mistakes were made."),
    M("Which opening delivers bad news best?",
      ["We value you as a customer and are always striving to improve.", "Your order will arrive on May 12, five days later than promised, because our warehouse flooded.", "Unfortunately, due to circumstances beyond our control, some delays may potentially occur.", "Thank you for your patience."], 1,
      "The news, the new date and the reason in one sentence. The reader can plan."),
    M("Which apology takes responsibility?",
      ["Mistakes were made.", "We are sorry if anyone was upset.", "We charged you twice. That was our error, and we have refunded the extra charge.", "We regret any inconvenience this may have caused."], 2,
      "Name what happened, own it and say what you did. If anyone was upset puts the problem on the reader."),
    WR("Rewrite this message so it leads with the news, gives the reason, says what happens next, and apologizes once without hedging.",
       [changed(),
        avoid("mistakes were made|any inconvenience|if anyone|may potentially", "No hedging phrases",
              hint="Replace them with what actually happened and who did it."),
        must("(sorry|apologi)", "Includes an apology"),
        must("(friday|monday|tuesday|wednesday|thursday|saturday|sunday|\\d)", "Gives a new date or time"),
        max_sentence(25, "No sentence over 25 words"),
        words(20, 80)],
       "Your furniture order will arrive on Friday the 14th, a week late. Our supplier shipped the wrong fabric, and we caught it at inspection. We are sorry for the wait. Your delivery slot is booked, and we have refunded the delivery fee.",
       "News first, then the reason, the apology, and what happens next. The reader has everything in four sentences.",
       starter="We wanted to reach out to thank you for your patience. Mistakes were made in our supply process and we regret any inconvenience this may potentially cause. Your order may be delayed."),
    O("Structure a bad news message.",
      ["The news itself", "The reason, briefly", "What you are doing about it", "What the reader needs to do, if anything"],
      "Readers can handle bad news. What they resent is having to dig for it."),
    C("Do not overcorrect into coldness",
      "Plain is not harsh. You can be direct and kind at once: say the hard thing clearly, then show you understand what it costs the reader."),
])

WI7 = L("Instructions people can follow", KW + ["instructions", "how to", "steps", "procedures", "documentation"], [
    C("One action per step, in the order people do them",
      "Good instructions use numbered steps, one action each, starting with a verb: Open, Click, Type. Put conditions before the action (If the light is red, unplug the router), say what success looks like, and warn before a risky step, not after it."),
    M("Which step is written best?",
      ["The settings should then be opened and the toggle located.", "Open Settings, then turn on Backup.", "You might want to consider possibly enabling the backup toggle in settings.", "Backup (settings) toggle on"], 1,
      "Verb first, one or two actions, plain names that match what is on screen."),
    M("Where should a warning go?",
      ["After the step it applies to", "Before the step it applies to", "At the end of the document", "In a footnote"], 1,
      "People act as they read. A warning after the step arrives after the damage."),
    WR("Write numbered instructions for resetting a password from the login page. Use at least four steps, start each step with a verb, and tell the reader what they should see at the end.",
       [must("^\\s*1[.)]", "Numbered steps starting at 1", flags="im"),
        must("^\\s*4[.)]", "At least four steps", flags="im"),
        must("^\\s*\\d[.)]\\s*(open|go|click|tap|select|enter|type|choose|check|press|follow|wait|sign|create|find|confirm|use|return)", "Steps start with a verb", flags="im",
             hint="Begin each step with an action word: Open, Click, Type."),
        must("(you will see|you should see|you'll see|appears|is shown|you are signed in|you're signed in|confirmation)", "Says what success looks like")],
       "1. Open the login page and click Forgot password.\n2. Enter the email address on your account and click Send link.\n3. Open the email from us and click Reset password.\n4. Type a new password twice and click Save.\nYou will see a message that your password has changed, and you are signed in.",
       "Numbered, one action each, verbs first, and the reader knows when they are done."),
    O("Test your instructions, in order.",
      ["Write the steps from memory", "Do the task yourself following only your steps", "Fix every step where you had to guess", "Watch someone else follow them"],
      "You cannot see the gaps in your own instructions until someone without your knowledge follows them."),
    C("Match the screen",
      "Use the exact labels people will see, in the same capitalization. If the button says Save changes, do not write click Submit."),
])

WI8 = L("Summaries that save time", KW + ["summary", "tldr", "executive summary", "condense", "brief"], [
    C("A summary is a decision tool",
      "A good summary tells a busy reader the main point, why it matters and what is needed, before any detail. Write it last, after you know what you are saying, and put it first. It must stand alone: someone who reads only the summary should still act correctly."),
    M("Which is a summary, not an introduction?",
      ["This report looks at our support tickets from the last quarter.", "Support tickets rose 30% last quarter, mostly about the new billing page; fixing two confusing fields should remove about half of them.", "In this document we will explore several topics.", "Support is very important to us."], 1,
      "It gives the finding, the cause and the action. An introduction only says what is coming."),
    M("When should you write the summary?",
      ["First, before the rest", "Last, once you know your conclusions, and place it at the top", "Never", "In the middle"], 1,
      "You can only summarize what you have worked out."),
    WR("Summarize this update in 40 words or fewer for an executive who will read nothing else. Lead with the main point and include the one thing you need from them.",
       [words(10, 40),
        changed(),
        must("approv|decid|sign|need|choose", "Says what you need from them"),
        must("(two weeks|2 weeks|june|delay|late)", "Keeps the main point about the delay")],
       "The app launch moves two weeks, to June 15, because security testing found two issues we must fix. Please approve the new date by Friday so marketing can reschedule.",
       "Point, reason, ask. An executive can decide from this alone.",
       starter="Over the past month the team has been working hard on many parts of the app, including design updates, performance work and the security review. The security review found two issues that need fixing, and fixing them will take about two weeks, which means the launch would move from June 1 to June 15. Marketing has a campaign planned and would need to reschedule. We need someone to approve the new date by Friday."),
    O("Write a summary, in order.",
      ["Finish the full draft", "Write the main point in one sentence", "Add why it matters and what you need", "Cut until it fits in a few lines and place it at the top"],
      "Full draft first, then compress. Summaries written before the thinking is done are guesses."),
    C("Summaries in meetings too",
      "End a meeting by saying the decisions and owners out loud, then send the same summary in writing. It prevents three people leaving with three different memories."),
])

WI9 = L("Capstone: a status update people read", KW + ["capstone", "status update", "weekly update", "report", "progress"], [
    C("Put the level together",
      "A status update uses everything from this level: a headline with the main point, plain specific facts, strong verbs, short paragraphs, honest bad news, a clear ask and a summary a reader can act on. You will write one."),
    M("Which update headline is most useful?",
      ["Weekly update", "Project status: various progress", "On track for June 15 launch; one risk needs a decision by Friday", "Things are going well"], 2,
      "Status, date, risk and the ask in one line. Many readers will read only this."),
    O("Order a status update.",
      ["Headline: overall status and the main point", "What changed since last time", "Risks and problems, with what you are doing", "What you need from the reader, with a deadline"],
      "Most important first. Asks at the end, clearly marked, so they are easy to find.",
      note="Some teams put the ask right after the headline. That works too, as long as the headline comes first."),
    WR("Write a status update for a real or imaginary project. Use lines starting with Status:, Done:, Next:, Risk: and Need:. Use at least one number or date, keep sentences under 25 words, and keep it between 50 and 150 words.",
       [must("^status:", "A Status: line", flags="im"),
        must("^done:", "A Done: line", flags="im"),
        must("^next:", "A Next: line", flags="im"),
        must("^risk:", "A Risk: line", flags="im"),
        must("^need:", "A Need: line", flags="im"),
        must("\\d", "At least one number or date"),
        max_sentence(25, "No sentence over 25 words"),
        avoid("\\b(very|really|a lot|some things|stuff)\\b", "No vague filler words"),
        words(50, 150)],
       "Status: On track for the June 15 launch, with one risk.\nDone: We finished checkout testing on 40 devices and fixed 12 bugs.\nNext: The team will run the load test on Tuesday and freeze features on Thursday.\nRisk: The payment provider has not confirmed the new API keys. We asked twice and escalated on Monday.\nNeed: Please call their account manager by Friday if we still have no keys.",
       "Headline status, plain facts, an honest risk and a clear ask with a date. That update gets read."),
    WR("Now edit your own update like an editor. Read it aloud, tick each item once it is true, and write a short note on what you changed.",
       [self_check("I read it aloud and fixed anything that sounded stiff"),
        self_check("Every sentence has an actor and a strong verb"),
        self_check("Someone reading only the Status line would know whether to worry"),
        words(5, 120, "A short note on what you changed")],
       "Read aloud, fixed two long sentences, replaced was completed with we finished.",
       "Self editing is a habit. A minute of rereading saves your reader several."),
    C("Intermediate complete",
      "You can write messages people act on. Advanced moves to persuasion: arguments, evidence, audiences and longer pieces."),
])

# =====================================================================
# Advanced: Writing that persuades
# =====================================================================

WA1 = L("Claims, evidence and reasons", KW + ["argument", "claim", "evidence", "reasoning", "warrant", "persuasion"], [
    C("Three parts of every argument",
      "An argument has a claim (what you want the reader to believe), evidence (facts, examples, data) and the reasoning that connects them, which is often left unsaid. We should open on Saturdays (claim). Twelve customers asked for it last month (evidence). Requests like these usually mean demand we are not serving (reasoning). When an argument fails, it is usually the unstated reasoning that the reader does not accept."),
    M("Claim: we should switch to the new supplier. Evidence: their prices are 10% lower. What reasoning is the reader most likely to question?",
      ["That 10% is a number", "That price is what matters most, when quality and reliability might matter more", "That suppliers exist", "Nothing"], 1,
      "The hidden assumption is that price outweighs everything else. Say it and defend it, or the reader will doubt it silently."),
    M("Which is evidence rather than a claim?",
      ["Our onboarding is confusing", "We need a new onboarding flow", "In five usability sessions, four people could not find the import button", "Onboarding should be simpler"], 2,
      "Evidence is something observed or measured. The rest are claims that need support."),
    WR("Write a short argument for a change you would like to see at work, school or home. Label three lines Claim:, Evidence: and Because: (the reasoning that connects them).",
       [must("^claim:", "A Claim: line", flags="im"),
        must("^evidence:", "An Evidence: line", flags="im"),
        must("^because:", "A Because: line with your reasoning", flags="im"),
        must("^evidence:.*(\\d|saw|observed|measured|asked|said|found|survey|test)", "The evidence is observed or measured, not another opinion", flags="im",
             hint="Use something that happened or was counted, such as 12 customers asked."),
        words(25, 120)],
       "Claim: We should move the team meeting from Monday 8 am to Tuesday 10 am.\nEvidence: Over the last 6 weeks, an average of 3 of 8 people joined late on Mondays.\nBecause: A slot people can reliably make wastes less time than one that half the room arrives late to.",
       "Writing the because line forces you to see the assumption the reader must accept."),
    O("Build an argument, in order.",
      ["Decide what you want the reader to believe or do", "Gather the strongest evidence", "Make the reasoning explicit", "Anticipate the main objection"],
      "Claim first, then support. Writing before you know the claim produces a tour of the evidence with no destination."),
    C("Fewer, stronger points",
      "Three solid reasons beat seven mixed ones. A weak point gives the skeptical reader something easy to attack, and they will judge the whole case by it."),
])

WA2 = L("Steelman the other side", KW + ["counterargument", "steelman", "objections", "fairness", "rebuttal"], [
    C("State their case better than they would",
      "Persuasive writers address the strongest objection, not a weak version of it. A strawman (knocking down a position nobody holds) convinces only people who already agree. A steelman states the opposing view fairly, concedes what is true in it, and then explains why your conclusion still holds. Readers trust writers who show they understand the other side."),
    M("You argue for remote work. Which is the steelman of the objection?",
      ["Some people just want to watch people work", "Remote work makes it harder for new hires to learn by overhearing and asking quick questions, which can slow their growth", "Remote workers are lazy", "Offices are nice"], 1,
      "It is the strongest honest version of the concern. If you can answer it, you have a real argument."),
    M("What does conceding a point do to your argument?",
      ["Always weakens it", "Often strengthens it, by showing you are fair and by narrowing the disagreement to where you are right", "Nothing", "Confuses readers"], 1,
      "Admitting what is true in the other view makes the rest of your case more credible."),
    WR("Write a paragraph that steelmans an objection to your own argument. Start with a fair statement of the objection, concede what is true in it, then explain why your view still holds. Use the words \"It is true that\" or \"Fair point\" somewhere.",
       [must("it is true that|it's true that|fair point|admittedly|granted", "Concedes something"),
        must("\\b(but|however|still|yet|even so)\\b", "Turns back to your view"),
        avoid("\\b(stupid|lazy|idiot|obviously wrong|ridiculous)\\b", "No insults or dismissals",
              hint="Describe the opposing view the way someone who holds it would."),
        words(40, 140),
        max_sentence(30, "No sentence over 30 words")],
       "The strongest objection to moving the meeting is that Tuesday 10 am collides with client calls for two people. It is true that those calls are hard to move. But both said they could shift one call a week, and a meeting everyone attends on time saves the whole team more than it costs them.",
       "Fair, specific, and still persuasive. A reader who held the objection feels heard."),
    O("Handle an objection, in order.",
      ["State the objection in its strongest form", "Concede what is true about it", "Show why your conclusion still holds", "Offer what you will do to reduce the cost"],
      "The last step often wins the reader: a concession with a remedy turns an opponent into a collaborator."),
    C("If you cannot answer it, change your view",
      "Sometimes the steelman wins. That is not failure; it is the point of thinking in writing. Revise the claim to one you can defend."),
])

WA3 = L("Answer first: the pyramid", KW + ["pyramid principle", "structure", "top down", "argument structure", "executive"], [
    C("Lead with the answer, then group the support",
      "Busy readers want the conclusion first. Top down structure, sometimes called the pyramid principle, puts the main point at the top, then two to four supporting points underneath, each backed by detail. The supporting points should not overlap and together should cover the case."),
    M("Which opening follows answer first?",
      ["First, some history of the project.", "We recommend delaying the launch two weeks, for three reasons: two security issues, an incomplete load test, and a holiday weekend.", "There are several factors to consider.", "Let's look at the data together."], 1,
      "The recommendation and the shape of the support in one sentence. The reader knows what follows and why."),
    M("Your three supporting points are: costs are lower, it is cheaper, and setup is faster. What is wrong?",
      ["Nothing", "Two of them are the same point, so the case looks wider than it is", "Three is too many", "They need numbers"], 1,
      "Overlapping points pad the argument. Merge them and find a genuinely different reason, or use two."),
    O("Arrange this memo top down.",
      ["We should move to the new scheduling tool", "It cuts booking time from 10 minutes to 2", "It integrates with the calendar we already pay for", "Two other teams use it and report fewer double bookings", "Next step: a two week trial with five people"],
      "The recommendation first, then the supporting reasons, then the next step. The order of the three reasons is a choice.",
      groups=[[1, 2, 3]]),
    WR("Write a short top down memo recommending something. First line: your recommendation. Then two or three lines starting with a dash or a number, each a separate supporting reason. Last line: Next step: and the action.",
       [lines(4, "At least four lines"),
        must("^\\s*(-|\\*|1[.)])\\s*\\S", "Supporting reasons as a list", flags="im",
             hint="Start each reason with a hyphen, an asterisk or a number."),
        must("^next step:", "A Next step: line", flags="im"),
        must("^(we|i) (should|recommend|propose)|^recommend", "The first line is the recommendation", flags="i",
             hint="Open with We should, I recommend or We propose."),
        words(30, 140)],
       "We should replace the paper sign up sheet with an online form.\n1. It removes the 20 minutes a week spent typing up the sheet.\n2. People can sign up from home, so fewer slots go empty.\n3. The form is free with the account we already have.\nNext step: run it for the March events and compare empty slots.",
       "Answer, grouped reasons, next step. A reader who stops after line one still knows what you want."),
    C("Narrative order is for stories",
      "Chronological order (first we did this, then that) suits stories and reports of what happened. Recommendations and decisions should still lead with the answer."),
])

WA4 = L("Writing for a skeptical reader", KW + ["skeptical", "credibility", "hedging", "overclaiming", "trust", "tone"], [
    C("Calibrate your confidence",
      "Skeptical readers look for overclaiming: always, never, guaranteed, proves, everyone. They also tune out a writer who hedges everything into mush. Match the strength of your words to the strength of your evidence: say clearly what you know, say what you think is likely, and say what you do not know."),
    M("Your test with 20 users found 15 preferred the new design. Which sentence is calibrated?",
      ["The new design is proven better", "Users love the new design", "In a test with 20 users, 15 preferred the new design, which suggests it is an improvement worth a larger test", "It might possibly be somewhat preferred"], 2,
      "It reports the evidence, draws a proportionate conclusion and names the next step. No overclaim, no mush."),
    M("Which word most often signals an overclaim?",
      ["suggests", "guaranteed", "in our test", "about"], 1,
      "Guaranteed promises something evidence rarely supports. Skeptics stop reading at it."),
    WR("Rewrite this overconfident paragraph so the claims match the evidence. Keep the facts: a two week trial, 8 of 10 staff said it saved time.",
       [changed(),
        avoid("\\b(proves?|guarantee[ds]?|everyone|always|never|revolutionary|definitely)\\b", "No overclaiming words",
              hint="Swap proves for suggests, and everyone for the actual numbers."),
        must("8 of 10|eight of ten|8 out of 10", "Keeps the actual numbers"),
        must("trial|two weeks|2 weeks", "Keeps the trial"),
        words(25, 90)],
       "In a two week trial, 8 of 10 staff said the new rota saved them time. That suggests it works for our team. A month long trial with the whole team would show whether the savings last.",
       "Calibrated writing is more persuasive to the readers you most need: the ones who check.",
       starter="The new rota is revolutionary. Our trial proves that everyone saves time and it will definitely work for every team. 8 of 10 staff said it saved time over two weeks, which guarantees success."),
    O("Edit for calibration.",
      ["Highlight every strong claim", "Check the evidence behind each one", "Strengthen claims your evidence supports and soften those it does not", "Add what you would need to know more"],
      "The goal is not softer writing. It is accurate writing, which is sometimes stronger than your draft."),
    C("Say what would change your mind",
      "A line like if the month long trial shows no savings, we should switch back tells skeptics you are reasoning, not selling. It often makes them more willing to agree."),
])

WA5 = L("Stories that carry a point", KW + ["story", "anecdote", "narrative", "example", "concrete detail"], [
    C("A story makes the abstract real",
      "One well chosen example often persuades more than a list of facts, because readers can picture it. A useful story in an argument is short, specific (a person, a moment, a detail), and clearly connected to the point. It should be true and representative: a vivid exception presented as typical is misleading."),
    M("Which opening story best supports an argument for clearer medication labels?",
      ["Medicine is important to health.", "Last spring my neighbor, who is 81, took her evening pill twice because the label said take 1 tablet 2 times daily and she had already taken one at lunch.", "Labels exist on many products.", "Everyone has trouble with labels."], 1,
      "A person, a moment and a concrete consequence that connects directly to the point."),
    M("When is a story misleading?",
      ["When it is short", "When an unusual case is presented as typical, or details are invented", "When it has a person in it", "When it is in the first paragraph"], 1,
      "Stories persuade powerfully, so they must be honest and representative. Pair them with evidence about how common the case is."),
    WR("Write a short story (one paragraph) that supports a point of your choice. Name a specific person or role, a specific moment, a concrete detail, and end with one sentence that connects the story to your point.",
       [words(50, 140),
        must("(yesterday|last|on (monday|tuesday|wednesday|thursday|friday|saturday|sunday)|morning|evening|afternoon|night|\\d)", "A specific moment or time"),
        must("(that is why|this is why|which is why|so we|so I|the point|the lesson|shows)", "Ends by connecting the story to the point",
             hint="Close with a line like That is why we should..."),
        max_sentence(30, "No sentence over 30 words")],
       "Last Thursday a new nurse on our ward spent twenty minutes searching three cupboards for a spare blood pressure cuff while a patient waited. The cuffs were there, behind unlabeled doors. Nobody had done anything wrong; the system simply hid what we had. That is why every supply cupboard should have a printed list of what is inside.",
       "Person, moment, detail, point. The reader sees the problem before you name the fix."),
    O("Use a story in an argument, in order.",
      ["Pick the point the story must carry", "Choose a true, representative example", "Tell it in a few specific sentences", "Connect it explicitly to the point"],
      "Point first. A story chosen because it is entertaining drifts away from the argument."),
    C("Specific details earn belief",
      "Twenty minutes, three cupboards and unlabeled doors are more believable than a long time and some confusion. Detail is how readers know you were there."),
])

WA6 = L("Numbers in prose", KW + ["numbers", "statistics", "data", "context", "comparisons", "percentages"], [
    C("A number needs a comparison",
      "A bare number means little: 4,000 complaints is a lot or a little depending on the base. Give the comparison that makes it meaningful (4,000 complaints, double last year), use the form readers grasp (one in five rather than 20.3%), round sensibly, and say where the number came from. Never present a guess as data."),
    M("Which sentence uses numbers best?",
      ["Complaints were 4,013.", "Complaints rose to about 4,000 last year, double the year before.", "Complaints were a significant number.", "Complaints went up by 100.0%."], 1,
      "Rounded, compared with something, and in a form readers can hold in their heads."),
    M("Your source says 18 of 90 surveyed customers used the feature. Which phrasing is accurate?",
      ["Most customers use the feature", "About one in five surveyed customers used the feature", "20% of all customers use the feature", "Customers love the feature"], 1,
      "18 of 90 is one in five of those surveyed. It does not tell you about all customers or whether they love it."),
    WR("Rewrite this sentence so the number has context and a readable form. Use only the facts given: 312 of 1,560 orders last month arrived late; the month before, 156 of 1,500 did.",
       [changed(),
        must("one in five|1 in 5|20%|20 percent", "Puts this month in a readable form (about one in five, or 20%)"),
        must("double|twice|two times|from about one in ten|10%", "Compares with the month before"),
        avoid("\\b(huge|massive|terrible|shocking)\\b", "Lets the numbers speak, no hype words"),
        words(12, 50)],
       "Last month about one in five orders arrived late, double the rate of the month before.",
       "Ratio, comparison and nothing invented. The reader understands the problem at once.",
       starter="312 orders were late last month."),
    O("Present a number, in order.",
      ["Check the source and what it actually measured", "Round it to the precision that matters", "Add the comparison that gives it meaning", "Say where it came from"],
      "Accuracy first. A well framed number that is wrong does more damage than an awkward one that is right."),
    C("Percent and percentage points",
      "If late deliveries go from 10% to 20%, that is a rise of 10 percentage points, or a 100% increase. Both are true; say which you mean. Mixing them up is one of the most common number mistakes in writing."),
])

WA7 = L("Proposals that get a yes", KW + ["proposal", "pitch", "business case", "request", "budget"], [
    C("Make the decision easy",
      "A proposal asks someone to spend money, time or attention. It gets a yes when the reader quickly sees the problem, the proposed solution, what it costs, what it gains, the main risk, and exactly what you want them to decide. Keep it short; attach detail for those who want it."),
    M("Which section do proposals most often forget?",
      ["The problem", "The specific decision being asked for", "The title", "The date"], 1,
      "Writers describe the idea well and then end without saying approve X by Y. The reader has to guess."),
    M("Your proposal costs 3,000. What makes the cost easiest to accept?",
      ["Hiding it in an appendix", "Stating it plainly next to the expected benefit and the cost of doing nothing", "Rounding it to a few thousand", "Mentioning it last"], 1,
      "Readers look for the cost first. Showing it beside the benefit lets them weigh it at once."),
    WR("Write a one page proposal for a small change. Use lines starting with Problem:, Proposal:, Cost:, Benefit:, Risk: and Decision:. Put any numbers in as clearly labeled examples or estimates.",
       [must("^problem:", "Problem:", flags="im"),
        must("^proposal:", "Proposal:", flags="im"),
        must("^cost:", "Cost:", flags="im"),
        must("^benefit:", "Benefit:", flags="im"),
        must("^risk:", "Risk:", flags="im"),
        must("^decision:.*(approve|agree|decide|choose|sign|yes)", "Decision: names exactly what you want them to approve", flags="im",
             hint="Write the decision as a question they can answer yes to, with a date."),
        words(60, 220)],
       "Problem: New volunteers wait an average of 3 weeks to start because training runs once a month.\nProposal: Record the training as four short videos so volunteers can start any week.\nCost: About 12 hours of staff time and no software costs (estimate).\nBenefit: Volunteers could start within a week, and staff stop repeating the same session monthly.\nRisk: Videos may miss questions people ask live, so we keep a monthly live Q and A.\nDecision: Can you approve 12 hours of staff time in April for this?",
       "Every section a decision maker needs, in the order they look for them, ending with a question they can say yes to."),
    O("Order a proposal.",
      ["Problem", "Proposal", "Cost and benefit", "Risk and how you will handle it", "The decision you need"],
      "Problem first so the reader cares; the decision last so it is the thing they remember."),
    C("Offer a smaller first step",
      "If the full proposal feels big, offer a pilot: a month, one team, a fixed budget. A small yes is easier to give and often grows."),
])

WA8 = L("Editing long pieces", KW + ["editing", "structure", "reverse outline", "revision", "cutting", "long form"], [
    C("Edit big things before small things",
      "With long pieces, edit in passes from large to small: structure first (is the order right, does every section earn its place), then paragraphs (one idea each, clear topic sentences), then sentences, then words. Polishing sentences in a section you later cut is wasted work. A reverse outline helps: write one line summarizing each paragraph, then read just the lines."),
    M("Your reverse outline shows paragraphs 3 and 7 make the same point. What do you do?",
      ["Nothing", "Merge them, or cut the weaker one, and check what the order should be", "Make both longer", "Swap their words"], 1,
      "Repetition is easy to miss in full text and obvious in an outline. That is why the outline exists."),
    M("Which edit should come first on a 3,000 word report?",
      ["Fix comma usage", "Check whether the sections are in the right order and all needed", "Choose a font", "Replace weak verbs"], 1,
      "Structure first. Fine edits come last, once you know what survives."),
    WR("Write a reverse outline for the following five paragraph summaries, then add a line starting with Fix: saying what you would change in the structure. The paragraphs are: 1 why our sign up rate fell; 2 the history of the company; 3 users abandon at the payment step; 4 users also abandon at the payment step on mobile; 5 our recommendation to add a guest checkout.",
       [lines(5, "At least five lines"),
        must("^fix:", "A Fix: line", flags="im"),
        must("^fix:.*(merge|combine|cut|remove|move|drop)", "The fix names a structural change", flags="im",
             hint="Look for a paragraph that does not serve the point and two that repeat each other."),
        must("(history|paragraph 2|2)", "Deals with the history paragraph"),
        must("(3 and 4|4 and 3|paragraphs 3|merge)", "Deals with the repeated payment step paragraphs")],
       "1. Sign up rate fell this quarter.\n2. Company history.\n3. Users leave at the payment step.\n4. Users leave at the payment step on mobile.\n5. Recommend a guest checkout.\nFix: cut paragraph 2, which does not serve the argument; merge 3 and 4 into one paragraph on where users leave; move the recommendation to the top.",
       "Outline, then judge. The fix is visible in seconds that would take a full reread to notice in the draft."),
    O("Edit in passes.",
      ["Structure: order and what to cut", "Paragraphs: one idea, clear first sentence", "Sentences: strong verbs, varied rhythm", "Words: precise terms, no filler"],
      "Big to small. Each pass is easier because the one before removed work."),
    C("Cut what you love if it does not serve",
      "The hardest cuts are the clever paragraphs that do not move the argument. Keep them in a separate file if that helps. Most of the time you will not miss them."),
])

WA9 = L("Capstone: an argument that persuades", KW + ["capstone", "op-ed", "essay", "persuasive essay", "argument"], [
    C("Put the level together",
      "A persuasive piece uses everything from this level: a clear claim up front, evidence and reasoning, a steelmanned objection, calibrated confidence, a short story, numbers with context, and a specific call to action. You will write one of 150 to 350 words."),
    M("Which final line is the strongest call to action?",
      ["Think about it.", "Ask the council to vote yes on the bike lane on March 12; the form takes two minutes.", "Change is needed.", "We all have a part to play."], 1,
      "A specific action, a date and a reason it is easy."),
    M("Your strongest evidence is one vivid story. What makes the piece more persuasive to a skeptic?",
      ["Telling the story twice", "Pairing it with evidence of how common the case is, or saying honestly if you do not know", "Making the story more dramatic", "Removing the numbers"], 1,
      "A story shows the problem is real; a count shows it is not rare. Skeptics need both, or an honest note on what you do not know."),
    O("Structure a short persuasive piece.",
      ["The claim, stated plainly", "The best evidence, with a story or example", "The strongest objection and your answer", "The call to action"],
      "Claim early so readers know what you are arguing; the objection before the close so the last thing they read is what to do."),
    WR("Write a persuasive piece of 150 to 350 words on a local or workplace issue you care about. Open with your claim, include evidence, steelman one objection, and end with a specific call to action. Label example numbers as examples if they are not real.",
       [words(150, 350),
        must("(it is true that|it's true that|fair point|admittedly|granted|critics|some say|opponents|the strongest objection)", "Addresses an objection"),
        must("\\b(but|however|still|yet)\\b", "Answers the objection"),
        must("\\d|(one|two|three|four|five|six|seven|eight|nine|ten) (of|in|out)", "Uses at least one number"),
        avoid("\\b(proves?|guarantee[ds]?|everyone knows|obviously)\\b", "Calibrated, no overclaiming"),
        must("(please|ask|vote|sign|join|email|write to|come to|reply)[^.]*[.!]\\s*$", "Ends with a specific call to action",
             hint="Make the last sentence tell the reader exactly what to do."),
        max_sentence(32, "No sentence over 32 words")],
       "Our library should open until 8 pm on weekdays. Right now it closes at 5, before most working parents can get there.\n\nLast month I watched a father arrive at 5:05 with two children and a bag of returns, and find the doors locked. In an example count over one week, the front desk logged 40 people arriving after closing.\n\nIt is true that longer hours cost money, and the budget is tight. But the library could open later on two weekday mornings, when the desk sees about one visitor an hour, and move those hours to the evening at no extra cost.\n\nLonger evening hours would serve the people who pay for the library and cannot currently use it. They would also give students a quiet place to study after school. The board votes on the schedule on May 3. Please email the board before then and ask them to approve the evening hours.",
       "Claim, story, numbers labeled honestly, a fair objection, an answer with a remedy, and a call to action with a date."),
    C("Advanced complete",
      "You can build an argument that persuades fair minded readers. Expert is about voice, complex material, decisions and editing others."),
])

# =====================================================================
# Expert: Writing with authority
# =====================================================================

WE1 = L("Voice without showing off", KW + ["voice", "style", "tone", "register", "personality", "plain style"], [
    C("Voice is consistent choices, not decoration",
      "A writer's voice comes from consistent choices: how formal, how warm, how direct, which words, how long the sentences run, what gets a joke and what never does. Strong voice usually reads as a person talking clearly, not as ornament. Showing off (rare words, long metaphors, clever asides) puts the writer between the reader and the point."),
    M("Which sentence has voice without showing off?",
      ["Verily, the quarterly figures doth disappoint.", "The quarter was bad, and I think we know why.", "In the grand tapestry of commerce, our quarter was a frayed thread.", "Quarterly performance was suboptimal relative to forecast parameters."], 1,
      "Plain, direct and recognizably a person. The others are costume, metaphor or jargon."),
    M("You are writing for your company's help center. Which tone choice is most fitting?",
      ["Very playful, with jokes in every step", "Calm, clear and friendly, with humor used rarely and never when someone is stuck", "Formal legal language", "Whatever you feel that day"], 1,
      "People arrive at help pages frustrated. Voice serves the reader's state, not the writer's mood."),
    WR("Rewrite this paragraph in a plain, confident voice. Keep the meaning. Cut the ornament and the jargon.",
       [changed(),
        avoid("\\b(synerg\\w*|leverag\\w*|paradigm|tapestry|journey|utiliz\\w*|holistic)\\b", "No ornament or jargon left",
              hint="Replace each fancy word with the plain one: use, whole, plan."),
        max_sentence(22, "No sentence over 22 words"),
        words(15, 60)],
       "We are changing how we plan projects. Each team will set three goals a quarter and review them every month. We think it will make priorities clearer and meetings shorter.",
       "Same content, a clear person behind it. That is what voice usually means in practical writing.",
       starter="On this exciting journey, we are leveraging a holistic paradigm shift to utilize synergies across the tapestry of our project planning, whereby each team will henceforth be aligning on three quarterly goals reviewed on a monthly cadence."),
    O("Develop a house voice, in order.",
      ["Describe the reader and their usual state of mind", "Pick three traits the voice should have, and what each is not", "Write sample passages for typical situations", "Test them with readers and adjust"],
      "Traits with their limits, such as friendly but not jokey, are what make a voice repeatable by a whole team."),
    WR("Write three voice traits for a brand or for yourself, one per line, in the form: trait, but not opposite. Example: direct, but not blunt.",
       [lines(3, "Three traits, one per line"),
        must("(^.+,\\s*but not .+$\\n?){3}", "Each line follows trait, but not opposite", flags="im",
             hint="Write each as: warm, but not gushing."),
        words(9, 60)],
       "Direct, but not blunt.\nWarm, but not gushing.\nExpert, but not academic.",
       "The but not halves do most of the work. They mark where a trait turns into a fault."),
    C("Read your favorite writers slowly",
      "Notice how they open, how long their sentences run, what they leave out. Imitating a writer you admire for a page is one of the fastest ways to widen your own range."),
])

WE2 = L("Explaining something hard", KW + ["explaining", "complex", "analogy", "teaching", "layers", "technical"], [
    C("Start from what the reader knows",
      "Hard ideas land when you build from the reader's existing knowledge: a familiar analogy, one concrete example, then the general rule, then the exceptions. Introduce one new idea at a time and name it once you have shown it. Test the explanation by asking what a smart reader outside the field would get wrong."),
    M("Which order works best for explaining compound interest to a newcomer?",
      ["The formula first, then an example", "A concrete example of money growing on its own growth, then the name, then the formula", "History of banking first", "A list of exceptions"], 1,
      "Example, then name, then rule. The formula makes sense once the reader has seen it happen."),
    M("What is the main risk of an analogy?",
      ["They are too short", "Readers carry over parts of the analogy that do not apply", "They are informal", "Nothing"], 1,
      "Say where the analogy breaks. A network is like a postal system, except letters can be copied for free."),
    WR("Explain how a vaccine trains the immune system to a curious 12 year old, in 60 to 140 words. Use one analogy, say where it stops working, and avoid the words antigen and antibody unless you explain them.",
       [words(60, 140),
        must("\\blike\\b|imagine|as if|similar to", "Uses an analogy"),
        must("(but unlike|except|the difference is|where it breaks|not quite|unlike)", "Says where the analogy stops working",
             hint="Add a line such as: Unlike a real wanted poster, ..."),
        avoid("\\b(antigens?|antibod(y|ies))\\b(?![^.]*(which|means|are|is a|called))", "No unexplained jargon"),
        max_sentence(24, "No sentence over 24 words")],
       "Your immune system is like a security team that learns faces. A vaccine shows it a harmless picture of a germ, such as a piece of its shell. The team learns what to look for. Later, if the real germ shows up, the team recognizes it fast and stops it before you get very sick. Unlike a photo on a wall, this memory lives in special cells. It can last for years, but some vaccines need a reminder dose.",
       "Familiar picture, the real mechanism in plain words, and an honest note on where the picture fails."),
    O("Explain a hard idea, in order.",
      ["Find what the reader already knows that is close", "Give one concrete example", "Name the idea and state the general rule", "Add the main exception or limit"],
      "Known, concrete, named, bounded. Each step rests on the one before."),
    C("Cut the second example",
      "Experts often stack examples. One clear example usually teaches more than three half explained ones. Add the second only if the first leaves a common misunderstanding."),
])

WE3 = L("Decisions in writing", KW + ["decision record", "decision doc", "adr", "options", "tradeoffs", "memo"], [
    C("Write down why, not just what",
      "Teams forget why they decided things, then relitigate them. A decision record captures the context, the options considered, the decision, and the consequences, including the downsides you accepted. Written before the decision, it improves thinking; kept after, it saves months of repeated debate."),
    M("Which part of a decision record is most often missing and most valuable later?",
      ["The date", "The options that were rejected and why", "The author's job title", "A summary"], 1,
      "Without the rejected options, future readers propose them again, not knowing they were already weighed."),
    M("Your decision has a real downside. What should the record say?",
      ["Nothing, it weakens the case", "Name it plainly as an accepted consequence, and what would make you revisit", "Hide it in an appendix", "Only mention benefits"], 1,
      "Honest records age well. Naming the trade off tells future readers when the decision might need to change."),
    WR("Write a short decision record for a choice you made or might make. Use lines starting with Context:, Options:, Decision:, Consequences: and Revisit if:. List at least two options.",
       [must("^context:", "Context:", flags="im"),
        must("^options:", "Options:", flags="im"),
        must("^options:.*(,|;| or |\\n\\s*(-|\\d))", "At least two options", flags="im"),
        must("^decision:", "Decision:", flags="im"),
        must("^consequences:.*(downside|cost|lose|slower|harder|risk|but|less)", "Consequences include a downside", flags="im",
             hint="Name at least one cost of the decision."),
        must("^revisit if:", "Revisit if:", flags="im"),
        words(50, 220)],
       "Context: Our team of four shares one spreadsheet for bookings, and double bookings happen about twice a month.\nOptions: keep the spreadsheet with a stricter process; buy a booking tool; build a simple form.\nDecision: Buy a booking tool, starting with the free plan.\nConsequences: Double bookings should stop; the downside is a new tool to learn and a monthly cost if we outgrow the free plan.\nRevisit if: the free plan limits block us or the team grows past ten.",
       "Context, real options, the decision, honest consequences and a trigger to revisit. Future you will thank present you."),
    O("Write a decision record, in order.",
      ["Describe the context and the problem", "List the real options, including doing nothing", "State the decision", "Record consequences and what would make you revisit"],
      "Doing nothing is always an option and often the one people secretly prefer. List it."),
    C("Short is fine",
      "A good decision record can be a few lines. Length is not rigor; the rejected options and the accepted downsides are."),
])

WE4 = L("Specialist writing for outsiders", KW + ["plain language", "jargon", "technical writing", "audience", "translation", "expert"], [
    C("Translate, do not dilute",
      "Experts writing for outsiders often either drown them in jargon or water the content down until it is wrong. The goal is accuracy in plain words: define a term the first time, replace jargon with everyday words where a plain word is just as precise, keep the numbers that matter, and tell the reader what it means for them."),
    M("A doctor writes: the lesion is benign. Which plain version keeps the meaning?",
      ["The spot is fine, forget it", "The spot is not cancer", "The lesion appears unremarkable", "Nothing to worry about ever"], 1,
      "Accurate and plain. The first and last overpromise; the third is still jargon."),
    M("When should a technical term stay in?",
      ["Never", "When the reader will need it again, such as to search for it or discuss it, and you define it on first use", "Always", "Only in footnotes"], 1,
      "Some terms are worth teaching. Define them once and use them consistently."),
    WR("Rewrite this note from an engineer for customers. Keep it accurate, explain what it means for them, and remove or explain the jargon.",
       [changed(),
        avoid("\\b(latency|p95|degraded|upstream|mitigat\\w*|RCA)\\b", "No unexplained jargon",
              hint="Say slower instead of latency, and say what a customer would notice."),
        must("(slow|slower|delay|took longer|seconds)", "Says what customers noticed"),
        must("(fixed|resolved|back to normal|working normally)", "Says it is fixed"),
        words(20, 80),
        max_sentence(25, "No sentence over 25 words")],
       "On Tuesday between 2 and 3 pm, pages took up to 10 seconds to load because one of our data providers was slow. It is fixed, and pages are back to normal. You do not need to do anything.",
       "What happened, what they saw, that it is fixed and what to do. Every customer can follow it.",
       starter="Between 14:00 and 15:00 on Tuesday, p95 latency was degraded due to an upstream provider issue. Mitigation was applied and an RCA will follow."),
    O("Translate expert text, in order.",
      ["Identify who will read it and what they need to do", "Mark every term an outsider would not know", "Replace or define each one", "Check with the expert that nothing became wrong"],
      "The last step is the one people skip. Plain and wrong is worse than jargon."),
    C("Keep a glossary",
      "In long documents or products, keep a short glossary of terms and use each one consistently. Two words for the same thing make readers think there are two things."),
])

WE5 = L("Editing other people's writing", KW + ["feedback", "editing others", "critique", "comments", "review"], [
    C("Edit for the writer's goal, not your taste",
      "Good editors ask what the writer is trying to do and help them do it. Comment first on the big issues (purpose, structure, missing points), then on paragraphs and sentences. Explain why, not just what: this sentence buries the ask helps; awkward does not. Mark what works too, so the writer keeps it."),
    M("Which comment is most useful?",
      ["Unclear.", "I lost the main point here; if the ask is the approval, could it move to the first line?", "I would never write it this way.", "Fix this."], 1,
      "It names the problem, the reason and a possible fix, phrased as an offer."),
    M("A draft has a structural problem and twenty comma issues. What do you comment on first?",
      ["The commas", "The structure, because fixing it may remove or rewrite many sentences", "Both equally", "Neither"], 1,
      "Line edits on paragraphs that will be cut waste everyone's time."),
    WR("Write three editing comments on a draft that opens with two paragraphs of background, puts the request in the last line, and uses the word utilize six times. One comment per line. Make at least one comment praise something, and phrase suggestions as questions or offers.",
       [lines(3, "Three comments, one per line"),
        must("(request|ask)[^\\n]*(top|first|start|move|earlier)|(move|put)[^\\n]*(request|ask)", "Addresses where the request sits"),
        must("utiliz", "Addresses the word utilize"),
        must("(works|like|strong|clear|good|helpful|great)", "Praises something specific"),
        must("\\?|could|might|would you|consider|what if", "Phrases suggestions as questions or offers"),
        avoid("\\b(bad|wrong|terrible|awful|lazy)\\b", "No judgment words")],
       "The request is the most important line, but it sits at the very end. Could it move to the first sentence?\nThe background is clear and helpful; could it shrink to two sentences after the request?\nUtilize appears six times. Would use work in most of them?",
       "Big issue first, specific praise, reasons, and suggestions the writer can accept or decline."),
    O("Edit a colleague's draft, in order.",
      ["Read it once without commenting to understand the goal", "Comment on purpose and structure", "Comment on paragraphs and sentences", "Summarize your top two suggestions at the top"],
      "The summary at the top tells the writer where to start, so twenty comments do not feel like twenty equal problems."),
    C("Ask before you rewrite",
      "Rewriting someone's paragraph in your voice can feel efficient and land as a takeover. Unless they asked for it, suggest and explain; let them write."),
])

WE6 = L("Style guides and consistency", KW + ["style guide", "consistency", "conventions", "house style", "terminology"], [
    C("Decide once, follow everywhere",
      "A style guide records choices so nobody has to remake them: how to write dates and numbers, which words to use for product features, capitalization of headings, how to address the reader, words to avoid. It frees writers to think about content and makes a team sound like one organization. The best guides are short, with examples."),
    M("Which entry is most useful in a style guide?",
      ["Write well.", "Dates: write 3 March 2026, not 03/03/26 or March 3rd.", "Be consistent.", "Use good grammar."], 1,
      "Specific rule, with right and wrong examples. Writers can apply it without interpretation."),
    M("Your product calls the same thing a workspace, a project and a board in different places. What is the effect?",
      ["None", "Readers assume they are three different things and get confused", "It looks more varied", "It helps search"], 1,
      "Consistency in terms is a usability issue, not just polish."),
    WR("Write four style guide entries for a team or product you know. Each entry on its own line, in the form: Topic: rule, then an example after the word Example:.",
       [lines(4, "Four entries"),
        must("(^[^:\\n]+:[^\\n]+example:[^\\n]+$\\n?){4}", "Each entry has a topic, a rule and an example", flags="im",
             hint="Format: Numbers: spell out one to nine, use digits from 10. Example: three files, 12 files."),
        words(30, 200)],
       "Numbers: spell out one to nine, use digits from 10. Example: three files, 12 files.\nHeadings: sentence case, no final period. Example: Set up your account\nProduct terms: call it a workspace, never a board or project. Example: Invite people to your workspace.\nAddress: speak to the reader as you. Example: You can change this later.",
       "Topic, rule, example. A new writer could apply all four on their first day."),
    O("Create a style guide, in order.",
      ["Collect the inconsistencies you actually see", "Decide a rule for each, with a reason", "Write each rule with an example", "Keep it short and update it when new questions come up"],
      "Start from real problems. Guides written from scratch tend to cover things nobody gets wrong and miss the things everyone does."),
    C("Borrow a base guide",
      "Most teams adopt a published guide for general questions and keep a short house guide for their own terms and choices. Only write down what differs."),
])

WE7 = L("Writing for scanning at scale", KW + ["documentation", "scanning", "headings", "information architecture", "help center", "docs"], [
    C("People hunt, they do not read",
      "In documentation and help centers, people arrive with a question and scan for an answer. Put the answer where scanning lands: descriptive headings phrased as tasks or questions, the key sentence first in each section, short paragraphs, lists for steps and options, and one topic per page so search results land in the right place."),
    M("Which heading helps a scanning reader most?",
      ["Overview", "Change your billing email", "Miscellaneous", "Section 4.2"], 1,
      "It matches the task the reader has in mind, in the words they would use."),
    M("A help page covers billing, passwords and notifications. What is the problem?",
      ["Nothing", "Search and links land on one long page where readers must hunt; split it into one task per page", "It is too short", "It needs more images"], 1,
      "One page per task lets search, links and headings all point exactly at the answer."),
    WR("Rewrite these vague headings for a help center as task or question headings people would scan for. Keep one heading per line, in the same order.",
       [changed(),
        lines(4, "Four headings, one per line"),
        avoid("^(general|miscellaneous|overview|other|info|information|details)\\s*$", "No vague headings left", flags="im"),
        must("^(how|what|why|can|change|set|add|remove|reset|cancel|update|connect|download|export|invite|turn)", "Headings start with a task verb or a question word", flags="im",
             hint="Start with what the reader wants to do: Reset your password."),
        words(10, 50)],
       "Reset your password\nChange your billing email\nTurn off email notifications\nCancel your subscription",
       "Task headings match what people search for and type. They are the most valuable words on the page.",
       starter="General\nBilling information\nNotifications overview\nOther"),
    O("Write a help article, in order.",
      ["Name the task in the title the way users would say it", "Give the answer or first step right away", "List the steps in order", "Add common problems at the end"],
      "Answer first; troubleshooting last, where people who need it look for it."),
    C("Measure what people search for",
      "Search logs in your help center show the words people use and the questions that fail. They are the best source of new headings and missing pages."),
])

WE8 = L("Honest persuasion", KW + ["ethics", "honesty", "manipulation", "spin", "misleading", "integrity"], [
    C("Persuade with what is true",
      "Writing can mislead without a single false sentence: cherry picked numbers, a scary anecdote presented as typical, false urgency, a buried catch, or a comparison chosen because it flatters. Honest persuasion gives the reader what they need to decide well, including what cuts against you. It also tends to work better over time, because readers remember being misled."),
    M("Which is misleading even though every word is true?",
      ["Our sign ups rose 40% this month", "Sign ups rose 40% this month (from 10 to 14), after a 60% fall the month before", "We gained 4 sign ups", "Sign ups changed"], 0,
      "A 40% rise from 10 to 14, after a large fall, tells a very different story. Leaving out the base and the context misleads."),
    M("Which marketing line uses false urgency?",
      ["Prices rise on 1 March, as announced in January", "Only 2 left!! (shown to every visitor, always)", "Sale ends Sunday", "New stock arrives monthly"], 1,
      "Claims of scarcity that are not true pressure people into decisions they might not make otherwise."),
    WR("Rewrite this promotion so it is honest and still persuasive. Keep the real facts: a 20% discount for the first three months, then the normal price of 12 a month; cancel any time.",
       [changed(),
        must("(three months|3 months)", "States the discount period"),
        must("12", "States the normal price"),
        must("cancel", "Mentions cancelling"),
        avoid("(only \\d+ (left|spots)|last chance|act now|hurry|ends tonight)", "No false urgency",
              hint="Remove pressure that is not true. The real offer can stand on its own."),
        avoid("\\bfree\\b", "Does not call a discount free"),
        words(15, 70)],
       "Get 20% off for your first three months, then it is 12 a month. Cancel any time from your account page, in two clicks.",
       "The reader knows exactly what they will pay and when. That is the kind of offer people stay with.",
       starter="HURRY, last chance!! Practically free! Only 3 spots left. Act now before this amazing deal ends tonight!"),
    O("Check a persuasive piece for honesty, in order.",
      ["List every claim and number", "Check each against the source and its context", "Ask what a fully informed reader would want to know that is missing", "Add it, even if it weakens the pitch"],
      "The third step is the hard one. It is also the one that separates persuasion from manipulation."),
    C("Disclose interests",
      "If you benefit from the reader's decision (you sell it, you are paid to recommend it, it helps your team), say so. Readers can still agree; they just get to weigh it."),
])

WE9 = L("Capstone: an explainer people finish", KW + ["capstone", "explainer", "long form", "article", "feature"], [
    C("Put the level together",
      "An explainer uses everything from this level: a clear voice, a hard idea built from what readers know, plain language, honest framing, and structure that scanners can use. You will write an outline and an opening for one, then edit it against a checklist."),
    M("Which explainer opening earns the next paragraph?",
      ["This article will explain inflation.", "If your grocery bill has crept up while your pay has not, you have met inflation. Here is what it is, why it happens and what you can and cannot control.", "Inflation is a complex macroeconomic phenomenon.", "Since the dawn of money, prices have existed."], 1,
      "It starts with the reader's experience, names the idea and promises a clear path."),
    O("Plan an explainer, in order.",
      ["Name the reader and the question they have", "Write the one sentence answer", "Outline sections that build from familiar to new", "Draft the opening last, once you know the path"],
      "The answer sentence is the spine. Writing the opening before you know the path tends to promise the wrong thing."),
    WR("Write the outline for an explainer on a topic you know well. First line: Reader: who it is for. Second: Answer: the one sentence answer. Then at least four lines starting with Section: as headings that build from familiar to new.",
       [must("^reader:", "A Reader: line", flags="im"),
        must("^answer:", "An Answer: line", flags="im"),
        must("(^section:.*\\n?){4,}", "At least four Section: lines", flags="im"),
        words(30, 160)],
       "Reader: adults who have never invested and feel lost.\nAnswer: An index fund lets you own a small piece of many companies at once, so one bad company matters less.\nSection: What owning a share means\nSection: Why one company is risky\nSection: How a fund spreads the risk\nSection: What it costs and what can still go wrong",
       "Reader, answer, and a path from familiar to new. The draft almost writes itself from here."),
    WR("Write the opening paragraph of that explainer, 60 to 150 words. Start from the reader's experience, name the idea, and say what the piece will cover. Keep sentences under 25 words.",
       [words(60, 150),
        max_sentence(25, "No sentence over 25 words"),
        must("\\byou\\b|\\byour\\b", "Speaks to the reader"),
        avoid("this article will|in this article|since the dawn|it is important to note", "No throat clearing openers"),
        avoid("\\b(synerg\\w*|leverag\\w*|paradigm|utiliz\\w*)\\b", "Plain words")],
       "You have probably heard that you should invest, and then heard ten conflicting ways to do it. Here is one of the simplest. An index fund lets you own a small piece of many companies at once. If one company does badly, it is a small part of what you own. Below you will see what a share is, why one company is risky and how a fund spreads that risk. Then we cover what it costs and what can still go wrong.",
       "Reader first, idea named, path promised, and the limits mentioned up front. That is an opening people keep reading."),
    WR("Edit your opening against this checklist, then write one line on the biggest change you made.",
       [self_check("I read it aloud and cut anything that sounded like a lecture"),
        self_check("Every technical term is explained or removed"),
        self_check("A reader who stopped here would know what the piece covers"),
        words(5, 80, "A short note on what you changed")],
       "Cut the second sentence, which repeated the first, and replaced diversification with spreads the risk.",
       "Expert writers revise more than beginners, not less. The checklist is how the habit sticks."),
    C("Expert complete",
      "You can write with a clear voice, explain hard things, record decisions, edit others and persuade honestly. Keep writing, and keep reading what you wrote out loud."),
])


def add(courses, picks):
    courses.append(course("writing-intermediate", "Practical writing", "Intermediate", "Writing people act on", "writing", "Writing", 55,
        "Strong verbs, rhythm, precise words, openings, requests, bad news, instructions and summaries.",
        [("Sentences with force", [WI1, WI2, WI3]), ("Messages that land", [WI4, WI5, WI6]),
         ("Documents that work", [WI7, WI8, WI9])], "writing"))
    courses.append(course("writing-advanced", "Persuasive writing", "Advanced", "Writing that persuades", "writing-intermediate", "Practical writing", 85,
        "Claims and evidence, steelmanning, answer first structure, skeptical readers, stories, numbers, proposals and editing.",
        [("Argument", [WA1, WA2, WA3]), ("Audience", [WA4, WA5, WA6]), ("Long form", [WA7, WA8, WA9])], "writing"))
    courses.append(course("writing-expert", "Expert writing", "Expert", "Writing with authority", "writing-advanced", "Persuasive writing", 85,
        "Voice, explaining hard ideas, decision records, plain language for outsiders, editing others, style guides, docs and honest persuasion.",
        [("Voice and clarity", [WE1, WE2, WE3]), ("Writing with others", [WE4, WE5, WE6]),
         ("Writing at scale", [WE7, WE8, WE9])], "writing"))
